Adobe PDF Library Java Documentation
com.datalogics.PDFL.FileAttachment Class Reference
Public Member Functions
synchronized void delete ()
FileAttachment (Document doc, String fileName)
FileAttachment (Document doc, String fileName, String keyName)
float getCollectionItemNumber (CollectionSchemaField collectionField)
String getCollectionItemString (CollectionSchemaField collectionField)
String getFileName ()
long getFileSize ()
void saveToFile (String fileName)
void saveToStream (javax.imageio.stream.ImageOutputStream stream) throws java.io.IOException
void setCollectionItemNumber (CollectionSchemaField collectionField, float value)
void setCollectionItemString (CollectionSchemaField collectionField, String value)
void updateFromFile (String fileName)
Protected Member Functions
synchronized void delete (Boolean disposing)
FileAttachment (long cPtr, boolean cMemoryOwn)
void finalize ()
Static Protected Member Functions
static long getCPtr (FileAttachment obj)
Detailed Description
A file attachment.Any file can be attached to the PDF document. The class allows to create attachment and manipulate by its content.
Constructor & Destructor Documentation
FileAttachment() [1/3]
com.datalogics.PDFL.FileAttachment.FileAttachment (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
FileAttachment() [2/3]
com.datalogics.PDFL.FileAttachment.FileAttachment (Document doc, String fileName)
Allows to add attachment into the PDF document.
Parameters
doc The PDF document (reference).
fileName The path to file which will be attached to the document.
FileAttachment() [3/3]
com.datalogics.PDFL.FileAttachment.FileAttachment (Document doc, String fileName, String keyName)
Allows to add attachment into the PDF document using the specified key name.
Parameters
doc The PDF document (reference).
fileName The path to file which will be attached to the document.
keyName The name of the key.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.FileAttachment.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.FileAttachment.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.FileAttachment.finalize () protected
getCollectionItemNumber()
float com.datalogics.PDFL.FileAttachment.getCollectionItemNumber (CollectionSchemaField collectionField)
GetCollectionItemNumber allows to obtain collection item according to the specified schema field.
Parameters
collectionField the field for which item value should be retrieved.
Returns
collection items value
getCollectionItemString()
String com.datalogics.PDFL.FileAttachment.getCollectionItemString (CollectionSchemaField collectionField)
GetCollectionItemString allows to obtain collection item value according to the specified schema field.
Parameters
collectionField the field for which item value should be retrieved.
Returns
collection items value
getCPtr()
long com.datalogics.PDFL.FileAttachment.getCPtr (FileAttachment obj) static protected
getFileName()
String com.datalogics.PDFL.FileAttachment.getFileName ()
Allow to obtain attachment's file name.
Returns
The attachment's file name.
getFileSize()
long com.datalogics.PDFL.FileAttachment.getFileSize ()
Allows to obtain attachment's size.
Returns
The attachment's size in bytes.
saveToFile()
void com.datalogics.PDFL.FileAttachment.saveToFile (String fileName)
Allows to save attachment to the specified file.
Parameters
fileName The path where attachment will be saved.
saveToStream()
void com.datalogics.PDFL.FileAttachment.saveToStream (javax.imageio.stream.ImageOutputStream stream) throws java.io.IOException
Saves a FileAttachment to a javax.imageio.stream.ImageInputStream.
Parameters
stream The stream from which to save the FileAttachment.
setCollectionItemNumber()
void com.datalogics.PDFL.FileAttachment.setCollectionItemNumber (CollectionSchemaField collectionField, float value)
SetCollectionItemNumber allows to add key to the collection item dictionary.
Parameters
collectionField schema field which contains information about data type. The parameter's subtype should be a Number.
value the item's value.
setCollectionItemString()
void com.datalogics.PDFL.FileAttachment.setCollectionItemString (CollectionSchemaField collectionField, String value)
SetCollectionItemString allows to add key to the collection item dictionary.
Parameters
collectionField schema field which contains information about data type. The parameter's subtype should be a Text.
value the item's value.
updateFromFile()
void com.datalogics.PDFL.FileAttachment.updateFromFile (String fileName)
Allows to update attachment from another file.
Parameters
fileName The path to the file from which attachment will be updated.