Adobe PDF Library Java Documentation
com.datalogics.PDFL.PostScriptCalculatorFunction Class Reference
Public Member Functions
java.util.List< Double > apply (java.util.List< Double > args)
synchronized void delete ()
String getCode ()
java.util.List< Double > getDomain ()
int getNInputs ()
int getNOutputs ()
java.util.List< Double > getRange ()
PDFStream getStream ()
PostScriptCalculatorFunction (java.util.List< Double > domain, java.util.List< Double > range, String code)
void setDomain (java.util.List< Double > domain)
void setRange (java.util.List< Double > range)
String toString ()
Static Public Attributes
static final Function DEFAULT
static final Function IDENTITY
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PostScriptCalculatorFunction (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Function obj)
static long getCPtr (PostScriptCalculatorFunction obj)
Detailed Description
A function represented as a stream containing code written in a small subset of the PostScript language.
Constructor & Destructor Documentation
PostScriptCalculatorFunction() [1/2]
com.datalogics.PDFL.PostScriptCalculatorFunction.PostScriptCalculatorFunction (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr(), and PostScriptCalculatorFunction().
PostScriptCalculatorFunction() [2/2]
com.datalogics.PDFL.PostScriptCalculatorFunction.PostScriptCalculatorFunction (java.util.List< Double > domain, java.util.List< Double > range, String code)
Create PostScript calculator function, represented as a stream containing code written in a small subset of the PostScript language.
Parameters
domain an array of 2 * m numbers, where m is the number of input values
range an array of 2 * n numbers, where n is the number of output values
code the code of the function, written in a subset of the PostScript language
Member Function Documentation
apply()
java.util.List< Double > com.datalogics.PDFL.Function.apply (java.util.List< Double > args) inherited
Apply the function to supplied input values
Parameters
args input values for the function. The number of input values must agree with the number of inputs the function takes.
Returns
a list of the result values from the function
Reimplemented in com.datalogics.PDFL.NamedFunction.
delete() [1/2]
synchronized void com.datalogics.PDFL.PostScriptCalculatorFunction.delete ()
Reimplemented from com.datalogics.PDFL.Function.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.PostScriptCalculatorFunction.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Function.
finalize()
void com.datalogics.PDFL.PostScriptCalculatorFunction.finalize () protected
Reimplemented from com.datalogics.PDFL.Function.
getCode()
String com.datalogics.PDFL.PostScriptCalculatorFunction.getCode ()
The code of the function, written in a subset of the PostScript language.
getCPtr() [1/2]
long com.datalogics.PDFL.Function.getCPtr (Function obj) static protected inherited
Referenced by com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), com.datalogics.PDFL.ExtendedGraphicState.setBlackGeneration(), and com.datalogics.PDFL.ExtendedGraphicState.setUndercolorRemoval().
getCPtr() [2/2]
long com.datalogics.PDFL.PostScriptCalculatorFunction.getCPtr (PostScriptCalculatorFunction obj) static protected
getDomain()
java.util.List< Double > com.datalogics.PDFL.Function.getDomain () inherited
The domain of the function. 2 * m elements, where m is the number of inputs to the function.
Each successive pair of elements gives the minimum and maximum values for one of the inputs.
Input values to the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getNInputs()
int com.datalogics.PDFL.Function.getNInputs () inherited
The number of inputs to the function.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getNOutputs()
int com.datalogics.PDFL.Function.getNOutputs () inherited
The number of outputs from the function.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getRange()
java.util.List< Double > com.datalogics.PDFL.Function.getRange () inherited
The range of the function. 2 * n elements, where n is the number of outputs from the function.
Each successive pair of elements gives the minimum and maximum values for one of the outputs.
Output values from the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getStream()
PDFStream com.datalogics.PDFL.PostScriptCalculatorFunction.getStream ()
The underlying stream for this PostScriptCalculatorFunction.
setDomain()
void com.datalogics.PDFL.Function.setDomain (java.util.List< Double > domain) inherited
The domain of the function. 2 * m elements, where m is the number of inputs to the function.
Each successive pair of elements gives the minimum and maximum values for one of the inputs.
Input values to the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
setRange()
void com.datalogics.PDFL.Function.setRange (java.util.List< Double > range) inherited
The range of the function. 2 * n elements, where n is the number of outputs from the function.
Each successive pair of elements gives the minimum and maximum values for one of the outputs.
Output values from the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
toString()
String com.datalogics.PDFL.PostScriptCalculatorFunction.toString ()
A string value describing the function.
Reimplemented from com.datalogics.PDFL.Function.
Member Data Documentation
DEFAULT
final Function com.datalogics.PDFL.Function.DEFAULT static inherited
IDENTITY
final Function com.datalogics.PDFL.Function.IDENTITY static inherited