Adobe PDF Library Java Documentation
com.datalogics.PDFL.CancelProc Class Reference
Public Member Functions
boolean Call ()
CancelProc ()
synchronized void delete ()
Protected Member Functions
CancelProc (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (CancelProc obj)
Detailed Description
A callback function used to abort an operation. A CancelProc() value is typically passed to a method that uses it to determine if an asynchronous operation should be ended.
At periodic intervals, the method calls the CancelProc. If the CancelProc returns a "true" boolean value, the method cancels the operation. If CancelProc returns false, the method allows the operation to continue. For example, CancelProc could be used to allow a user to click a Cancel button to end a function.
Constructor & Destructor Documentation
CancelProc() [1/2]
com.datalogics.PDFL.CancelProc.CancelProc (long cPtr, boolean cMemoryOwn) protected
Referenced by Call(), and getCPtr().
CancelProc() [2/2]
com.datalogics.PDFL.CancelProc.CancelProc ()
A callback function used to abort an operation. A CancelProc() value is typically passed to a method that uses it to determine if an asynchronous operation should be ended.
At periodic intervals, the method calls the CancelProc. If the CancelProc returns a "true" boolean value, the method cancels the operation. If CancelProc returns false, the method allows the operation to continue. For example, CancelProc could be used to allow a user to click a Cancel button to end a function.
Member Function Documentation
Call()
boolean com.datalogics.PDFL.CancelProc.Call ()
delete() [1/2]
synchronized void com.datalogics.PDFL.CancelProc.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.CancelProc.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.CancelProc.finalize () protected
getCPtr()
long com.datalogics.PDFL.CancelProc.getCPtr (CancelProc obj) static protected
Referenced by com.datalogics.PDFL.SignDoc.createCancelProc(), com.datalogics.PDFL.Document.embedFonts(), com.datalogics.PDFL.Document.embedFonts(), com.datalogics.PDFL.Document.insertPages(), com.datalogics.PDFL.PDFOptimizer.optimize(), com.datalogics.PDFL.PDFOptimizer.optimize(), com.datalogics.PDFL.Document.save(), com.datalogics.PDFL.Document.save(), com.datalogics.PDFL.Document.save(), and com.datalogics.PDFL.DrawParams.setCancelProc().