Adobe PDF Library Java Documentation
com.datalogics.PDFL.XPSConvertParams Class Reference
Public Member Functions
synchronized void delete ()
String getPathToSettingsFile ()
void setPathToSettingsFile (String theSettingsFile)
XPSConvertParams ()
XPSConvertParams (String SettingsFile)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
XPSConvertParams (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (XPSConvertParams obj)
Detailed Description
Class that works with XPS conversion parameters. The XML Paper Specification (XPS) is a standard document format that Microsoft created in 2006 as an alternative to the PDF format. The XPS format is intended to be a simple but secure file format, without embedded images or video clips, and easy to share and print.
NOTE: This class is only available on Windows or Linux.
Constructor & Destructor Documentation
XPSConvertParams() [1/3]
com.datalogics.PDFL.XPSConvertParams.XPSConvertParams (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
XPSConvertParams() [2/3]
com.datalogics.PDFL.XPSConvertParams.XPSConvertParams ()
Set up default parameters for XPS conversion.
XPSConvertParams() [3/3]
com.datalogics.PDFL.XPSConvertParams.XPSConvertParams (String SettingsFile)
Set up parameters for XPS conversion.
Parameters
SettingsFile The path to the .joboptions file to use. By default, the Standard.joboptions file located in the Resources directory is used. The default file will be used if the specified file is not found.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.XPSConvertParams.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.XPSConvertParams.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.XPSConvertParams.finalize () protected
getCPtr()
long com.datalogics.PDFL.XPSConvertParams.getCPtr (XPSConvertParams obj) static protected
Referenced by com.datalogics.PDFL.Document.Document().
getPathToSettingsFile()
String com.datalogics.PDFL.XPSConvertParams.getPathToSettingsFile ()
The path to the .joboptions file to use.
setPathToSettingsFile()
void com.datalogics.PDFL.XPSConvertParams.setPathToSettingsFile (String theSettingsFile)
The path to the .joboptions file to use.