Adobe PDF Library Java Documentation
com.datalogics.PDFL.LanguageSetting Class Reference
Public Member Functions
synchronized void delete ()
Language getLanguage ()
boolean getProhibit ()
LanguageSetting (Language language, boolean prohibit)
void setLanguage (Language value)
void setProhibit (boolean value)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
LanguageSetting (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (LanguageSetting obj)
Detailed Description
Specify a language, along with any metadata about that language.
Constructor & Destructor Documentation
LanguageSetting() [1/2]
com.datalogics.PDFL.LanguageSetting.LanguageSetting (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
LanguageSetting() [2/2]
com.datalogics.PDFL.LanguageSetting.LanguageSetting (Language language, boolean prohibit)
create a language setting.
Parameters
language the language to specify
prohibit Instead of loading this language, prohibit the language from being loaded as an adjunct of another language.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.LanguageSetting.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.LanguageSetting.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.LanguageSetting.finalize () protected
getCPtr()
long com.datalogics.PDFL.LanguageSetting.getCPtr (LanguageSetting obj) static protected
getLanguage()
Language com.datalogics.PDFL.LanguageSetting.getLanguage ()
The language being specified.
getProhibit()
boolean com.datalogics.PDFL.LanguageSetting.getProhibit ()
Instead of loading this language, prohibit the language from being loaded as an adjunct of another language.
setLanguage()
void com.datalogics.PDFL.LanguageSetting.setLanguage (Language value)
The language being specified.
setProhibit()
void com.datalogics.PDFL.LanguageSetting.setProhibit (boolean value)
Instead of loading this language, prohibit the language from being loaded as an adjunct of another language.