Adobe PDF Library Java Documentation
com.datalogics.PDFL.ViewDestination Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
Rect getDestRect ()
String getFitType ()
int getPageNumber ()
PDFArray getPDFArray ()
double getZoom ()
void setDestRect (Rect ViewDestRect)
void setFitType (String ViewDestFitType)
void setPageNumber (int ViewDestPageNum)
void setZoom (double ViewDestZoomFactor)
String toString ()
ViewDestination (Document doc, int pageNum, String fitType, Rect r, double zoom)
Static Public Attributes
static final double NULL_VALUE
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
ViewDestination (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (ViewDestination obj)
Detailed Description
Represents a particular view of a page in a document. A destination describes a place in the PDF document where the user will be taken in response to clicking a hyperlink. The destination defines where a bookmark or hyperlink points to.
The ViewDestination contains a reference to a page, a place (rectangle) on that page, and information specifying how to adjust the view to fit the window's size and shape.
Constructor & Destructor Documentation
ViewDestination() [1/2]
com.datalogics.PDFL.ViewDestination.ViewDestination (long cPtr, boolean cMemoryOwn) protected
Referenced by equals(), and getCPtr().
ViewDestination() [2/2]
com.datalogics.PDFL.ViewDestination.ViewDestination (Document doc, int pageNum, String fitType, Rect r, double zoom)
General purpose constructor: construct with all elements
Parameters
doc Containing document
pageNum Target page number
fitType Fit Type must be: "XYZ", "Fit", "FitH", "FitV", "FitR", "FitB", "FitBH", or "FitBV".
r Target rectangle
zoom Zoom level
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.ViewDestination.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.ViewDestination.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.ViewDestination.equals (Object rhs)
finalize()
void com.datalogics.PDFL.ViewDestination.finalize () protected
getCPtr()
long com.datalogics.PDFL.ViewDestination.getCPtr (ViewDestination obj) static protected
Referenced by com.datalogics.PDFL.GoToAction.GoToAction(), com.datalogics.PDFL.GoToAction.setDestination(), and com.datalogics.PDFL.LinkAnnotation.setDestination().
getDestRect()
Rect com.datalogics.PDFL.ViewDestination.getDestRect ()
The destination rectangle.
getFitType()
String com.datalogics.PDFL.ViewDestination.getFitType ()
The fit type.
getPageNumber()
int com.datalogics.PDFL.ViewDestination.getPageNumber ()
The page number of the destination
getPDFArray()
PDFArray com.datalogics.PDFL.ViewDestination.getPDFArray ()
Retrieve the PDFObject representation of this object
getZoom()
double com.datalogics.PDFL.ViewDestination.getZoom ()
The zoom factor for the destination.
setDestRect()
void com.datalogics.PDFL.ViewDestination.setDestRect (Rect ViewDestRect)
Set the destination rectangle of the view.
setFitType()
void com.datalogics.PDFL.ViewDestination.setFitType (String ViewDestFitType)
Set the fit type for the view
setPageNumber()
void com.datalogics.PDFL.ViewDestination.setPageNumber (int ViewDestPageNum)
Set the page number of the destination starting at 0
setZoom()
void com.datalogics.PDFL.ViewDestination.setZoom (double ViewDestZoomFactor)
Set the zoom factor for the destination.
toString()
String com.datalogics.PDFL.ViewDestination.toString ()
Member Data Documentation
NULL_VALUE
final double com.datalogics.PDFL.ViewDestination.NULL_VALUE static
Constant used for "null" values in destination rectangles or zoom.