Adobe PDF Library Java Documentation
com.datalogics.PDFL.EmbedFlags Enum Reference
Static Public Member Functions
static int FlagsToInt (java.lang.Iterable< EmbedFlags > flags)
static java.util.EnumSet< EmbedFlags > IntToFlags (int value)
Public Attributes
DONT_SCAN_DOCUMENT
NONE
SUBSET
SUBSET_OF_EMBEDDED_FONT
Member Function Documentation
FlagsToInt()
int com.datalogics.PDFL.EmbedFlags.FlagsToInt (java.lang.Iterable< EmbedFlags > flags) static
Referenced by com.datalogics.PDFL.Document.embedFonts(), com.datalogics.PDFL.Document.embedFonts(), com.datalogics.PDFL.Document.embedFonts(), and com.datalogics.PDFL.Document.embedFonts().
IntToFlags()
java.util.EnumSet< EmbedFlags > com.datalogics.PDFL.EmbedFlags.IntToFlags (int value) static
Member Data Documentation
DONT_SCAN_DOCUMENT
com.datalogics.PDFL.EmbedFlags.DONT_SCAN_DOCUMENT
If set, the document will not be scanned for font usage when embedding and subsetting. This flag only takes effect if a list of specific fonts to embed is given.
NONE
com.datalogics.PDFL.EmbedFlags.NONE
Fonts marked for subsetting/embedding will be embedded.
SUBSET
com.datalogics.PDFL.EmbedFlags.SUBSET
Fonts will be subset when embedded. Otherwise the entire font will be embedded. Full fonts should only be embedded if the information in the fonts indicates it can be used for editible embedding. Fonts that have more than 2048 characters will be subset embedded regardless of the setting of this flag.
This flag implies a scan of the document text to ensure that all required characters are in the subset.
SUBSET_OF_EMBEDDED_FONT
com.datalogics.PDFL.EmbedFlags.SUBSET_OF_EMBEDDED_FONT
If set, fonts that have already been embedded but are not subset fonts, will be reembedded as a subset font.
If clear, already embedded fonts will not be re-scanned for embedding at all.