Programming Reference: Main Page
com.datalogics.PDFL.PrintProgressProc Class Reference
Public Member Functions
.datalogics.metadata.Callback void Call (int page, int total, float stagePercent, String info, PrintProgressStage stage)
synchronized void delete ()
PrintProgressProc ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PrintProgressProc (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PrintProgressProc obj)
Detailed Description
Print progress callback function, a class used to notify print client of the progress during print operations. A PrintProgressProc() is typically passed to some method that takes a long time to complete. At frequent intervals, the method calls the PrintProgressProc().
Constructor & Destructor Documentation
PrintProgressProc() [1/2]
com.datalogics.PDFL.PrintProgressProc.PrintProgressProc (long cPtr, boolean cMemoryOwn) protected
PrintProgressProc() [2/2]
com.datalogics.PDFL.PrintProgressProc.PrintProgressProc ()
Print progress callback function, a class used to notify print client of the progress during print operations. A PrintProgressProc() is typically passed to some method that takes a long time to complete. At frequent intervals, the method calls the PrintProgressProc().
Member Function Documentation
Call()
.datalogics.metadata.Callback void com.datalogics.PDFL.PrintProgressProc.Call (int page, int total, float stagePercent, String info, PrintProgressStage stage)
delete() [1/2]
synchronized void com.datalogics.PDFL.PrintProgressProc.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.PrintProgressProc.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.PrintProgressProc.finalize () protected
getCPtr()
static long com.datalogics.PDFL.PrintProgressProc.getCPtr (PrintProgressProc obj) static protected
Referenced by com.datalogics.PDFL.Document.exportAsPostScript(), com.datalogics.PDFL.Document.print(), and com.datalogics.PDFL.Document.printToFile().