Programming Reference: Main Page
com.datalogics.PDFL.Rect Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
double getBottom ()
double getHeight ()
double getLeft ()
double getLLx ()
double getLLy ()
double getRight ()
double getTop ()
double getURx ()
double getURy ()
double getWidth ()
boolean inRect (Rect r2)
Rect intersect (Rect r2)
boolean isEmpty ()
boolean overlaps (Rect r2)
Rect ()
Rect (double nLLx, double nLLy, double nURx, double nURy)
Rect (java.awt.geom.Rectangle2D r)
void setBottom (double bottom)
void setLeft (double left)
void setLLx (double value)
void setLLy (double value)
void setRight (double right)
void setTop (double top)
void setURx (double value)
void setURy (double value)
String toString ()
Rect transform (Matrix arg0)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Rect (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Rect obj)
Detailed Description
A rect holds four coordinates for a rectangle. The coordinates for a rectangle include left, top, right, bottom. Width () and height () defines the rectangle's width and height. LLx and LLy defines lower left corner, and URx and URy defines the upper right corner.
Constructor & Destructor Documentation
Rect() [1/4]
com.datalogics.PDFL.Rect.Rect (long cPtr, boolean cMemoryOwn) protected
Rect() [2/4]
com.datalogics.PDFL.Rect.Rect (java.awt.geom.Rectangle2D r)
Create a Rect from a java.awt rectangle type
Note that the coordinate systems are inverted for PDFL. Smaller X/Y values are assigned to the lower left coordinate.
Parameters
r a rectangle
Rect() [3/4]
com.datalogics.PDFL.Rect.Rect ()
Create a rectangle with all values zero.
Rect() [4/4]
com.datalogics.PDFL.Rect.Rect (double nLLx, double nLLy, double nURx, double nURy)
Create a Rect.
Parameters
nLLx the X coordinate of the lower left corner of the rectangle
nLLy the Y coordinate of the lower left corner of the rectangle
nURx the X coordinate of the upper right corner of the rectangle
nURy the Y coordinate of the upper right corner of the rectangle
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.Rect.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.Rect.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.Rect.equals (Object rhs)
finalize()
void com.datalogics.PDFL.Rect.finalize () protected
getBottom()
double com.datalogics.PDFL.Rect.getBottom ()
the Y coordinate of the lower left corner of the rectangle.
getCPtr()
static long com.datalogics.PDFL.Rect.getCPtr (Rect obj) static protected
Referenced by com.datalogics.PDFL.Page.addNewAnnotation(), com.datalogics.PDFL.Content.addPage(), com.datalogics.PDFL.Annotation.Annotation(), com.datalogics.PDFL.CircleAnnotation.CircleAnnotation(), com.datalogics.PDFL.Page.createAnnotation(), com.datalogics.PDFL.Document.createPage(), com.datalogics.PDFL.FreeTextAnnotation.FreeTextAnnotation(), com.datalogics.PDFL.Page.getImage(), com.datalogics.PDFL.Page.getImageSeparations(), com.datalogics.PDFL.InkAnnotation.InkAnnotation(), com.datalogics.PDFL.Rect.inRect(), com.datalogics.PDFL.Rect.intersect(), com.datalogics.PDFL.LineAnnotation.LineAnnotation(), com.datalogics.PDFL.LinkAnnotation.LinkAnnotation(), com.datalogics.PDFL.Rect.overlaps(), com.datalogics.PDFL.Page.Page(), com.datalogics.PDFL.Text.rectIntersectsCharacter(), com.datalogics.PDFL.Text.rectIntersectsTextRun(), com.datalogics.PDFL.RemoteDestination.RemoteDestination(), com.datalogics.PDFL.Page.setArtBox(), com.datalogics.PDFL.Page.setBleedBox(), com.datalogics.PDFL.ShadingPattern.setBoundingBox(), com.datalogics.PDFL.PrintParams.setBoundingBox(), com.datalogics.PDFL.Page.setCropBox(), com.datalogics.PDFL.RemoteDestination.setDestRect(), com.datalogics.PDFL.DrawParams.setDestRect(), com.datalogics.PDFL.ViewDestination.setDestRect(), com.datalogics.PDFL.Page.setMediaBox(), com.datalogics.PDFL.Annotation.setRect(), com.datalogics.PDFL.Page.setTrimBox(), com.datalogics.PDFL.DrawParams.setUpdateRect(), com.datalogics.PDFL.SquareAnnotation.SquareAnnotation(), and com.datalogics.PDFL.ViewDestination.ViewDestination().
getHeight()
double com.datalogics.PDFL.Rect.getHeight ()
The height of the Rect.
getLeft()
double com.datalogics.PDFL.Rect.getLeft ()
the X coordinate of the lower left corner of the rectangle.
getLLx()
double com.datalogics.PDFL.Rect.getLLx ()
the X coordinate of the lower left corner of the rectangle.
getLLy()
double com.datalogics.PDFL.Rect.getLLy ()
the Y coordinate of the lower left corner of the rectangle.
getRight()
double com.datalogics.PDFL.Rect.getRight ()
the X coordinate of the upper right corner of the rectangle.
getTop()
double com.datalogics.PDFL.Rect.getTop ()
the Y coordinate of the upper right corner of the rectangle.
getURx()
double com.datalogics.PDFL.Rect.getURx ()
the X coordinate of the upper right corner of the rectangle.
getURy()
double com.datalogics.PDFL.Rect.getURy ()
the Y coordinate of the upper right corner of the rectangle.
getWidth()
double com.datalogics.PDFL.Rect.getWidth ()
The width of the Rect.
inRect()
boolean com.datalogics.PDFL.Rect.inRect (Rect r2)
Check if this rectangle is inside the parameter rectangle.
intersect()
Rect com.datalogics.PDFL.Rect.intersect (Rect r2)
Obtain the intersection of this rectangle and another rectangle.
isEmpty()
boolean com.datalogics.PDFL.Rect.isEmpty ()
Check if this rectangle is empty.
overlaps()
boolean com.datalogics.PDFL.Rect.overlaps (Rect r2)
Check if two rectangles overlap.
setBottom()
void com.datalogics.PDFL.Rect.setBottom (double bottom)
the Y coordinate of the lower left corner of the rectangle.
setLeft()
void com.datalogics.PDFL.Rect.setLeft (double left)
the X coordinate of the lower left corner of the rectangle.
setLLx()
void com.datalogics.PDFL.Rect.setLLx (double value)
the X coordinate of the lower left corner of the rectangle.
setLLy()
void com.datalogics.PDFL.Rect.setLLy (double value)
the Y coordinate of the lower left corner of the rectangle.
setRight()
void com.datalogics.PDFL.Rect.setRight (double right)
the X coordinate of the upper right corner of the rectangle.
setTop()
void com.datalogics.PDFL.Rect.setTop (double top)
the Y coordinate of the upper right corner of the rectangle.
setURx()
void com.datalogics.PDFL.Rect.setURx (double value)
the X coordinate of the upper right corner of the rectangle.
setURy()
void com.datalogics.PDFL.Rect.setURy (double value)
the Y coordinate of the upper right corner of the rectangle.
toString()
String com.datalogics.PDFL.Rect.toString ()
transform()
Rect com.datalogics.PDFL.Rect.transform (Matrix arg0)
Transform the coordinates of the rectangle by the given Matrix Object.