Programming Reference: Main Page
com.datalogics.PDFL.Group Class Reference
Public Member Functions
Group clone ()
Group clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Group colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
synchronized void delete ()
Rect getBoundingBox ()
Clip getClip ()
Content getContent ()
Matrix getMatrix ()
Group ()
Group (Content content)
void rotate (double theta)
void scale (double sx, double sy)
void setClip (Clip clip)
void setContent (Content content)
void setMatrix (Matrix matrix)
void translate (double tx, double ty)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Group (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Element obj)
static long getCPtr (Group obj)
Detailed Description
A set of elements to be used within a PDF document. A Group represents objects in a content object, but it resides in memory.
Therefore the group has no state and is not represented in any way in a PDF content stream. When used in a Clip, a group is used to associate Text objects into a single clipping object.
Constructor & Destructor Documentation
Group() [1/3]
com.datalogics.PDFL.Group.Group (long cPtr, boolean cMemoryOwn) protected
Group() [2/3]
com.datalogics.PDFL.Group.Group ()
Create a new Group.
Group() [3/3]
com.datalogics.PDFL.Group.Group (Content content)
Create a Group with the given Content.
Parameters
content The new Content of the group.
Member Function Documentation
clone() [1/2]
Group com.datalogics.PDFL.Group.clone ()
Makes a copy of the group.
Make a copy of an group to obtain a new group that has a distinct set of attributes.
Returns
The copied group.
Reimplemented from com.datalogics.PDFL.Element.
clone() [2/2]
Group com.datalogics.PDFL.Group.clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Makes a copy of the group.
Make a copy of an group to obtain a new group that has a distinct set of attributes.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied group.
Reimplemented from com.datalogics.PDFL.Element.
colorConvert()
Group com.datalogics.PDFL.Group.colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
Applies the specified ICC ColorProfile to the elements in the Group object
Parameters
document The document the element belongs to.
prof The ICC ColorProfile to be applied.
intent The ICC Rendering Intent for the ColorProfile
embed If true, embed the color space and make the object calibrated. If it is false and the target profile is CMYK, RGB, or Gray, the colors space of the resulting objects, after conversion, will be DeviceCMYK, DeviceRGB, or DeviceGray, respectively.
Returns
A new Group object with the applied ICC ColorProfile.
delete() [1/2]
synchronized void com.datalogics.PDFL.Group.delete ()
Reimplemented from com.datalogics.PDFL.Element.
delete() [2/2]
synchronized void com.datalogics.PDFL.Group.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Element.
finalize()
void com.datalogics.PDFL.Group.finalize () protected
Reimplemented from com.datalogics.PDFL.Element.
getBoundingBox()
Rect com.datalogics.PDFL.Element.getBoundingBox () inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
getClip()
Clip com.datalogics.PDFL.Element.getClip () inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
getContent()
Content com.datalogics.PDFL.Group.getContent ()
Obtain the content of a Group.
getCPtr() [1/2]
static long com.datalogics.PDFL.Element.getCPtr (Element obj) static protected inherited
Referenced by com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Content.addElement(), and com.datalogics.PDFL.Content.Content().
getCPtr() [2/2]
static long com.datalogics.PDFL.Group.getCPtr (Group obj) static protected
getMatrix()
Matrix com.datalogics.PDFL.Element.getMatrix () inherited
The transformation matrix for the element.
rotate()
void com.datalogics.PDFL.Element.rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Reimplemented in com.datalogics.PDFL.Image.
scale()
void com.datalogics.PDFL.Element.scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
setClip()
void com.datalogics.PDFL.Element.setClip (Clip clip) inherited
Sets the current Clip for an Element.
Parameters
clip The clip to set as the current clip for this element.
setContent()
void com.datalogics.PDFL.Group.setContent (Content content)
Set the content of a Group.
Parameters
content The new Content of the group.
setMatrix()
void com.datalogics.PDFL.Element.setMatrix (Matrix matrix) inherited
Set the transformation matrix for the element.
Parameters
matrix the transformation matrix for the element.
translate()
void com.datalogics.PDFL.Element.translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Reimplemented in com.datalogics.PDFL.Image.