Programming Reference: Main Page
com.datalogics.PDFL.Element Class Reference
Public Member Functions
Element clone ()
Element clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
synchronized void delete ()
Rect getBoundingBox ()
Clip getClip ()
Matrix getMatrix ()
void rotate (double theta)
void scale (double sx, double sy)
void setClip (Clip clip)
void setMatrix (Matrix matrix)
void translate (double tx, double ty)
Protected Member Functions
synchronized void delete (Boolean disposing)
Element (long cPtr, boolean cMemoryOwn)
void finalize ()
Static Protected Member Functions
static long getCPtr (Element obj)
Detailed Description
The base class for elements of the content of a page. An element is a building block; everything in a PDF file is an element. An element object can be associated with a large amount of unmanaged memory in APDFL and should be deleted when the object is no longer in use.
Constructor & Destructor Documentation
Element()
com.datalogics.PDFL.Element.Element (long cPtr, boolean cMemoryOwn) protected
Member Function Documentation
clone() [1/2]
Element com.datalogics.PDFL.Element.clone ()
Makes a copy of the element.
Make a copy of an element to obtain a new element that has a distinct set of attributes.
Note: TextRun objects may not be cloned.
Returns
The copied element.
Reimplemented in com.datalogics.PDFL.Text, com.datalogics.PDFL.Path, com.datalogics.PDFL.Image, com.datalogics.PDFL.Group, com.datalogics.PDFL.Form, and com.datalogics.PDFL.Container.
clone() [2/2]
Element com.datalogics.PDFL.Element.clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Makes a copy of the element.
Make a copy of an element to obtain a new element that has a distinct set of attributes.
Note: TextRun objects may not be cloned.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied element.
Reimplemented in com.datalogics.PDFL.Text, com.datalogics.PDFL.Path, com.datalogics.PDFL.Image, com.datalogics.PDFL.Group, and com.datalogics.PDFL.Container.
delete() [1/2]
synchronized void com.datalogics.PDFL.Element.delete ()
Reimplemented in com.datalogics.PDFL.TextRun, com.datalogics.PDFL.Text, com.datalogics.PDFL.Shading, com.datalogics.PDFL.PostScript, com.datalogics.PDFL.Path, com.datalogics.PDFL.Image, com.datalogics.PDFL.Group, com.datalogics.PDFL.Form, and com.datalogics.PDFL.Container.
delete() [2/2]
synchronized void com.datalogics.PDFL.Element.delete (Boolean disposing) protected
Reimplemented in com.datalogics.PDFL.TextRun, com.datalogics.PDFL.Text, com.datalogics.PDFL.Shading, com.datalogics.PDFL.PostScript, com.datalogics.PDFL.Path, com.datalogics.PDFL.Image, com.datalogics.PDFL.Group, com.datalogics.PDFL.Form, and com.datalogics.PDFL.Container.
finalize()
void com.datalogics.PDFL.Element.finalize () protected
Reimplemented in com.datalogics.PDFL.TextRun, com.datalogics.PDFL.Text, com.datalogics.PDFL.Shading, com.datalogics.PDFL.PostScript, com.datalogics.PDFL.Path, com.datalogics.PDFL.Image, com.datalogics.PDFL.Group, com.datalogics.PDFL.Form, and com.datalogics.PDFL.Container.
getBoundingBox()
Rect com.datalogics.PDFL.Element.getBoundingBox ()
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
getClip()
Clip com.datalogics.PDFL.Element.getClip ()
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
getCPtr()
static long com.datalogics.PDFL.Element.getCPtr (Element obj) static protected
Referenced by com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Content.addElement(), and com.datalogics.PDFL.Content.Content().
getMatrix()
Matrix com.datalogics.PDFL.Element.getMatrix ()
The transformation matrix for the element.
rotate()
void com.datalogics.PDFL.Element.rotate (double theta)
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Reimplemented in com.datalogics.PDFL.Image.
scale()
void com.datalogics.PDFL.Element.scale (double sx, double sy)
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
setClip()
void com.datalogics.PDFL.Element.setClip (Clip clip)
Sets the current Clip for an Element.
Parameters
clip The clip to set as the current clip for this element.
setMatrix()
void com.datalogics.PDFL.Element.setMatrix (Matrix matrix)
Set the transformation matrix for the element.
Parameters
matrix the transformation matrix for the element.
translate()
void com.datalogics.PDFL.Element.translate (double tx, double ty)
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Reimplemented in com.datalogics.PDFL.Image.