Programming Reference: Main Page
com.datalogics.PDFL.Matrix Class Reference
Public Member Functions
Matrix concat (Matrix Mt)
synchronized void delete ()
boolean equals (Object rhs)
double getA ()
double getB ()
double getC ()
double getD ()
double getH ()
double getV ()
Matrix invert ()
Matrix ()
Matrix (double na, double nb, double nc, double nd, double nh, double nv)
Matrix rotate (double T)
Matrix scale (double sx, double sy)
void setA (double value)
void setB (double value)
void setC (double value)
void setD (double value)
void setH (double value)
void setV (double value)
String toString ()
Matrix translate (double tx, double ty)
Static Public Member Functions
static Matrix multiply (Matrix m1, Matrix m2)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Matrix (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Matrix obj)
Detailed Description
A transformation matrix in a PDF file is specified by six numbers. The matrix is usually in the form of an array containing the six elements [a b c d h v].
A translation is specified as [ 1 0 0 1 tx ty], where tx and ty are the distance to translate from the origin of the coordinate system in the horizontal and vertical dimension, respectively.
A scaling is obtained by [sx 0 0 sy 0 0]. This scales the coordinates so that 1 unit in the horizontal and vertical dimension of the new coordinate system is the same size as sx and sy units, respectively, as in the previous coordinate system.
A rotation is produced by [ cos T sin T -sin T cos T 0 0 ], which has the effect of rotating the coordinate system axes by an angle T (degrees) counterclockwise.
For a description of the Transformation Matrices, see section 8.3.4 of the ISO 32000-1:2008, Document Management-Portable Document Format-Part 1: PDF 1.7, page 119.
This material indicates that the matrix specifying a transformation is premultiplied with the current transformation matrix, i.e.,
M' = Mt * M
The implementation of the Scale, Rotate, and Translate convenience functions of Matrix reflect the same order of operations, so that they are consistent with the PDF Reference manual. They are also consistent with the scale, rotate, and translate operators in PostScript, from which the coordinate system model in PDF is derived.
Constructor & Destructor Documentation
Matrix() [1/3]
com.datalogics.PDFL.Matrix.Matrix (long cPtr, boolean cMemoryOwn) protected
Matrix() [2/3]
com.datalogics.PDFL.Matrix.Matrix ()
the default constructor creates a transformation matrix to translate the rectangle 1 element (1/72nd of an inch) from the origin.
Matrix() [3/3]
com.datalogics.PDFL.Matrix.Matrix (double na, double nb, double nc, double nd, double nh, double nv)
Member Function Documentation
concat()
Matrix com.datalogics.PDFL.Matrix.concat (Matrix Mt)
Concatenate a matrix onto an existing matrix. The concatenation is done according to section 8.3.4, "Transformation Matrices", of the ISO 32000-1:2008, Document Management-Portable Document Format-Part 1: PDF 1.7, page 119.
The product returned is:
M' = Mt * M
This corresponds to the action of the cm operator in section 4.3.3, "Graphic State Operators".
Returns
the transformed matrix
delete() [1/2]
synchronized void com.datalogics.PDFL.Matrix.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.Matrix.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.Matrix.equals (Object rhs)
finalize()
void com.datalogics.PDFL.Matrix.finalize () protected
getA()
double com.datalogics.PDFL.Matrix.getA ()
getB()
double com.datalogics.PDFL.Matrix.getB ()
getC()
double com.datalogics.PDFL.Matrix.getC ()
getCPtr()
static long com.datalogics.PDFL.Matrix.getCPtr (Matrix obj) static protected
Referenced by com.datalogics.PDFL.Text.addGlyphs(), com.datalogics.PDFL.Content.addPage(), com.datalogics.PDFL.Text.changeMatrixForTextRun(), com.datalogics.PDFL.Text.changeTextMatrixForTextRun(), com.datalogics.PDFL.Matrix.concat(), com.datalogics.PDFL.Point.distanceTransform(), com.datalogics.PDFL.Matrix.multiply(), com.datalogics.PDFL.DrawParams.setMatrix(), com.datalogics.PDFL.Element.setMatrix(), com.datalogics.PDFL.TextRun.TextRun(), com.datalogics.PDFL.Point.transform(), com.datalogics.PDFL.Quad.transform(), and com.datalogics.PDFL.Rect.transform().
getD()
double com.datalogics.PDFL.Matrix.getD ()
getH()
double com.datalogics.PDFL.Matrix.getH ()
getV()
double com.datalogics.PDFL.Matrix.getV ()
invert()
Matrix com.datalogics.PDFL.Matrix.invert ()
Invert the Matrix object and return a new Matrix object.
multiply()
static Matrix com.datalogics.PDFL.Matrix.multiply (Matrix m1, Matrix m2) static
Multiply two transformation matrices.
Parameters
m1 a matrix
m2 a matrix
Returns
the matrix product m1 x m2
rotate()
Matrix com.datalogics.PDFL.Matrix.rotate (double T)
Rotate a matrix by T degrees counterclockwise units. Rotation is done by creating the matrix [ cos T sin T -sin T cos T 0 0 ], and calling the Concat function with that matrix.
Parameters
T The rotation, counterclockwise
Returns
the result [cos T sin T -sin T 0 0] * M
scale()
Matrix com.datalogics.PDFL.Matrix.scale (double sx, double sy)
Scale a matrix by (sx,sy) units. Scaling is done by creating the matrix [sx 0 0 sy 0 0], and calling the Concat function with that matrix.
Parameters
sx X scaling factor
sy Y scaling factor
Returns
the result [sx 0 0 sy 0 0] * M
setA()
void com.datalogics.PDFL.Matrix.setA (double value)
setB()
void com.datalogics.PDFL.Matrix.setB (double value)
setC()
void com.datalogics.PDFL.Matrix.setC (double value)
setD()
void com.datalogics.PDFL.Matrix.setD (double value)
setH()
void com.datalogics.PDFL.Matrix.setH (double value)
setV()
void com.datalogics.PDFL.Matrix.setV (double value)
toString()
String com.datalogics.PDFL.Matrix.toString ()
translate()
Matrix com.datalogics.PDFL.Matrix.translate (double tx, double ty)
Translate a matrix by (tx,ty) units. Translation is done by creating the matrix [ 1 0 0 1 tx ty ], and calling the Concat function with that matrix.
Parameters
tx X translation distance
ty Y translation distance
Returns
the result [1 0 0 1 tx ty] * M