Programming Reference: Main Page
com.datalogics.PDFL.ProgressMonitor Class Reference
Public Member Functions
.datalogics.metadata.Callback void beginOperation ()
synchronized void delete ()
.datalogics.metadata.Callback void endOperation ()
.datalogics.metadata.Callback int getCurrentValue ()
.datalogics.metadata.Callback int getDuration ()
ProgressMonitor ()
.datalogics.metadata.Callback void setCurrentValue (int currentValue)
.datalogics.metadata.Callback void setDuration (int duration)
.datalogics.metadata.Callback void setText (String text)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
ProgressMonitor (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (ProgressMonitor obj)
Detailed Description
Represents the progress of an operation. The class can display a dialog if a process will take time, and the Progress method can indicate how long the process will last.
Constructor & Destructor Documentation
ProgressMonitor() [1/2]
com.datalogics.PDFL.ProgressMonitor.ProgressMonitor (long cPtr, boolean cMemoryOwn) protected
ProgressMonitor() [2/2]
com.datalogics.PDFL.ProgressMonitor.ProgressMonitor ()
Member Function Documentation
beginOperation()
.datalogics.metadata.Callback void com.datalogics.PDFL.ProgressMonitor.beginOperation ()
Initializes the progress monitor and displays it with a current value of zero. This method will be called first when the progress monitor is used.
delete() [1/2]
synchronized void com.datalogics.PDFL.ProgressMonitor.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.ProgressMonitor.delete (Boolean disposing) protected
endOperation()
.datalogics.metadata.Callback void com.datalogics.PDFL.ProgressMonitor.endOperation ()
Draws the progress monitor with its current value set to the progress monitor's duration (a full progress monitor), then removes the progress monitor from the display.
finalize()
void com.datalogics.PDFL.ProgressMonitor.finalize () protected
getCPtr()
static long com.datalogics.PDFL.ProgressMonitor.getCPtr (ProgressMonitor obj) static protected
Referenced by com.datalogics.PDFL.Document.embedFonts(), com.datalogics.PDFL.Document.insertPages(), com.datalogics.PDFL.PDFOptimizer.optimize(), and com.datalogics.PDFL.Document.save().
getCurrentValue()
.datalogics.metadata.Callback int com.datalogics.PDFL.ProgressMonitor.getCurrentValue ()
The current value of the progress monitor. The allowed value ranges from 0 (empty) to the value passed to SetDuration.
For example, if the progress monitor's duration is 10, the current value must be between 0 and 10, inclusive.
getDuration()
.datalogics.metadata.Callback int com.datalogics.PDFL.ProgressMonitor.getDuration ()
The progress monitor's duration.
setCurrentValue()
.datalogics.metadata.Callback void com.datalogics.PDFL.ProgressMonitor.setCurrentValue (int currentValue)
Sets the current value of the progress monitor and updates the display. The allowed value ranges from 0 (empty) to the value passed to SetDuration.
For example, if the progress monitor's duration is 10, the current value must be between 0 and 10, inclusive.
Parameters
currentValue The progress monitor's current value.
setDuration()
.datalogics.metadata.Callback void com.datalogics.PDFL.ProgressMonitor.setDuration (int duration)
Sets the value that corresponds to a full progress monitor display. The progress monitor is subsequently filled in by setting its current value. This method will be called before setting the progress monitor's current value.
Parameters
duration The maximum value the progress monitor will be allowed to have.
setText()
.datalogics.metadata.Callback void com.datalogics.PDFL.ProgressMonitor.setText (String text)
Display a text string in the progress monitor.