Programming Reference: Main Page
com.datalogics.PDFL.PDFStream Class Reference
Public Member Functions
PDFObject clone ()
PDFObject clone (Document doc)
PDFObject clone (Document doc, boolean indirect)
PDFObject clone (PDFObject obj)
PDFObject clone (PDFObject obj, boolean indirect)
PDFObjectComparison compareTo (PDFObject rhs)
synchronized void delete ()
void destroy ()
boolean enumPDFObjects (PDFObjectEnumProc enumProc)
boolean equals (Object rhs)
PDFDict getDict ()
Document getDocument ()
java.io.InputStream getFilteredStream ()
int getGeneration ()
int getID ()
boolean getIndirect ()
int getLength ()
int getPDFHashValue ()
java.io.InputStream getStream (PDFStreamOpenMode mode)
int getStreamPos ()
java.io.InputStream getUnfilteredStream ()
PDFStream (java.io.InputStream stream, Document doc, PDFDict encoding_dict, PDFArray encoding_params)
PDFStream (java.io.InputStream stream, PDFObject docFromObj, PDFDict encoding_dict, PDFArray encoding_params)
void SetData (java.io.InputStream stream, PDFDict encoding_dict, PDFArray encoding_params)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PDFStream (BaseInputNozzle nozzle, Document doc, PDFDict encoding_dict, PDFArray encoding_params)
PDFStream (BaseInputNozzle nozzle, PDFObject docFromObj, PDFDict encoding_dict, PDFArray encoding_params)
PDFStream (long cPtr, boolean cMemoryOwn)
void setDataInternal (BaseInputNozzle nozzle, PDFDict encoding_dict, PDFArray encoding_params)
Static Protected Member Functions
static long getCPtr (PDFObject obj)
static long getCPtr (PDFStream obj)
Detailed Description
Represents a stream of data within a PDF document. All objects in a PDF document are built from a collection of simpler objects that represent fundamental datatypes like numbers, strings and arrays.
PDFObject and its subclasses allow direct access and manipulation of these simple objects. Some subclasses represent single data elements (e.g. PDFInteger represents a single integer value); other subclasses represent a collection of PDFObjects (e.g. PDFArray is an indexed array of data elements).
A PDFStream represents a stream of unsigned bytes, and may be inserted into any collection object. It includes a dictionary that describes how the data in the stream is encoded and other useful information about the stream. A PDFStream is always an indirect object.
PDFStreams can be encoded using built-in filters. These filters include compression schemes for most popular image formats, and text encoding translators to permit safe transmission of the document over the Internet. The data in a PDFStream will be automatically encoded when it is created; the user can read either the encoded (raw) or decoded (filtered) data.
PDFStreams can be used for any large collection of data that need not be read into memory all at once, including image data, multimedia data or XML markup.
Constructor & Destructor Documentation
PDFStream() [1/5]
com.datalogics.PDFL.PDFStream.PDFStream (long cPtr, boolean cMemoryOwn) protected
PDFStream() [2/5]
com.datalogics.PDFL.PDFStream.PDFStream (java.io.InputStream stream, Document doc, PDFDict encoding_dict, PDFArray encoding_params)
General constructor
Parameters
stream java.io.InputStream which will provide data for this PDFStream
doc Document object containing this PDFStream
encoding_dict PDFDict describing properties of this stream, including the encoding
encoding_params PDFArray describing parameters for encoding this stream
PDFStream() [3/5]
com.datalogics.PDFL.PDFStream.PDFStream (java.io.InputStream stream, PDFObject docFromObj, PDFDict encoding_dict, PDFArray encoding_params)
General constructor
Parameters
stream java.io.InputStream which will provide data for this PDFStream
docFromObj The new PDFArray will be created in the same document as this object.
encoding_dict PDFDict describing properties of this stream, including the encoding
encoding_params PDFArray describing parameters for encoding this stream
PDFStream() [4/5]
com.datalogics.PDFL.PDFStream.PDFStream (BaseInputNozzle nozzle, Document doc, PDFDict encoding_dict, PDFArray encoding_params) protected
PDFStream() [5/5]
com.datalogics.PDFL.PDFStream.PDFStream (BaseInputNozzle nozzle, PDFObject docFromObj, PDFDict encoding_dict, PDFArray encoding_params) protected
Member Function Documentation
clone() [1/5]
PDFObject com.datalogics.PDFL.PDFObject.clone () inherited
Makes a new copy of this PDFObject in memory, in the same document and using same direct/indirect setting as this PDFObject.
clone() [2/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (Document doc) inherited
Makes a new copy of this PDFObject in memory, in the supplied document, using the same direct/indirect setting as this PDFObject.
clone() [3/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (Document doc, boolean indirect) inherited
Makes a new copy of this PDFObject in memory, in the supplied document, using supplied direct/indirect setting.
clone() [4/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (PDFObject obj) inherited
Makes a new copy of this PDFObject in memory, in the same document as another object, using the same direct/indirect setting as this PDFObject.
clone() [5/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (PDFObject obj, boolean indirect) inherited
Makes a new copy of this PDFObject in memory, in the same document as another object, using supplied direct/indirect setting.
compareTo()
PDFObjectComparison com.datalogics.PDFL.PDFObject.compareTo (PDFObject rhs) inherited
Compares this object to another object. The result is useful for ordering or sorting PDFObjects. No other significance should be attached to the result. In particular, an unequal result indicates nothing about the type of either object.
The result is valid only within a single instance of the document.
Parameters
rhs the other PDFObject to compare.
Returns
A PDFObjectComparison value that relates this object to the rhs object
delete() [1/2]
synchronized void com.datalogics.PDFL.PDFStream.delete ()
Reimplemented from com.datalogics.PDFL.PDFObject.
delete() [2/2]
synchronized void com.datalogics.PDFL.PDFStream.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.PDFObject.
destroy()
void com.datalogics.PDFL.PDFObject.destroy () inherited
Destroys this object.
This method does nothing if this object is a direct scalar object.
If a composite object (an array, dictionary or stream) is destroyed:
All the direct objects in it are automatically destroyed.
The indirect objects in it are not destroyed.
enumPDFObjects()
boolean com.datalogics.PDFL.PDFObject.enumPDFObjects (PDFObjectEnumProc enumProc) inherited
Enumerates the elements of a PDFObject by calling a user-supplied procedure for each component of the object.
For scalars or strings, the proc is not called, and CosObjEnum() returns true.
For dictionaries, proc is called for each key-value pair. The order in which the key-value pairs are enumerated is undefined.
For arrays, proc is called with each element as the first paramater to proc, and the NULL object as the second parameter. Array elements are enumerated in ascending order of index.
For streams, proc is called once, with the stream's dictionary as the first parameter to the proc and the NULL object as the second parameter.
Parameters
enumProc A user-supplied callback to call for each element of the object. of obj. Neither proc nor any routine called by proc may modify the object. Doing so can produce undefined results or errors. For example, if the object is an array, enumProc must not call Remove(); if the object is a dictionary, enumProc must not call Put().
Returns
Returns true if every call to enumProc returned true. As soon as any call to enumProc returns false, the enumeration stops and EnumPDFObject() returns false.
equals()
boolean com.datalogics.PDFL.PDFObject.equals (Object rhs) inherited
finalize()
void com.datalogics.PDFL.PDFStream.finalize () protected
Reimplemented from com.datalogics.PDFL.PDFObject.
getCPtr() [1/2]
static long com.datalogics.PDFL.PDFObject.getCPtr (PDFObject obj) static protected inherited
Referenced by com.datalogics.PDFL.PDFArray.add(), com.datalogics.PDFL.PDFObjectEnumProc.Call(), com.datalogics.PDFL.PDFObject.clone(), com.datalogics.PDFL.PDFObject.compareTo(), com.datalogics.PDFL.PDFArray.insert(), com.datalogics.PDFL.PDFArray.PDFArray(), com.datalogics.PDFL.PDFBoolean.PDFBoolean(), com.datalogics.PDFL.PDFDict.PDFDict(), com.datalogics.PDFL.PDFInteger.PDFInteger(), com.datalogics.PDFL.PDFName.PDFName(), com.datalogics.PDFL.PDFReal.PDFReal(), com.datalogics.PDFL.PDFStream.PDFStream(), com.datalogics.PDFL.PDFString.PDFString(), com.datalogics.PDFL.PDFArray.put(), com.datalogics.PDFL.NumberTree.put(), com.datalogics.PDFL.PDFDict.put(), com.datalogics.PDFL.NameTree.put(), and com.datalogics.PDFL.PDFArray.remove().
getCPtr() [2/2]
static long com.datalogics.PDFL.PDFStream.getCPtr (PDFStream obj) static protected
Referenced by com.datalogics.PDFL.ICCBasedColorSpace.ICCBasedColorSpace().
getDict()
PDFDict com.datalogics.PDFL.PDFStream.getDict ()
The encoding dictionary for the stream. This includes all required information for decoding the stream.
getDocument()
Document com.datalogics.PDFL.PDFObject.getDocument () inherited
The Document of which this object is a member.
Returns null if the Document is not known by DLE, or if it is a temporary document.
If the Document is not null, then it shares the same internal data with other Document objects that refer to the same file. Document objects returned this way do not contribute to the internal count that keeps the Document open, and will become invalid if the main reference to the document is disposed.
Returns
the Document in which the object resides.
getFilteredStream()
java.io.InputStream com.datalogics.PDFL.PDFStream.getFilteredStream ()
The stream data of this object, decoded according to the filter data in its dictionary.
getGeneration()
int com.datalogics.PDFL.PDFObject.getGeneration () inherited
The generation number for this object. Only indirect objects have a generation number.
getID()
int com.datalogics.PDFL.PDFObject.getID () inherited
The ID number for this object. Only indirect objects have an ID number.
getIndirect()
boolean com.datalogics.PDFL.PDFObject.getIndirect () inherited
Indicates if this object is indirect or direct.
getLength()
int com.datalogics.PDFL.PDFStream.getLength ()
The encoded length of the stream.
getPDFHashValue()
int com.datalogics.PDFL.PDFObject.getPDFHashValue () inherited
The 32-bit hash value for this object. The hash value is used internally to quickly access the object, and is not generally useful for PDFObject users. Note that two PDFObjects with equal hash values are not necessarily equal; use Equals() to check for equality.
getStream()
java.io.InputStream com.datalogics.PDFL.PDFStream.getStream (PDFStreamOpenMode mode)
The stream data of this object, processed according to the mode
Parameters
mode the open mode with which to read this stream
getStreamPos()
int com.datalogics.PDFL.PDFStream.getStreamPos ()
The byte offset of this stream in the PDF file.
getUnfilteredStream()
java.io.InputStream com.datalogics.PDFL.PDFStream.getUnfilteredStream ()
The unfiltered data of this stream object.
SetData()
void com.datalogics.PDFL.PDFStream.SetData (java.io.InputStream stream, PDFDict encoding_dict, PDFArray encoding_params)
Replace the data in this PDFStream
Parameters
stream java.io.InputStream which will provide data for this PDFStream
encoding_dict PDFDict describing properties of this stream, including the encoding
encoding_params PDFArray describing parameters for encoding this stream
setDataInternal()
void com.datalogics.PDFL.PDFStream.setDataInternal (BaseInputNozzle nozzle, PDFDict encoding_dict, PDFArray encoding_params) protected
Referenced by com.datalogics.PDFL.PDFStream.SetData().
toString()
String com.datalogics.PDFL.PDFStream.toString ()
Reimplemented from com.datalogics.PDFL.PDFObject.