Programming Reference: Main Page
com.datalogics.PDFL.PDFString Class Reference
Public Member Functions
PDFObject clone ()
PDFObject clone (Document doc)
PDFObject clone (Document doc, boolean indirect)
PDFObject clone (PDFObject obj)
PDFObject clone (PDFObject obj, boolean indirect)
PDFObjectComparison compareTo (PDFObject rhs)
synchronized void delete ()
void destroy ()
boolean enumPDFObjects (PDFObjectEnumProc enumProc)
boolean equals (Object rhs)
byte[] getBytes ()
Document getDocument ()
int getGeneration ()
int getID ()
boolean getIndirect ()
int getPDFHashValue ()
boolean getStoredAsHex ()
String getValue ()
PDFString (byte[] value, Document doc, boolean indirect, boolean storedAsHex)
PDFString (byte[] value, PDFObject docFromObj, boolean indirect, boolean storedAsHex)
PDFString (String value, Document doc, boolean indirect, boolean storedAsHex)
PDFString (String value, Document doc, boolean indirect, boolean storedAsHex, boolean storedAsUTF16)
PDFString (String value, PDFObject docFromObj, boolean indirect, boolean storedAsHex)
PDFString (String value, PDFObject docFromObj, boolean indirect, boolean storedAsHex, boolean storedAsUTF16)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PDFString (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PDFObject obj)
static long getCPtr (PDFString obj)
Detailed Description
Represents an array of unsigned bytes within a PDF document. A PDFString is a single data element that represents an array of unsigned bytes. It may be inserted into any collection object. PDFString may be a string of human readable text, but this is not required, and it may be stored either as characters or as hex values.
Constructor & Destructor Documentation
PDFString() [1/7]
com.datalogics.PDFL.PDFString.PDFString (long cPtr, boolean cMemoryOwn) protected
PDFString() [2/7]
com.datalogics.PDFL.PDFString.PDFString (byte[] value, Document doc, boolean indirect, boolean storedAsHex)
General constructor
Parameters
value Array of bytes stored in this PDFString
doc Document object containing this PDFString
indirect flag marking this as an indirect PDFObject
storedAsHex flag indicating this PDFString should be stored as hex values
PDFString() [3/7]
com.datalogics.PDFL.PDFString.PDFString (byte[] value, PDFObject docFromObj, boolean indirect, boolean storedAsHex)
General constructor
Parameters
value Array of bytes stored in this PDFString
docFromObj The new PDFString will be created in the same document as this object.
indirect flag marking this as an indirect PDFObject
storedAsHex flag indicating this PDFString should be stored as hex values
PDFString() [4/7]
com.datalogics.PDFL.PDFString.PDFString (String value, Document doc, boolean indirect, boolean storedAsHex, boolean storedAsUTF16)
String constructor
The provided string value is a Unicode string object. If storedAsUTF16 is true, it will be stored in the document at UTF-16BE. Otherwise it will be stored as PDFDocEncoding if it only contains characters within the PDFDocEncoding character set, else it will be stored as UTF-16BE.
Parameters
value String stored in this PDFString
doc Document object containing this PDFString
indirect flag marking this as an indirect PDFObject
storedAsHex flag indicating this PDFString should be stored as hex values
storedAsUTF16 flag indicating this PDFString should be stored as UTF-16BE, even if it could be encoded as PDFDocEncoding
PDFString() [5/7]
com.datalogics.PDFL.PDFString.PDFString (String value, PDFObject docFromObj, boolean indirect, boolean storedAsHex, boolean storedAsUTF16)
String constructor
The provided string value is a Unicode string object. If storedAsUTF16 is true, it will be stored in the document at UTF-16BE. Otherwise it will be stored as PDFDocEncoding if it only contains characters within the PDFDocEncoding character set, else it will be stored as UTF-16BE.
Parameters
value String stored in this PDFString
docFromObj The new PDFString will be created in the same document as this object.
indirect flag marking this as an indirect PDFObject
storedAsHex flag indicating this PDFString should be stored as hex values
storedAsUTF16 flag indicating this PDFString should be stored as UTF-16BE, even if it could be encoded as PDFDocEncoding
PDFString() [6/7]
com.datalogics.PDFL.PDFString.PDFString (String value, Document doc, boolean indirect, boolean storedAsHex)
String constructor
The provided string value is a Unicode string object. If it only contains characters within the PDFDocEncoding character set, it will be stored in that encoding; otherwise it will be stored in the document as UTF-16BE.
Parameters
value String stored in this PDFString
doc Document object containing this PDFString
indirect flag marking this as an indirect PDFObject
storedAsHex flag indicating this PDFString should be stored as hex values
PDFString() [7/7]
com.datalogics.PDFL.PDFString.PDFString (String value, PDFObject docFromObj, boolean indirect, boolean storedAsHex)
String constructor
The provided string value is a Unicode string object. If it only contains characters within the PDFDocEncoding character set, it will be stored in that encoding; otherwise it will be stored in the document as UTF-16BE.
Parameters
value String stored in this PDFString
docFromObj The new PDFString will be created in the same document as this object.
indirect flag marking this as an indirect PDFObject
storedAsHex flag indicating this PDFString should be stored as hex values
Member Function Documentation
clone() [1/5]
PDFObject com.datalogics.PDFL.PDFObject.clone () inherited
Makes a new copy of this PDFObject in memory, in the same document and using same direct/indirect setting as this PDFObject.
clone() [2/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (Document doc) inherited
Makes a new copy of this PDFObject in memory, in the supplied document, using the same direct/indirect setting as this PDFObject.
clone() [3/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (Document doc, boolean indirect) inherited
Makes a new copy of this PDFObject in memory, in the supplied document, using supplied direct/indirect setting.
clone() [4/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (PDFObject obj) inherited
Makes a new copy of this PDFObject in memory, in the same document as another object, using the same direct/indirect setting as this PDFObject.
clone() [5/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (PDFObject obj, boolean indirect) inherited
Makes a new copy of this PDFObject in memory, in the same document as another object, using supplied direct/indirect setting.
compareTo()
PDFObjectComparison com.datalogics.PDFL.PDFObject.compareTo (PDFObject rhs) inherited
Compares this object to another object. The result is useful for ordering or sorting PDFObjects. No other significance should be attached to the result. In particular, an unequal result indicates nothing about the type of either object.
The result is valid only within a single instance of the document.
Parameters
rhs the other PDFObject to compare.
Returns
A PDFObjectComparison value that relates this object to the rhs object
delete() [1/2]
synchronized void com.datalogics.PDFL.PDFString.delete ()
Reimplemented from com.datalogics.PDFL.PDFObject.
delete() [2/2]
synchronized void com.datalogics.PDFL.PDFString.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.PDFObject.
destroy()
void com.datalogics.PDFL.PDFObject.destroy () inherited
Destroys this object.
This method does nothing if this object is a direct scalar object.
If a composite object (an array, dictionary or stream) is destroyed:
All the direct objects in it are automatically destroyed.
The indirect objects in it are not destroyed.
enumPDFObjects()
boolean com.datalogics.PDFL.PDFObject.enumPDFObjects (PDFObjectEnumProc enumProc) inherited
Enumerates the elements of a PDFObject by calling a user-supplied procedure for each component of the object.
For scalars or strings, the proc is not called, and CosObjEnum() returns true.
For dictionaries, proc is called for each key-value pair. The order in which the key-value pairs are enumerated is undefined.
For arrays, proc is called with each element as the first paramater to proc, and the NULL object as the second parameter. Array elements are enumerated in ascending order of index.
For streams, proc is called once, with the stream's dictionary as the first parameter to the proc and the NULL object as the second parameter.
Parameters
enumProc A user-supplied callback to call for each element of the object. of obj. Neither proc nor any routine called by proc may modify the object. Doing so can produce undefined results or errors. For example, if the object is an array, enumProc must not call Remove(); if the object is a dictionary, enumProc must not call Put().
Returns
Returns true if every call to enumProc returned true. As soon as any call to enumProc returns false, the enumeration stops and EnumPDFObject() returns false.
equals()
boolean com.datalogics.PDFL.PDFObject.equals (Object rhs) inherited
finalize()
void com.datalogics.PDFL.PDFString.finalize () protected
Reimplemented from com.datalogics.PDFL.PDFObject.
getBytes()
byte [] com.datalogics.PDFL.PDFString.getBytes ()
Byte array of this PDFString.
This method returns the raw data of the PDFString, without respect to any encoding. It should be used when the contents of the object represent data instead of human readable text, or when direct access to the underlying data is required.
getCPtr() [1/2]
static long com.datalogics.PDFL.PDFObject.getCPtr (PDFObject obj) static protected inherited
Referenced by com.datalogics.PDFL.PDFArray.add(), com.datalogics.PDFL.PDFObjectEnumProc.Call(), com.datalogics.PDFL.PDFObject.clone(), com.datalogics.PDFL.PDFObject.compareTo(), com.datalogics.PDFL.PDFArray.insert(), com.datalogics.PDFL.PDFArray.PDFArray(), com.datalogics.PDFL.PDFBoolean.PDFBoolean(), com.datalogics.PDFL.PDFDict.PDFDict(), com.datalogics.PDFL.PDFInteger.PDFInteger(), com.datalogics.PDFL.PDFName.PDFName(), com.datalogics.PDFL.PDFReal.PDFReal(), com.datalogics.PDFL.PDFStream.PDFStream(), com.datalogics.PDFL.PDFString.PDFString(), com.datalogics.PDFL.PDFArray.put(), com.datalogics.PDFL.NumberTree.put(), com.datalogics.PDFL.PDFDict.put(), com.datalogics.PDFL.NameTree.put(), and com.datalogics.PDFL.PDFArray.remove().
getCPtr() [2/2]
static long com.datalogics.PDFL.PDFString.getCPtr (PDFString obj) static protected
Referenced by com.datalogics.PDFL.NameTree.get(), com.datalogics.PDFL.NameTree.put(), and com.datalogics.PDFL.NameTree.remove().
getDocument()
Document com.datalogics.PDFL.PDFObject.getDocument () inherited
The Document of which this object is a member.
Returns null if the Document is not known by DLE, or if it is a temporary document.
If the Document is not null, then it shares the same internal data with other Document objects that refer to the same file. Document objects returned this way do not contribute to the internal count that keeps the Document open, and will become invalid if the main reference to the document is disposed.
Returns
the Document in which the object resides.
getGeneration()
int com.datalogics.PDFL.PDFObject.getGeneration () inherited
The generation number for this object. Only indirect objects have a generation number.
getID()
int com.datalogics.PDFL.PDFObject.getID () inherited
The ID number for this object. Only indirect objects have an ID number.
getIndirect()
boolean com.datalogics.PDFL.PDFObject.getIndirect () inherited
Indicates if this object is indirect or direct.
getPDFHashValue()
int com.datalogics.PDFL.PDFObject.getPDFHashValue () inherited
The 32-bit hash value for this object. The hash value is used internally to quickly access the object, and is not generally useful for PDFObject users. Note that two PDFObjects with equal hash values are not necessarily equal; use Equals() to check for equality.
getStoredAsHex()
boolean com.datalogics.PDFL.PDFString.getStoredAsHex ()
Indicates that the data is stored as hexadecimal values.
getValue()
String com.datalogics.PDFL.PDFString.getValue ()
The byte array as a native string object. This is a convenience for typical uses where a PDFString holds a human readable string instead of a byte array.
The text may be encoded within the PDF as either UTF-16BE or PDFDocEncoding; in either case, it will be converted to a Unicode string object appropriate to the platform.
If you need to access the contents of the PDFString object without respect to an encoding, use the Bytes property.
toString()
String com.datalogics.PDFL.PDFString.toString ()
Reimplemented from com.datalogics.PDFL.PDFObject.