Programming Reference: Main Page
com.datalogics.PDFL.OptionalContentOrderNode Class Reference
Public Member Functions
synchronized void delete ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
OptionalContentOrderNode (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (OptionalContentOrderNode obj)
Detailed Description
Base class for items in the OptionalContentConfig Order array. Items in the OptionalContentConfig's Order array are either OptionalContentOrderLeaf or OptionalContentOrderArray. This is the base class for both; you cannot instantiate an OptionalContentOrderNode, only one of its child classes.
Constructor & Destructor Documentation
OptionalContentOrderNode()
com.datalogics.PDFL.OptionalContentOrderNode.OptionalContentOrderNode (long cPtr, boolean cMemoryOwn) protected
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.OptionalContentOrderNode.delete ()
Reimplemented in com.datalogics.PDFL.OptionalContentOrderLeaf, and com.datalogics.PDFL.OptionalContentOrderArray.
delete() [2/2]
synchronized void com.datalogics.PDFL.OptionalContentOrderNode.delete (Boolean disposing) protected
Reimplemented in com.datalogics.PDFL.OptionalContentOrderLeaf, and com.datalogics.PDFL.OptionalContentOrderArray.
finalize()
void com.datalogics.PDFL.OptionalContentOrderNode.finalize () protected
Reimplemented in com.datalogics.PDFL.OptionalContentOrderLeaf, and com.datalogics.PDFL.OptionalContentOrderArray.
getCPtr()
static long com.datalogics.PDFL.OptionalContentOrderNode.getCPtr (OptionalContentOrderNode obj) static protected
Referenced by com.datalogics.PDFL.OptionalContentOrderArray.add(), com.datalogics.PDFL.OptionalContentOrderArray.insert(), and com.datalogics.PDFL.OptionalContentOrderArray.put().