Programming Reference: Main Page
com.datalogics.PDFL.PrintCancelProc Class Reference
Public Member Functions
.datalogics.metadata.Callback boolean Call ()
synchronized void delete ()
PrintCancelProc ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PrintCancelProc (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PrintCancelProc obj)
Detailed Description
Print cancellation callback function, a class used to cancel print operations. A PrintCancelProc() is typically passed to some method that takes a long time to complete. At frequent intervals, the method calls the PrintCancelProc().
If the PrintCancelProc() returns true, the method cancels its operation; if the PrintCancelProc() returns false, the method continues.
Constructor & Destructor Documentation
PrintCancelProc() [1/2]
com.datalogics.PDFL.PrintCancelProc.PrintCancelProc (long cPtr, boolean cMemoryOwn) protected
PrintCancelProc() [2/2]
com.datalogics.PDFL.PrintCancelProc.PrintCancelProc ()
Print cancellation callback function, a class used to cancel print operations. A PrintCancelProc() is typically passed to some method that takes a long time to complete. At frequent intervals, the method calls the PrintCancelProc().
If the PrintCancelProc() returns true, the method cancels its operation; if the PrintCancelProc() returns false, the method continues.
Member Function Documentation
Call()
.datalogics.metadata.Callback boolean com.datalogics.PDFL.PrintCancelProc.Call ()
delete() [1/2]
synchronized void com.datalogics.PDFL.PrintCancelProc.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.PrintCancelProc.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.PrintCancelProc.finalize () protected
getCPtr()
static long com.datalogics.PDFL.PrintCancelProc.getCPtr (PrintCancelProc obj) static protected
Referenced by com.datalogics.PDFL.Document.exportAsPostScript(), com.datalogics.PDFL.Document.print(), and com.datalogics.PDFL.Document.printToFile().