Programming Reference: Main Page
com.datalogics.PDFL.Bookmark Class Reference
Public Member Functions
void addChild (Bookmark child)
void addNextSibling (Bookmark NewRightSibling)
void addPreviousSibling (Bookmark NewLeftSibling)
void addSubtree (Bookmark subtree, String title)
Bookmark createNewChild (Page page, String title)
Bookmark createNewChild (String title)
Bookmark createNewSibling (String title)
synchronized void delete ()
void destroy ()
boolean equals (Object rhs)
Bookmark findDescendentBookmark (String title)
Bookmark findDescendentBookmark (String title, int maxDepth)
Action getAction ()
Color getColor ()
int getCount ()
Bookmark getFirstChild ()
java.util.EnumSet< BookmarkFlags > getFlags ()
int getIndent ()
Bookmark getLastChild ()
Bookmark getNext ()
boolean getOpen ()
Bookmark getParent ()
PDFDict getPDFDict ()
Bookmark getPrevious ()
String getTitle ()
ViewDestination getViewDestination ()
boolean hasChildren ()
boolean isOpen ()
void setAction (Action action)
void setColor (Color bookmarkcolor)
void setFlags (java.util.EnumSet< BookmarkFlags > arg0)
void setOpen (boolean openvalue)
void setTitle (String title)
String toString ()
void unlink ()
Protected Member Functions
Bookmark (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (Bookmark obj)
Detailed Description
A bookmark on a page of a PDF document. Each bookmark has a title that appears on screen, and an action that specifies what happens when a user clicks on the bookmark.
The typical action for a user-created bookmark is to move to another location in the current document, although any action (see Action) can be specified. For more information on document outlines and bookmarks see section 12.3.3 of the ISO 32000-1:2008, Document Management-Portable Document Format-Part 1: PDF 1.7, page 367.
Constructor & Destructor Documentation
Bookmark()
com.datalogics.PDFL.Bookmark.Bookmark (long cPtr, boolean cMemoryOwn) protected
Member Function Documentation
addChild()
void com.datalogics.PDFL.Bookmark.addChild (Bookmark child)
Add an existing bookmark to be the child bookmark of a parent.
Parameters
child the bookmark being added.
addNextSibling()
void com.datalogics.PDFL.Bookmark.addNextSibling (Bookmark NewRightSibling)
Add a bookmark to a tree as the next (right) sibling.
Parameters
NewRightSibling The bookmark to become the new right sibling.
addPreviousSibling()
void com.datalogics.PDFL.Bookmark.addPreviousSibling (Bookmark NewLeftSibling)
Add a bookmark to a tree as the previous (left) sibling.
Parameters
NewLeftSibling The bookmark to become the new left sibling.
addSubtree()
void com.datalogics.PDFL.Bookmark.addSubtree (Bookmark subtree, String title)
Add a copy of a subtree as the new last child of a parent bookmark, and gives the subtree an initial title.
Parameters
subtree The bookmark subtree to add.
title the title of the newly added subtree.
createNewChild() [1/2]
Bookmark com.datalogics.PDFL.Bookmark.createNewChild (Page page, String title)
(Deprecated, function will be removed in version 2.5, use single-parameter CreateNewChild() method instead) Create a bookmark and add to a parent as the last child bookmark, and give the new bookmark an initial title.
Parameters
page The PDF page of the new child bookmark.
title The initial title of the new child bookmark.
Returns
The newly created child bookmark.
createNewChild() [2/2]
Bookmark com.datalogics.PDFL.Bookmark.createNewChild (String title)
Create a new bookmark and add to a parent as the last child bookmark, using supplied string as the initial text.
Parameters
title The initial text of the new child bookmark.
Returns
The newly created child bookmark.
createNewSibling()
Bookmark com.datalogics.PDFL.Bookmark.createNewSibling (String title)
Create a new bookmark in a tree as the next (right) sibling, using supplied string as the initial text.
Parameters
title The initial text for the new right sibling.
Returns
The newly created sibling bookmark.
delete() [1/2]
synchronized void com.datalogics.PDFL.Bookmark.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.Bookmark.delete (Boolean disposing) protected
destroy()
void com.datalogics.PDFL.Bookmark.destroy ()
Removes a bookmark subtree from the bookmark tree containing it.
equals()
boolean com.datalogics.PDFL.Bookmark.equals (Object rhs)
finalize()
void com.datalogics.PDFL.Bookmark.finalize () protected
findDescendentBookmark() [1/2]
Bookmark com.datalogics.PDFL.Bookmark.findDescendentBookmark (String title)
Find bookmark by its title within the subtree of which this bookmark is the root, searching within the entire subtree.
Parameters
title The title of the bookmark for which to search.
Returns
The bookmark within this bookmark's tree that has the supplied title. Returns NULL if there is no bookmark with the supplied title.
findDescendentBookmark() [2/2]
Bookmark com.datalogics.PDFL.Bookmark.findDescendentBookmark (String title, int maxDepth)
Find bookmark by its title within the subtree of which this bookmark is the root, searching within the subtree to a depth determined by maxDepth (e.g., 0 = this bookmark only and not any of its children, 1 = search one level below this bookmark level, etc.)
Parameters
title The title of the bookmark for which to search.
maxDepth If supplied, declares the number of levels below this bookmark to search. (If omitted, the entire subtree is searched.)
Returns
The bookmark within this bookmark's tree that has the supplied title. Returns NULL if there is no bookmark with the supplied title.
getAction()
Action com.datalogics.PDFL.Bookmark.getAction ()
Get the Action for a bookmark.
Returns
The action of the bookmark.
getColor()
Color com.datalogics.PDFL.Bookmark.getColor ()
Get the color of the bookmark.
Returns
the color, or null if no color was specified
getCount()
int com.datalogics.PDFL.Bookmark.getCount ()
Get the number of open bookmarks in the subtree under this bookmark.
Returns
the number of open bookmarks.
getCPtr()
static long com.datalogics.PDFL.Bookmark.getCPtr (Bookmark obj) static protected
Referenced by com.datalogics.PDFL.Bookmark.addChild(), com.datalogics.PDFL.Bookmark.addNextSibling(), com.datalogics.PDFL.Bookmark.addPreviousSibling(), and com.datalogics.PDFL.Bookmark.addSubtree().
getFirstChild()
Bookmark com.datalogics.PDFL.Bookmark.getFirstChild ()
Gets a bookmark's first child.
Returns
The first child of Bookmark, or null if Bookmark has no children.
getFlags()
java.util.EnumSet<BookmarkFlags> com.datalogics.PDFL.Bookmark.getFlags ()
Get the flags for the bookmark.
Returns
the flags
getIndent()
int com.datalogics.PDFL.Bookmark.getIndent ()
Get the indentation level of a bookmark in its containing tree.
Returns
the indentation level of the bookmark.
getLastChild()
Bookmark com.datalogics.PDFL.Bookmark.getLastChild ()
Gets a bookmark's last child.
Returns
The last child of Bookmark, or null if Bookmark has no children.
getNext()
Bookmark com.datalogics.PDFL.Bookmark.getNext ()
Gets a bookmark's next (right) sibling.
Returns
The Bookmark object's next (right) sibling. It returns null if Bookmark has no next sibling (that is, it is its parent's last child).
getOpen()
boolean com.datalogics.PDFL.Bookmark.getOpen ()
Is the bookmark open?
Returns
true if the bookmark is open.
getParent()
Bookmark com.datalogics.PDFL.Bookmark.getParent ()
Gets a bookmark's parent.
Returns
The Bookmark object's parent. It returns null if Bookmark has no parent (that is, it is the root of the tree).
getPDFDict()
PDFDict com.datalogics.PDFL.Bookmark.getPDFDict ()
Get the dictionary associated with the bookmark.
Returns
The dictionary associated with the bookmark.
getPrevious()
Bookmark com.datalogics.PDFL.Bookmark.getPrevious ()
Gets a bookmark's previous (left) sibling.
Returns
The Bookmark object's previous (left) sibling. It returns null if Bookmark has no previous sibling (that is, it is its parent's first child).
getTitle()
String com.datalogics.PDFL.Bookmark.getTitle ()
The title of the bookmark.
getViewDestination()
ViewDestination com.datalogics.PDFL.Bookmark.getViewDestination ()
If this bookmark has a GoTo action, then return the destination of the action, else return null.
Returns
the view destination
hasChildren()
boolean com.datalogics.PDFL.Bookmark.hasChildren ()
Does the bookmark have children?
Returns
true if the bookmark has children.
isOpen()
boolean com.datalogics.PDFL.Bookmark.isOpen ()
Is the bookmark open?
Returns
true if the bookmark is open.
setAction()
void com.datalogics.PDFL.Bookmark.setAction (Action action)
Set the Action for a bookmark.
Parameters
action The action to set for the bookmark.
setColor()
void com.datalogics.PDFL.Bookmark.setColor (Color bookmarkcolor)
Set the color of the bookmark.
setFlags()
void com.datalogics.PDFL.Bookmark.setFlags (java.util.EnumSet< BookmarkFlags > arg0)
Set the flags for the bookmark to the parameter values.
setOpen()
void com.datalogics.PDFL.Bookmark.setOpen (boolean openvalue)
Set if the bookmark is open or closed.
setTitle()
void com.datalogics.PDFL.Bookmark.setTitle (String title)
The title of the bookmark.
toString()
String com.datalogics.PDFL.Bookmark.toString ()
unlink()
void com.datalogics.PDFL.Bookmark.unlink ()
Unlinks the bookmark from the bookmark tree that contains it and adjusts the tree appropriately.