Programming Reference: Main Page
com.datalogics.PDFL.PageMarkFlags Enum Reference
Static Public Member Functions
static int FlagsToInt (java.lang.Iterable< PageMarkFlags > flags)
static java.util.EnumSet< PageMarkFlags > IntToFlags (int value)
Public Attributes
BLEED_MARKS
COLOR_BARS
CROP_MARKS
PAGE_INFO
REGISTRATION_MARKS
SLUR_MARKS
TRIM_MARKS
Detailed Description
Bit flags indicating which page marks are emitted for color separations.
Member Function Documentation
FlagsToInt()
static int com.datalogics.PDFL.PageMarkFlags.FlagsToInt (java.lang.Iterable< PageMarkFlags > flags) static
Referenced by com.datalogics.PDFL.SeparationParams.setPageMarksToEmit(), and com.datalogics.PDFL.PrintParams.setWhichMarks().
IntToFlags()
static java.util.EnumSet<PageMarkFlags> com.datalogics.PDFL.PageMarkFlags.IntToFlags (int value) static
Referenced by com.datalogics.PDFL.SeparationParams.getPageMarksToEmit(), and com.datalogics.PDFL.PrintParams.getWhichMarks().
Member Data Documentation
BLEED_MARKS
com.datalogics.PDFL.PageMarkFlags.BLEED_MARKS
COLOR_BARS
com.datalogics.PDFL.PageMarkFlags.COLOR_BARS
CROP_MARKS
com.datalogics.PDFL.PageMarkFlags.CROP_MARKS
PAGE_INFO
com.datalogics.PDFL.PageMarkFlags.PAGE_INFO
REGISTRATION_MARKS
com.datalogics.PDFL.PageMarkFlags.REGISTRATION_MARKS
SLUR_MARKS
com.datalogics.PDFL.PageMarkFlags.SLUR_MARKS
TRIM_MARKS
com.datalogics.PDFL.PageMarkFlags.TRIM_MARKS