var NAVTREEINDEX0 =
{
"_font_01and_01_unicode_01_information.html":[6],
"_font_01and_01_unicode_01_information.html#unicode_overview":[6,0],
"_getting_01_started.html":[1],
"_getting_01_started.html#gettingstarted_overview":[1,0],
"_licensing.html":[2],
"_licensing.html#licensing_section":[2,0],
"_licensing.html#proxy_configuration":[2,1],
"_memory_01_management.html":[3],
"_memory_01_management.html#mm_overview":[3,0],
"_o_c_r_01_processing.html":[4],
"_o_c_r_01_processing.html#mm_ocr_overview":[4,0],
"_resources_01_explained.html":[5],
"_resources_01_explained.html#resources_section":[5,0],
"index.html":[],
"index.html#main_intro_sec":[0],
"index.html#seealso":[0,0],
"pages.html":[]
};
