Adobe PDF Library Java Documentation
com.datalogics.PDFL.Point Class Reference
Public Member Functions
synchronized void delete ()
Point distanceTransform (Matrix arg0)
boolean equals (Object rhs)
double getH ()
double getV ()
Point ()
Point (double nh, double nv)
void setH (double value)
void setV (double value)
String toString ()
Point transform (Matrix arg0)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Point (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Point obj)
Detailed Description
Represents a discrete point or space in a PDF. A Point in a PDF document is in the right plane, relative to the origin being the lower left corner of the document.
Constructor & Destructor Documentation
Point() [1/3]
com.datalogics.PDFL.Point.Point (long cPtr, boolean cMemoryOwn) protected
Point() [2/3]
com.datalogics.PDFL.Point.Point ()
Create a new point at the origin (0.0, 0.0).
Point() [3/3]
com.datalogics.PDFL.Point.Point (double nh, double nv)
Create a new point at the specified coordinates.
Parameters
nh the horizontal coordinate
nv the vertical coordinate
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.Point.delete ()
Referenced by com.datalogics.PDFL.AxialShadingPattern.getCoords(), com.datalogics.PDFL.InkAnnotation.getScribble(), com.datalogics.PDFL.PolygonAnnotation.getVertices(), and com.datalogics.PDFL.PolyLineAnnotation.getVertices().
delete() [2/2]
synchronized void com.datalogics.PDFL.Point.delete (Boolean disposing) protected
distanceTransform()
Point com.datalogics.PDFL.Point.distanceTransform (Matrix arg0)
Distance Transform the Point Object by the values in the Matrix parameter, which is a transformation without any translation.
equals()
boolean com.datalogics.PDFL.Point.equals (Object rhs)
finalize()
void com.datalogics.PDFL.Point.finalize () protected
getCPtr()
static long com.datalogics.PDFL.Point.getCPtr (Point obj) static protected
Referenced by com.datalogics.PDFL.Path.addCurve(), com.datalogics.PDFL.Path.addCurveV(), com.datalogics.PDFL.Path.addCurveY(), com.datalogics.PDFL.Path.addLine(), com.datalogics.PDFL.Path.addRect(), com.datalogics.PDFL.LinkAnnotation.copyTo(), com.datalogics.PDFL.CurveTo.CurveTo(), com.datalogics.PDFL.CurveToV.CurveToV(), com.datalogics.PDFL.CurveToY.CurveToY(), com.datalogics.PDFL.LineAnnotation.LineAnnotation(), com.datalogics.PDFL.LineTo.LineTo(), com.datalogics.PDFL.MoveTo.MoveTo(), com.datalogics.PDFL.Path.moveTo(), com.datalogics.PDFL.Text.pointIntersectsCharacter(), com.datalogics.PDFL.Text.pointIntersectsTextRun(), com.datalogics.PDFL.Quad.Quad(), com.datalogics.PDFL.RectSegment.RectSegment(), com.datalogics.PDFL.LineAnnotation.setEndPoint(), com.datalogics.PDFL.LineTo.setPoint(), com.datalogics.PDFL.MoveTo.setPoint(), com.datalogics.PDFL.RectSegment.setPoint(), com.datalogics.PDFL.CurveTo.setPoint1(), com.datalogics.PDFL.CurveToY.setPoint1(), com.datalogics.PDFL.CurveTo.setPoint2(), com.datalogics.PDFL.CurveToV.setPoint2(), com.datalogics.PDFL.CurveTo.setPoint3(), com.datalogics.PDFL.CurveToV.setPoint3(), com.datalogics.PDFL.CurveToY.setPoint3(), and com.datalogics.PDFL.LineAnnotation.setStartPoint().
getH()
double com.datalogics.PDFL.Point.getH ()
The horizontal coordinate of the point.
getV()
double com.datalogics.PDFL.Point.getV ()
The vertical coordinate of the point.
setH()
void com.datalogics.PDFL.Point.setH (double value)
The horizontal coordinate of the point.
setV()
void com.datalogics.PDFL.Point.setV (double value)
The vertical coordinate of the point.
toString()
String com.datalogics.PDFL.Point.toString ()
transform()
Point com.datalogics.PDFL.Point.transform (Matrix arg0)
Transform the Point Object by the values in the Matrix parameter.