Adobe PDF Library Java Documentation
com.datalogics.PDFL.CollectionSchemaField Class Reference
Public Member Functions
CollectionSchemaField (String fieldID, SchemaFieldSubtype subtype)
synchronized void delete ()
boolean getEditable ()
String getID ()
int getIndex ()
String getName ()
SchemaFieldSubtype getSubtype ()
boolean getVisible ()
void setEditable (boolean isEditable)
void setIndex (int idx)
void setName (String name)
void setVisible (boolean isVisible)
Protected Member Functions
CollectionSchemaField (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (CollectionSchemaField obj)
Detailed Description
Allows for the creation of collection schema field objects. Parameters that are part of a schema's field may be set.
Constructor & Destructor Documentation
CollectionSchemaField() [1/2]
com.datalogics.PDFL.CollectionSchemaField.CollectionSchemaField (long cPtr, boolean cMemoryOwn) protected
CollectionSchemaField() [2/2]
com.datalogics.PDFL.CollectionSchemaField.CollectionSchemaField (String fieldID, SchemaFieldSubtype subtype)
CCollectionSchemaField allows to create CollectionSchemaField object. The constructor accepts identifier value and subtype required by the schema field.
Parameters
fieldID the schema field ID. The ID is used during creation and extraction of the schema field. It is the unique identifier of the schema field.
subtype the schema field subtype. The subtypes are predefined. The value of this parameter must correspond to the one of the SchemaFieldSubtype enum values.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.CollectionSchemaField.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.CollectionSchemaField.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.CollectionSchemaField.finalize () protected
getCPtr()
static long com.datalogics.PDFL.CollectionSchemaField.getCPtr (CollectionSchemaField obj) static protected
Referenced by com.datalogics.PDFL.CollectionSchema.addField(), com.datalogics.PDFL.FileAttachment.getCollectionItemNumber(), com.datalogics.PDFL.FileAttachment.getCollectionItemString(), com.datalogics.PDFL.CollectionSchema.removeField(), com.datalogics.PDFL.FileAttachment.setCollectionItemNumber(), and com.datalogics.PDFL.FileAttachment.setCollectionItemString().
getEditable()
boolean com.datalogics.PDFL.CollectionSchemaField.getEditable ()
GetEditable allows to obtain information about edit mode of the current field.
Returns
whether edit mode is allowed or not.
getID()
String com.datalogics.PDFL.CollectionSchemaField.getID ()
GetID allows to obtain the unique id with which schema field has been created.
Returns
the unique field's id.
getIndex()
int com.datalogics.PDFL.CollectionSchemaField.getIndex ()
GetIndex allows to obtain field index.
Returns
the index of the field.
getName()
String com.datalogics.PDFL.CollectionSchemaField.getName ()
GetName allows to obtain field name.
Returns
the field name.
getSubtype()
SchemaFieldSubtype com.datalogics.PDFL.CollectionSchemaField.getSubtype ()
GetSubtype allows to obtain the field subtype.
Returns
field subtype. One of the ShemaFieldSubtype enum values.
getVisible()
boolean com.datalogics.PDFL.CollectionSchemaField.getVisible ()
GetVisible allows to obtain information about filed visibility.
Returns
true if current schema field is visible, false otherwise.
setEditable()
void com.datalogics.PDFL.CollectionSchemaField.setEditable (boolean isEditable)
SetEditable allows to change edit mode for shema field.Its value false by default.
Parameters
isEditable pass true to allow to edit this field or false otherwise.
setIndex()
void com.datalogics.PDFL.CollectionSchemaField.setIndex (int idx)
SetIndex allows to set field index. NOTE: the field indexes are zero-based in ascending order without gaps.
Parameters
idx field index.
setName()
void com.datalogics.PDFL.CollectionSchemaField.setName (String name)
SetName allows to change field name.
Parameters
name the new field name.
setVisible()
void com.datalogics.PDFL.CollectionSchemaField.setVisible (boolean isVisible)
SetVisible allows to set field's default visibility.Its value true by default.
Parameters
isVisible the visibility flag.