Adobe PDF Library Java Documentation
com.datalogics.PDFL.Container Class Reference
Public Member Functions
Container clone ()
Container clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Container colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
Container ()
Container (String mcTag)
synchronized void delete ()
Rect getBoundingBox ()
Clip getClip ()
Content getContent ()
String getMarkedContentTag ()
Matrix getMatrix ()
OptionalContentMembershipDict getOptionalContentMembershipDict ()
PDFDict getPDFDict ()
boolean isCurrentlyVisible (OptionalContentContext occ)
boolean isCurrentlyVisible (OptionalContentContext occ, Content content)
boolean makeVisible (OptionalContentContext occ, Content content)
void rotate (double theta)
void scale (double sx, double sy)
void setClip (Clip clip)
void setContent (Content content)
void setMarkedContentTag (String mcTag)
void setMatrix (Matrix matrix)
void setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd)
void translate (double tx, double ty)
Protected Member Functions
Container (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (Container obj)
static long getCPtr (Element obj)
Detailed Description
A container class represents a group of elements on a page in a PDF file. In the PDF file, every container has a set of Marked Content tags, starting with Begin Marked Content (BMC or BDC) and ending with End Marked Content (EMC), so each container has a BMC/EMC or BDC/EMC pair of tags. These tags can be used to define the beginning and end of metadata around objects, providing information about the text and shapes within a PDF file. Containers can be nested within other containers.
Constructor & Destructor Documentation
Container() [1/3]
com.datalogics.PDFL.Container.Container (long cPtr, boolean cMemoryOwn) protected
Container() [2/3]
com.datalogics.PDFL.Container.Container ()
Create a new Container.
The new Container has no tag and is not associated with a dictionary.
Container() [3/3]
com.datalogics.PDFL.Container.Container (String mcTag)
Create a new Container with a given Marked Content Tag.
The new Container has a Marked Content tag but is not associated with a dictionary.
Member Function Documentation
clone() [1/2]
Container com.datalogics.PDFL.Container.clone ()
Makes a copy of the container.
Make a copy of an container to obtain a new container that has a distinct set of attributes.
Returns
The copied container.
Reimplemented from com.datalogics.PDFL.Element.
clone() [2/2]
Container com.datalogics.PDFL.Container.clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Makes a copy of the container.
Make a copy of an container to obtain a new container that has a distinct set of attributes.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied container.
Reimplemented from com.datalogics.PDFL.Element.
colorConvert()
Container com.datalogics.PDFL.Container.colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
Applies the specified ICC ColorProfile to the objects in the Container
Parameters
document The document the element belongs to.
prof The ICC ColorProfile to be applied.
intent The ICC Rendering Intent for the ColorProfile
embed If true, embed the color space and make the objects calibrated. If it is false and the target profile is CMYK, RGB, or Gray, the colors space of the resulting objects, after conversion, will be DeviceCMYK, DeviceRGB, or DeviceGray, respectively.
Returns
A new Container with the applied ICC ColorProfile.
delete() [1/2]
synchronized void com.datalogics.PDFL.Container.delete ()
Reimplemented from com.datalogics.PDFL.Element.
delete() [2/2]
synchronized void com.datalogics.PDFL.Container.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Element.
finalize()
void com.datalogics.PDFL.Container.finalize () protected
Reimplemented from com.datalogics.PDFL.Element.
getBoundingBox()
Rect com.datalogics.PDFL.Element.getBoundingBox () inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
getClip()
Clip com.datalogics.PDFL.Element.getClip () inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
getContent()
Content com.datalogics.PDFL.Container.getContent ()
Obtain the content of a container.
getCPtr() [1/2]
static long com.datalogics.PDFL.Container.getCPtr (Container obj) static protected
getCPtr() [2/2]
static long com.datalogics.PDFL.Element.getCPtr (Element obj) static protected inherited
Referenced by com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Content.addElement(), and com.datalogics.PDFL.Content.Content().
getMarkedContentTag()
String com.datalogics.PDFL.Container.getMarkedContentTag ()
The container's Marked Content Tag.
getMatrix()
Matrix com.datalogics.PDFL.Element.getMatrix () inherited
The transformation matrix for the element.
getOptionalContentMembershipDict()
OptionalContentMembershipDict com.datalogics.PDFL.Container.getOptionalContentMembershipDict ()
The OptionalContentMembershipDict property for this Container.
Setting this property will attach the Container to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Container is detached from any OptionalContentMembershipDict.
Returns
the OptionalContentMembershipDict
getPDFDict()
PDFDict com.datalogics.PDFL.Container.getPDFDict ()
Retrieve the PDFObject representation of this object
isCurrentlyVisible() [1/2]
boolean com.datalogics.PDFL.Container.isCurrentlyVisible (OptionalContentContext occ)
Tests whether a container is visible in a given optional content context, considering the current ON-OFF states of the optional-content groups in the optional-content dictionary (OCMD) and the dictionary's visibility policy.
If the container occurs more than once within the content, this method only checks the visibility of the first occurrence of the container.
This method determines visibility without considering the visbility of the Content object that the container belongs to. To determine the visibility of a container while taking the Content's visibility into considderation, use the alternate version of this method.
Returns
true if the container is currently visible.
isCurrentlyVisible() [2/2]
boolean com.datalogics.PDFL.Container.isCurrentlyVisible (OptionalContentContext occ, Content content)
Tests whether a container is visible in a given optional content context and content.
If the container occurs more than once within the content, this method only checks the visibility of the first occurrence of the container.
Returns
true if the container is currently visible.
makeVisible()
boolean com.datalogics.PDFL.Container.makeVisible (OptionalContentContext occ, Content content)
Makes a container visible in a given optional content context and content by manipulating the ON-OFF states of the optional content groups.
Parameters
occ The optional content context in which the container is made visible.
content The content containing the container.
Returns
true if the container is successfully made visible in the given context and content, false otherwise
rotate()
void com.datalogics.PDFL.Element.rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Reimplemented in com.datalogics.PDFL.Image.
scale()
void com.datalogics.PDFL.Element.scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
setClip()
void com.datalogics.PDFL.Element.setClip (Clip clip) inherited
Sets the current Clip for an Element.
Parameters
clip The clip to set as the current clip for this element.
setContent()
void com.datalogics.PDFL.Container.setContent (Content content)
Set the content of a container.
Parameters
content The new Content of the container.
setMarkedContentTag()
void com.datalogics.PDFL.Container.setMarkedContentTag (String mcTag)
The container's Marked Content Tag.
setMatrix()
void com.datalogics.PDFL.Element.setMatrix (Matrix matrix) inherited
Set the transformation matrix for the element.
Parameters
matrix the transformation matrix for the element.
setOptionalContentMembershipDict()
void com.datalogics.PDFL.Container.setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd)
The OptionalContentMembershipDict property for this Container.
Setting this property will attach the Container to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Container is detached from any OptionalContentMembershipDict.
Parameters
ocmd the OptionalContentMembershipDict
translate()
void com.datalogics.PDFL.Element.translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Reimplemented in com.datalogics.PDFL.Image.