Adobe PDF Library Java Documentation
com.datalogics.PDFL.Function Class Reference
Public Member Functions
java.util.List< Double > apply (java.util.List< Double > args)
synchronized void delete ()
java.util.List< Double > getDomain ()
int getNInputs ()
int getNOutputs ()
java.util.List< Double > getRange ()
void setDomain (java.util.List< Double > domain)
void setRange (java.util.List< Double > range)
String toString ()
Static Public Attributes
static final Function DEFAULT
static final Function IDENTITY
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Function (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Function obj)
Detailed Description
A function is a process. A function takes input values and manipulates them to create output values.
Constructor & Destructor Documentation
Function()
com.datalogics.PDFL.Function.Function (long cPtr, boolean cMemoryOwn) protected
Member Function Documentation
apply()
java.util.List<Double> com.datalogics.PDFL.Function.apply (java.util.List< Double > args)
Apply the function to supplied input values
Parameters
args input values for the function. The number of input values must agree with the number of inputs the function takes.
Returns
a list of the result values from the function
Reimplemented in com.datalogics.PDFL.NamedFunction.
delete() [1/2]
synchronized void com.datalogics.PDFL.Function.delete ()
Reimplemented in com.datalogics.PDFL.PostScriptCalculatorFunction, com.datalogics.PDFL.NamedFunction, and com.datalogics.PDFL.ExponentialFunction.
Referenced by com.datalogics.PDFL.AxialShadingPattern.getFunction(), and com.datalogics.PDFL.ExtendedGraphicState.getTransferFunction().
delete() [2/2]
synchronized void com.datalogics.PDFL.Function.delete (Boolean disposing) protected
Reimplemented in com.datalogics.PDFL.PostScriptCalculatorFunction, and com.datalogics.PDFL.ExponentialFunction.
finalize()
void com.datalogics.PDFL.Function.finalize () protected
Reimplemented in com.datalogics.PDFL.PostScriptCalculatorFunction, com.datalogics.PDFL.NamedFunction, and com.datalogics.PDFL.ExponentialFunction.
getCPtr()
static long com.datalogics.PDFL.Function.getCPtr (Function obj) static protected
Referenced by com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), com.datalogics.PDFL.ExtendedGraphicState.setBlackGeneration(), and com.datalogics.PDFL.ExtendedGraphicState.setUndercolorRemoval().
getDomain()
java.util.List<Double> com.datalogics.PDFL.Function.getDomain ()
The domain of the function. 2 * m elements, where m is the number of inputs to the function.
Each successive pair of elements gives the minimum and maximum values for one of the inputs.
Input values to the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getNInputs()
int com.datalogics.PDFL.Function.getNInputs ()
The number of inputs to the function.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getNOutputs()
int com.datalogics.PDFL.Function.getNOutputs ()
The number of outputs from the function.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getRange()
java.util.List<Double> com.datalogics.PDFL.Function.getRange ()
The range of the function. 2 * n elements, where n is the number of outputs from the function.
Each successive pair of elements gives the minimum and maximum values for one of the outputs.
Output values from the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
setDomain()
void com.datalogics.PDFL.Function.setDomain (java.util.List< Double > domain)
The domain of the function. 2 * m elements, where m is the number of inputs to the function.
Each successive pair of elements gives the minimum and maximum values for one of the inputs.
Input values to the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
setRange()
void com.datalogics.PDFL.Function.setRange (java.util.List< Double > range)
The range of the function. 2 * n elements, where n is the number of outputs from the function.
Each successive pair of elements gives the minimum and maximum values for one of the outputs.
Output values from the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
toString()
String com.datalogics.PDFL.Function.toString ()
Convert the function to a displayable string.
Reimplemented in com.datalogics.PDFL.PostScriptCalculatorFunction, com.datalogics.PDFL.NamedFunction, and com.datalogics.PDFL.ExponentialFunction.
Member Data Documentation
DEFAULT
final Function com.datalogics.PDFL.Function.DEFAULT static
IDENTITY
final Function com.datalogics.PDFL.Function.IDENTITY static