Adobe PDF Library Java Documentation
com.datalogics.PDFL.PDFDict Class Reference
Public Member Functions
PDFObject clone ()
PDFObject clone (Document doc)
PDFObject clone (Document doc, boolean indirect)
PDFObject clone (PDFObject obj)
PDFObject clone (PDFObject obj, boolean indirect)
PDFObjectComparison compareTo (PDFObject rhs)
boolean contains (PDFName key)
boolean contains (String key)
synchronized void delete ()
void destroy ()
boolean enumPDFObjects (PDFObjectEnumProc enumProc)
boolean equals (Object rhs)
PDFObject get (PDFName key)
PDFObject get (String key)
Document getDocument ()
int getGeneration ()
int getID ()
boolean getIndirect ()
java.util.List< PDFObject > getKeys ()
int getPDFHashValue ()
String getXMPMetadata ()
PDFDict (Document doc, boolean indirect)
PDFDict (PDFObject docFromObj, boolean indirect)
void put (PDFName key, PDFObject obj)
void put (String key, PDFObject obj)
void remove (PDFName key)
void remove (String key)
void setXMPMetadata (String metadata)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PDFDict (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PDFDict obj)
static long getCPtr (PDFObject obj)
Detailed Description
Represents an associative collection of data elements within a PDF document. All objects in a PDF document are built from a collection of simpler objects that represent fundamental datatypes like numbers, strings and arrays. PDFObject and its subclasses allow direct access and manipulation of these simple objects. Some subclasses represent single data elements, such as PDFInteger, which represents a single integer value. Other subclasses represent a collection of PDFObjects, like PDFArray, an indexed array of data elements.
A PDFDict is a heterogenous collection object that maps other PDFObjects (including other PDFDicts) to PDFName objects.
Constructor & Destructor Documentation
PDFDict() [1/3]
com.datalogics.PDFL.PDFDict.PDFDict (long cPtr, boolean cMemoryOwn) protected
PDFDict() [2/3]
com.datalogics.PDFL.PDFDict.PDFDict (Document doc, boolean indirect)
General constructor
Parameters
doc Document object containing this PDFDict
indirect flag marking this as an indirect PDFObject
PDFDict() [3/3]
com.datalogics.PDFL.PDFDict.PDFDict (PDFObject docFromObj, boolean indirect)
General constructor
Parameters
docFromObj The new PDFArray will be created in the same document as this object.
indirect flag marking this as an indirect PDFObject
Member Function Documentation
clone() [1/5]
PDFObject com.datalogics.PDFL.PDFObject.clone () inherited
Makes a new copy of this PDFObject in memory, in the same document and using same direct/indirect setting as this PDFObject.
clone() [2/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (Document doc) inherited
Makes a new copy of this PDFObject in memory, in the supplied document, using the same direct/indirect setting as this PDFObject.
clone() [3/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (Document doc, boolean indirect) inherited
Makes a new copy of this PDFObject in memory, in the supplied document, using supplied direct/indirect setting.
clone() [4/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (PDFObject obj) inherited
Makes a new copy of this PDFObject in memory, in the same document as another object, using the same direct/indirect setting as this PDFObject.
clone() [5/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (PDFObject obj, boolean indirect) inherited
Makes a new copy of this PDFObject in memory, in the same document as another object, using supplied direct/indirect setting.
compareTo()
PDFObjectComparison com.datalogics.PDFL.PDFObject.compareTo (PDFObject rhs) inherited
Compares this object to another object. The result is useful for ordering or sorting PDFObjects. No other significance should be attached to the result. In particular, an unequal result indicates nothing about the type of either object.
The result is valid only within a single instance of the document.
Parameters
rhs the other PDFObject to compare.
Returns
A PDFObjectComparison value that relates this object to the rhs object
contains() [1/2]
boolean com.datalogics.PDFL.PDFDict.contains (PDFName key)
Tests whether the given key exists in the dictionary
Parameters
key A PDFName for the key
Returns
true if the given key exists
contains() [2/2]
boolean com.datalogics.PDFL.PDFDict.contains (String key)
Tests whether the given key exists in the dictionary
Parameters
key A string representing the name for the key
Returns
true if the given key exists
delete() [1/2]
synchronized void com.datalogics.PDFL.PDFDict.delete ()
Reimplemented from com.datalogics.PDFL.PDFObject.
delete() [2/2]
synchronized void com.datalogics.PDFL.PDFDict.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.PDFObject.
destroy()
void com.datalogics.PDFL.PDFObject.destroy () inherited
Destroys this object.
This method does nothing if this object is a direct scalar object.
If a composite object (an array, dictionary or stream) is destroyed:
All the direct objects in it are automatically destroyed.
The indirect objects in it are not destroyed.
enumPDFObjects()
boolean com.datalogics.PDFL.PDFObject.enumPDFObjects (PDFObjectEnumProc enumProc) inherited
Enumerates the elements of a PDFObject by calling a user-supplied procedure for each component of the object.
For scalars or strings, the proc is not called, and CosObjEnum() returns true.
For dictionaries, proc is called for each key-value pair. The order in which the key-value pairs are enumerated is undefined.
For arrays, proc is called with each element as the first paramater to proc, and the NULL object as the second parameter. Array elements are enumerated in ascending order of index.
For streams, proc is called once, with the stream's dictionary as the first parameter to the proc and the NULL object as the second parameter.
Parameters
enumProc A user-supplied callback to call for each element of the object. of obj. Neither proc nor any routine called by proc may modify the object. Doing so can produce undefined results or errors. For example, if the object is an array, enumProc must not call Remove(); if the object is a dictionary, enumProc must not call Put().
Returns
Returns true if every call to enumProc returned true. As soon as any call to enumProc returns false, the enumeration stops and EnumPDFObject() returns false.
equals()
boolean com.datalogics.PDFL.PDFObject.equals (Object rhs) inherited
finalize()
void com.datalogics.PDFL.PDFDict.finalize () protected
Reimplemented from com.datalogics.PDFL.PDFObject.
get() [1/2]
PDFObject com.datalogics.PDFL.PDFDict.get (PDFName key)
Returns the object matching the given key.
Parameters
key A PDFName for the key
Returns
A PDFObject matching the key
get() [2/2]
PDFObject com.datalogics.PDFL.PDFDict.get (String key)
Returns the object matching the given key string.
Parameters
key A string representing the name for the key
Returns
A PDFObject matching the key
getCPtr() [1/2]
static long com.datalogics.PDFL.PDFDict.getCPtr (PDFDict obj) static protected
Referenced by com.datalogics.PDFL.Document.lookForKidsInNameTree(), com.datalogics.PDFL.PDFStream.PDFStream(), and com.datalogics.PDFL.PDFStream.setDataInternal().
getCPtr() [2/2]
static long com.datalogics.PDFL.PDFObject.getCPtr (PDFObject obj) static protected inherited
Referenced by com.datalogics.PDFL.PDFArray.add(), com.datalogics.PDFL.PDFObjectEnumProc.Call(), com.datalogics.PDFL.PDFObject.clone(), com.datalogics.PDFL.PDFObject.compareTo(), com.datalogics.PDFL.PDFArray.insert(), com.datalogics.PDFL.PDFArray.PDFArray(), com.datalogics.PDFL.PDFBoolean.PDFBoolean(), com.datalogics.PDFL.PDFDict.PDFDict(), com.datalogics.PDFL.PDFInteger.PDFInteger(), com.datalogics.PDFL.PDFName.PDFName(), com.datalogics.PDFL.PDFReal.PDFReal(), com.datalogics.PDFL.PDFStream.PDFStream(), com.datalogics.PDFL.PDFString.PDFString(), com.datalogics.PDFL.PDFArray.put(), com.datalogics.PDFL.NumberTree.put(), com.datalogics.PDFL.PDFDict.put(), com.datalogics.PDFL.NameTree.put(), and com.datalogics.PDFL.PDFArray.remove().
getDocument()
Document com.datalogics.PDFL.PDFObject.getDocument () inherited
The Document of which this object is a member.
Returns null if the Document is not known by PDFL, or if it is a temporary document.
If the Document is not null, then it shares the same internal data with other Document objects that refer to the same file. Document objects returned this way do not contribute to the internal count that keeps the Document open, and will become invalid if the main reference to the document is disposed.
Returns
the Document in which the object resides.
getGeneration()
int com.datalogics.PDFL.PDFObject.getGeneration () inherited
The generation number for this object. Only indirect objects have a generation number.
getID()
int com.datalogics.PDFL.PDFObject.getID () inherited
The ID number for this object. Only indirect objects have an ID number.
getIndirect()
boolean com.datalogics.PDFL.PDFObject.getIndirect () inherited
Indicates if this object is indirect or direct.
getKeys()
java.util.List<PDFObject> com.datalogics.PDFL.PDFDict.getKeys ()
Get a list of all keys in the dictionary
Returns
a list of all the keys
getPDFHashValue()
int com.datalogics.PDFL.PDFObject.getPDFHashValue () inherited
The 32-bit hash value for this object. The hash value is used internally to quickly access the object, and is not generally useful for PDFObject users. Note that two PDFObjects with equal hash values are not necessarily equal; use Equals() to check for equality.
getXMPMetadata()
String com.datalogics.PDFL.PDFDict.getXMPMetadata ()
The XMP metadata associated with this dictionary.
NULL if there is no such data.
Note: PDFL will not attempt to verify that obj is one of the objects specified to allow XMP metadata by the PDF reference.
put() [1/2]
void com.datalogics.PDFL.PDFDict.put (PDFName key, PDFObject obj)
Puts an object with the matching key into the dictionary, adding the entry if the key is not already present.
Parameters
key A PDFName for the key
obj A PDFObject to add to the dictionary
put() [2/2]
void com.datalogics.PDFL.PDFDict.put (String key, PDFObject obj)
Puts an object with the matching key string into the dictionary, adding the entry if the key is not already present.
Parameters
key A string representing the name for the key
obj A PDFObject to add to the dictionary
remove() [1/2]
void com.datalogics.PDFL.PDFDict.remove (PDFName key)
Removes a key/object pair from the dictionary.
Parameters
key A PDFName for the key
remove() [2/2]
void com.datalogics.PDFL.PDFDict.remove (String key)
Removes a key/object pair from the dictionary.
Parameters
key A string representing the name for the key
setXMPMetadata()
void com.datalogics.PDFL.PDFDict.setXMPMetadata (String metadata)
The XMP metadata associated with this dictionary.
NULL if there is no such data.
Note: PDFL will not attempt to verify that obj is one of the objects that is specified in the PDF reference to allow XMP metadata.
toString()
String com.datalogics.PDFL.PDFDict.toString ()
Reimplemented from com.datalogics.PDFL.PDFObject.