Adobe PDF Library Java Documentation
com.datalogics.PDFL.DrawFlags Enum Reference
Static Public Member Functions
static int FlagsToInt (java.lang.Iterable< DrawFlags > flags)
static java.util.EnumSet< DrawFlags > IntToFlags (int value)
Public Attributes
DIRECTLY_IMPOSED
DISPLAY_OVER_PRINT_PREVIEW
DO_LAZY_ERASE
DO_NOT_DOWNLOAD_FONTS
DO_NOT_SUBSTITUTE_WORKING_SPACES
EMIT_PAGE_GROUP
FORCE_GDIPORT
IS_PRINT_PREVIEWING
IS_PRINTING
IS_PSPRINTING
OPTIMIZE_FOR_INTERACTIVE
PASS_METADATATO_AGMPORT
PASS_OCTO_AGMPORT
PASS_OPITO_AGMPORT
SUPPRESS_RASTER_ALPHA
SWAP_COMPONENTS
USE_ANNOT_FACES
USE_PRINTER_MARK_ANNOTS
USE_STAMP_ANNOTS_ONLY
USE_TRAP_ANNOTS
WORKING_SPACES_ONLY_FOR_CHANGE
WRITING_TO_EMF
Member Function Documentation
FlagsToInt()
static int com.datalogics.PDFL.DrawFlags.FlagsToInt (java.lang.Iterable< DrawFlags > flags) static
Referenced by com.datalogics.PDFL.PageImageParams.PageImageParams(), com.datalogics.PDFL.DrawParams.setFlags(), and com.datalogics.PDFL.PageImageParams.setPageDrawFlags().
IntToFlags()
static java.util.EnumSet<DrawFlags> com.datalogics.PDFL.DrawFlags.IntToFlags (int value) static
Referenced by com.datalogics.PDFL.DrawParams.getFlags(), and com.datalogics.PDFL.PageImageParams.getPageDrawFlags().
Member Data Documentation
DIRECTLY_IMPOSED
com.datalogics.PDFL.DrawFlags.DIRECTLY_IMPOSED
Directly imposed page.
DISPLAY_OVER_PRINT_PREVIEW
com.datalogics.PDFL.DrawFlags.DISPLAY_OVER_PRINT_PREVIEW
Display overprint preview.
DO_LAZY_ERASE
com.datalogics.PDFL.DrawFlags.DO_LAZY_ERASE
Erase the page while rendering only as needed.
DO_NOT_DOWNLOAD_FONTS
com.datalogics.PDFL.DrawFlags.DO_NOT_DOWNLOAD_FONTS
Do not download fonts during rendering. Use this flag to prevent fonts from being downloaded/named to the output. Active when writing GDI output, such as to a metafile or printer on Windows.
DO_NOT_SUBSTITUTE_WORKING_SPACES
com.datalogics.PDFL.DrawFlags.DO_NOT_SUBSTITUTE_WORKING_SPACES
Do not substitute working spaces.
EMIT_PAGE_GROUP
com.datalogics.PDFL.DrawFlags.EMIT_PAGE_GROUP
Emit a page group.
FORCE_GDIPORT
com.datalogics.PDFL.DrawFlags.FORCE_GDIPORT
If set, this forces the window draw code to attempt to use GDI instructions internally instead of assuming the incoming Platform device context contains enough information to allow APDFL to make a useful determination. Only honored on Windows. Useful when drawing to a window during print preview, when the supplied hDC is for the screen and does not allow APDFL to adequately instantiate drawing bounds.
IS_PRINT_PREVIEWING
com.datalogics.PDFL.DrawFlags.IS_PRINT_PREVIEWING
Same as ForceGDIPort.
IS_PRINTING
com.datalogics.PDFL.DrawFlags.IS_PRINTING
The page is being printed.
IS_PSPRINTING
com.datalogics.PDFL.DrawFlags.IS_PSPRINTING
PostScript printing.
OPTIMIZE_FOR_INTERACTIVE
com.datalogics.PDFL.DrawFlags.OPTIMIZE_FOR_INTERACTIVE
PASS_METADATATO_AGMPORT
com.datalogics.PDFL.DrawFlags.PASS_METADATATO_AGMPORT
Pass metadata to AGM port.
PASS_OCTO_AGMPORT
com.datalogics.PDFL.DrawFlags.PASS_OCTO_AGMPORT
Pass optional content to AGM port.
PASS_OPITO_AGMPORT
com.datalogics.PDFL.DrawFlags.PASS_OPITO_AGMPORT
Pass open prepress interface (OPI) to AGM port.
SUPPRESS_RASTER_ALPHA
com.datalogics.PDFL.DrawFlags.SUPPRESS_RASTER_ALPHA
Suppress raster alpha.
SWAP_COMPONENTS
com.datalogics.PDFL.DrawFlags.SWAP_COMPONENTS
Render colors in BGR order rather than RGB. It is only valid for calls to Page.DrawContents and only when outputing to an RGB colorspace.
USE_ANNOT_FACES
com.datalogics.PDFL.DrawFlags.USE_ANNOT_FACES
Draw annotation appearances.
USE_PRINTER_MARK_ANNOTS
com.datalogics.PDFL.DrawFlags.USE_PRINTER_MARK_ANNOTS
Use printer's mark annotations.
USE_STAMP_ANNOTS_ONLY
com.datalogics.PDFL.DrawFlags.USE_STAMP_ANNOTS_ONLY
If set, only consider Stamp annotations. This overrides UseAnnotFaces.
USE_TRAP_ANNOTS
com.datalogics.PDFL.DrawFlags.USE_TRAP_ANNOTS
Use trap network annotations.
WORKING_SPACES_ONLY_FOR_CHANGE
com.datalogics.PDFL.DrawFlags.WORKING_SPACES_ONLY_FOR_CHANGE
If this is set, only use a working space instead of a device space if the process color model of the target device is different than that of the source.
WRITING_TO_EMF
com.datalogics.PDFL.DrawFlags.WRITING_TO_EMF
Indicate that the drawing is writing to an Enhanced MetaFile. This prevents fonts from being downloaded, but may advise other flags in the future.