Programming Reference: Main Page
Datalogics.PDFL.Text Class Reference
Public Member Functions
void AddGlyphs (System.Collections.Generic.List< System.Char > glyphIDs, System.Collections.Generic.List< System.Char > uniText, Font font, GraphicState gState, TextState state, Matrix matrix, TextFlags flags)
void AddGlyphs (System.Collections.Generic.List< System.Char > glyphIDs, System.Collections.Generic.List< System.Char > uniText, Font font, GraphicState gState, TextState state, Matrix matrix, TextFlags flags, int index)
void AddRun (TextRun run)
void AddRun (TextRun run, int index)
void ChangeMatrixForTextRun (Matrix newMatrix, int textRunIndex)
void ChangeTextMatrixForTextRun (Matrix newMatrix, int textRunIndex)
new Text Clone ()
new Text Clone (ElementCloneFlags cloneFlags)
Text ColorConvert (Document document, ColorProfile prof, RenderIntent intent, bool embed)
void Dispose ()
override void Dispose (bool disposing)
int FindTextRunIndexForCharacter (int characterIndex)
Point GetAdvanceForCharacter (int characterIndex)
Point GetAdvanceForTextRun (int textRunIndex)
Rect GetBoundingBoxForCharacter (int characterIndex)
TextRun GetRun (int index)
Matrix GetTextMatrixForCharacter (int characterIndex)
Matrix GetTextMatrixForTextRun (int textRunIndex)
bool PointIntersectsCharacter (Point p, int index)
bool PointIntersectsTextRun (Point p, int index)
bool RectIntersectsCharacter (Rect r, int index)
bool RectIntersectsTextRun (Rect r, int index)
void RemoveRuns (int index, int count)
void Rotate (double theta)
void Scale (double sx, double sy)
void SplitTextRunAtCharacter (int splitLocation)
Text ()
void Translate (double tx, double ty)
Properties
Rect BoundingBox [get]
Clip Clip [get, set]
Matrix Matrix [get, set]
int NumberOfCharacters [get]
int NumberOfRuns [get]
Detailed Description
A container that represents a series of text elements and characters.
A Text object is container that represents both a series of TextRun elements and a series of text characters. Operations can be performed on individual TextRuns within a Text or on individual characters within a Text by specifying the index of the individual TextRun or character. All indices start at 0.
Constructor & Destructor Documentation
Text()
Datalogics.PDFL.Text.Text ()
Referenced by Datalogics.PDFL.Text.Clone(), and Datalogics.PDFL.Text.ColorConvert().
Member Function Documentation
AddGlyphs() [1/2]
void Datalogics.PDFL.Text.AddGlyphs (System.Collections.Generic.List< System.Char > glyphIDs, System.Collections.Generic.List< System.Char > uniText, Font font, GraphicState gState, TextState state, Matrix matrix, TextFlags flags)
Adds Unicode text to a Text object
Parameters
glyphIDs Glyphs IDs in the specified font for adding to the page's content
uniText Unicode codes for the specified glyph IDs
font Font for wich GlyphIDs were specified
gState The GraphicsState for Text element
state TextState flags
matrix matrix for the Text element
flags TextFlags that specifies what kind of text to add
AddGlyphs() [2/2]
void Datalogics.PDFL.Text.AddGlyphs (System.Collections.Generic.List< System.Char > glyphIDs, System.Collections.Generic.List< System.Char > uniText, Font font, GraphicState gState, TextState state, Matrix matrix, TextFlags flags, int index)
Adds Unicode text to a Text object
Parameters
glyphIDs Glyphs IDs in the specified font to add to the page's content
uniText Unicode codes for the specified glyph IDs
font Font for wich GlyphIDs were specified
gState The GraphicsState for Text element
state TextState flags
matrix matrix for the Text element
flags TextFlags that specifies what kind of text to add
index The index after which to add the character or text run.
AddRun() [1/2]
void Datalogics.PDFL.Text.AddRun (TextRun run)
Adds a TextRun to the end of this text element.
AddRun() [2/2]
void Datalogics.PDFL.Text.AddRun (TextRun run, int index)
Adds a TextRun at the specified index.
Parameters
run TextRun to be added
index Index, where TextRun should be placed
ChangeMatrixForTextRun()
void Datalogics.PDFL.Text.ChangeMatrixForTextRun (Matrix newMatrix, int textRunIndex)
Changes the transformation matrix from user space to the current text space for the specified TextRun. Unlike ChangeTextMatrixForTextRun(), this function does not change fontSize, hScale, and textRise in the textState of PDEText. The H and V values of the matrix indicate the origin of the first character.
Parameters
newMatrix The new transformation matrix to use for the TextRun.
textRunIndex The index of a TextRun, relative to the Text object (the first TextRun in the Text object is at index 0).
ChangeTextMatrixForTextRun()
void Datalogics.PDFL.Text.ChangeTextMatrixForTextRun (Matrix newMatrix, int textRunIndex)
Changes the transformation matrix from user space to the current text space for the specified TextRun. The H and V values of the matrix indicate the origin of the first character.
Parameters
newMatrix The new transformation matrix to use for the TextRun.
textRunIndex The index of a TextRun, relative to the Text object (the first TextRun in the Text object is at index 0).
Clone() [1/2]
new Text Datalogics.PDFL.Text.Clone ()
Makes a copy of the text.
Make a copy of an text to obtain a new text that has a distinct set of attributes.
Returns
The copied text.
References Datalogics.PDFL.Text.Text().
Clone() [2/2]
new Text Datalogics.PDFL.Text.Clone (ElementCloneFlags cloneFlags)
Makes a copy of the text.
Make a copy of an text to obtain a new text that has a distinct set of attributes.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied text.
References Datalogics.PDFL.Text.Text().
ColorConvert()
Text Datalogics.PDFL.Text.ColorConvert (Document document, ColorProfile prof, RenderIntent intent, bool embed)
Applies the specified ICC ColorProfile to the Text object
Parameters
document The document the element belongs to.
prof The ICC ColorProfile to be applied.
intent The ICC Rendering Intent for the ColorProfile
embed If true, embed the color space and make the object calibrated. If it is false and the target profile is CMYK, RGB, or Gray, the colors space of the resulting object, after conversion, will be DeviceCMYK, DeviceRGB, or DeviceGray, respectively.
Returns
A new Text object with the applied ICC ColorProfile.
References Datalogics.PDFL.Text.Text().
Dispose() [1/2]
void Datalogics.PDFL.Element.Dispose () inherited
Dispose() [2/2]
override void Datalogics.PDFL.Text.Dispose (bool disposing) virtual
Reimplemented from Datalogics.PDFL.Element.
FindTextRunIndexForCharacter()
int Datalogics.PDFL.Text.FindTextRunIndexForCharacter (int characterIndex)
Finds the index of the TextRun that contains the nth character in a Text object.
Parameters
characterIndex The index of a character, relative to the Text object (the first character in the Text object is at index 0).
Returns
The index of the TextRun that contains the character specified by characterIndex.
GetAdvanceForCharacter()
Point Datalogics.PDFL.Text.GetAdvanceForCharacter (int characterIndex)
Gets the advance width of a character, in user space. The advance width is the amount by which the current point advances when the character is drawn.
Advance width may be horizontal or vertical, depending on the writing style. Thus, the return value has both a horizontal and a vertical component.
Parameters
characterIndex The index of a character, relative to the Text object (the first character in the Text object is at index 0).
Returns
A value specifying both the horizontal and vertical components of the advance width of a character in user space.
GetAdvanceForTextRun()
Point Datalogics.PDFL.Text.GetAdvanceForTextRun (int textRunIndex)
Gets the advance width of a TextRun, in user space. The advance width is the amount by which the current point advances when the TextRun is drawn.
Advance width may be horizontal or vertical, depending on the writing style. Thus, the return value has both a horizontal and a vertical component.
Parameters
textRunIndex The index of a TextRun, relative to the Text object (the first TextRun in the Text object is at index 0).
Returns
A value specifying both the horizontal and vertical components of the advance width of a TextRun in user space.
GetBoundingBoxForCharacter()
Rect Datalogics.PDFL.Text.GetBoundingBoxForCharacter (int characterIndex)
The bounding box for a character in this text element.
Parameters
characterIndex The index of a character, relative to the Text object (the first character in the Text object is at index 0)
Returns
A Rect specifying the bounding box for the character.
GetRun()
TextRun Datalogics.PDFL.Text.GetRun (int index)
Obtains the TextRun at the specified index.
GetTextMatrixForCharacter()
Matrix Datalogics.PDFL.Text.GetTextMatrixForCharacter (int characterIndex)
Gets the transformation matrix from user space to the current text space for the specified character. The H and V values of the matrix indicate the origin of the first character.
Parameters
characterIndex The index of a character, relative to the Text object (the first character in the Text object is at index 0).
Returns
The transformation matrix for the character specified by characterIndex.
References Datalogics.PDFL.Element.Matrix.
GetTextMatrixForTextRun()
Matrix Datalogics.PDFL.Text.GetTextMatrixForTextRun (int textRunIndex)
Gets the transformation matrix from user space to the current text space for the specified TextRun. The H and V values of the matrix indicate the origin of the first character.
Parameters
textRunIndex The index of a TextRun, relative to the Text object (the first TextRun in the Text object is at index 0).
Returns
The transformation matrix for the TextRun specified by TextRunIndex.
References Datalogics.PDFL.Element.Matrix.
PointIntersectsCharacter()
bool Datalogics.PDFL.Text.PointIntersectsCharacter (Point p, int index)
Tests whether a point is on a specified character within this Text object.
Parameters
p The point to test, in user space coordinates.
index The index of the character. The first character in the Text has an index of 0.
Returns
true if the point is on the character, false if the point is not on the character.
PointIntersectsTextRun()
bool Datalogics.PDFL.Text.PointIntersectsTextRun (Point p, int index)
Tests whether a point is on a specified TextRun within this Text object.
Parameters
p The point to test, in user space coordinates.
index The index of the TextRun. The first TextRun in the Text has an index of 0.
Returns
true if the point is on the TextRun, false if the point is not on the TextRun.
RectIntersectsCharacter()
bool Datalogics.PDFL.Text.RectIntersectsCharacter (Rect r, int index)
Tests whether any part of a rectangle is on a specified character within this Text object.
Parameters
r The rect to test, in user space coordinates.
index The index of the character. The first character in the Text has an index of 0.
Returns
true if any part of the rectangle is on the character, false if no part of the rectangle is on the character.
RectIntersectsTextRun()
bool Datalogics.PDFL.Text.RectIntersectsTextRun (Rect r, int index)
Tests whether any part of a rectangle is on a specified TextRun within this Text object.
Parameters
r The rect to test, in user space coordinates.
index The index of the TextRun. The first TextRun in the Text has an index of 0.
Returns
true if any part of the rectangle is on the TextRun, false if no part of the rectangle is on the TextRun.
RemoveRuns()
void Datalogics.PDFL.Text.RemoveRuns (int index, int count)
Removes a count of TextRuns, starting from index
Parameters
index Start position of range to delete
count Count of TextRuns to delete
Rotate()
void Datalogics.PDFL.Element.Rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Scale()
void Datalogics.PDFL.Element.Scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
SplitTextRunAtCharacter()
void Datalogics.PDFL.Text.SplitTextRunAtCharacter (int splitLocation)
Splits the TextRun containing the character at the specified location into two contiguous TextRuns. The character at the specified index will be part of the first TextRun.
Parameters
splitLocation The split location, relative to the Text object.
Translate()
void Datalogics.PDFL.Element.Translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Property Documentation
BoundingBox
Rect Datalogics.PDFL.Element.BoundingBox get inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
Clip
Clip Datalogics.PDFL.Element.Clip get set inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
Matrix
Matrix Datalogics.PDFL.Element.Matrix get set inherited
The transformation matrix for the element.
Referenced by Datalogics.PDFL.Text.GetTextMatrixForCharacter(), and Datalogics.PDFL.Text.GetTextMatrixForTextRun().
NumberOfCharacters
int Datalogics.PDFL.Text.NumberOfCharacters get
The number of characters in this text element.
NumberOfRuns
int Datalogics.PDFL.Text.NumberOfRuns get
The number of text runs in this text element.