Adobe PDF Library .NET Framework Documentation
Datalogics.PDFL.Point Class Reference
Public Member Functions
void Dispose ()
virtual void Dispose (bool disposing)
Point DistanceTransform (Matrix arg0)
override bool Equals (object obj)
Point ()
Point (double nh, double nv)
override string ToString ()
Point Transform (Matrix arg0)
Properties
double H [get, set]
double V [get, set]
Detailed Description
Represents a discrete point or space in a PDF.
A Point in a PDF document is in the right plane, relative to the origin being the lower left corner of the document.
Constructor & Destructor Documentation
Point() [1/2]
Datalogics.PDFL.Point.Point ()
Create a new point at the origin (0.0, 0.0).
Referenced by Datalogics.PDFL.Point.DistanceTransform(), and Datalogics.PDFL.Point.Transform().
Point() [2/2]
Datalogics.PDFL.Point.Point (double nh, double nv)
Create a new point at the specified coordinates.
Parameters
nh the horizontal coordinate
nv the vertical coordinate
Member Function Documentation
Dispose() [1/2]
void Datalogics.PDFL.Point.Dispose ()
Dispose() [2/2]
virtual void Datalogics.PDFL.Point.Dispose (bool disposing) virtual
DistanceTransform()
Point Datalogics.PDFL.Point.DistanceTransform (Matrix arg0)
Distance Transform the Point Object by the values in the Matrix parameter, which is a transformation without any translation.
References Datalogics.PDFL.Point.Point().
Equals()
override bool Datalogics.PDFL.Point.Equals (object obj)
ToString()
override string Datalogics.PDFL.Point.ToString ()
Transform()
Point Datalogics.PDFL.Point.Transform (Matrix arg0)
Transform the Point Object by the values in the Matrix parameter.
References Datalogics.PDFL.Point.Point().
Property Documentation
H
double Datalogics.PDFL.Point.H get set
The horizontal coordinate of the point.
V
double Datalogics.PDFL.Point.V get set
The vertical coordinate of the point.