Adobe PDF Library .NET Framework Documentation
Datalogics.PDFL.Rect Class Reference
Public Member Functions
void Dispose ()
virtual void Dispose (bool disposing)
override bool Equals (object obj)
bool InRect (Rect r2)
Rect Intersect (Rect r2)
bool IsEmpty ()
bool Overlaps (Rect r2)
Rect ()
Rect (double nLLx, double nLLy, double nURx, double nURy)
Rect (System.Drawing.Rectangle r)
Rect (System.Drawing.RectangleF r)
override string ToString ()
Rect Transform (Matrix arg0)
Static Public Member Functions
static implicit operator Rect (System.Drawing.Rectangle r)
static implicit operator Rect (System.Drawing.RectangleF r)
Properties
double Bottom [get, set]
double Height [get]
double Left [get, set]
double LLx [get, set]
double LLy [get, set]
double Right [get, set]
int RoundedHeight [get]
int RoundedWidth [get]
double Top [get, set]
double URx [get, set]
double URy [get, set]
double Width [get]
Detailed Description
A rect holds four coordinates for a rectangle.
The coordinates for a rectangle include left, top, right, bottom. Width () and height () defines the rectangle's width and height. LLx and LLy defines lower left corner, and URx and URy defines the upper right corner.
Constructor & Destructor Documentation
Rect() [1/4]
Datalogics.PDFL.Rect.Rect (System.Drawing.RectangleF r)
Construct a Rect from a System.Drawing.RectangleF
Note that the coordinate systems are inverted for PDFL. Smaller X/Y values are assigned to the lower left coordinate.
Parameters
r The rectangle to convert
Rect() [2/4]
Datalogics.PDFL.Rect.Rect (System.Drawing.Rectangle r)
Construct a Rect from a System.Drawing.Rectangle
Note that the coordinate systems are inverted for PDFL. Smaller X/Y values are assigned to the lower left coordinate.
Parameters
r The rectangle to convert
Rect() [3/4]
Datalogics.PDFL.Rect.Rect ()
Create a rectangle with all values zero.
Referenced by Datalogics.PDFL.Rect.Intersect(), Datalogics.PDFL.Rect.operator Rect(), and Datalogics.PDFL.Rect.Transform().
Rect() [4/4]
Datalogics.PDFL.Rect.Rect (double nLLx, double nLLy, double nURx, double nURy)
Create a Rect.
Parameters
nLLx the X coordinate of the lower left corner of the rectangle
nLLy the Y coordinate of the lower left corner of the rectangle
nURx the X coordinate of the upper right corner of the rectangle
nURy the Y coordinate of the upper right corner of the rectangle
Member Function Documentation
Dispose() [1/2]
void Datalogics.PDFL.Rect.Dispose ()
Dispose() [2/2]
virtual void Datalogics.PDFL.Rect.Dispose (bool disposing) virtual
Equals()
override bool Datalogics.PDFL.Rect.Equals (object obj)
InRect()
bool Datalogics.PDFL.Rect.InRect (Rect r2)
Check if this rectangle is inside the parameter rectangle.
Intersect()
Rect Datalogics.PDFL.Rect.Intersect (Rect r2)
Obtain the intersection of this rectangle and another rectangle.
References Datalogics.PDFL.Rect.Rect().
IsEmpty()
bool Datalogics.PDFL.Rect.IsEmpty ()
Check if this rectangle is empty.
operator Rect() [1/2]
static implicit Datalogics.PDFL.Rect.operator Rect (System.Drawing.Rectangle r) static
Convert a System.Drawing.Rectangle to a Rect
Note that the coordinate systems are inverted for PDFL. Smaller X/Y values are assigned to the lower left coordinate.
Parameters
r The rectangle to convert
References Datalogics.PDFL.Rect.Rect().
operator Rect() [2/2]
static implicit Datalogics.PDFL.Rect.operator Rect (System.Drawing.RectangleF r) static
Convert a System.Drawing.RectangleF to a Rect
Note that the coordinate systems are inverted for PDFL. Smaller X/Y values are assigned to the lower left coordinate.
Parameters
r The rectangle to convert
References Datalogics.PDFL.Rect.Rect().
Overlaps()
bool Datalogics.PDFL.Rect.Overlaps (Rect r2)
Check if two rectangles overlap.
ToString()
override string Datalogics.PDFL.Rect.ToString ()
Transform()
Rect Datalogics.PDFL.Rect.Transform (Matrix arg0)
Transform the coordinates of the rectangle by the given Matrix Object.
References Datalogics.PDFL.Rect.Rect().
Property Documentation
Bottom
double Datalogics.PDFL.Rect.Bottom get set
the Y coordinate of the lower left corner of the rectangle
Height
double Datalogics.PDFL.Rect.Height get
The height of the Rect.
Left
double Datalogics.PDFL.Rect.Left get set
the X coordinate of the lower left corner of the rectangle
LLx
double Datalogics.PDFL.Rect.LLx get set
the X coordinate of the lower left corner of the rectangle
LLy
double Datalogics.PDFL.Rect.LLy get set
the Y coordinate of the lower left corner of the rectangle
Right
double Datalogics.PDFL.Rect.Right get set
the X coordinate of the upper right corner of the rectangle
RoundedHeight
int Datalogics.PDFL.Rect.RoundedHeight get
Referenced by Datalogics.PDFL.Page.DrawContents().
RoundedWidth
int Datalogics.PDFL.Rect.RoundedWidth get
Referenced by Datalogics.PDFL.Page.DrawContents().
Top
double Datalogics.PDFL.Rect.Top get set
the Y coordinate of the upper right corner of the rectangle
URx
double Datalogics.PDFL.Rect.URx get set
the X coordinate of the upper right corner of the rectangle
URy
double Datalogics.PDFL.Rect.URy get set
the Y coordinate of the upper right corner of the rectangle
Width
double Datalogics.PDFL.Rect.Width get
The width of the Rect.