Programming Reference: Main Page
Datalogics.PDFL.Matrix Class Reference
Public Member Functions
Matrix Concat (Matrix Mt)
void Dispose ()
virtual void Dispose (bool disposing)
override bool Equals (object obj)
Matrix Invert ()
Matrix ()
Matrix (double na, double nb, double nc, double nd, double nh, double nv)
Matrix Rotate (double T)
Matrix Scale (double sx, double sy)
override string ToString ()
Matrix Translate (double tx, double ty)
Static Public Member Functions
static Matrix Multiply (Matrix m1, Matrix m2)
Properties
double A [get, set]
double B [get, set]
double C [get, set]
double D [get, set]
double H [get, set]
double V [get, set]
Detailed Description
A transformation matrix in a PDF file is specified by six numbers.
The matrix is usually in the form of an array containing the six elements [a b c d h v].
A translation is specified as [ 1 0 0 1 tx ty], where tx and ty are the distance to translate from the origin of the coordinate system in the horizontal and vertical dimension, respectively.
A scaling is obtained by [sx 0 0 sy 0 0]. This scales the coordinates so that 1 unit in the horizontal and vertical dimension of the new coordinate system is the same size as sx and sy units, respectively, as in the previous coordinate system.
A rotation is produced by [ cos T sin T -sin T cos T 0 0 ], which has the effect of rotating the coordinate system axes by an angle T (degrees) counterclockwise.
For a description of the Transformation Matrices, see section 8.3.4 of the ISO 32000-1:2008, Document Management-Portable Document Format-Part 1: PDF 1.7, page 119.
This material indicates that the matrix specifying a transformation is premultiplied with the current transformation matrix, i.e.,
M' = Mt * M
The implementation of the Scale, Rotate, and Translate convenience functions of Matrix reflect the same order of operations, so that they are consistent with the PDF Reference manual. They are also consistent with the scale, rotate, and translate operators in PostScript, from which the coordinate system model in PDF is derived.
Constructor & Destructor Documentation
Matrix() [1/2]
Datalogics.PDFL.Matrix.Matrix ()
the default constructor creates a transformation matrix to translate the rectangle 1 element (1/72nd of an inch) from the origin.
Referenced by Datalogics.PDFL.Matrix.Concat(), Datalogics.PDFL.Matrix.Invert(), Datalogics.PDFL.Matrix.Multiply(), Datalogics.PDFL.Matrix.Rotate(), Datalogics.PDFL.Matrix.Scale(), and Datalogics.PDFL.Matrix.Translate().
Matrix() [2/2]
Datalogics.PDFL.Matrix.Matrix (double na, double nb, double nc, double nd, double nh, double nv)
Member Function Documentation
Concat()
Matrix Datalogics.PDFL.Matrix.Concat (Matrix Mt)
Concatenate a matrix onto an existing matrix.
The concatenation is done according to section 8.3.4, "Transformation Matrices", of the ISO 32000-1:2008, Document Management-Portable Document Format-Part 1: PDF 1.7, page 119.
The product returned is:
M' = Mt * M
This corresponds to the action of the cm operator in section 4.3.3, "Graphic State Operators".
Returns
the transformed matrix
References Datalogics.PDFL.Matrix.Matrix().
Dispose() [1/2]
void Datalogics.PDFL.Matrix.Dispose ()
Dispose() [2/2]
virtual void Datalogics.PDFL.Matrix.Dispose (bool disposing) virtual
Equals()
override bool Datalogics.PDFL.Matrix.Equals (object obj)
Invert()
Matrix Datalogics.PDFL.Matrix.Invert ()
Invert the Matrix object and return a new Matrix object.
References Datalogics.PDFL.Matrix.Matrix().
Multiply()
static Matrix Datalogics.PDFL.Matrix.Multiply (Matrix m1, Matrix m2) static
Multiply two transformation matrices.
Parameters
m1 a matrix
m2 a matrix
Returns
the matrix product m1 x m2
References Datalogics.PDFL.Matrix.Matrix().
Rotate()
Matrix Datalogics.PDFL.Matrix.Rotate (double T)
Rotate a matrix by T degrees counterclockwise units.
Rotation is done by creating the matrix [ cos T sin T -sin T cos T 0 0 ], and calling the Concat function with that matrix.
Parameters
T The rotation, counterclockwise
Returns
the result [cos T sin T -sin T 0 0] * M
References Datalogics.PDFL.Matrix.Matrix().
Scale()
Matrix Datalogics.PDFL.Matrix.Scale (double sx, double sy)
Scale a matrix by (sx,sy) units.
Scaling is done by creating the matrix [sx 0 0 sy 0 0], and calling the Concat function with that matrix.
Parameters
sx X scaling factor
sy Y scaling factor
Returns
the result [sx 0 0 sy 0 0] * M
References Datalogics.PDFL.Matrix.Matrix().
ToString()
override string Datalogics.PDFL.Matrix.ToString ()
Translate()
Matrix Datalogics.PDFL.Matrix.Translate (double tx, double ty)
Translate a matrix by (tx,ty) units.
Translation is done by creating the matrix [ 1 0 0 1 tx ty ], and calling the Concat function with that matrix.
Parameters
tx X translation distance
ty Y translation distance
Returns
the result [1 0 0 1 tx ty] * M
References Datalogics.PDFL.Matrix.Matrix().
Property Documentation
A
double Datalogics.PDFL.Matrix.A get set
B
double Datalogics.PDFL.Matrix.B get set
C
double Datalogics.PDFL.Matrix.C get set
D
double Datalogics.PDFL.Matrix.D get set
H
double Datalogics.PDFL.Matrix.H get set
V
double Datalogics.PDFL.Matrix.V get set