.NET API Reference: Datalogics.PDFL.DeviceNColorSpace Class Reference
Datalogics.PDFL.DeviceNColorSpace Class Reference
Public Member Functions
DeviceNColorSpace (System.Collections.Generic.IList< System.String > names, ColorSpace alternate, Function tintTransform)
void Dispose ()
override void Dispose (bool disposing)
override bool Equals (object obj)
override string ToString ()
Static Public Member Functions
static bool operator!= (ColorSpace a, ColorSpace b)
static bool operator== (ColorSpace a, ColorSpace b)
Properties
ColorSpace Alternate [get]
PDFDict Attributes [get]
static ColorSpace DeviceCMYK [get]
static ColorSpace DeviceGray [get]
static ColorSpace DeviceRGB [get]
static ColorSpace DeviceRGBA [get]
Function Function [get]
static ColorSpace Lab [get]
static ColorSpace LabA [get]
string Name [get]
System.Collections.Generic.IList< System.String > Names [get]
int NumComponents [get]
PDFObject PDFObject [get]
Detailed Description
Represents a color space with an arbitrary number of color components.
DeviceN color spaces were designed to represent color spaces containing multiple color components that correspond to the colorants of some target device. They provide greater flexibility than is possible with standard device color spaces such as DeviceCMYK or with individual Separation color spaces. For example, it is possible to create a DeviceN color space consisting of only the cyan, magenta, and yellow color components, with the black component excluded.
Constructor & Destructor Documentation
DeviceNColorSpace()
Datalogics.PDFL.DeviceNColorSpace.DeviceNColorSpace (System.Collections.Generic.IList< System.String > names, ColorSpace alternate, Function tintTransform)
Create a DeviceN color space.
Parameters
names the names of the colorants that the DeviceN space is intended to represent, among which may be All, or None
alternate the alternate color space, which can be any device or CIE-based color space but not another special color space (Pattern, Indexed, Separation, or DeviceN).
tintTransform function, called with the tint value and returning the corresponding color component values. That is, the number of components and the interpretation of their values depend on the alternate color space.
References Function.
Member Function Documentation
Dispose() [1/2]
void Datalogics.PDFL.ColorSpace.Dispose () inherited
References Dispose().
Referenced by Dispose().
Dispose() [2/2]
override void Datalogics.PDFL.DeviceNColorSpace.Dispose (bool disposing) virtual
Reimplemented from Datalogics.PDFL.ColorSpace.
Equals()
override bool Datalogics.PDFL.ColorSpace.Equals (object obj) inherited
Referenced by operator==().
operator!=()
bool Datalogics.PDFL.ColorSpace.operator!= (ColorSpace a, ColorSpace b) static inherited
operator==()
bool Datalogics.PDFL.ColorSpace.operator== (ColorSpace a, ColorSpace b) static inherited
References Equals().
ToString()
override string Datalogics.PDFL.ColorSpace.ToString () inherited
Convert a colorSpace to a string.
Property Documentation
Alternate
ColorSpace Datalogics.PDFL.DeviceNColorSpace.Alternate get
Attributes
PDFDict Datalogics.PDFL.DeviceNColorSpace.Attributes get
DeviceCMYK
ColorSpace Datalogics.PDFL.ColorSpace.DeviceCMYK static get inherited
DeviceGray
ColorSpace Datalogics.PDFL.ColorSpace.DeviceGray static get inherited
DeviceRGB
ColorSpace Datalogics.PDFL.ColorSpace.DeviceRGB static get inherited
Referenced by Datalogics.PDFL.Page.DrawContents().
DeviceRGBA
ColorSpace Datalogics.PDFL.ColorSpace.DeviceRGBA static get inherited
Referenced by Datalogics.PDFL.Page.DrawContents().
Function
Function Datalogics.PDFL.DeviceNColorSpace.Function get
Referenced by DeviceNColorSpace().
Lab
ColorSpace Datalogics.PDFL.ColorSpace.Lab static get inherited
LabA
ColorSpace Datalogics.PDFL.ColorSpace.LabA static get inherited
Name
string Datalogics.PDFL.ColorSpace.Name get inherited
Referenced by Datalogics.PDFL.Page.GetBitmap().
Names
System.Collections.Generic.IList<System.String> Datalogics.PDFL.DeviceNColorSpace.Names get
NumComponents
int Datalogics.PDFL.ColorSpace.NumComponents get inherited
PDFObject
PDFObject Datalogics.PDFL.ColorSpace.PDFObject get inherited