var hierarchy =
[
    [ "com.datalogics.PDFL.Action", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_action.html", [
      [ "com.datalogics.PDFL.GoToAction", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_go_to_action.html", null ],
      [ "com.datalogics.PDFL.LaunchAction", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_launch_action.html", null ],
      [ "com.datalogics.PDFL.RemoteGoToAction", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_remote_go_to_action.html", null ],
      [ "com.datalogics.PDFL.URIAction", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_u_r_i_action.html", null ]
    ] ],
    [ "com.datalogics.PDFL.AddPageFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_add_page_flags.html", null ],
    [ "com.datalogics.PDFL.Annotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_annotation.html", [
      [ "com.datalogics.PDFL.CircleAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_circle_annotation.html", null ],
      [ "com.datalogics.PDFL.FreeTextAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_free_text_annotation.html", null ],
      [ "com.datalogics.PDFL.InkAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_ink_annotation.html", null ],
      [ "com.datalogics.PDFL.LineAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_line_annotation.html", null ],
      [ "com.datalogics.PDFL.LinkAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_link_annotation.html", null ],
      [ "com.datalogics.PDFL.PolyLineAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_poly_line_annotation.html", null ],
      [ "com.datalogics.PDFL.PolygonAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_polygon_annotation.html", null ],
      [ "com.datalogics.PDFL.Redaction", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_redaction.html", null ],
      [ "com.datalogics.PDFL.SquareAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_square_annotation.html", null ],
      [ "com.datalogics.PDFL.TextMarkupAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_text_markup_annotation.html", [
        [ "com.datalogics.PDFL.HighlightAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_highlight_annotation.html", null ],
        [ "com.datalogics.PDFL.UnderlineAnnotation", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_underline_annotation.html", null ]
      ] ]
    ] ],
    [ "com.datalogics.PDFL.AnnotationFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_annotation_flags.html", null ],
    [ "com.datalogics.PDFL.BlendMode", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_blend_mode.html", null ],
    [ "com.datalogics.PDFL.Bookmark", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_bookmark.html", null ],
    [ "com.datalogics.PDFL.BookmarkFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_bookmark_flags.html", null ],
    [ "com.datalogics.PDFL.CancelProc", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_cancel_proc.html", null ],
    [ "com.datalogics.PDFL.Clip", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_clip.html", null ],
    [ "com.datalogics.PDFL.Collection", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_collection.html", null ],
    [ "com.datalogics.PDFL.CollectionSchema", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_collection_schema.html", null ],
    [ "com.datalogics.PDFL.CollectionSchemaField", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_collection_schema_field.html", null ],
    [ "com.datalogics.PDFL.CollectionSortItem", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_collection_sort_item.html", null ],
    [ "com.datalogics.PDFL.CollectionSplitType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_collection_split_type.html", null ],
    [ "com.datalogics.PDFL.CollectionViewType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_collection_view_type.html", null ],
    [ "com.datalogics.PDFL.Color", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_color.html", null ],
    [ "com.datalogics.PDFL.ColorConvertActions", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_color_convert_actions.html", null ],
    [ "com.datalogics.PDFL.ColorConvertActionType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_color_convert_action_type.html", null ],
    [ "com.datalogics.PDFL.ColorConvertCSpaceType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_color_convert_c_space_type.html", null ],
    [ "com.datalogics.PDFL.ColorConvertObjAttrs", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_color_convert_obj_attrs.html", null ],
    [ "com.datalogics.PDFL.ColorConvertParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_color_convert_params.html", null ],
    [ "com.datalogics.PDFL.ColorProfile", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_color_profile.html", null ],
    [ "com.datalogics.PDFL.ColorSpace", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_color_space.html", [
      [ "com.datalogics.PDFL.CalGrayColorSpace", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_cal_gray_color_space.html", null ],
      [ "com.datalogics.PDFL.CalRGBColorSpace", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_cal_r_g_b_color_space.html", null ],
      [ "com.datalogics.PDFL.DeviceNColorSpace", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_device_n_color_space.html", null ],
      [ "com.datalogics.PDFL.ICCBasedColorSpace", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_i_c_c_based_color_space.html", null ],
      [ "com.datalogics.PDFL.IndexedColorSpace", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_indexed_color_space.html", null ],
      [ "com.datalogics.PDFL.LabColorSpace", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_lab_color_space.html", null ],
      [ "com.datalogics.PDFL.NamedColorSpace", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_named_color_space.html", null ],
      [ "com.datalogics.PDFL.SeparationColorSpace", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_separation_color_space.html", null ]
    ] ],
    [ "com.datalogics.PDFL.ColorValueConverter", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_color_value_converter.html", null ],
    [ "com.datalogics.PDFL.CompressImageType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_compress_image_type.html", null ],
    [ "com.datalogics.PDFL.CompressionCode", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_compression_code.html", null ],
    [ "com.datalogics.PDFL.CompressionType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_compression_type.html", null ],
    [ "com.datalogics.PDFL.CompressQuality", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_compress_quality.html", null ],
    [ "com.datalogics.PDFL.Content", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_content.html", null ],
    [ "com.datalogics.PDFL.DocTextFinder", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_doc_text_finder.html", null ],
    [ "com.datalogics.PDFL.DocTextFinderMatch", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_doc_text_finder_match.html", null ],
    [ "com.datalogics.PDFL.DocTextFinderQuadInfo", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_doc_text_finder_quad_info.html", null ],
    [ "com.datalogics.PDFL.Document", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_document.html", null ],
    [ "com.datalogics.PDFL.DrawFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_draw_flags.html", null ],
    [ "com.datalogics.PDFL.DrawParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_draw_params.html", null ],
    [ "com.datalogics.PDFL.Duplex", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_duplex.html", null ],
    [ "com.datalogics.PDFL.Element", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_element.html", [
      [ "com.datalogics.PDFL.Container", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_container.html", null ],
      [ "com.datalogics.PDFL.Form", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_form.html", null ],
      [ "com.datalogics.PDFL.Group", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_group.html", null ],
      [ "com.datalogics.PDFL.Image", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_image.html", null ],
      [ "com.datalogics.PDFL.Path", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_path.html", null ],
      [ "com.datalogics.PDFL.PostScript", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_post_script.html", null ],
      [ "com.datalogics.PDFL.Shading", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_shading.html", null ],
      [ "com.datalogics.PDFL.Text", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_text.html", null ],
      [ "com.datalogics.PDFL.TextRun", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_text_run.html", null ]
    ] ],
    [ "com.datalogics.PDFL.ElementCloneFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_element_clone_flags.html", null ],
    [ "com.datalogics.PDFL.EmbedFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_embed_flags.html", null ],
    [ "com.datalogics.PDFL.EncodingInfo", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_encoding_info.html", null ],
    [ "com.datalogics.PDFL.EncryptionType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_encryption_type.html", null ],
    [ "com.datalogics.PDFL.ExtendedGraphicState", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_extended_graphic_state.html", null ],
    [ "com.datalogics.PDFL.FarEastFont", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_far_east_font.html", null ],
    [ "com.datalogics.PDFL.FileAttachment", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_file_attachment.html", null ],
    [ "com.datalogics.PDFL.FileSpecification", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_file_specification.html", null ],
    [ "com.datalogics.PDFL.FlattenerColorCompression", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_flattener_color_compression.html", null ],
    [ "com.datalogics.PDFL.FlattenerGrayCompression", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_flattener_gray_compression.html", null ],
    [ "com.datalogics.PDFL.FlattenerMonoCompression", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_flattener_mono_compression.html", null ],
    [ "com.datalogics.PDFL.FlattenerQualitySetting", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_flattener_quality_setting.html", null ],
    [ "com.datalogics.PDFL.FlattenTransparencyParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_flatten_transparency_params.html", null ],
    [ "com.datalogics.PDFL.Font", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_font.html", null ],
    [ "com.datalogics.PDFL.FontCreateFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_font_create_flags.html", null ],
    [ "com.datalogics.PDFL.FontFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_font_flags.html", null ],
    [ "com.datalogics.PDFL.FontRescanFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_font_rescan_flags.html", null ],
    [ "com.datalogics.PDFL.Function", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_function.html", [
      [ "com.datalogics.PDFL.ExponentialFunction", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_exponential_function.html", null ],
      [ "com.datalogics.PDFL.NamedFunction", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_named_function.html", null ],
      [ "com.datalogics.PDFL.PostScriptCalculatorFunction", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_post_script_calculator_function.html", null ]
    ] ],
    [ "com.datalogics.PDFL.GraphicState", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_graphic_state.html", null ],
    [ "com.datalogics.PDFL.HighlightStyle", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_highlight_style.html", null ],
    [ "com.datalogics.PDFL.HorizontalAlignment", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_horizontal_alignment.html", null ],
    [ "com.datalogics.PDFL.ImageCollection", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_image_collection.html", null ],
    [ "com.datalogics.PDFL.ImageData", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_image_data.html", null ],
    [ "com.datalogics.PDFL.ImageSaveParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_image_save_params.html", null ],
    [ "com.datalogics.PDFL.ImageType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_image_type.html", null ],
    [ "com.datalogics.PDFL.Inclusion", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_inclusion.html", null ],
    [ "com.datalogics.PDFL.Ink", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_ink.html", null ],
    [ "com.datalogics.PDFL.InkTypes", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_ink_types.html", null ],
    [ "com.datalogics.PDFL.Language", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_language.html", null ],
    [ "com.datalogics.PDFL.LanguageSetting", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_language_setting.html", null ],
    [ "com.datalogics.PDFL.Library", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_library.html", null ],
    [ "com.datalogics.PDFL.LibraryFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_library_flags.html", null ],
    [ "com.datalogics.PDFL.LineCap", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_line_cap.html", null ],
    [ "com.datalogics.PDFL.LineEndingStyle", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_line_ending_style.html", null ],
    [ "com.datalogics.PDFL.LineJoin", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_line_join.html", null ],
    [ "com.datalogics.PDFL.LogOutputFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_log_output_flags.html", null ],
    [ "com.datalogics.PDFL.LogParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_log_params.html", null ],
    [ "com.datalogics.PDFL.Matrix", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_matrix.html", null ],
    [ "com.datalogics.PDFL.MirrorOptions", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_mirror_options.html", null ],
    [ "com.datalogics.PDFL.NameTree", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_name_tree.html", null ],
    [ "com.datalogics.PDFL.NumberStyle", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_number_style.html", null ],
    [ "com.datalogics.PDFL.NumberTree", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_number_tree.html", null ],
    [ "com.datalogics.PDFL.ObjectCompressionType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_object_compression_type.html", null ],
    [ "com.datalogics.PDFL.OCREngine", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_o_c_r_engine.html", null ],
    [ "com.datalogics.PDFL.OCRParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_o_c_r_params.html", null ],
    [ "com.datalogics.PDFL.OptimizerOption", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_optimizer_option.html", null ],
    [ "com.datalogics.PDFL.OptionalContentBaseState", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_optional_content_base_state.html", null ],
    [ "com.datalogics.PDFL.OptionalContentConfig", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_optional_content_config.html", null ],
    [ "com.datalogics.PDFL.OptionalContentContext", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_optional_content_context.html", null ],
    [ "com.datalogics.PDFL.OptionalContentDrawingPolicy", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_optional_content_drawing_policy.html", null ],
    [ "com.datalogics.PDFL.OptionalContentGroup", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_optional_content_group.html", null ],
    [ "com.datalogics.PDFL.OptionalContentMembershipDict", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_optional_content_membership_dict.html", null ],
    [ "com.datalogics.PDFL.OptionalContentOrderNode", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_optional_content_order_node.html", [
      [ "com.datalogics.PDFL.OptionalContentOrderArray", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_optional_content_order_array.html", null ],
      [ "com.datalogics.PDFL.OptionalContentOrderLeaf", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_optional_content_order_leaf.html", null ]
    ] ],
    [ "com.datalogics.PDFL.OutputType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_output_type.html", null ],
    [ "com.datalogics.PDFL.OverprintMode", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_overprint_mode.html", null ],
    [ "com.datalogics.PDFL.Page", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_page.html", null ],
    [ "com.datalogics.PDFL.PageDeleteFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_page_delete_flags.html", null ],
    [ "com.datalogics.PDFL.PageImageParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_page_image_params.html", null ],
    [ "com.datalogics.PDFL.PageInsertFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_page_insert_flags.html", null ],
    [ "com.datalogics.PDFL.PageLabel", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_page_label.html", null ],
    [ "com.datalogics.PDFL.PageMarkFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_page_mark_flags.html", null ],
    [ "com.datalogics.PDFL.PageMode", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_page_mode.html", null ],
    [ "com.datalogics.PDFL.PageRange", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_page_range.html", null ],
    [ "com.datalogics.PDFL.PageRenderWarning", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_page_render_warning.html", null ],
    [ "com.datalogics.PDFL.PageRotation", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_page_rotation.html", null ],
    [ "com.datalogics.PDFL.PageSegmentationMode", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_page_segmentation_mode.html", null ],
    [ "com.datalogics.PDFL.PageSpec", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_page_spec.html", null ],
    [ "com.datalogics.PDFL.PageTilingMode", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_page_tiling_mode.html", null ],
    [ "com.datalogics.PDFL.PaperSource", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_paper_source.html", null ],
    [ "com.datalogics.PDFL.PathOperators", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_path_operators.html", null ],
    [ "com.datalogics.PDFL.PathPaintOpFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_path_paint_op_flags.html", null ],
    [ "com.datalogics.PDFL.Pattern", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_pattern.html", [
      [ "com.datalogics.PDFL.ShadingPattern", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_shading_pattern.html", [
        [ "com.datalogics.PDFL.AxialShadingPattern", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_axial_shading_pattern.html", null ]
      ] ]
    ] ],
    [ "com.datalogics.PDFL.PDETextFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_e_text_flags.html", null ],
    [ "com.datalogics.PDFL.PDFAConvertParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_a_convert_params.html", null ],
    [ "com.datalogics.PDFL.PDFAConvertResult", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_a_convert_result.html", null ],
    [ "com.datalogics.PDFL.PDFAConvertType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_a_convert_type.html", null ],
    [ "com.datalogics.PDFL.PDFlattenerColorCompSet", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_flattener_color_comp_set.html", null ],
    [ "com.datalogics.PDFL.PDFlattenerGrayscaleCompSet", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_flattener_grayscale_comp_set.html", null ],
    [ "com.datalogics.PDFL.PDFlattenerMonochromeCompSet", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_flattener_monochrome_comp_set.html", null ],
    [ "com.datalogics.PDFL.PDFlattenerQualitySetting", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_flattener_quality_setting.html", null ],
    [ "com.datalogics.PDFL.PDFLConstants", "interfacecom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_l_constants.html", [
      [ "com.datalogics.PDFL.PDFL", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_l.html", null ]
    ] ],
    [ "com.datalogics.PDFL.PDFObject", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_object.html", [
      [ "com.datalogics.PDFL.PDFArray", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_array.html", null ],
      [ "com.datalogics.PDFL.PDFBoolean", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_boolean.html", null ],
      [ "com.datalogics.PDFL.PDFDict", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_dict.html", null ],
      [ "com.datalogics.PDFL.PDFInteger", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_integer.html", null ],
      [ "com.datalogics.PDFL.PDFName", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_name.html", null ],
      [ "com.datalogics.PDFL.PDFReal", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_real.html", null ],
      [ "com.datalogics.PDFL.PDFStream", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_stream.html", null ],
      [ "com.datalogics.PDFL.PDFString", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_string.html", null ]
    ] ],
    [ "com.datalogics.PDFL.PDFObjectEnumProc", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_object_enum_proc.html", null ],
    [ "com.datalogics.PDFL.PDFOptimizer", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_optimizer.html", null ],
    [ "com.datalogics.PDFL.PDFStreamOpenMode", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_stream_open_mode.html", null ],
    [ "com.datalogics.PDFL.PDFXConvertParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_x_convert_params.html", null ],
    [ "com.datalogics.PDFL.PDFXConvertResult", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_x_convert_result.html", null ],
    [ "com.datalogics.PDFL.PDFXConvertType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_p_d_f_x_convert_type.html", null ],
    [ "com.datalogics.PDFL.Performance", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_performance.html", null ],
    [ "com.datalogics.PDFL.PermissionFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_permission_flags.html", null ],
    [ "com.datalogics.PDFL.PermissionRequestOperation", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_permission_request_operation.html", null ],
    [ "com.datalogics.PDFL.Point", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_point.html", null ],
    [ "com.datalogics.PDFL.PrintCancelProc", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_print_cancel_proc.html", null ],
    [ "com.datalogics.PDFL.PrintParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_print_params.html", null ],
    [ "com.datalogics.PDFL.PrintProgressProc", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_print_progress_proc.html", null ],
    [ "com.datalogics.PDFL.PrintProgressStage", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_print_progress_stage.html", null ],
    [ "com.datalogics.PDFL.PrintUserParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_print_user_params.html", null ],
    [ "com.datalogics.PDFL.PrintWhat", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_print_what.html", null ],
    [ "com.datalogics.PDFL.PrintWhatAnnotFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_print_what_annot_flags.html", null ],
    [ "com.datalogics.PDFL.ProgressMonitor", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_progress_monitor.html", null ],
    [ "com.datalogics.PDFL.Quad", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_quad.html", null ],
    [ "com.datalogics.PDFL.Rect", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_rect.html", null ],
    [ "com.datalogics.PDFL.RemoteDestination", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_remote_destination.html", null ],
    [ "com.datalogics.PDFL.RenderIntent", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_render_intent.html", null ],
    [ "com.datalogics.PDFL.RenderProgressProc", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_render_progress_proc.html", null ],
    [ "com.datalogics.PDFL.RenderProgressStage", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_render_progress_stage.html", null ],
    [ "com.datalogics.PDFL.ReportProc", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_report_proc.html", null ],
    [ "com.datalogics.PDFL.ReportType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_report_type.html", null ],
    [ "com.datalogics.PDFL.RolledBackDocument", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_rolled_back_document.html", null ],
    [ "RuntimeException", null, [
      [ "com.datalogics.PDFL.LibraryException", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_library_exception.html", null ]
    ] ],
    [ "com.datalogics.PDFL.SaveFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_save_flags.html", null ],
    [ "com.datalogics.PDFL.SchemaFieldSubtype", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_schema_field_subtype.html", null ],
    [ "com.datalogics.PDFL.Segment", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_segment.html", [
      [ "com.datalogics.PDFL.ClosePath", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_close_path.html", null ],
      [ "com.datalogics.PDFL.CurveTo", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_curve_to.html", null ],
      [ "com.datalogics.PDFL.CurveToV", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_curve_to_v.html", null ],
      [ "com.datalogics.PDFL.CurveToY", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_curve_to_y.html", null ],
      [ "com.datalogics.PDFL.LineTo", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_line_to.html", null ],
      [ "com.datalogics.PDFL.MoveTo", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_move_to.html", null ],
      [ "com.datalogics.PDFL.RectSegment", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_rect_segment.html", null ]
    ] ],
    [ "com.datalogics.PDFL.SeparationFontOptions", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_separation_font_options.html", null ],
    [ "com.datalogics.PDFL.SeparationParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_separation_params.html", null ],
    [ "com.datalogics.PDFL.SeparationPlate", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_separation_plate.html", null ],
    [ "com.datalogics.PDFL.SeparationPreviewOptions", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_separation_preview_options.html", null ],
    [ "com.datalogics.PDFL.SmoothFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_smooth_flags.html", null ],
    [ "com.datalogics.PDFL.Style", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_style.html", null ],
    [ "com.datalogics.PDFL.StyleTransition", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_style_transition.html", null ],
    [ "com.datalogics.PDFL.TempStoreType", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_temp_store_type.html", null ],
    [ "com.datalogics.PDFL.TextFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_text_flags.html", null ],
    [ "com.datalogics.PDFL.TextRenderMode", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_text_render_mode.html", null ],
    [ "com.datalogics.PDFL.TextState", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_text_state.html", null ],
    [ "com.datalogics.PDFL.TIFFByteOrder", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_t_i_f_f_byte_order.html", null ],
    [ "com.datalogics.PDFL.VerticalAlignment", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_vertical_alignment.html", null ],
    [ "com.datalogics.PDFL.ViewDestination", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_view_destination.html", null ],
    [ "com.datalogics.PDFL.VisibilityPolicy", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_visibility_policy.html", null ],
    [ "com.datalogics.PDFL.WatermarkDrawOption", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_watermark_draw_option.html", null ],
    [ "com.datalogics.PDFL.WatermarkParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_watermark_params.html", null ],
    [ "com.datalogics.PDFL.WatermarkTextParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_watermark_text_params.html", null ],
    [ "com.datalogics.PDFL.Word", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_word.html", null ],
    [ "com.datalogics.PDFL.WordAttributeFlags", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_word_attribute_flags.html", null ],
    [ "com.datalogics.PDFL.WordFinder", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_word_finder.html", null ],
    [ "com.datalogics.PDFL.WordFinderConfig", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_word_finder_config.html", null ],
    [ "com.datalogics.PDFL.WordFinderVersion", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_word_finder_version.html", null ],
    [ "com.datalogics.PDFL.WordProc", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_word_proc.html", null ],
    [ "com.datalogics.PDFL.WritingMode", "enumcom_1_1datalogics_1_1_p_d_f_l_1_1_writing_mode.html", null ],
    [ "com.datalogics.PDFL.XPSConvertParams", "classcom_1_1datalogics_1_1_p_d_f_l_1_1_x_p_s_convert_params.html", null ]
];