Programming Reference: Main Page
com.datalogics.PDFL.Shading Class Reference
Public Member Functions
Element clone ()
Element clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
synchronized void delete ()
Rect getBoundingBox ()
Clip getClip ()
ColorSpace getColorSpace ()
GraphicState getGraphicState ()
Matrix getMatrix ()
void rotate (double theta)
void scale (double sx, double sy)
void setClip (Clip clip)
void setMatrix (Matrix matrix)
void translate (double tx, double ty)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Shading (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Element obj)
static long getCPtr (Shading obj)
Detailed Description
Represents a region shaded with color, as defined by a shading dictionary. A shading pattern defines a gradient fill in a graphic that produces a smooth transition between colors across the area covered by the graphic area. The "sh" paint operator is invoked for the shading object. This does not correspond to a shading dictionary within a PDF pattern. Refer to the Pattern object for shading dictionaries used in PDF patterns.
A shading pattern defines a gradient fill in a graphic that produces a smooth transition between colors across the area covered by the graphic area. The "sh" paint operator is invoked for the shading object. This does not correspond to a shading dictionary within a PDF pattern. Refer to the Pattern object for shading dictionaries used in PDF patterns.
For more detail, see sections 8.7.4.2 and 8.7.4.3, Shading Operator and Shading Dictionaries, under "Shading Patterns," of the ISO 32000-1:2008, Document Management-Portable Document Format-Part 1: PDF 1.7, pages 181-4.
Constructor & Destructor Documentation
Shading()
com.datalogics.PDFL.Shading.Shading (long cPtr, boolean cMemoryOwn) protected
Member Function Documentation
clone() [1/2]
Element com.datalogics.PDFL.Element.clone () inherited
Makes a copy of the element.
Make a copy of an element to obtain a new element that has a distinct set of attributes.
Note: TextRun objects may not be cloned.
Returns
The copied element.
Reimplemented in com.datalogics.PDFL.Text, com.datalogics.PDFL.Path, com.datalogics.PDFL.Image, com.datalogics.PDFL.Group, com.datalogics.PDFL.Form, and com.datalogics.PDFL.Container.
clone() [2/2]
Element com.datalogics.PDFL.Element.clone (java.util.EnumSet< ElementCloneFlags > cloneFlags) inherited
Makes a copy of the element.
Make a copy of an element to obtain a new element that has a distinct set of attributes.
Note: TextRun objects may not be cloned.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied element.
Reimplemented in com.datalogics.PDFL.Text, com.datalogics.PDFL.Path, com.datalogics.PDFL.Image, com.datalogics.PDFL.Group, and com.datalogics.PDFL.Container.
delete() [1/2]
synchronized void com.datalogics.PDFL.Shading.delete ()
Reimplemented from com.datalogics.PDFL.Element.
delete() [2/2]
synchronized void com.datalogics.PDFL.Shading.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Element.
finalize()
void com.datalogics.PDFL.Shading.finalize () protected
Reimplemented from com.datalogics.PDFL.Element.
getBoundingBox()
Rect com.datalogics.PDFL.Element.getBoundingBox () inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
getClip()
Clip com.datalogics.PDFL.Element.getClip () inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
getColorSpace()
ColorSpace com.datalogics.PDFL.Shading.getColorSpace ()
Get the ColorSpace of the current Shading object.
getCPtr() [1/2]
static long com.datalogics.PDFL.Element.getCPtr (Element obj) static protected inherited
Referenced by com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Content.addElement(), and com.datalogics.PDFL.Content.Content().
getCPtr() [2/2]
static long com.datalogics.PDFL.Shading.getCPtr (Shading obj) static protected
getGraphicState()
GraphicState com.datalogics.PDFL.Shading.getGraphicState ()
Get the graphic state of the current Shading object.
May return null if this element does not have a GraphicState.
getMatrix()
Matrix com.datalogics.PDFL.Element.getMatrix () inherited
The transformation matrix for the element.
rotate()
void com.datalogics.PDFL.Element.rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Reimplemented in com.datalogics.PDFL.Image.
scale()
void com.datalogics.PDFL.Element.scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
setClip()
void com.datalogics.PDFL.Element.setClip (Clip clip) inherited
Sets the current Clip for an Element.
Parameters
clip The clip to set as the current clip for this element.
setMatrix()
void com.datalogics.PDFL.Element.setMatrix (Matrix matrix) inherited
Set the transformation matrix for the element.
Parameters
matrix the transformation matrix for the element.
translate()
void com.datalogics.PDFL.Element.translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Reimplemented in com.datalogics.PDFL.Image.