Programming Reference: Main Page
com.datalogics.PDFL.CalRGBColorSpace Class Reference
Public Member Functions
CalRGBColorSpace (java.util.List< Double > whitePoint)
CalRGBColorSpace (java.util.List< Double > whitePoint, java.util.List< Double > blackPoint, java.util.List< Double > gamma, java.util.List< Double > matrix)
synchronized void delete ()
boolean equals (Object rhs)
java.util.List< Double > getBlackPoint ()
java.util.List< Double > getGamma ()
java.util.List< Double > getMatrix ()
String getName ()
int getNumComponents ()
PDFObject getPDFObject ()
java.util.List< Double > getWhitePoint ()
String toString ()
Static Public Attributes
static final ColorSpace DEVICE_CMYK
static final ColorSpace DEVICE_GRAY
static final ColorSpace DEVICE_RGB
static final ColorSpace DEVICE_RGBA
static final ColorSpace LAB
static final ColorSpace LAB_A
Protected Member Functions
CalRGBColorSpace (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (CalRGBColorSpace obj)
static long getCPtr (ColorSpace obj)
Detailed Description
A calibrated RGB color space. A CalRGB color space (Red, Green, Blue) is a CIE-based ABC color space with only one transformation stage instead of two.
In this type of space, A, B, and C represent calibrated red, green, and blue color values. These three color components must be in the range 0.0 to 1.0; component values falling outside that range are adjusted to the nearest valid value without error indication.
See section 8.6.5.3 of the ISO 32000-1:2008, Document Management-Portable Document Format-Part 1: PDF 1.7, page 146.
Constructor & Destructor Documentation
CalRGBColorSpace() [1/3]
com.datalogics.PDFL.CalRGBColorSpace.CalRGBColorSpace (long cPtr, boolean cMemoryOwn) protected
CalRGBColorSpace() [2/3]
com.datalogics.PDFL.CalRGBColorSpace.CalRGBColorSpace (java.util.List< Double > whitePoint, java.util.List< Double > blackPoint, java.util.List< Double > gamma, java.util.List< Double > matrix)
Create a CalRGB color space.
Parameters
whitePoint An array of three numbers specifying the tristimulus value, in the CIE 1931 XYZ space, of the diffuse white point. The numbers X and Z must be positive, and Y must be equal to 1.0.
blackPoint An array of three numbers specifying the tristimulus value, in the CIE 1931 XYZ space, of the diffuse black point. All three of these numbers must be non-negative.
gamma An array of three numbers [ GR GG GB ] specifying the gamma for the red, green, and blue (A, B, and C) components of the color space.
matrix An array of nine numbers [ XA YA ZA XB YB ZB XC YC ZC ] specifying the linear interpretation of the decoded A, B, and C components of the color space with respect to the final XYZ representation.
CalRGBColorSpace() [3/3]
com.datalogics.PDFL.CalRGBColorSpace.CalRGBColorSpace (java.util.List< Double > whitePoint)
Create a CalRGB color space.
The blackPoint defaults to [0.0, 0.0, 0.0].
The gamma defaults to [1.0, 1.0, 1.0].
The matrix defaults to [1 0 0 0 1 0 0 0 1]
Parameters
whitePoint An array of three numbers specifying the tristimulus value, in the CIE 1931 XYZ space, of the diffuse white point. The numbers X and Z must be positive, and Y must be equal to 1.0.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.CalRGBColorSpace.delete ()
Reimplemented from com.datalogics.PDFL.ColorSpace.
delete() [2/2]
synchronized void com.datalogics.PDFL.CalRGBColorSpace.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.ColorSpace.
equals()
boolean com.datalogics.PDFL.ColorSpace.equals (Object rhs) inherited
Reimplemented in com.datalogics.PDFL.NamedColorSpace.
finalize()
void com.datalogics.PDFL.CalRGBColorSpace.finalize () protected
Reimplemented from com.datalogics.PDFL.ColorSpace.
getBlackPoint()
java.util.List<Double> com.datalogics.PDFL.CalRGBColorSpace.getBlackPoint ()
An array of three numbers specifying the tristimulus value, in the CIE 1931 XYZ space, of the diffuse black point. All three of these numbers must be non-negative.
getCPtr() [1/2]
static long com.datalogics.PDFL.CalRGBColorSpace.getCPtr (CalRGBColorSpace obj) static protected
getCPtr() [2/2]
static long com.datalogics.PDFL.ColorSpace.getCPtr (ColorSpace obj) static protected inherited
Referenced by com.datalogics.PDFL.Image.Image(), com.datalogics.PDFL.PageImageParams.PageImageParams(), com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), com.datalogics.PDFL.ICCBasedColorSpace.setAlternate(), com.datalogics.PDFL.DrawParams.setColorSpace(), com.datalogics.PDFL.ShadingPattern.setColorSpace(), com.datalogics.PDFL.Content.setDefaultColorSpace(), and com.datalogics.PDFL.PageImageParams.setImageColorSpace().
getGamma()
java.util.List<Double> com.datalogics.PDFL.CalRGBColorSpace.getGamma ()
A number G defining the gamma for the gray component. G must be positive and is generally greater than or equal to 1.
getMatrix()
java.util.List<Double> com.datalogics.PDFL.CalRGBColorSpace.getMatrix ()
An array of nine numbers [ XA YA ZA XB YB ZB XC YC ZC ] specifying the linear interpretation of the decoded A, B, and C components of the color space with respect to the final XYZ representation.
getName()
String com.datalogics.PDFL.ColorSpace.getName () inherited
The name of the color space. A named color space may be named something like DeviceRGB. More complicated color spaces may have a name like Indexed or ICCBased.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getNumComponents()
int com.datalogics.PDFL.ColorSpace.getNumComponents () inherited
The number of components in the color space.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getPDFObject()
PDFObject com.datalogics.PDFL.ColorSpace.getPDFObject () inherited
Get the PDFObject associated with the color space. This may be a PDFName, PDFDict, PDFStream, or PDFArray.
Returns
The PDFObject associated with the color space.
getWhitePoint()
java.util.List<Double> com.datalogics.PDFL.CalRGBColorSpace.getWhitePoint ()
An array of three numbers specifying the tristimulus value, in the CIE 1931 XYZ space, of the diffuse white point. The numbers X and Z must be positive, and Y must be equal to 1.0.
toString()
String com.datalogics.PDFL.ColorSpace.toString () inherited
Convert a colorSpace to a string.
Member Data Documentation
DEVICE_CMYK
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_CMYK static inherited
DEVICE_GRAY
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_GRAY static inherited
DEVICE_RGB
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGB static inherited
DEVICE_RGBA
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGBA static inherited
LAB
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB static inherited
LAB_A
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB_A static inherited