Programming Reference: Main Page
com.datalogics.PDFL.SeparationColorSpace Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
ColorSpace getAlternate ()
Function getFunction ()
String getName ()
int getNumComponents ()
PDFObject getPDFObject ()
String getSeparationName ()
SeparationColorSpace (Page page, Ink ink)
SeparationColorSpace (String separationName, ColorSpace alternate, Function tintTransform)
String toString ()
Static Public Attributes
static final ColorSpace DEVICE_CMYK
static final ColorSpace DEVICE_GRAY
static final ColorSpace DEVICE_RGB
static final ColorSpace DEVICE_RGBA
static final ColorSpace LAB
static final ColorSpace LAB_A
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
SeparationColorSpace (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (ColorSpace obj)
static long getCPtr (SeparationColorSpace obj)
Detailed Description
Defines the use of additional named colorants in a PDF document. Colorants in a separation color space are also sometimes referred to as spot colorants. The device displaying or printing the PDF document will supply an appropriate color based on the colorant included in the separation color space.
Constructor & Destructor Documentation
SeparationColorSpace() [1/3]
com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace (long cPtr, boolean cMemoryOwn) protected
SeparationColorSpace() [2/3]
com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace (String separationName, ColorSpace alternate, Function tintTransform)
Create a separation color space.
Parameters
separationName the name of the colorant that the Separation space is intended to represent, or All, or None
alternate the alternate color space, which can be any device or CIE-based color space but not another special color space (Pattern, Indexed, Separation, or DeviceN).
tintTransform function, called with the tint value and returning the corresponding color component values. That is, the number of components and the interpretation of their values depend on the alternate color space.
SeparationColorSpace() [3/3]
com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace (Page page, Ink ink)
Create a separation color space from page's Ink. If page doesn't have a separation color space with passed ink in it's resources, then linear grayscale tint transform function and CMYK as alternate colorspace will be used.
Parameters
page Page, that contains an ink
ink Represents an ink used in a page
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.SeparationColorSpace.delete ()
Reimplemented from com.datalogics.PDFL.ColorSpace.
delete() [2/2]
synchronized void com.datalogics.PDFL.SeparationColorSpace.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.ColorSpace.
equals()
boolean com.datalogics.PDFL.ColorSpace.equals (Object rhs) inherited
Reimplemented in com.datalogics.PDFL.NamedColorSpace.
finalize()
void com.datalogics.PDFL.SeparationColorSpace.finalize () protected
Reimplemented from com.datalogics.PDFL.ColorSpace.
getAlternate()
ColorSpace com.datalogics.PDFL.SeparationColorSpace.getAlternate ()
the alternate color space, which can be any device or CIE-based color space but not another special color space (Pattern, Indexed, Separation, or DeviceN).
getCPtr() [1/2]
static long com.datalogics.PDFL.ColorSpace.getCPtr (ColorSpace obj) static protected inherited
Referenced by com.datalogics.PDFL.Image.Image(), com.datalogics.PDFL.PageImageParams.PageImageParams(), com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), com.datalogics.PDFL.ICCBasedColorSpace.setAlternate(), com.datalogics.PDFL.DrawParams.setColorSpace(), com.datalogics.PDFL.ShadingPattern.setColorSpace(), com.datalogics.PDFL.Content.setDefaultColorSpace(), and com.datalogics.PDFL.PageImageParams.setImageColorSpace().
getCPtr() [2/2]
static long com.datalogics.PDFL.SeparationColorSpace.getCPtr (SeparationColorSpace obj) static protected
getFunction()
Function com.datalogics.PDFL.SeparationColorSpace.getFunction ()
A function, called with the tint value and returning the corresponding color component values. That is, the number of components and the interpretation of their values depend on the alternate color space.
getName()
String com.datalogics.PDFL.ColorSpace.getName () inherited
The name of the color space. A named color space may be named something like DeviceRGB. More complicated color spaces may have a name like Indexed or ICCBased.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getNumComponents()
int com.datalogics.PDFL.ColorSpace.getNumComponents () inherited
The number of components in the color space.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getPDFObject()
PDFObject com.datalogics.PDFL.ColorSpace.getPDFObject () inherited
Get the PDFObject associated with the color space. This may be a PDFName, PDFDict, PDFStream, or PDFArray.
Returns
The PDFObject associated with the color space.
getSeparationName()
String com.datalogics.PDFL.SeparationColorSpace.getSeparationName ()
the name of the colorant that the Separation space is intended to represent, or All, or None.
toString()
String com.datalogics.PDFL.ColorSpace.toString () inherited
Convert a colorSpace to a string.
Member Data Documentation
DEVICE_CMYK
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_CMYK static inherited
DEVICE_GRAY
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_GRAY static inherited
DEVICE_RGB
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGB static inherited
DEVICE_RGBA
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGBA static inherited
LAB
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB static inherited
LAB_A
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB_A static inherited