Programming Reference: Main Page
com.datalogics.PDFL.Form Class Reference
Public Member Functions
Form clone ()
Element clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Form colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
synchronized void delete ()
Form (Content content)
Form (Content content, Document document)
Rect getBoundingBox ()
Clip getClip ()
Content getContent ()
GraphicState getGraphicState ()
Matrix getMatrix ()
OptionalContentMembershipDict getOptionalContentMembershipDict ()
PDFStream getStream ()
boolean isCurrentlyVisible (OptionalContentContext occ)
boolean isCurrentlyVisible (OptionalContentContext occ, Content content)
boolean makeVisible (OptionalContentContext occ, Content content)
void rotate (double theta)
void scale (double sx, double sy)
void setClip (Clip clip)
void setContent (Content content)
void setGraphicState (GraphicState gstate)
void setMatrix (Matrix matrix)
void setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd)
void translate (double tx, double ty)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Form (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Element obj)
static long getCPtr (Form obj)
Detailed Description
Represents a PDF form XObject. This is not to be confused with a PDF fillable form; a Form XObject is an object outside the page content stream.
A form XObject is a way to group a number of PDF objects together, into a single container. A Form XObject can hold both text and images, and can be defined once within a PDF file and then reused multiple times in the same PDF, and across multiple pages.
Constructor & Destructor Documentation
Form() [1/3]
com.datalogics.PDFL.Form.Form (long cPtr, boolean cMemoryOwn) protected
Form() [2/3]
com.datalogics.PDFL.Form.Form (Content content)
Create a form with the given Content.
Form() [3/3]
com.datalogics.PDFL.Form.Form (Content content, Document document)
Create a form with the given Content.
Specifying the document optimizes data usage for this image within that document.
Parameters
content The content from which to create the form
document the document in which the image is intended to be used.
Member Function Documentation
clone() [1/2]
Form com.datalogics.PDFL.Form.clone ()
Creates a new form from an existing form object. Creates a copy of the Form, including the underlying Content.
Returns
The newly created form object.
Reimplemented from com.datalogics.PDFL.Element.
clone() [2/2]
Element com.datalogics.PDFL.Element.clone (java.util.EnumSet< ElementCloneFlags > cloneFlags) inherited
Makes a copy of the element.
Make a copy of an element to obtain a new element that has a distinct set of attributes.
Note: TextRun objects may not be cloned.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied element.
Reimplemented in com.datalogics.PDFL.Text, com.datalogics.PDFL.Path, com.datalogics.PDFL.Image, com.datalogics.PDFL.Group, and com.datalogics.PDFL.Container.
colorConvert()
Form com.datalogics.PDFL.Form.colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
Applies the specified ICC ColorProfile to the objects in the form
Parameters
document The document the element belongs to.
prof The ICC ColorProfile to be applied.
intent The ICC Rendering Intent for the ColorProfile
embed If true, embed the color space and make the objects calibrated. If it is false and the target profile is CMYK, RGB, or Gray, the colors space of the resulting objects, after conversion, will be DeviceCMYK, DeviceRGB, or DeviceGray, respectively.
Returns
A new Form with the applied ICC ColorProfile.
delete() [1/2]
synchronized void com.datalogics.PDFL.Form.delete ()
Reimplemented from com.datalogics.PDFL.Element.
delete() [2/2]
synchronized void com.datalogics.PDFL.Form.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Element.
finalize()
void com.datalogics.PDFL.Form.finalize () protected
Reimplemented from com.datalogics.PDFL.Element.
getBoundingBox()
Rect com.datalogics.PDFL.Element.getBoundingBox () inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
getClip()
Clip com.datalogics.PDFL.Element.getClip () inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
getContent()
Content com.datalogics.PDFL.Form.getContent ()
The Content contained in the form.
getCPtr() [1/2]
static long com.datalogics.PDFL.Element.getCPtr (Element obj) static protected inherited
Referenced by com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Content.addElement(), and com.datalogics.PDFL.Content.Content().
getCPtr() [2/2]
static long com.datalogics.PDFL.Form.getCPtr (Form obj) static protected
Referenced by com.datalogics.PDFL.Annotation.setNormalAppearance().
getGraphicState()
GraphicState com.datalogics.PDFL.Form.getGraphicState ()
Get the graphic state of this Form.
May return null if this element does not have a GraphicState.
getMatrix()
Matrix com.datalogics.PDFL.Element.getMatrix () inherited
The transformation matrix for the element.
getOptionalContentMembershipDict()
OptionalContentMembershipDict com.datalogics.PDFL.Form.getOptionalContentMembershipDict ()
The OptionalContentMembershipDict property for this Form.
Setting this property will attach the Form to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Form is detached from any OptionalContentMembershipDict.
Returns
the OptionalContentMembershipDict
getStream()
PDFStream com.datalogics.PDFL.Form.getStream ()
Get the stream associated with the form.
Returns
The stream associated with the form.
isCurrentlyVisible() [1/2]
boolean com.datalogics.PDFL.Form.isCurrentlyVisible (OptionalContentContext occ)
Tests whether a form is visible in a given optional content context, considering the current ON-OFF states of the optional-content groups in the optional-content dictionary (OCMD) and the dictionary's visibility policy.
If the form occurs more than once within the content, this method only checks the visibility of the first occurrence of the form.
This method determines visibility without considering the visbility of the Content object that the form belongs to. To determine the visibility of a form while taking the Content's visibility into consideration, use the alternate version of this method.
Returns
true if the form is currently visible.
isCurrentlyVisible() [2/2]
boolean com.datalogics.PDFL.Form.isCurrentlyVisible (OptionalContentContext occ, Content content)
Tests whether an form is visible in a given optional content context and content.
If the form occurs more than once within the content, this method only checks the visibility of the first occurrence of the form.
Returns
true if the form is currently visible.
makeVisible()
boolean com.datalogics.PDFL.Form.makeVisible (OptionalContentContext occ, Content content)
Makes a form visible in a given optional content context and content by manipulating the ON-OFF states of the optional content groups.
Parameters
occ The optional content context in which the form is made visible.
content The content containing the form.
Returns
true if the form is successfully made visible in the given context and content, false otherwise
rotate()
void com.datalogics.PDFL.Element.rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Reimplemented in com.datalogics.PDFL.Image.
scale()
void com.datalogics.PDFL.Element.scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
setClip()
void com.datalogics.PDFL.Element.setClip (Clip clip) inherited
Sets the current Clip for an Element.
Parameters
clip The clip to set as the current clip for this element.
setContent()
void com.datalogics.PDFL.Form.setContent (Content content)
The Content contained in the form.
setGraphicState()
void com.datalogics.PDFL.Form.setGraphicState (GraphicState gstate)
Set the Graphic State of this Form.
Parameters
gstate the new/updated Graphic State for the Form.
setMatrix()
void com.datalogics.PDFL.Element.setMatrix (Matrix matrix) inherited
Set the transformation matrix for the element.
Parameters
matrix the transformation matrix for the element.
setOptionalContentMembershipDict()
void com.datalogics.PDFL.Form.setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd)
The OptionalContentMembershipDict property for this Form.
Setting this property will attach the Form to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Form is detached from any OptionalContentMembershipDict.
Parameters
ocmd the OptionalContentMembershipDict
translate()
void com.datalogics.PDFL.Element.translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Reimplemented in com.datalogics.PDFL.Image.