Programming Reference: Main Page
com.datalogics.PDFL.ColorSpace Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
String getName ()
int getNumComponents ()
PDFObject getPDFObject ()
String toString ()
Static Public Attributes
static final ColorSpace DEVICE_CMYK
static final ColorSpace DEVICE_GRAY
static final ColorSpace DEVICE_RGB
static final ColorSpace DEVICE_RGBA
static final ColorSpace LAB
static final ColorSpace LAB_A
Protected Member Functions
ColorSpace (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (ColorSpace obj)
Detailed Description
Base class for all color spaces. CalCMYK was never truly completed and is now deprecated. DLE returns DeviceCMYK for cases where the source file has CalCMYK, as suggested by that note.
See section 8.6.5 of the ISO 32000-1:2008, Document Management-Portable Document Format-Part 1: PDF 1.7, page 144.
Constructor & Destructor Documentation
ColorSpace()
com.datalogics.PDFL.ColorSpace.ColorSpace (long cPtr, boolean cMemoryOwn) protected
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.ColorSpace.delete ()
Reimplemented in com.datalogics.PDFL.SeparationColorSpace, com.datalogics.PDFL.NamedColorSpace, com.datalogics.PDFL.LabColorSpace, com.datalogics.PDFL.IndexedColorSpace, com.datalogics.PDFL.ICCBasedColorSpace, com.datalogics.PDFL.DeviceNColorSpace, com.datalogics.PDFL.CalRGBColorSpace, and com.datalogics.PDFL.CalGrayColorSpace.
delete() [2/2]
synchronized void com.datalogics.PDFL.ColorSpace.delete (Boolean disposing) protected
Reimplemented in com.datalogics.PDFL.SeparationColorSpace, com.datalogics.PDFL.LabColorSpace, com.datalogics.PDFL.IndexedColorSpace, com.datalogics.PDFL.ICCBasedColorSpace, com.datalogics.PDFL.DeviceNColorSpace, com.datalogics.PDFL.CalRGBColorSpace, and com.datalogics.PDFL.CalGrayColorSpace.
equals()
boolean com.datalogics.PDFL.ColorSpace.equals (Object rhs)
Reimplemented in com.datalogics.PDFL.NamedColorSpace.
finalize()
void com.datalogics.PDFL.ColorSpace.finalize () protected
Reimplemented in com.datalogics.PDFL.SeparationColorSpace, com.datalogics.PDFL.NamedColorSpace, com.datalogics.PDFL.LabColorSpace, com.datalogics.PDFL.IndexedColorSpace, com.datalogics.PDFL.ICCBasedColorSpace, com.datalogics.PDFL.DeviceNColorSpace, com.datalogics.PDFL.CalRGBColorSpace, and com.datalogics.PDFL.CalGrayColorSpace.
getCPtr()
static long com.datalogics.PDFL.ColorSpace.getCPtr (ColorSpace obj) static protected
Referenced by com.datalogics.PDFL.Image.Image(), com.datalogics.PDFL.PageImageParams.PageImageParams(), com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), com.datalogics.PDFL.ICCBasedColorSpace.setAlternate(), com.datalogics.PDFL.DrawParams.setColorSpace(), com.datalogics.PDFL.ShadingPattern.setColorSpace(), com.datalogics.PDFL.Content.setDefaultColorSpace(), and com.datalogics.PDFL.PageImageParams.setImageColorSpace().
getName()
String com.datalogics.PDFL.ColorSpace.getName ()
The name of the color space. A named color space may be named something like DeviceRGB. More complicated color spaces may have a name like Indexed or ICCBased.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getNumComponents()
int com.datalogics.PDFL.ColorSpace.getNumComponents ()
The number of components in the color space.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getPDFObject()
PDFObject com.datalogics.PDFL.ColorSpace.getPDFObject ()
Get the PDFObject associated with the color space. This may be a PDFName, PDFDict, PDFStream, or PDFArray.
Returns
The PDFObject associated with the color space.
toString()
String com.datalogics.PDFL.ColorSpace.toString ()
Convert a colorSpace to a string.
Member Data Documentation
DEVICE_CMYK
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_CMYK static
DEVICE_GRAY
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_GRAY static
DEVICE_RGB
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGB static
DEVICE_RGBA
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGBA static
LAB
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB static
LAB_A
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB_A static