Programming Reference: Main Page
com.datalogics.PDFL.OptionalContentOrderArray Class Reference
Public Member Functions
void add (OptionalContentOrderNode node)
synchronized void delete ()
OptionalContentOrderNode get (int index)
int getLength ()
String getTitle ()
void insert (int index, OptionalContentOrderNode node)
OptionalContentOrderArray (Document doc)
OptionalContentOrderArray (Document doc, String title)
void put (int index, OptionalContentOrderNode node)
void removeAt (int index)
void setTitle (String title)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
OptionalContentOrderArray (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (OptionalContentOrderArray obj)
static long getCPtr (OptionalContentOrderNode obj)
Detailed Description
Array node class for items in the OptionalContentConfig Order array. Items in the Order array can be arranged into a tree structure; subarrays within the parent array form 'branches' of the tree. Each OptionalContentOrderArray may contain OptionalContentOrderLeafs or OptionalContentOrderArrays in a specific order; this order determines how they will appear in the 'Layers' control of the viewer.
By placing OptionalContentOrderArrays into a higher-level array, branches can be added to the tree. The 'Title' property is a string that will appear next to the expand/collapse branch control in the Acrobat 'Layers' control panel.
Constructor & Destructor Documentation
OptionalContentOrderArray() [1/3]
com.datalogics.PDFL.OptionalContentOrderArray.OptionalContentOrderArray (long cPtr, boolean cMemoryOwn) protected
OptionalContentOrderArray() [2/3]
com.datalogics.PDFL.OptionalContentOrderArray.OptionalContentOrderArray (Document doc)
Create an OptionalContentOrderArray with no title.
Parameters
doc The Document this OptionalContentOrderArray is being created in
OptionalContentOrderArray() [3/3]
com.datalogics.PDFL.OptionalContentOrderArray.OptionalContentOrderArray (Document doc, String title)
Create an OptionalContentOrderArray with a title.
Parameters
title The string which will appear in the Layer control panel
doc The Document this OptionalContentOrderArray is being created in
Member Function Documentation
add()
void com.datalogics.PDFL.OptionalContentOrderArray.add (OptionalContentOrderNode node)
Adds an OptionalContentOrderNode to the end of the Array.
Parameters
node The OptionalContentOrderNode to append to the Array
delete() [1/2]
synchronized void com.datalogics.PDFL.OptionalContentOrderArray.delete ()
Reimplemented from com.datalogics.PDFL.OptionalContentOrderNode.
delete() [2/2]
synchronized void com.datalogics.PDFL.OptionalContentOrderArray.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.OptionalContentOrderNode.
finalize()
void com.datalogics.PDFL.OptionalContentOrderArray.finalize () protected
Reimplemented from com.datalogics.PDFL.OptionalContentOrderNode.
get()
OptionalContentOrderNode com.datalogics.PDFL.OptionalContentOrderArray.get (int index)
Returns the OptionalContentOrderNode at the given index.
Parameters
index The index at which to fetch an OptionalContentOrderNode.
Returns
An OptionalContentOrderNode, or null if there is nothing at that index.
getCPtr() [1/2]
static long com.datalogics.PDFL.OptionalContentOrderArray.getCPtr (OptionalContentOrderArray obj) static protected
getCPtr() [2/2]
static long com.datalogics.PDFL.OptionalContentOrderNode.getCPtr (OptionalContentOrderNode obj) static protected inherited
Referenced by com.datalogics.PDFL.OptionalContentOrderArray.add(), com.datalogics.PDFL.OptionalContentOrderArray.insert(), and com.datalogics.PDFL.OptionalContentOrderArray.put().
getLength()
int com.datalogics.PDFL.OptionalContentOrderArray.getLength ()
The number of OptionalContentOrderNodes currently in this array.
getTitle()
String com.datalogics.PDFL.OptionalContentOrderArray.getTitle ()
The title string of this Array. This title will appear next to the expand/collapse control in the 'Layers' control panel in Acrobat.
This field may be set null to remove the title.
Returns
The title string of this OptionalContentOrderArray.
insert()
void com.datalogics.PDFL.OptionalContentOrderArray.insert (int index, OptionalContentOrderNode node)
Inserts an OptionalContentOrderNode at the given index, displacing existing objects. All objects following this will have their index increased by one.
Parameters
index The index at which to insert the Node
node The OptionalContentOrderNode to insert in the Array
put()
void com.datalogics.PDFL.OptionalContentOrderArray.put (int index, OptionalContentOrderNode node)
Puts an OptionalContentOrderNode at the given index, replacing the existing item. The index can be greater than the current length of the array; the array will be extended and the empty slots filled with null objects.
Parameters
index The index at which to replace the existing Node
node The OptionalContentOrderNode to place in the Array
removeAt()
void com.datalogics.PDFL.OptionalContentOrderArray.removeAt (int index)
Removes the OptionalContentOrderNode at the given index. The length of the array is reduced by 1.
Parameters
index The index of the OptionalContentOrderNode to remove
setTitle()
void com.datalogics.PDFL.OptionalContentOrderArray.setTitle (String title)
The title string of this Array. This title will appear next to the expand/collapse control in the 'Layers' control panel in Acrobat.
This field may be set null to remove the title.
Parameters
title The title string of this OptionalContentOrderArray.