Programming Reference: Main Page
com.datalogics.PDFL.Text Class Reference
Public Member Functions
void addGlyphs (java.util.List< java.lang.Character > glyphIDs, java.util.List< java.lang.Character > uniText, Font font, GraphicState gState, TextState state, Matrix matrix, java.util.EnumSet< TextFlags > flags)
void addGlyphs (java.util.List< java.lang.Character > glyphIDs, java.util.List< java.lang.Character > uniText, Font font, GraphicState gState, TextState state, Matrix matrix, java.util.EnumSet< TextFlags > flags, int index)
void addRun (TextRun run)
void addRun (TextRun run, int index)
void changeMatrixForTextRun (Matrix newMatrix, int textRunIndex)
void changeTextMatrixForTextRun (Matrix newMatrix, int textRunIndex)
Text clone ()
Text clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Text colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
synchronized void delete ()
int findTextRunIndexForCharacter (int characterIndex)
Point getAdvanceForCharacter (int characterIndex)
Point getAdvanceForTextRun (int textRunIndex)
Rect getBoundingBox ()
Rect getBoundingBoxForCharacter (int characterIndex)
Clip getClip ()
Matrix getMatrix ()
int getNumberOfCharacters ()
int getNumberOfRuns ()
TextRun getRun (int index)
Matrix getTextMatrixForCharacter (int characterIndex)
Matrix getTextMatrixForTextRun (int textRunIndex)
boolean pointIntersectsCharacter (Point p, int index)
boolean pointIntersectsTextRun (Point p, int index)
boolean rectIntersectsCharacter (Rect r, int index)
boolean rectIntersectsTextRun (Rect r, int index)
void removeRuns (int index, int count)
void rotate (double theta)
void scale (double sx, double sy)
void setClip (Clip clip)
void setMatrix (Matrix matrix)
void splitTextRunAtCharacter (int splitLocation)
Text ()
void translate (double tx, double ty)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Text (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Element obj)
static long getCPtr (Text obj)
Detailed Description
A container that represents a series of text elements and characters. A Text object is container that represents both a series of TextRun elements and a series of text characters. Operations can be performed on individual TextRuns within a Text or on individual characters within a Text by specifying the index of the individual TextRun or character. All indices start at 0.
Constructor & Destructor Documentation
Text() [1/2]
com.datalogics.PDFL.Text.Text (long cPtr, boolean cMemoryOwn) protected
Text() [2/2]
com.datalogics.PDFL.Text.Text ()
Member Function Documentation
addGlyphs() [1/2]
void com.datalogics.PDFL.Text.addGlyphs (java.util.List< java.lang.Character > glyphIDs, java.util.List< java.lang.Character > uniText, Font font, GraphicState gState, TextState state, Matrix matrix, java.util.EnumSet< TextFlags > flags)
Adds Unicode text to a Text object
Parameters
glyphIDs Glyphs IDs in the specified font for adding to the page's content
uniText Unicode codes for the specified glyph IDs
font Font for wich GlyphIDs were specified
gState The GraphicsState for Text element
state TextState flags
matrix matrix for the Text element
flags TextFlags that specifies what kind of text to add
addGlyphs() [2/2]
void com.datalogics.PDFL.Text.addGlyphs (java.util.List< java.lang.Character > glyphIDs, java.util.List< java.lang.Character > uniText, Font font, GraphicState gState, TextState state, Matrix matrix, java.util.EnumSet< TextFlags > flags, int index)
Adds Unicode text to a Text object
Parameters
glyphIDs Glyphs IDs in the specified font to add to the page's content
uniText Unicode codes for the specified glyph IDs
font Font for wich GlyphIDs were specified
gState The GraphicsState for Text element
state TextState flags
matrix matrix for the Text element
flags TextFlags that specifies what kind of text to add
index The index after which to add the character or text run.
addRun() [1/2]
void com.datalogics.PDFL.Text.addRun (TextRun run)
Adds a TextRun to the end of this text element.
addRun() [2/2]
void com.datalogics.PDFL.Text.addRun (TextRun run, int index)
Adds a TextRun at the specified index.
Parameters
run TextRun to be added
index Index, where TextRun should be placed
changeMatrixForTextRun()
void com.datalogics.PDFL.Text.changeMatrixForTextRun (Matrix newMatrix, int textRunIndex)
Changes the transformation matrix from user space to the current text space for the specified TextRun. Unlike ChangeTextMatrixForTextRun(), this function does not change fontSize, hScale, and textRise in the textState of PDEText. The H and V values of the matrix indicate the origin of the first character.
Parameters
newMatrix The new transformation matrix to use for the TextRun.
textRunIndex The index of a TextRun, relative to the Text object (the first TextRun in the Text object is at index 0).
changeTextMatrixForTextRun()
void com.datalogics.PDFL.Text.changeTextMatrixForTextRun (Matrix newMatrix, int textRunIndex)
Changes the transformation matrix from user space to the current text space for the specified TextRun. The H and V values of the matrix indicate the origin of the first character.
Parameters
newMatrix The new transformation matrix to use for the TextRun.
textRunIndex The index of a TextRun, relative to the Text object (the first TextRun in the Text object is at index 0).
clone() [1/2]
Text com.datalogics.PDFL.Text.clone ()
Makes a copy of the text.
Make a copy of an text to obtain a new text that has a distinct set of attributes.
Returns
The copied text.
Reimplemented from com.datalogics.PDFL.Element.
clone() [2/2]
Text com.datalogics.PDFL.Text.clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Makes a copy of the text.
Make a copy of an text to obtain a new text that has a distinct set of attributes.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied text.
Reimplemented from com.datalogics.PDFL.Element.
colorConvert()
Text com.datalogics.PDFL.Text.colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
Applies the specified ICC ColorProfile to the Text object
Parameters
document The document the element belongs to.
prof The ICC ColorProfile to be applied.
intent The ICC Rendering Intent for the ColorProfile
embed If true, embed the color space and make the object calibrated. If it is false and the target profile is CMYK, RGB, or Gray, the colors space of the resulting object, after conversion, will be DeviceCMYK, DeviceRGB, or DeviceGray, respectively.
Returns
A new Text object with the applied ICC ColorProfile.
delete() [1/2]
synchronized void com.datalogics.PDFL.Text.delete ()
Reimplemented from com.datalogics.PDFL.Element.
delete() [2/2]
synchronized void com.datalogics.PDFL.Text.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Element.
finalize()
void com.datalogics.PDFL.Text.finalize () protected
Reimplemented from com.datalogics.PDFL.Element.
findTextRunIndexForCharacter()
int com.datalogics.PDFL.Text.findTextRunIndexForCharacter (int characterIndex)
Finds the index of the TextRun that contains the nth character in a Text object.
Parameters
characterIndex The index of a character, relative to the Text object (the first character in the Text object is at index 0).
Returns
The index of the TextRun that contains the character specified by characterIndex.
getAdvanceForCharacter()
Point com.datalogics.PDFL.Text.getAdvanceForCharacter (int characterIndex)
Gets the advance width of a character, in user space. The advance width is the amount by which the current point advances when the character is drawn.
Advance width may be horizontal or vertical, depending on the writing style. Thus, the return value has both a horizontal and a vertical component.
Parameters
characterIndex The index of a character, relative to the Text object (the first character in the Text object is at index 0).
Returns
A value specifying both the horizontal and vertical components of the advance width of a character in user space.
getAdvanceForTextRun()
Point com.datalogics.PDFL.Text.getAdvanceForTextRun (int textRunIndex)
Gets the advance width of a TextRun, in user space. The advance width is the amount by which the current point advances when the TextRun is drawn.
Advance width may be horizontal or vertical, depending on the writing style. Thus, the return value has both a horizontal and a vertical component.
Parameters
textRunIndex The index of a TextRun, relative to the Text object (the first TextRun in the Text object is at index 0).
Returns
A value specifying both the horizontal and vertical components of the advance width of a TextRun in user space.
getBoundingBox()
Rect com.datalogics.PDFL.Element.getBoundingBox () inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
getBoundingBoxForCharacter()
Rect com.datalogics.PDFL.Text.getBoundingBoxForCharacter (int characterIndex)
The bounding box for a character in this text element.
Parameters
characterIndex The index of a character, relative to the Text object (the first character in the Text object is at index 0)
Returns
A Rect specifying the bounding box for the character.
getClip()
Clip com.datalogics.PDFL.Element.getClip () inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
getCPtr() [1/2]
static long com.datalogics.PDFL.Element.getCPtr (Element obj) static protected inherited
Referenced by com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Content.addElement(), and com.datalogics.PDFL.Content.Content().
getCPtr() [2/2]
static long com.datalogics.PDFL.Text.getCPtr (Text obj) static protected
getMatrix()
Matrix com.datalogics.PDFL.Element.getMatrix () inherited
The transformation matrix for the element.
getNumberOfCharacters()
int com.datalogics.PDFL.Text.getNumberOfCharacters ()
The number of characters in this text element.
getNumberOfRuns()
int com.datalogics.PDFL.Text.getNumberOfRuns ()
The number of text runs in this text element.
getRun()
TextRun com.datalogics.PDFL.Text.getRun (int index)
Obtains the TextRun at the specified index.
getTextMatrixForCharacter()
Matrix com.datalogics.PDFL.Text.getTextMatrixForCharacter (int characterIndex)
Gets the transformation matrix from user space to the current text space for the specified character. The H and V values of the matrix indicate the origin of the first character.
Parameters
characterIndex The index of a character, relative to the Text object (the first character in the Text object is at index 0).
Returns
The transformation matrix for the character specified by characterIndex.
getTextMatrixForTextRun()
Matrix com.datalogics.PDFL.Text.getTextMatrixForTextRun (int textRunIndex)
Gets the transformation matrix from user space to the current text space for the specified TextRun. The H and V values of the matrix indicate the origin of the first character.
Parameters
textRunIndex The index of a TextRun, relative to the Text object (the first TextRun in the Text object is at index 0).
Returns
The transformation matrix for the TextRun specified by TextRunIndex.
pointIntersectsCharacter()
boolean com.datalogics.PDFL.Text.pointIntersectsCharacter (Point p, int index)
Tests whether a point is on a specified character within this Text object.
Parameters
p The point to test, in user space coordinates.
index The index of the character. The first character in the Text has an index of 0.
Returns
true if the point is on the character, false if the point is not on the character.
pointIntersectsTextRun()
boolean com.datalogics.PDFL.Text.pointIntersectsTextRun (Point p, int index)
Tests whether a point is on a specified TextRun within this Text object.
Parameters
p The point to test, in user space coordinates.
index The index of the TextRun. The first TextRun in the Text has an index of 0.
Returns
true if the point is on the TextRun, false if the point is not on the TextRun.
rectIntersectsCharacter()
boolean com.datalogics.PDFL.Text.rectIntersectsCharacter (Rect r, int index)
Tests whether any part of a rectangle is on a specified character within this Text object.
Parameters
r The rect to test, in user space coordinates.
index The index of the character. The first character in the Text has an index of 0.
Returns
true if any part of the rectangle is on the character, false if no part of the rectangle is on the character.
rectIntersectsTextRun()
boolean com.datalogics.PDFL.Text.rectIntersectsTextRun (Rect r, int index)
Tests whether any part of a rectangle is on a specified TextRun within this Text object.
Parameters
r The rect to test, in user space coordinates.
index The index of the TextRun. The first TextRun in the Text has an index of 0.
Returns
true if any part of the rectangle is on the TextRun, false if no part of the rectangle is on the TextRun.
removeRuns()
void com.datalogics.PDFL.Text.removeRuns (int index, int count)
Removes a count of TextRuns, starting from index
Parameters
index Start position of range to delete
count Count of TextRuns to delete
rotate()
void com.datalogics.PDFL.Element.rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Reimplemented in com.datalogics.PDFL.Image.
scale()
void com.datalogics.PDFL.Element.scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
setClip()
void com.datalogics.PDFL.Element.setClip (Clip clip) inherited
Sets the current Clip for an Element.
Parameters
clip The clip to set as the current clip for this element.
setMatrix()
void com.datalogics.PDFL.Element.setMatrix (Matrix matrix) inherited
Set the transformation matrix for the element.
Parameters
matrix the transformation matrix for the element.
splitTextRunAtCharacter()
void com.datalogics.PDFL.Text.splitTextRunAtCharacter (int splitLocation)
Splits the TextRun containing the character at the specified location into two contiguous TextRuns. The character at the specified index will be part of the first TextRun.
Parameters
splitLocation The split location, relative to the Text object.
translate()
void com.datalogics.PDFL.Element.translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Reimplemented in com.datalogics.PDFL.Image.