Programming Reference: Main Page
com.datalogics.PDFL.DrawParams Class Reference
Public Member Functions
synchronized void delete ()
DrawParams ()
DrawParams (DrawParams rhs)
boolean getBypassCopyPerm ()
CancelProc getCancelProc ()
ColorSpace getColorSpace ()
Rect getDestRect ()
boolean getEnableBlackPointCompensation ()
boolean getEnableThinLineHeuristics ()
java.util.EnumSet< DrawFlags > getFlags ()
ColorProfile getICCProfile ()
String getICCProfileCustomPath ()
Matrix getMatrix ()
OptionalContentContext getOptionalContentContext ()
RenderProgressProc getProgressProc ()
RenderIntent getRenderIntent ()
java.util.EnumSet< SmoothFlags > getSmoothFlags ()
Rect getUpdateRect ()
void setBypassCopyPerm (boolean value)
void setCancelProc (CancelProc cancelProc)
void setColorSpace (ColorSpace colorSpace)
void setDestRect (Rect rect)
void setEnableBlackPointCompensation (boolean value)
void setEnableThinLineHeuristics (boolean value)
void setFlags (java.util.EnumSet< DrawFlags > value)
void setICCProfile (ColorProfile colorProfile)
void setICCProfileCustomPath (String colorProfilePath)
void setMatrix (Matrix matrix)
void setOptionalContentContext (OptionalContentContext context)
void setProgressProc (RenderProgressProc progressProc)
void setRenderIntent (RenderIntent value)
void setSmoothFlags (java.util.EnumSet< SmoothFlags > value)
void setUpdateRect (Rect rect)
Protected Member Functions
synchronized void delete (Boolean disposing)
DrawParams (long cPtr, boolean cMemoryOwn)
void finalize ()
Static Protected Member Functions
static long getCPtr (DrawParams obj)
Detailed Description
Settings for rendering PDF pages as images. This is used for rendering PDF pages to images, such as PNG or JPG files, to export to separate files or to send to a printer.
Constructor & Destructor Documentation
DrawParams() [1/3]
com.datalogics.PDFL.DrawParams.DrawParams (long cPtr, boolean cMemoryOwn) protected
DrawParams() [2/3]
com.datalogics.PDFL.DrawParams.DrawParams ()
DrawParams() [3/3]
com.datalogics.PDFL.DrawParams.DrawParams (DrawParams rhs)
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.DrawParams.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.DrawParams.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.DrawParams.finalize () protected
getBypassCopyPerm()
boolean com.datalogics.PDFL.DrawParams.getBypassCopyPerm ()
Bypass copy permissions. Only used when drawing to a bitmap.
getCancelProc()
CancelProc com.datalogics.PDFL.DrawParams.getCancelProc ()
Get the cancel callback.
getColorSpace()
ColorSpace com.datalogics.PDFL.DrawParams.getColorSpace ()
The color space in which the bitmap data is represented. It must be one of DeviceGray, DeviceRGB, DeviceRGBA, DeviceCMYK, Lab, or LabA. Only used when drawing to a bitmap.
getCPtr()
static long com.datalogics.PDFL.DrawParams.getCPtr (DrawParams obj) static protected
Referenced by com.datalogics.PDFL.Page.drawContents(), and com.datalogics.PDFL.DrawParams.DrawParams().
getDestRect()
Rect com.datalogics.PDFL.DrawParams.getDestRect ()
The rectangle of the bitmap. It is defined in device space coordinates. Only used when drawing to a bitmap.
Referenced by com.datalogics.PDFL.Page.drawContents().
getEnableBlackPointCompensation()
boolean com.datalogics.PDFL.DrawParams.getEnableBlackPointCompensation ()
Enable/disable black point compensation.
getEnableThinLineHeuristics()
boolean com.datalogics.PDFL.DrawParams.getEnableThinLineHeuristics ()
Enable/disable thin line adjustments when drawing rectangles
getFlags()
java.util.EnumSet<DrawFlags> com.datalogics.PDFL.DrawParams.getFlags ()
Drawing flags.
getICCProfile()
ColorProfile com.datalogics.PDFL.DrawParams.getICCProfile ()
Gets the ICC Profile of the colorspace to be used for rendering from a known value.
NOTE: The ICCProfileCustomPath must not be set for this property to be used. The profile must be compatible with the ColorSpace property value, which can't be set to ICCBased either.
getICCProfileCustomPath()
String com.datalogics.PDFL.DrawParams.getICCProfileCustomPath ()
Gets the ICC Profile of the colorspace to be used for rendering from a custom file path.
NOTE: The ICCProfile is ignored when this property is a non-empty string. The profile must be compatible with the ColorSpace property value, which can't be set to ICCBased either.
getMatrix()
Matrix com.datalogics.PDFL.DrawParams.getMatrix ()
A pointer to the matrix to concatenate onto the default page matrix. It is useful for converting from page to window coordinates and for scaling.
getOptionalContentContext()
OptionalContentContext com.datalogics.PDFL.DrawParams.getOptionalContentContext ()
The optional-content context to use for visibility state information, or NULL to use the document's current states in the default context.
getProgressProc()
RenderProgressProc com.datalogics.PDFL.DrawParams.getProgressProc ()
Get the progress callback.
getRenderIntent()
RenderIntent com.datalogics.PDFL.DrawParams.getRenderIntent ()
Default rendering intent is RelColorimetric (relative colorimetric). Only used when drawing to a bitmap.
getSmoothFlags()
java.util.EnumSet<SmoothFlags> com.datalogics.PDFL.DrawParams.getSmoothFlags ()
Smoothing flags. Only used when drawing to a bitmap.
getUpdateRect()
Rect com.datalogics.PDFL.DrawParams.getUpdateRect ()
A rectangle represented by the coordinates of its four sides, which specifies the area to draw.
setBypassCopyPerm()
void com.datalogics.PDFL.DrawParams.setBypassCopyPerm (boolean value)
Bypass copy permissions. Only used when drawing to a bitmap.
setCancelProc()
void com.datalogics.PDFL.DrawParams.setCancelProc (CancelProc cancelProc)
Set the cancel callback.
Parameters
cancelProc a CancelProc, which can return true to cancel the operation, may be null.
setColorSpace()
void com.datalogics.PDFL.DrawParams.setColorSpace (ColorSpace colorSpace)
The color space in which the bitmap data is represented. It must be one of DeviceGray, DeviceRGB, DeviceRGBA, DeviceCMYK, Lab, or LabA. Only used when drawing to a bitmap.
setDestRect()
void com.datalogics.PDFL.DrawParams.setDestRect (Rect rect)
The rectangle of the bitmap. It is defined in device space coordinates. Only used when drawing to a bitmap.
setEnableBlackPointCompensation()
void com.datalogics.PDFL.DrawParams.setEnableBlackPointCompensation (boolean value)
Enable/disable black point compensation.
setEnableThinLineHeuristics()
void com.datalogics.PDFL.DrawParams.setEnableThinLineHeuristics (boolean value)
Enable/disable thin line adjustments when drawing rectangles
setFlags()
void com.datalogics.PDFL.DrawParams.setFlags (java.util.EnumSet< DrawFlags > value)
Drawing flags.
setICCProfile()
void com.datalogics.PDFL.DrawParams.setICCProfile (ColorProfile colorProfile)
Sets the ICC Profile of the colorspace to be used for rendering to a known value.
NOTE: The ICCProfileCustomPath must not be set for this property to be used. The profile must be compatible with the ColorSpace property value, which can't be set to ICCBased either.
setICCProfileCustomPath()
void com.datalogics.PDFL.DrawParams.setICCProfileCustomPath (String colorProfilePath)
Sets the ICC Profile of the colorspace to be used for rendering from a custom file path.
NOTE: The ICCProfile is ignored when this property is a non-empty string. The profile must be compatible with the ColorSpace property value, which can't be set to ICCBased either.
setMatrix()
void com.datalogics.PDFL.DrawParams.setMatrix (Matrix matrix)
A pointer to the matrix to concatenate onto the default page matrix. It is useful for converting from page to window coordinates and for scaling.
setOptionalContentContext()
void com.datalogics.PDFL.DrawParams.setOptionalContentContext (OptionalContentContext context)
The optional-content context to use for visibility state information, or NULL to use the document's current states in the default context.
setProgressProc()
void com.datalogics.PDFL.DrawParams.setProgressProc (RenderProgressProc progressProc)
Set the progress callback.
Parameters
progressProc a RenderProgressProc, that can receive updates regarding rendering progress, may be null.
setRenderIntent()
void com.datalogics.PDFL.DrawParams.setRenderIntent (RenderIntent value)
Default rendering intent is RelColorimetric (relative colorimetric). Only used when drawing to a bitmap.
setSmoothFlags()
void com.datalogics.PDFL.DrawParams.setSmoothFlags (java.util.EnumSet< SmoothFlags > value)
Smoothing flags. Only used when drawing to a bitmap.
setUpdateRect()
void com.datalogics.PDFL.DrawParams.setUpdateRect (Rect rect)
A rectangle represented by the coordinates of its four sides, which specifies the area to draw.