Programming Reference: Main Page
com.datalogics.PDFL.OptionalContentGroup Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
java.util.List< String > getIntent ()
String getName ()
PDFDict getPDFDict ()
OptionalContentGroup (Document doc, String name)
void setIntent (java.util.List< String > intents)
void setName (String name)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
OptionalContentGroup (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (OptionalContentGroup obj)
Detailed Description
A dictionary used to manage graphics images in a PDF. An Optional Content Group is a dictionary that represents a set of graphics images that users can turn on or off in a PDF document, making them visible or invisible.
In Adobe Acrobat or Adobe Reader, Optional Content Groups are referred to as "layers."
Constructor & Destructor Documentation
OptionalContentGroup() [1/2]
com.datalogics.PDFL.OptionalContentGroup.OptionalContentGroup (long cPtr, boolean cMemoryOwn) protected
OptionalContentGroup() [2/2]
com.datalogics.PDFL.OptionalContentGroup.OptionalContentGroup (Document doc, String name)
Create a new OptionalContentGroup.
Parameters
doc The document that the new OptionalContentGroup will belong to.
name The name given to the new OptionalContentGroup.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.OptionalContentGroup.delete ()
Referenced by com.datalogics.PDFL.OptionalContentConfig.getOffArray(), com.datalogics.PDFL.OptionalContentConfig.getOnArray(), com.datalogics.PDFL.Document.getOptionalContentGroups(), and com.datalogics.PDFL.OptionalContentMembershipDict.getOptionalContentGroups().
delete() [2/2]
synchronized void com.datalogics.PDFL.OptionalContentGroup.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.OptionalContentGroup.equals (Object rhs)
finalize()
void com.datalogics.PDFL.OptionalContentGroup.finalize () protected
getCPtr()
static long com.datalogics.PDFL.OptionalContentGroup.getCPtr (OptionalContentGroup obj) static protected
Referenced by com.datalogics.PDFL.OptionalContentContext.getStateOfOCG(), com.datalogics.PDFL.OptionalContentOrderLeaf.OptionalContentOrderLeaf(), com.datalogics.PDFL.Document.removeOCG(), and com.datalogics.PDFL.OptionalContentContext.setStateOfOCG().
getIntent()
java.util.List<String> com.datalogics.PDFL.OptionalContentGroup.getIntent ()
Gets the intent list for an optional-content group. An intent is a string value broadly describing the intended use, either View or Design.
A group's content is considered to be optional (that is, the group's state is considered in its visibility) if any intent in its list matches an intent of the context. The intent list of the context is usually set from the intent list of the document configuration.
Returns
An array containing intent strings.
getName()
String com.datalogics.PDFL.OptionalContentGroup.getName ()
Get the name of the optional content group
Returns
the name
getPDFDict()
PDFDict com.datalogics.PDFL.OptionalContentGroup.getPDFDict ()
Retrieve the PDFObject representation of this object
setIntent()
void com.datalogics.PDFL.OptionalContentGroup.setIntent (java.util.List< String > intents)
Sets the intent list for an optional-content group. An intent is a string value broadly describing the intended use, either View or Design.
A group's content is considered to be optional (that is, the group's state is considered in its visibility) if any intent in its list matches an intent of the context. The intent list of the context is usually set from the intent list of the document configuration.
setName()
void com.datalogics.PDFL.OptionalContentGroup.setName (String name)
Set the name of the optional content group
toString()
String com.datalogics.PDFL.OptionalContentGroup.toString ()