Programming Reference: Main Page
com.datalogics.PDFL.Quad Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
Point getBottomLeft ()
Point getBottomRight ()
Point getTopLeft ()
Point getTopRight ()
Quad ()
Quad (Point nTopLeft, Point nTopRight, Point nBottomLeft, Point nBottomRight)
Rect toRect ()
String toString ()
Quad transform (Matrix arg0)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Quad (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Quad obj)
Detailed Description
Represents a quadrilateral in a program. A quadrilateral is a polygon graphic that has four sides or edges and four corners, Bottom Left, Bottom Right, Top Left, and Top Right.
Constructor & Destructor Documentation
Quad() [1/3]
com.datalogics.PDFL.Quad.Quad (long cPtr, boolean cMemoryOwn) protected
Quad() [2/3]
com.datalogics.PDFL.Quad.Quad ()
Creates a Quad with all points at the origin.
Quad() [3/3]
com.datalogics.PDFL.Quad.Quad (Point nTopLeft, Point nTopRight, Point nBottomLeft, Point nBottomRight)
Creates a Quad from a set of 4 points.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.Quad.delete ()
Referenced by com.datalogics.PDFL.Word.getCharQuads(), com.datalogics.PDFL.DocTextFinderQuadInfo.getQuads(), com.datalogics.PDFL.Redaction.getQuads(), com.datalogics.PDFL.TextMarkupAnnotation.getQuads(), and com.datalogics.PDFL.Word.getQuads().
delete() [2/2]
synchronized void com.datalogics.PDFL.Quad.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.Quad.equals (Object rhs)
finalize()
void com.datalogics.PDFL.Quad.finalize () protected
getBottomLeft()
Point com.datalogics.PDFL.Quad.getBottomLeft ()
Bottom left corner of the Quad.
getBottomRight()
Point com.datalogics.PDFL.Quad.getBottomRight ()
Bottom right corner of the Quad.
getCPtr()
static long com.datalogics.PDFL.Quad.getCPtr (Quad obj) static protected
getTopLeft()
Point com.datalogics.PDFL.Quad.getTopLeft ()
Top left corner of the Quad.
getTopRight()
Point com.datalogics.PDFL.Quad.getTopRight ()
Top right corner of the Quad.
toRect()
Rect com.datalogics.PDFL.Quad.toRect ()
Returns a rectangle describing the same area as the quad.
toString()
String com.datalogics.PDFL.Quad.toString ()
Returns a string representation of the quad by calling each point's ToString function.
transform()
Quad com.datalogics.PDFL.Quad.transform (Matrix arg0)
Create a new quad from the results of a Transform on each point of the Quad.