Programming Reference: Main Page
com.datalogics.PDFL.SmoothFlags Enum Reference
Static Public Member Functions
static int FlagsToInt (java.lang.Iterable< SmoothFlags > flags)
static java.util.EnumSet< SmoothFlags > IntToFlags (int value)
Public Attributes
IMAGE
IMAGE_ANTI_ALIAS_ONLY
IMAGE_BICUBIC_RESAMPLE
IMAGE_BICUBIC_RESAMPLE_AND_ANTI_ALIAS
IMAGE_LINEAR_RESAMPLE
LINE_ART
NONE
TEXT
TEXT_ANTI_ALIAS_ENABLE_DDR
TEXT_ANTI_ALIAS_ENABLE_PREVIEW
Member Function Documentation
FlagsToInt()
static int com.datalogics.PDFL.SmoothFlags.FlagsToInt (java.lang.Iterable< SmoothFlags > flags) static
Referenced by com.datalogics.PDFL.Page.drawContents(), com.datalogics.PDFL.PageImageParams.PageImageParams(), com.datalogics.PDFL.DrawParams.setSmoothFlags(), and com.datalogics.PDFL.PageImageParams.setSmoothing().
IntToFlags()
static java.util.EnumSet<SmoothFlags> com.datalogics.PDFL.SmoothFlags.IntToFlags (int value) static
Referenced by com.datalogics.PDFL.DrawParams.getSmoothFlags(), and com.datalogics.PDFL.PageImageParams.getSmoothing().
Member Data Documentation
IMAGE
com.datalogics.PDFL.SmoothFlags.IMAGE
Draw smooth image. This will cause raster images to be resampled to match the target imaging resolution using an averaged subsampling algorithm, and will cause images to be antialiased when drawn. Recommended for general PDF viewing applications.
IMAGE_ANTI_ALIAS_ONLY
com.datalogics.PDFL.SmoothFlags.IMAGE_ANTI_ALIAS_ONLY
Antialias (smooth) images at low resolutions, but do not resample images when they do not match the target imaging resolution.
This is not recommended for most callers.
IMAGE_BICUBIC_RESAMPLE
com.datalogics.PDFL.SmoothFlags.IMAGE_BICUBIC_RESAMPLE
Resample images using bicubic resampling, but do not antialias images. This will cause raster images to be resampled to match the target imaging resolution using a bicubic subsampling algorithm. Recommended for conversion of PDF pages to high-resolution (>= 300dpi) images. Rendering with this option takes longer than with the ImageLinearResample smoothing option, but generates higher quality output.
IMAGE_BICUBIC_RESAMPLE_AND_ANTI_ALIAS
com.datalogics.PDFL.SmoothFlags.IMAGE_BICUBIC_RESAMPLE_AND_ANTI_ALIAS
Enhanced image smoothing controls: Draw smooth image and resample using bicubic resampling. This will cause raster images to be resampled to match the target imaging resolution using a bicubic subsampling algorithm, and will cause images to be antialiased when drawn. Recommended for general imaging applications. Rendering with this option takes longer than with the Image smoothing option, but generates higher quality output.
IMAGE_LINEAR_RESAMPLE
com.datalogics.PDFL.SmoothFlags.IMAGE_LINEAR_RESAMPLE
Resample images using linear average subsampling, but do not antialias images. This will cause raster images to be resampled to match the target imaging resolution using a linear average subsampling algorithm. Recommended for conversion of PDF pages to high-resolution (>= 300dpi) images. Rendering with this option is faster than with the ImageBicubicResample smoothing option, but generates lower quality output.
LINE_ART
com.datalogics.PDFL.SmoothFlags.LINE_ART
Draw smooth line art. This will cause paths (vector line art elements) to be antialiased. Recommended for lower-resolution applications such as on-screen viewing at low zoom levels.
NONE
com.datalogics.PDFL.SmoothFlags.NONE
Do not smooth any drawn elements
TEXT
com.datalogics.PDFL.SmoothFlags.TEXT
Draw smooth text. This will cause text to be antialiased when drawn. Recommended for lower-resolution applications such as on-screen viewing at low zoom levels. Equivalent to the Smooth Text: for Monitor option in Acrobat/Reader rendering preferences.
TEXT_ANTI_ALIAS_ENABLE_DDR
com.datalogics.PDFL.SmoothFlags.TEXT_ANTI_ALIAS_ENABLE_DDR
Enhanced text antialiasing controls: Antialias (smooth) text using the DDR sub-pixel antialiasing algorithm. Equivalent to the Smooth Text: for Laptop/LCD Screen option in Acrobat/Reader rendering preferences. Recommended for zoom factors of 150% or more.
TEXT_ANTI_ALIAS_ENABLE_PREVIEW
com.datalogics.PDFL.SmoothFlags.TEXT_ANTI_ALIAS_ENABLE_PREVIEW
Enable special text "preview" rendering and antialiasing for better visual results when generating images at lower resolutions intended for on-screen viewing. This prevents text from looking badly kerned or looking to have poor inter-character spacing.
We recommend this for use for viewing applications at zoom levels of 150% or less, though you will want to experiment and decide for yourself.
Do not use this for non-viewing applications. Do not scale up or down the rendered image that is generated from drawing a page using this flag - it will look very blurry and unfocused.