Adobe PDF Library Java Documentation
com.datalogics.PDFL.Content Class Reference
Public Member Functions
void addElement (Element NewElem)
void addElement (Element NewElem, int addAfterIndex)
void addPage (int insertAfterIndex, Document containerDoc, Page srcPage, Matrix dstMatrix, java.util.List< String > annotTypes, java.util.EnumSet< AddPageFlags > flags, Rect bbox)
Content ()
Content (Element firstElem)
synchronized void delete ()
boolean flattenOptionalContent (OptionalContentContext occ)
Rect getBoundingBox ()
ColorSpace getDefaultColorSpace (String name)
Element getElement (int index)
int getNumElements ()
void removeElement (int index)
void setDefaultColorSpace (String name, ColorSpace colorSpace)
String toString ()
Static Public Attributes
static final int BEFORE_FIRST
Protected Member Functions
Content (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (Content obj)
Detailed Description
Class that represents the collection of elements on a PDF page. A content object represents a collection of elements that make up a page in a PDF file. A content object is more convenient to use than directly parsing or working with a page content stream. This is because a page can include a large collection of individual stream objects. Working with a content object, you can avoid focusing on this level of detail. The content converts individual stream items to a structured form, making it unnecessary to parse the individual syntax for each one. A content object can be associated with a large amount of unmanaged memory in APDFL and should be deleted when the object is no longer in use.
The index associated with Content is 0-based, so 0 is the first element.
Constructor & Destructor Documentation
Content() [1/3]
com.datalogics.PDFL.Content.Content (long cPtr, boolean cMemoryOwn) protected
Content() [2/3]
com.datalogics.PDFL.Content.Content ()
Create content
Content() [3/3]
com.datalogics.PDFL.Content.Content (Element firstElem)
Create content with a first Element.
Parameters
firstElem The Element which is to be added to the beginning of the new Content object.
Member Function Documentation
addElement() [1/2]
void com.datalogics.PDFL.Content.addElement (Element NewElem)
Adds an existing Element at the end of the content object.
Parameters
NewElem The Element which is to be added to the end of the existing Content object.
addElement() [2/2]
void com.datalogics.PDFL.Content.addElement (Element NewElem, int addAfterIndex)
Adds an existing Element at the given index of the content object.
Parameters
NewElem The Element which is to be added to the end of the existing Content object.
addAfterIndex The position after which to insert the new Element, the index is 0-based so 0 is the first element. To insert a new element as the first element use the Content.BeforeFirst constant.
addPage()
void com.datalogics.PDFL.Content.addPage (int insertAfterIndex, Document containerDoc, Page srcPage, Matrix dstMatrix, java.util.List< String > annotTypes, java.util.EnumSet< AddPageFlags > flags, Rect bbox)
Adds the specfied Page to the Content as a Form. It adds a reference to the Xobject form at the indicated index in the Content; the index may be less than 0, which indicates the object is to be appended to the content.
Parameters
insertAfterIndex The index indicates the location after which the specified element is to be added. The index should be BeforeFirst to add to the beginning of the display list.
containerDoc The Document in which the page is contained.
srcPage The page that will be inserted at insertAfterIndex in theContent.
dstMatrix (May be NULL) The matrix applied to the default matrix of the Page that is inserted into the Document.
annotTypes If the page contains annotations, the annotTypes list is used to determine which annotation types are pumped into the page contents of the CosDoc.
flags (May be 0) AllAnnotations specifies all annotation types. If this is not set, then the annotTypes list will be consulted.
bbox (May be NULL) specifies the destination BBox for the page being inserted. If it is NULL, the new page's media box is used.
delete() [1/2]
synchronized void com.datalogics.PDFL.Content.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.Content.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.Content.finalize () protected
flattenOptionalContent()
boolean com.datalogics.PDFL.Content.flattenOptionalContent (OptionalContentContext occ)
Flattens optional content within this Content object.
Removes elements that are not visible in the given optional content context and removes optional content information from any visible elements.
The optional content information formerly associated with this Content object will NOT be deleted from the document, as it is possible that content elsewhere in the document may be using the information.
Parameters
occ The optional content context in which content is checked for visibility.
Returns
true if the content was successfully flattened, false otherwise.
getBoundingBox()
Rect com.datalogics.PDFL.Content.getBoundingBox ()
The bounding box for this content.
The bounding box is a rectangle that is at least large enough to contain the bounding boxes for all the elements in the Content.
getCPtr()
static long com.datalogics.PDFL.Content.getCPtr (Content obj) static protected
Referenced by com.datalogics.PDFL.Form.Form(), com.datalogics.PDFL.Group.Group(), com.datalogics.PDFL.Container.isCurrentlyVisible(), com.datalogics.PDFL.Form.isCurrentlyVisible(), com.datalogics.PDFL.Container.makeVisible(), com.datalogics.PDFL.Form.makeVisible(), com.datalogics.PDFL.Container.setContent(), com.datalogics.PDFL.Form.setContent(), and com.datalogics.PDFL.Group.setContent().
getDefaultColorSpace()
ColorSpace com.datalogics.PDFL.Content.getDefaultColorSpace (String name)
Get a default color space from a Content object.
Parameters
name The name of the color space to get. It must be one of DefaultRGB, DefaultCMYK, or DefaultGray.
Returns
The color space used as the default. May return null if no default is set.
getElement()
Element com.datalogics.PDFL.Content.getElement (int index)
Get the element specified by index.
getNumElements()
int com.datalogics.PDFL.Content.getNumElements ()
The number of elements in the Content object.
removeElement()
void com.datalogics.PDFL.Content.removeElement (int index)
Removes the Element at the specified index.
Parameters
index The position at which to remove the Element
setDefaultColorSpace()
void com.datalogics.PDFL.Content.setDefaultColorSpace (String name, ColorSpace colorSpace)
Set a default color space from a Content object.
Parameters
name The name of the color space to set. It must be one of DefaultRGB, DefaultCMYK, or DefaultGray.
colorSpace The color space to set. It may not be a Lab, Indexed or Pattern color space.
toString()
String com.datalogics.PDFL.Content.toString ()
Member Data Documentation
BEFORE_FIRST
final int com.datalogics.PDFL.Content.BEFORE_FIRST static
Position for inserting an element before the first element.