Adobe PDF Library Java Documentation
com.datalogics.PDFL.Path Class Reference
Public Member Functions
void addCurve (Point Point1, Point Point2, Point Point3)
void addCurveV (Point Point1, Point Point2)
void addCurveY (Point Point1, Point Point2)
void addLine (Point Point)
void addRect (Point Point, double Width, double Height)
Path clone ()
Path clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
void closePath ()
Path colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
synchronized void delete ()
Rect getBoundingBox ()
Clip getClip ()
GraphicState getGraphicState ()
Matrix getMatrix ()
java.util.EnumSet< PathPaintOpFlags > getPaintOp ()
java.util.List< Segment > getSegments ()
void moveTo (Point Point)
Path ()
Path (GraphicState graphicState)
void rotate (double theta)
void scale (double sx, double sy)
void setClip (Clip clip)
void setGraphicState (GraphicState gstate)
void setMatrix (Matrix matrix)
void setPaintOp (java.util.EnumSet< PathPaintOpFlags > paintops)
void setSegments (java.util.List< Segment > segments)
void translate (double tx, double ty)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Path (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Element obj)
static long getCPtr (Path obj)
Detailed Description
A path in a PDF file defines shapes. Paths in PDF files are used to draw lines, define filled areas, and define boundaries for clipping graphics. A path is composed of straight and curved line segments.
Constructor & Destructor Documentation
Path() [1/3]
com.datalogics.PDFL.Path.Path (long cPtr, boolean cMemoryOwn) protected
Path() [2/3]
com.datalogics.PDFL.Path.Path ()
Create a path.
Path() [3/3]
com.datalogics.PDFL.Path.Path (GraphicState graphicState)
Create a path with a given graphic state.
Parameters
graphicState the initial graphic state for the path
Member Function Documentation
addCurve()
void com.datalogics.PDFL.Path.addCurve (Point Point1, Point Point2, Point Point3)
Adds a Bezier curve from the current path using the first two points specified as Bezier control points ending at the third point. The new current point is then set to the third point.
Parameters
Point1 first Bezier control point
Point2 second Bezier control point
Point3 the ending Point of the Bezier curve which will also be the current point of the current path.
addCurveV()
void com.datalogics.PDFL.Path.addCurveV (Point Point1, Point Point2)
Adds a Bezier curve from the current path. This extends from the current path to the point Point2 using the current point and the first point specified as Bezier control points ending at the second point. The new current point is then set to the second point.
Parameters
Point1 first Bezier control point
Point2 the ending Point of the Bezier curve which will also be the new current point of the path.
addCurveY()
void com.datalogics.PDFL.Path.addCurveY (Point Point1, Point Point2)
Adds a Bezier curve from the current path. This extends from the current path to the point Point2 using the two points specified as Bezier control points ending at the second point. The new current point is then set to the second point.
Parameters
Point1 first Bezier control point
Point2 second Bezier control point and the ending Point of the Bezier curve which will also be the new current point of the path.
addLine()
void com.datalogics.PDFL.Path.addLine (Point Point)
Adds a line to the current path from the current path position. The given point becomes the new current position.
Parameters
Point the coordinates of the endpoint of the new line.
addRect()
void com.datalogics.PDFL.Path.addRect (Point Point, double Width, double Height)
Adds a rectangle to the current path with the lower left corner at the give point, and with the width and height specified.
Parameters
Point the coordinates of the lower left corner of the new rectangle.
Width the width of the new rectangle.
Height the height of the new rectangle.
clone() [1/2]
Path com.datalogics.PDFL.Path.clone ()
Makes a copy of the path.
Make a copy of an path to obtain a new path that has a distinct set of attributes.
Returns
The copied path.
Reimplemented from com.datalogics.PDFL.Element.
clone() [2/2]
Path com.datalogics.PDFL.Path.clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Makes a copy of the path.
Make a copy of an path to obtain a new path that has a distinct set of attributes.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied path.
Reimplemented from com.datalogics.PDFL.Element.
closePath()
void com.datalogics.PDFL.Path.closePath ()
Closes the current subpath.
colorConvert()
Path com.datalogics.PDFL.Path.colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
Applies the specified ICC ColorProfile to the Path
Parameters
document The document the element belongs to.
prof The ICC ColorProfile to be applied.
intent The ICC Rendering Intent for the ColorProfile
embed If true, embed the color space and make the object calibrated. If it is false and the target profile is CMYK, RGB, or Gray, the colors space of the resulting object, after conversion, will be DeviceCMYK, DeviceRGB, or DeviceGray, respectively.
Returns
A new Path with the applied ICC ColorProfile.
delete() [1/2]
synchronized void com.datalogics.PDFL.Path.delete ()
Reimplemented from com.datalogics.PDFL.Element.
delete() [2/2]
synchronized void com.datalogics.PDFL.Path.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Element.
finalize()
void com.datalogics.PDFL.Path.finalize () protected
Reimplemented from com.datalogics.PDFL.Element.
getBoundingBox()
Rect com.datalogics.PDFL.Element.getBoundingBox () inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
getClip()
Clip com.datalogics.PDFL.Element.getClip () inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
getCPtr() [1/2]
static long com.datalogics.PDFL.Element.getCPtr (Element obj) static protected inherited
Referenced by com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Content.addElement(), and com.datalogics.PDFL.Content.Content().
getCPtr() [2/2]
static long com.datalogics.PDFL.Path.getCPtr (Path obj) static protected
getGraphicState()
GraphicState com.datalogics.PDFL.Path.getGraphicState ()
Get the graphic state of the current path.
May return null if this element does not have a GraphicState.
getMatrix()
Matrix com.datalogics.PDFL.Element.getMatrix () inherited
The transformation matrix for the element.
getPaintOp()
java.util.EnumSet<PathPaintOpFlags> com.datalogics.PDFL.Path.getPaintOp ()
Gets the fill and stroke attributes of a path.
Returns
the PathPaintOpFlags flags describing the fill and stroke attributes.
getSegments()
java.util.List<Segment> com.datalogics.PDFL.Path.getSegments ()
Get the segments of the path.
Returns a list of Segment objects, one for each segment in the path.
moveTo()
void com.datalogics.PDFL.Path.moveTo (Point Point)
Moves the current point of the path to the given point.
Parameters
Point the coordinates of the new current point.
rotate()
void com.datalogics.PDFL.Element.rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Reimplemented in com.datalogics.PDFL.Image.
scale()
void com.datalogics.PDFL.Element.scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
setClip()
void com.datalogics.PDFL.Element.setClip (Clip clip) inherited
Sets the current Clip for an Element.
Parameters
clip The clip to set as the current clip for this element.
setGraphicState()
void com.datalogics.PDFL.Path.setGraphicState (GraphicState gstate)
Set the Graphic State of the current path.
Parameters
gstate the new/updated Graphic State for the path.
setMatrix()
void com.datalogics.PDFL.Element.setMatrix (Matrix matrix) inherited
Set the transformation matrix for the element.
Parameters
matrix the transformation matrix for the element.
setPaintOp()
void com.datalogics.PDFL.Path.setPaintOp (java.util.EnumSet< PathPaintOpFlags > paintops)
Sets the fill and stroke attributes of a path.
Parameters
paintops the flags describing the fill and stroke attributes.
setSegments()
void com.datalogics.PDFL.Path.setSegments (java.util.List< Segment > segments)
Set the segments of the path.
Parameters
segments The segments in the path. This list must have at least one element.
translate()
void com.datalogics.PDFL.Element.translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Reimplemented in com.datalogics.PDFL.Image.