Adobe PDF Library Java Documentation
com.datalogics.PDFL.DeviceNColorSpace Class Reference
Public Member Functions
synchronized void delete ()
DeviceNColorSpace (java.util.List< String > names, ColorSpace alternate, Function tintTransform)
boolean equals (Object rhs)
ColorSpace getAlternate ()
PDFDict getAttributes ()
Function getFunction ()
String getName ()
java.util.List< String > getNames ()
int getNumComponents ()
PDFObject getPDFObject ()
String toString ()
Static Public Attributes
static final ColorSpace DEVICE_CMYK
static final ColorSpace DEVICE_GRAY
static final ColorSpace DEVICE_RGB
static final ColorSpace DEVICE_RGBA
static final ColorSpace LAB
static final ColorSpace LAB_A
Protected Member Functions
synchronized void delete (Boolean disposing)
DeviceNColorSpace (long cPtr, boolean cMemoryOwn)
void finalize ()
Static Protected Member Functions
static long getCPtr (ColorSpace obj)
static long getCPtr (DeviceNColorSpace obj)
Detailed Description
Represents a color space with an arbitrary number of color components. DeviceN color spaces were designed to represent color spaces containing multiple color components that correspond to the colorants of some target device. They provide greater flexibility than is possible with standard device color spaces such as DeviceCMYK or with individual Separation color spaces. For example, it is possible to create a DeviceN color space consisting of only the cyan, magenta, and yellow color components, with the black component excluded.
Constructor & Destructor Documentation
DeviceNColorSpace() [1/2]
com.datalogics.PDFL.DeviceNColorSpace.DeviceNColorSpace (long cPtr, boolean cMemoryOwn) protected
DeviceNColorSpace() [2/2]
com.datalogics.PDFL.DeviceNColorSpace.DeviceNColorSpace (java.util.List< String > names, ColorSpace alternate, Function tintTransform)
Create a DeviceN color space.
Parameters
names the names of the colorants that the DeviceN space is intended to represent, among which may be All, or None
alternate the alternate color space, which can be any device or CIE-based color space but not another special color space (Pattern, Indexed, Separation, or DeviceN).
tintTransform function, called with the tint value and returning the corresponding color component values. That is, the number of components and the interpretation of their values depend on the alternate color space.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.DeviceNColorSpace.delete ()
Reimplemented from com.datalogics.PDFL.ColorSpace.
delete() [2/2]
synchronized void com.datalogics.PDFL.DeviceNColorSpace.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.ColorSpace.
equals()
boolean com.datalogics.PDFL.ColorSpace.equals (Object rhs) inherited
Reimplemented in com.datalogics.PDFL.NamedColorSpace.
finalize()
void com.datalogics.PDFL.DeviceNColorSpace.finalize () protected
Reimplemented from com.datalogics.PDFL.ColorSpace.
getAlternate()
ColorSpace com.datalogics.PDFL.DeviceNColorSpace.getAlternate ()
the alternate color space, which can be any device or CIE-based color space but not another special color space (Pattern, Indexed, Separation, or DeviceN).
getAttributes()
PDFDict com.datalogics.PDFL.DeviceNColorSpace.getAttributes ()
The dictionary of extended attributes associated with the color space.
getCPtr() [1/2]
static long com.datalogics.PDFL.ColorSpace.getCPtr (ColorSpace obj) static protected inherited
Referenced by com.datalogics.PDFL.Image.Image(), com.datalogics.PDFL.PageImageParams.PageImageParams(), com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), com.datalogics.PDFL.ICCBasedColorSpace.setAlternate(), com.datalogics.PDFL.DrawParams.setColorSpace(), com.datalogics.PDFL.ShadingPattern.setColorSpace(), com.datalogics.PDFL.Content.setDefaultColorSpace(), and com.datalogics.PDFL.PageImageParams.setImageColorSpace().
getCPtr() [2/2]
static long com.datalogics.PDFL.DeviceNColorSpace.getCPtr (DeviceNColorSpace obj) static protected
getFunction()
Function com.datalogics.PDFL.DeviceNColorSpace.getFunction ()
A function, called with the tint value and returning the corresponding color component values. That is, the number of components and the interpretation of their values depend on the alternate color space.
getName()
String com.datalogics.PDFL.ColorSpace.getName () inherited
The name of the color space. A named color space may be named something like DeviceRGB. More complicated color spaces may have a name like Indexed or ICCBased.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getNames()
java.util.List<String> com.datalogics.PDFL.DeviceNColorSpace.getNames ()
the names of the colorant that the DeviceN space is intended to represent, some of which may be All or None.
getNumComponents()
int com.datalogics.PDFL.ColorSpace.getNumComponents () inherited
The number of components in the color space.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getPDFObject()
PDFObject com.datalogics.PDFL.ColorSpace.getPDFObject () inherited
Get the PDFObject associated with the color space. This may be a PDFName, PDFDict, PDFStream, or PDFArray.
Returns
The PDFObject associated with the color space.
toString()
String com.datalogics.PDFL.ColorSpace.toString () inherited
Convert a colorSpace to a string.
Member Data Documentation
DEVICE_CMYK
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_CMYK static inherited
DEVICE_GRAY
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_GRAY static inherited
DEVICE_RGB
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGB static inherited
DEVICE_RGBA
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGBA static inherited
LAB
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB static inherited
LAB_A
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB_A static inherited