Adobe PDF Library Java Documentation
com.datalogics.PDFL.OptionalContentContext Class Reference
Public Member Functions
OptionalContentContext clone ()
synchronized void delete ()
boolean equals (Object rhs)
OptionalContentDrawingPolicy getDrawOptionalContent ()
java.util.List< Boolean > getOCGStates (java.util.List< OptionalContentGroup > ocgs)
boolean getStateOfOCG (OptionalContentGroup ocg)
OptionalContentContext (Document document)
void setDrawOptionalContent (OptionalContentDrawingPolicy newPolicy)
void setOCGStates (java.util.List< OptionalContentGroup > ocgs, java.util.List< Boolean > newStates)
void setStateOfOCG (OptionalContentGroup ocg, boolean newValue)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
OptionalContentContext (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (OptionalContentContext obj)
Detailed Description
Defines the context for optional content in a PDF. An Optional Content Context is a status object that defines the context for optional content within a document.
The context tracks the On/Off status for Optional Content Groups (layers) within a document. It contains flags that control whether to display content that is marked as optional.
Constructor & Destructor Documentation
OptionalContentContext() [1/2]
com.datalogics.PDFL.OptionalContentContext.OptionalContentContext (long cPtr, boolean cMemoryOwn) protected
OptionalContentContext() [2/2]
com.datalogics.PDFL.OptionalContentContext.OptionalContentContext (Document document)
Creates a context object that represents an optional-content state of the document, using the current state as the initial state for each group (OCG), as determined by the document's optional-content configuration.
Parameters
document The document for which to create a context.
Member Function Documentation
clone()
OptionalContentContext com.datalogics.PDFL.OptionalContentContext.clone ()
Makes a copy of the optional content context.
Returns
A copy of the original optional content context.
delete() [1/2]
synchronized void com.datalogics.PDFL.OptionalContentContext.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.OptionalContentContext.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.OptionalContentContext.equals (Object rhs)
finalize()
void com.datalogics.PDFL.OptionalContentContext.finalize () protected
getCPtr()
static long com.datalogics.PDFL.OptionalContentContext.getCPtr (OptionalContentContext obj) static protected
Referenced by com.datalogics.PDFL.Content.flattenOptionalContent(), com.datalogics.PDFL.Document.flattenOptionalContent(), com.datalogics.PDFL.Page.flattenOptionalContent(), com.datalogics.PDFL.Annotation.isCurrentlyVisible(), com.datalogics.PDFL.Container.isCurrentlyVisible(), com.datalogics.PDFL.Form.isCurrentlyVisible(), com.datalogics.PDFL.Container.makeVisible(), com.datalogics.PDFL.Form.makeVisible(), com.datalogics.PDFL.SeparationParams.setOCContext(), com.datalogics.PDFL.DrawParams.setOptionalContentContext(), and com.datalogics.PDFL.PrintParams.setOptionalContentContext().
getDrawOptionalContent()
OptionalContentDrawingPolicy com.datalogics.PDFL.OptionalContentContext.getDrawOptionalContent ()
Gets the drawing policy for the optional content in this optional content context.
Returns
The drawing policy for optional content in this optional content context.
getOCGStates()
java.util.List<Boolean> com.datalogics.PDFL.OptionalContentContext.getOCGStates (java.util.List< OptionalContentGroup > ocgs)
Gets the ON-OFF states for the given optional-content groups (OCGs) in the given optional-content context.
Parameters
ocgs A list of optional-content groups whose states are obtained.
Returns
An array of OCG states corresponding to the array of OCGs, true for ON and false for OFF.
getStateOfOCG()
boolean com.datalogics.PDFL.OptionalContentContext.getStateOfOCG (OptionalContentGroup ocg)
Gets the ON-OFF state for the given optional content group (OCG) in this optional content context.
Parameters
ocg The optional content group whose state will be retrieved.
setDrawOptionalContent()
void com.datalogics.PDFL.OptionalContentContext.setDrawOptionalContent (OptionalContentDrawingPolicy newPolicy)
Sets the drawing policy for the optional content in this optional content context.
Parameters
newPolicy The new drawing policy for optional content in this optional content context.
setOCGStates()
void com.datalogics.PDFL.OptionalContentContext.setOCGStates (java.util.List< OptionalContentGroup > ocgs, java.util.List< Boolean > newStates)
Sets the ON-OFF states for the given optional-content groups (OCGs) in the given optional-content context. The newStates vector must be large enough to hold as many Boolean values as there are OCGs.
Parameters
ocgs A list of optional-content groups.
newStates A list of new OCG states corresponding to the list of OCGs, true for ON and false for OFF. The list must contain as many states as there are non-NULL OCGs in the pdocgs list.
setStateOfOCG()
void com.datalogics.PDFL.OptionalContentContext.setStateOfOCG (OptionalContentGroup ocg, boolean newValue)
Sets the ON-OFF state for the given optional content group (OCG) in this optional content context.
Parameters
ocg The optional content group whose state will be set.
newValue The new ON-OFF state for the optional content group.
toString()
String com.datalogics.PDFL.OptionalContentContext.toString ()