Adobe PDF Library Java Documentation
com.datalogics.PDFL.NamedFunction Class Reference
Public Member Functions
java.util.List< Double > apply (java.util.List< Double > args)
synchronized void delete ()
boolean equals (Object rhs)
java.util.List< Double > getDomain ()
String getName ()
int getNInputs ()
int getNOutputs ()
java.util.List< Double > getRange ()
void setDomain (java.util.List< Double > domain)
void setRange (java.util.List< Double > range)
String toString ()
Static Public Attributes
static final Function DEFAULT
static final Function IDENTITY
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
NamedFunction (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Function obj)
static long getCPtr (NamedFunction obj)
Detailed Description
Defines a function currently in use. A Function is a process; it takes input values and manipulates them to create output values.
Constructor & Destructor Documentation
NamedFunction()
com.datalogics.PDFL.NamedFunction.NamedFunction (long cPtr, boolean cMemoryOwn) protected
Member Function Documentation
apply()
java.util.List<Double> com.datalogics.PDFL.NamedFunction.apply (java.util.List< Double > args)
Apply the function to supplied input values.
For Identity functions, this returns the same inputs. Not defined for any other kinds of named functions.
Parameters
args input values for the function. The number of input values must agree with the number of inputs the function takes.
Returns
a list of the result values from the function
Reimplemented from com.datalogics.PDFL.Function.
delete() [1/2]
synchronized void com.datalogics.PDFL.NamedFunction.delete ()
Reimplemented from com.datalogics.PDFL.Function.
delete() [2/2]
synchronized void com.datalogics.PDFL.Function.delete (Boolean disposing) protected inherited
Reimplemented in com.datalogics.PDFL.PostScriptCalculatorFunction, and com.datalogics.PDFL.ExponentialFunction.
equals()
boolean com.datalogics.PDFL.NamedFunction.equals (Object rhs)
finalize()
void com.datalogics.PDFL.NamedFunction.finalize () protected
Reimplemented from com.datalogics.PDFL.Function.
getCPtr() [1/2]
static long com.datalogics.PDFL.Function.getCPtr (Function obj) static protected inherited
Referenced by com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), com.datalogics.PDFL.ExtendedGraphicState.setBlackGeneration(), and com.datalogics.PDFL.ExtendedGraphicState.setUndercolorRemoval().
getCPtr() [2/2]
static long com.datalogics.PDFL.NamedFunction.getCPtr (NamedFunction obj) static protected
getDomain()
java.util.List<Double> com.datalogics.PDFL.NamedFunction.getDomain ()
The domain of the function. 2 * m elements, where m is the number of inputs to the function.
Throws a 'not implemented' exception for named functions.
Reimplemented from com.datalogics.PDFL.Function.
getName()
String com.datalogics.PDFL.NamedFunction.getName ()
The name of the function.
getNInputs()
int com.datalogics.PDFL.NamedFunction.getNInputs ()
The number of inputs to the function.Throws a 'not implemented' exception for named functions.
Reimplemented from com.datalogics.PDFL.Function.
getNOutputs()
int com.datalogics.PDFL.NamedFunction.getNOutputs ()
The number of outputs from the function.Throws a 'not implemented' exception for named functions.
Reimplemented from com.datalogics.PDFL.Function.
getRange()
java.util.List<Double> com.datalogics.PDFL.NamedFunction.getRange ()
The range of the function. 2 * n elements, where n is the number of outputs from the function.
Throws a 'not implemented' exception for named functions.
Reimplemented from com.datalogics.PDFL.Function.
setDomain()
void com.datalogics.PDFL.NamedFunction.setDomain (java.util.List< Double > domain)
The domain of the function. 2 * m elements, where m is the number of inputs to the function.
Throws a 'not implemented' exception for named functions.
Reimplemented from com.datalogics.PDFL.Function.
setRange()
void com.datalogics.PDFL.NamedFunction.setRange (java.util.List< Double > range)
The range of the function. 2 * n elements, where n is the number of outputs from the function.
Throws a 'not implemented' exception for named functions.
Reimplemented from com.datalogics.PDFL.Function.
toString()
String com.datalogics.PDFL.NamedFunction.toString ()
Convert the function to a displayable string.
Reimplemented from com.datalogics.PDFL.Function.
Member Data Documentation
DEFAULT
final Function com.datalogics.PDFL.Function.DEFAULT static inherited
IDENTITY
final Function com.datalogics.PDFL.Function.IDENTITY static inherited