Adobe PDF Library Java Documentation
com.datalogics.PDFL.PDFObject Class Reference
Public Member Functions
PDFObject clone ()
PDFObject clone (Document doc)
PDFObject clone (Document doc, boolean indirect)
PDFObject clone (PDFObject obj)
PDFObject clone (PDFObject obj, boolean indirect)
PDFObjectComparison compareTo (PDFObject rhs)
synchronized void delete ()
void destroy ()
boolean enumPDFObjects (PDFObjectEnumProc enumProc)
boolean equals (Object rhs)
Document getDocument ()
int getGeneration ()
int getID ()
boolean getIndirect ()
int getPDFHashValue ()
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PDFObject (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PDFObject obj)
Detailed Description
Represents the underlying simple data element of an object in a PDF document. All objects in a PDF document are built from a collection of simpler objects that represent fundamental datatypes like numbers, strings and arrays. PDFObject and its subclasses allow direct access and manipulation of these simple objects. Some subclasses represent single data elements. For example, PDFInteger represents a single integer value. Others represent a collection of PDFObjects, such as PDFArray, an indexed array of data elements.
PDFObject is the superclass of these simple objects. A PDFObject cannot be directly instantiated, but any of its subclasses may.
Any PDFObject may be either direct or indirect. A direct object exists within its collection object (such as a PDFArray) and can be referenced only within that collection object. An indirect object exists outside of any collection object and can be referenced by many collection objects.
Constructor & Destructor Documentation
PDFObject()
com.datalogics.PDFL.PDFObject.PDFObject (long cPtr, boolean cMemoryOwn) protected
Member Function Documentation
clone() [1/5]
PDFObject com.datalogics.PDFL.PDFObject.clone ()
Makes a new copy of this PDFObject in memory, in the same document and using same direct/indirect setting as this PDFObject.
clone() [2/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (Document doc)
Makes a new copy of this PDFObject in memory, in the supplied document, using the same direct/indirect setting as this PDFObject.
clone() [3/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (Document doc, boolean indirect)
Makes a new copy of this PDFObject in memory, in the supplied document, using supplied direct/indirect setting.
clone() [4/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (PDFObject obj)
Makes a new copy of this PDFObject in memory, in the same document as another object, using the same direct/indirect setting as this PDFObject.
clone() [5/5]
PDFObject com.datalogics.PDFL.PDFObject.clone (PDFObject obj, boolean indirect)
Makes a new copy of this PDFObject in memory, in the same document as another object, using supplied direct/indirect setting.
compareTo()
PDFObjectComparison com.datalogics.PDFL.PDFObject.compareTo (PDFObject rhs)
Compares this object to another object. The result is useful for ordering or sorting PDFObjects. No other significance should be attached to the result. In particular, an unequal result indicates nothing about the type of either object.
The result is valid only within a single instance of the document.
Parameters
rhs the other PDFObject to compare.
Returns
A PDFObjectComparison value that relates this object to the rhs object
delete() [1/2]
synchronized void com.datalogics.PDFL.PDFObject.delete ()
Reimplemented in com.datalogics.PDFL.PDFString, com.datalogics.PDFL.PDFStream, com.datalogics.PDFL.PDFReal, com.datalogics.PDFL.PDFName, com.datalogics.PDFL.PDFInteger, com.datalogics.PDFL.PDFDict, com.datalogics.PDFL.PDFBoolean, and com.datalogics.PDFL.PDFArray.
Referenced by com.datalogics.PDFL.PDFDict.getKeys().
delete() [2/2]
synchronized void com.datalogics.PDFL.PDFObject.delete (Boolean disposing) protected
Reimplemented in com.datalogics.PDFL.PDFString, com.datalogics.PDFL.PDFStream, com.datalogics.PDFL.PDFReal, com.datalogics.PDFL.PDFName, com.datalogics.PDFL.PDFInteger, com.datalogics.PDFL.PDFDict, com.datalogics.PDFL.PDFBoolean, and com.datalogics.PDFL.PDFArray.
destroy()
void com.datalogics.PDFL.PDFObject.destroy ()
Destroys this object.
This method does nothing if this object is a direct scalar object.
If a composite object (an array, dictionary or stream) is destroyed:
All the direct objects in it are automatically destroyed.
The indirect objects in it are not destroyed.
enumPDFObjects()
boolean com.datalogics.PDFL.PDFObject.enumPDFObjects (PDFObjectEnumProc enumProc)
Enumerates the elements of a PDFObject by calling a user-supplied procedure for each component of the object.
For scalars or strings, the proc is not called, and CosObjEnum() returns true.
For dictionaries, proc is called for each key-value pair. The order in which the key-value pairs are enumerated is undefined.
For arrays, proc is called with each element as the first paramater to proc, and the NULL object as the second parameter. Array elements are enumerated in ascending order of index.
For streams, proc is called once, with the stream's dictionary as the first parameter to the proc and the NULL object as the second parameter.
Parameters
enumProc A user-supplied callback to call for each element of the object. of obj. Neither proc nor any routine called by proc may modify the object. Doing so can produce undefined results or errors. For example, if the object is an array, enumProc must not call Remove(); if the object is a dictionary, enumProc must not call Put().
Returns
Returns true if every call to enumProc returned true. As soon as any call to enumProc returns false, the enumeration stops and EnumPDFObject() returns false.
equals()
boolean com.datalogics.PDFL.PDFObject.equals (Object rhs)
finalize()
void com.datalogics.PDFL.PDFObject.finalize () protected
Reimplemented in com.datalogics.PDFL.PDFString, com.datalogics.PDFL.PDFStream, com.datalogics.PDFL.PDFReal, com.datalogics.PDFL.PDFName, com.datalogics.PDFL.PDFInteger, com.datalogics.PDFL.PDFDict, com.datalogics.PDFL.PDFBoolean, and com.datalogics.PDFL.PDFArray.
getCPtr()
static long com.datalogics.PDFL.PDFObject.getCPtr (PDFObject obj) static protected
Referenced by com.datalogics.PDFL.PDFArray.add(), com.datalogics.PDFL.PDFObjectEnumProc.Call(), com.datalogics.PDFL.PDFObject.clone(), com.datalogics.PDFL.PDFObject.compareTo(), com.datalogics.PDFL.PDFArray.insert(), com.datalogics.PDFL.PDFArray.PDFArray(), com.datalogics.PDFL.PDFBoolean.PDFBoolean(), com.datalogics.PDFL.PDFDict.PDFDict(), com.datalogics.PDFL.PDFInteger.PDFInteger(), com.datalogics.PDFL.PDFName.PDFName(), com.datalogics.PDFL.PDFReal.PDFReal(), com.datalogics.PDFL.PDFStream.PDFStream(), com.datalogics.PDFL.PDFString.PDFString(), com.datalogics.PDFL.PDFArray.put(), com.datalogics.PDFL.NumberTree.put(), com.datalogics.PDFL.PDFDict.put(), com.datalogics.PDFL.NameTree.put(), and com.datalogics.PDFL.PDFArray.remove().
getDocument()
Document com.datalogics.PDFL.PDFObject.getDocument ()
The Document of which this object is a member.
Returns null if the Document is not known by PDFL, or if it is a temporary document.
If the Document is not null, then it shares the same internal data with other Document objects that refer to the same file. Document objects returned this way do not contribute to the internal count that keeps the Document open, and will become invalid if the main reference to the document is disposed.
Returns
the Document in which the object resides.
getGeneration()
int com.datalogics.PDFL.PDFObject.getGeneration ()
The generation number for this object. Only indirect objects have a generation number.
getID()
int com.datalogics.PDFL.PDFObject.getID ()
The ID number for this object. Only indirect objects have an ID number.
getIndirect()
boolean com.datalogics.PDFL.PDFObject.getIndirect ()
Indicates if this object is indirect or direct.
getPDFHashValue()
int com.datalogics.PDFL.PDFObject.getPDFHashValue ()
The 32-bit hash value for this object. The hash value is used internally to quickly access the object, and is not generally useful for PDFObject users. Note that two PDFObjects with equal hash values are not necessarily equal; use Equals() to check for equality.
toString()
String com.datalogics.PDFL.PDFObject.toString ()
Reimplemented in com.datalogics.PDFL.PDFString, com.datalogics.PDFL.PDFStream, com.datalogics.PDFL.PDFReal, com.datalogics.PDFL.PDFName, com.datalogics.PDFL.PDFInteger, com.datalogics.PDFL.PDFDict, com.datalogics.PDFL.PDFBoolean, and com.datalogics.PDFL.PDFArray.