Adobe PDF Library Java Documentation
com.datalogics.PDFL.ICCBasedColorSpace Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
ColorSpace getAlternate ()
String getName ()
int getNumComponents ()
PDFObject getPDFObject ()
java.util.List< Double > getRange ()
PDFStream getStream ()
ICCBasedColorSpace (PDFStream iccStream)
ICCBasedColorSpace (PDFStream iccStream, int nComps)
void setAlternate (ColorSpace alternate)
void setRange (java.util.List< Double > range)
String toString ()
Static Public Attributes
static final ColorSpace DEVICE_CMYK
static final ColorSpace DEVICE_GRAY
static final ColorSpace DEVICE_RGB
static final ColorSpace DEVICE_RGBA
static final ColorSpace LAB
static final ColorSpace LAB_A
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
ICCBasedColorSpace (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (ColorSpace obj)
static long getCPtr (ICCBasedColorSpace obj)
Detailed Description
Works with the ICC color space. The International Color Consortium (ICC) developed the ICC color space in 1993 to serve as a universal standard for for printing or presenting content with digital devices, and across all operating systems and platforms.
The ICC color standard applies regardless the hardware or software involved, and is used to make sure that color images and text appear properly on a wide variety of platforms.
Constructor & Destructor Documentation
ICCBasedColorSpace() [1/3]
com.datalogics.PDFL.ICCBasedColorSpace.ICCBasedColorSpace (long cPtr, boolean cMemoryOwn) protected
ICCBasedColorSpace() [2/3]
com.datalogics.PDFL.ICCBasedColorSpace.ICCBasedColorSpace (PDFStream iccStream, int nComps)
Create an ICC-based color stream.
Parameters
iccStream stream containing the ICC profile
nComps The number of components (1, 3, or 4)
ICCBasedColorSpace() [3/3]
com.datalogics.PDFL.ICCBasedColorSpace.ICCBasedColorSpace (PDFStream iccStream)
Create an ICC-based color stream.
Parameters
iccStream stream containing the ICC profile
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.ICCBasedColorSpace.delete ()
Reimplemented from com.datalogics.PDFL.ColorSpace.
delete() [2/2]
synchronized void com.datalogics.PDFL.ICCBasedColorSpace.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.ColorSpace.
equals()
boolean com.datalogics.PDFL.ColorSpace.equals (Object rhs) inherited
Reimplemented in com.datalogics.PDFL.NamedColorSpace.
finalize()
void com.datalogics.PDFL.ICCBasedColorSpace.finalize () protected
Reimplemented from com.datalogics.PDFL.ColorSpace.
getAlternate()
ColorSpace com.datalogics.PDFL.ICCBasedColorSpace.getAlternate ()
An alternate color space to be used in case the one specified in the stream data is not supported (for example, by applications designed for earlier versions of PDF). The alternate space may be any valid color space (except a Pattern color space) that has the number of components specified by N. If this entry is omitted and the application does not understand the ICC profile data, the color space used is DeviceGray, DeviceRGB, or DeviceCMYK, depending on whether the value of N is 1, 3, or 4, respectively.
getCPtr() [1/2]
static long com.datalogics.PDFL.ColorSpace.getCPtr (ColorSpace obj) static protected inherited
Referenced by com.datalogics.PDFL.Image.Image(), com.datalogics.PDFL.PageImageParams.PageImageParams(), com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), com.datalogics.PDFL.ICCBasedColorSpace.setAlternate(), com.datalogics.PDFL.DrawParams.setColorSpace(), com.datalogics.PDFL.ShadingPattern.setColorSpace(), com.datalogics.PDFL.Content.setDefaultColorSpace(), and com.datalogics.PDFL.PageImageParams.setImageColorSpace().
getCPtr() [2/2]
static long com.datalogics.PDFL.ICCBasedColorSpace.getCPtr (ICCBasedColorSpace obj) static protected
getName()
String com.datalogics.PDFL.ColorSpace.getName () inherited
The name of the color space. A named color space may be named something like DeviceRGB. More complicated color spaces may have a name like Indexed or ICCBased.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getNumComponents()
int com.datalogics.PDFL.ColorSpace.getNumComponents () inherited
The number of components in the color space.
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getPDFObject()
PDFObject com.datalogics.PDFL.ColorSpace.getPDFObject () inherited
Get the PDFObject associated with the color space. This may be a PDFName, PDFDict, PDFStream, or PDFArray.
Returns
The PDFObject associated with the color space.
getRange()
java.util.List<Double> com.datalogics.PDFL.ICCBasedColorSpace.getRange ()
An array of 2 * NumComponents numbers [ min0 max0 min1 max1 ... ] specifying the minimum and maximum valid values of the corresponding color components. These values must match the information in the ICC profile. Default value: [ 0.0 1.0 0.0 1.0 ... ]
getStream()
PDFStream com.datalogics.PDFL.ICCBasedColorSpace.getStream ()
The PDFStream containing the ICC-based data and other attributes.
setAlternate()
void com.datalogics.PDFL.ICCBasedColorSpace.setAlternate (ColorSpace alternate)
An alternate color space to be used in case the one specified in the stream data is not supported (for example, by applications designed for earlier versions of PDF). The alternate space may be any valid color space (except a Pattern color space) that has the number of components specified by N. If this entry is omitted and the application does not understand the ICC profile data, the color space used is DeviceGray, DeviceRGB, or DeviceCMYK, depending on whether the value of N is 1, 3, or 4, respectively.
setRange()
void com.datalogics.PDFL.ICCBasedColorSpace.setRange (java.util.List< Double > range)
An array of 2 * NumComponents numbers [ min0 max0 min1 max1 ... ] specifying the minimum and maximum valid values of the corresponding color components. These values must match the information in the ICC profile. Default value: [ 0.0 1.0 0.0 1.0 ... ]
toString()
String com.datalogics.PDFL.ColorSpace.toString () inherited
Convert a colorSpace to a string.
Member Data Documentation
DEVICE_CMYK
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_CMYK static inherited
DEVICE_GRAY
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_GRAY static inherited
DEVICE_RGB
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGB static inherited
DEVICE_RGBA
final ColorSpace com.datalogics.PDFL.ColorSpace.DEVICE_RGBA static inherited
LAB
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB static inherited
LAB_A
final ColorSpace com.datalogics.PDFL.ColorSpace.LAB_A static inherited