Adobe PDF Library Java Documentation
com.datalogics.PDFL.GraphicState Class Reference
Public Member Functions
synchronized void delete ()
java.util.List< Double > getDashPattern ()
ExtendedGraphicState getExtendedGraphicState ()
Color getFillColor ()
LineCap getLineCap ()
double getLineFlatness ()
LineJoin getLineJoin ()
double getMiterLimit ()
RenderIntent getRenderIntent ()
Color getStrokeColor ()
double getWidth ()
GraphicState ()
void setDashPattern (java.util.List< Double > DashPattern)
void setExtendedGraphicState (ExtendedGraphicState extendedGraphicState)
void setFillColor (Color fillcolor)
void setLineCap (LineCap LineCap)
void setLineFlatness (double flatness)
void setLineJoin (LineJoin LineJoin)
void setMiterLimit (double miterLimit)
void setRenderIntent (RenderIntent renderingIntent)
void setStrokeColor (Color strokecolor)
void setWidth (double width)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
GraphicState (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (GraphicState obj)
Detailed Description
The graphic state is an internal data structure in a PDF file. The graphics state holds the parameters that describe graphics within that file.
These parameters define how individual graphics are presented on the page, including layers and transparencies.
Constructor & Destructor Documentation
GraphicState() [1/2]
com.datalogics.PDFL.GraphicState.GraphicState (long cPtr, boolean cMemoryOwn) protected
GraphicState() [2/2]
com.datalogics.PDFL.GraphicState.GraphicState ()
Create a new default GraphicState.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.GraphicState.delete ()
delete() [2/2]
synchronized void com.datalogics.PDFL.GraphicState.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.GraphicState.finalize () protected
getCPtr()
static long com.datalogics.PDFL.GraphicState.getCPtr (GraphicState obj) static protected
Referenced by com.datalogics.PDFL.Text.addGlyphs(), com.datalogics.PDFL.Path.Path(), com.datalogics.PDFL.Form.setGraphicState(), com.datalogics.PDFL.Image.setGraphicState(), com.datalogics.PDFL.Path.setGraphicState(), com.datalogics.PDFL.TextRun.setGraphicState(), and com.datalogics.PDFL.TextRun.TextRun().
getDashPattern()
java.util.List<Double> com.datalogics.PDFL.GraphicState.getDashPattern ()
The line DashPattern controls the pattern of dashes and gaps used to stroke paths. It is specified by a dash phase and then a series of elements of a DashPattern list. The DashPattern's members are numbers that specify the lengths of alternating dashes and gaps; the numbers must be nonnegative and not all zero. The dash phase specifies the distance into the dash pattern at which to start the dash. The elements of both the DashPattern List and the dash phase are expressed in user space units. This retrieves the DashPattern used by the Pattern list current graphic state.
Returns
A list containing the dash phase followed by the contents of the DashPattern.
getExtendedGraphicState()
ExtendedGraphicState com.datalogics.PDFL.GraphicState.getExtendedGraphicState ()
The ExtendedGraphicState, which can contain additional graphic state parameters.
getFillColor()
Color com.datalogics.PDFL.GraphicState.getFillColor ()
The fill color of the GraphicState.
getLineCap()
LineCap com.datalogics.PDFL.GraphicState.getLineCap ()
The line cap used by the current GraphicState.
getLineFlatness()
double com.datalogics.PDFL.GraphicState.getLineFlatness ()
The line flatness corresponding to the i operator.Default is 1.0.
getLineJoin()
LineJoin com.datalogics.PDFL.GraphicState.getLineJoin ()
The line join style used by the current GraphicState.
getMiterLimit()
double com.datalogics.PDFL.GraphicState.getMiterLimit ()
The miter limit corresponding to the M operator.Default is 10.0.
getRenderIntent()
RenderIntent com.datalogics.PDFL.GraphicState.getRenderIntent ()
A color rendering intent corresponding to the Intent key in the image dictionary. The default is RelColorimetric.
getStrokeColor()
Color com.datalogics.PDFL.GraphicState.getStrokeColor ()
The stroke color of the GraphicState.
getWidth()
double com.datalogics.PDFL.GraphicState.getWidth ()
The width used for drawing by the current GraphicState.
setDashPattern()
void com.datalogics.PDFL.GraphicState.setDashPattern (java.util.List< Double > DashPattern)
The line DashPattern controls the pattern of dashes and gaps used to stroke paths. It is specified by a dash phase and then a series of elements of a DashPattern list. The DashPattern's members are numbers that specify the lengths of alternating dashes and gaps; the numbers must be nonnegative and not all zero. The dash phase specifies the distance into the dash pattern at which to start the dash. The elements of both the DashPattern List and the dash phase are expressed in user space units. This retrieves the DashPattern used by the Pattern list current graphic state.
Parameters
DashPattern A list containing the dash phase followed by the contents of the DashPattern.
setExtendedGraphicState()
void com.datalogics.PDFL.GraphicState.setExtendedGraphicState (ExtendedGraphicState extendedGraphicState)
The ExtendedGraphicState, which can contain additional graphic state parameters.
setFillColor()
void com.datalogics.PDFL.GraphicState.setFillColor (Color fillcolor)
The fill color of the GraphicState.
Parameters
fillcolor (DeviceGray, GrayScalevalue or fillcolor (DeviceRGB, Redvalue, Greenvalue, Bluevalue or fillcolor (DeviceCMYK, Cyanvalue, Magentavalue, Yellowvalue, Blackvalue
setLineCap()
void com.datalogics.PDFL.GraphicState.setLineCap (LineCap LineCap)
The line cap used by the current GraphicState.
setLineFlatness()
void com.datalogics.PDFL.GraphicState.setLineFlatness (double flatness)
The line flatness corresponding to the i operator.Default is 1.0.
setLineJoin()
void com.datalogics.PDFL.GraphicState.setLineJoin (LineJoin LineJoin)
The line join style to be used by the current GraphicState.
setMiterLimit()
void com.datalogics.PDFL.GraphicState.setMiterLimit (double miterLimit)
The miter limit corresponding to the M operator.Default is 10.0.
setRenderIntent()
void com.datalogics.PDFL.GraphicState.setRenderIntent (RenderIntent renderingIntent)
A color rendering intent corresponding to the Intent key in the image dictionary. The default is RelColorimetric.
setStrokeColor()
void com.datalogics.PDFL.GraphicState.setStrokeColor (Color strokecolor)
The stroke color of the GraphicState.
Parameters
strokecolor (DeviceGray, GrayScalevalue or strokecolor (DeviceRGB, Redvalue, Greenvalue, Bluevalue or strokecolor (DeviceCMYK, Cyanvalue, Magentavalue, Yellowvalue, Blackvalue
setWidth()
void com.datalogics.PDFL.GraphicState.setWidth (double width)
The width used for drawing by the current GraphicState.