Adobe PDF Library Java Documentation
com.datalogics.PDFL.OptionalContentOrderLeaf Class Reference
Public Member Functions
synchronized void delete ()
OptionalContentGroup getOptionalContentGroup ()
OptionalContentOrderLeaf (OptionalContentGroup ocg)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
OptionalContentOrderLeaf (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (OptionalContentOrderLeaf obj)
static long getCPtr (OptionalContentOrderNode obj)
Detailed Description
Leaf node class for items in the OptionalContentConfig Order array. Items in the Order array can be arranged into a tree structure. Each 'leaf' on this tree would be an OptionalContentOrderLeaf that contains a reference to an OptionalContentGroup in this document.
Constructor & Destructor Documentation
OptionalContentOrderLeaf() [1/2]
com.datalogics.PDFL.OptionalContentOrderLeaf.OptionalContentOrderLeaf (long cPtr, boolean cMemoryOwn) protected
OptionalContentOrderLeaf() [2/2]
com.datalogics.PDFL.OptionalContentOrderLeaf.OptionalContentOrderLeaf (OptionalContentGroup ocg)
Create an OptionalContentOrderLeaf that refers to the OptionalContentGroup.
Parameters
ocg The OptionalContentGroup this object will refer to.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.OptionalContentOrderLeaf.delete ()
Reimplemented from com.datalogics.PDFL.OptionalContentOrderNode.
delete() [2/2]
synchronized void com.datalogics.PDFL.OptionalContentOrderLeaf.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.OptionalContentOrderNode.
finalize()
void com.datalogics.PDFL.OptionalContentOrderLeaf.finalize () protected
Reimplemented from com.datalogics.PDFL.OptionalContentOrderNode.
getCPtr() [1/2]
static long com.datalogics.PDFL.OptionalContentOrderLeaf.getCPtr (OptionalContentOrderLeaf obj) static protected
getCPtr() [2/2]
static long com.datalogics.PDFL.OptionalContentOrderNode.getCPtr (OptionalContentOrderNode obj) static protected inherited
Referenced by com.datalogics.PDFL.OptionalContentOrderArray.add(), com.datalogics.PDFL.OptionalContentOrderArray.insert(), and com.datalogics.PDFL.OptionalContentOrderArray.put().
getOptionalContentGroup()
OptionalContentGroup com.datalogics.PDFL.OptionalContentOrderLeaf.getOptionalContentGroup ()
Gets the OptionalContentGroup refered to by this OptionalContentOrderLeaf.
Returns
The OptionalContentGroup this object refers to.