Adobe PDF Library Java Documentation
com.datalogics.PDFL.ElementCloneFlags Enum Reference
Static Public Member Functions
static int FlagsToInt (java.lang.Iterable< ElementCloneFlags > flags)
static java.util.EnumSet< ElementCloneFlags > IntToFlags (int value)
Public Attributes
COPY_CLIPPING
NO_GRAPHIC_STATE
NONE
Member Function Documentation
FlagsToInt()
static int com.datalogics.PDFL.ElementCloneFlags.FlagsToInt (java.lang.Iterable< ElementCloneFlags > flags) static
Referenced by com.datalogics.PDFL.Container.clone(), com.datalogics.PDFL.Element.clone(), com.datalogics.PDFL.Group.clone(), com.datalogics.PDFL.Image.clone(), com.datalogics.PDFL.Path.clone(), and com.datalogics.PDFL.Text.clone().
IntToFlags()
static java.util.EnumSet<ElementCloneFlags> com.datalogics.PDFL.ElementCloneFlags.IntToFlags (int value) static
Member Data Documentation
COPY_CLIPPING
com.datalogics.PDFL.ElementCloneFlags.COPY_CLIPPING
Acquire the clip path and put it in the copied object.NoGraphicState must not be set.
NO_GRAPHIC_STATE
com.datalogics.PDFL.ElementCloneFlags.NO_GRAPHIC_STATE
The copied element does not need a GraphicState.
NONE
com.datalogics.PDFL.ElementCloneFlags.NONE
Normal copying.