Adobe PDF Library Java Documentation
com.datalogics.PDFL.CurveToV Class Reference
Public Member Functions
CurveToV (double x2, double y2, double x3, double y3)
CurveToV (Point point2, Point point3)
synchronized void delete ()
Point getPoint2 ()
Point getPoint3 ()
void setPoint2 (Point value)
void setPoint3 (Point value)
String toString ()
Protected Member Functions
CurveToV (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (CurveToV obj)
static long getCPtr (Segment obj)
Detailed Description
A curveto operator where the first control point matches the beginning. The current point is the beginning point in the curve.
The name CurveToV is drawn from the "V" path construction operator.
Constructor & Destructor Documentation
CurveToV() [1/3]
com.datalogics.PDFL.CurveToV.CurveToV (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
CurveToV() [2/3]
com.datalogics.PDFL.CurveToV.CurveToV (Point point2, Point point3)
Append a cubic Be패zier curve to the current path.The curve extends from the current point to point3, using the current point and point2 as the Be패zier control points.The new current point is point3.
Parameters
point2 the second control point.
point3 the new current point.
CurveToV() [3/3]
com.datalogics.PDFL.CurveToV.CurveToV (double x2, double y2, double x3, double y3)
Append a cubic Be패zier curve to the current path.The curve extends from the current point to the point (x3, y3), using the current point and (x2, y2) as the Be패zier control points.The new current point is (x3 ,y3).
Parameters
x2 The x-coordinate of the second control point.
y2 The y-coordinate of the second control point.
x3 The x-coordinate of the new current point.
y3 The y-coordinate of the new current point.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.CurveToV.delete ()
Reimplemented from com.datalogics.PDFL.Segment.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.CurveToV.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Segment.
finalize()
void com.datalogics.PDFL.CurveToV.finalize () protected
Reimplemented from com.datalogics.PDFL.Segment.
getCPtr() [1/2]
long com.datalogics.PDFL.CurveToV.getCPtr (CurveToV obj) static protected
getCPtr() [2/2]
long com.datalogics.PDFL.Segment.getCPtr (Segment obj) static protected inherited
getPoint2()
Point com.datalogics.PDFL.CurveToV.getPoint2 ()
The second control point.
getPoint3()
Point com.datalogics.PDFL.CurveToV.getPoint3 ()
The new current point.
setPoint2()
void com.datalogics.PDFL.CurveToV.setPoint2 (Point value)
The second control point.
setPoint3()
void com.datalogics.PDFL.CurveToV.setPoint3 (Point value)
The new current point.
toString()
String com.datalogics.PDFL.CurveToV.toString ()
Reimplemented from com.datalogics.PDFL.Segment.