Adobe PDF Library Java Documentation
com.datalogics.PDFL.WordFinderConfig Class Reference
Public Member Functions
synchronized void delete ()
boolean getDisableCharReordering ()
boolean getDisableTaggedPDF ()
boolean getIgnoreCharGaps ()
boolean getIgnoreLineGaps ()
boolean getNoAnnots ()
boolean getNoEncodingGuess ()
boolean getNoExtCharOffset ()
boolean getNoHyphenDetection ()
boolean getNoLigatureExp ()
boolean getNoSkewedQuads ()
boolean getNoStyleInfo ()
boolean getNoTextRenderMode3 ()
boolean getNoXYSort ()
boolean getPreciseQuad ()
boolean getPreserveRedundantChars ()
boolean getPreserveSpaces ()
boolean getTrustNBSpace ()
boolean getUnknownToStdEnc ()
void setDisableCharReordering (boolean value)
void setDisableTaggedPDF (boolean value)
void setIgnoreCharGaps (boolean value)
void setIgnoreLineGaps (boolean value)
void setNoAnnots (boolean value)
void setNoEncodingGuess (boolean value)
void setNoExtCharOffset (boolean value)
void setNoHyphenDetection (boolean value)
void setNoLigatureExp (boolean value)
void setNoSkewedQuads (boolean value)
void setNoStyleInfo (boolean value)
void setNoTextRenderMode3 (boolean value)
void setNoXYSort (boolean value)
void setPreciseQuad (boolean value)
void setPreserveRedundantChars (boolean value)
void setPreserveSpaces (boolean value)
void setTrustNBSpace (boolean value)
void setUnknownToStdEnc (boolean value)
WordFinderConfig ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
WordFinderConfig (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (WordFinderConfig obj)
Detailed Description
A word finder configuration that customizes the way the extraction is performed.In the default configuration, all options are false.
Constructor & Destructor Documentation
WordFinderConfig() [1/2]
com.datalogics.PDFL.WordFinderConfig.WordFinderConfig (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
WordFinderConfig() [2/2]
com.datalogics.PDFL.WordFinderConfig.WordFinderConfig ()
A word finder configuration that customizes the way the extraction is performed.In the default configuration, all options are false.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.WordFinderConfig.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.WordFinderConfig.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.WordFinderConfig.finalize () protected
getCPtr()
long com.datalogics.PDFL.WordFinderConfig.getCPtr (WordFinderConfig obj) static protected
Referenced by com.datalogics.PDFL.DocTextFinder.DocTextFinder(), com.datalogics.PDFL.DocTextFinder.DocTextFinder(), and com.datalogics.PDFL.WordFinder.WordFinder().
getDisableCharReordering()
boolean com.datalogics.PDFL.WordFinderConfig.getDisableCharReordering ()
When true, it disables reconstructing the character orders, and the word finding algorithm is applied to the characters in the drawing order. By default, word finder reorders characters on a single line by the relative horizontal character locations. Most of the time, the character reordering feature improves the text extraction quality. However, on a PDF page with heavily overlapped character bounding boxes, the outcome becomes somewhat unpredictable. In such case, disabling the character reordering (disableCharReordering = true) may produce a more static result.
getDisableTaggedPDF()
boolean com.datalogics.PDFL.WordFinderConfig.getDisableTaggedPDF ()
When true, it disables tagged PDF support and treats the document as non-tagged PDF. Use this to keep the word finder in legacy mode when it is created with the latest algorithm version.
getIgnoreCharGaps()
boolean com.datalogics.PDFL.WordFinderConfig.getIgnoreCharGaps ()
When true, it disables converting large character gaps to space characters, so that the word finder reports a character space only when a space character appears in the original PDF content. This option has no effect on tagged PDF.
getIgnoreLineGaps()
boolean com.datalogics.PDFL.WordFinderConfig.getIgnoreLineGaps ()
When true, it disables treating vertical movements as line breaks, so that the word finder determines a line break only when a line break character or special tag information appears in the original PDF content. This option has no effect on tagged PDF.
getNoAnnots()
boolean com.datalogics.PDFL.WordFinderConfig.getNoAnnots ()
When true, it disables extracting text from text annotations. Normally, the word finder extracts text from the normal appearances of text annotations that are inside the page crop box.
getNoEncodingGuess()
boolean com.datalogics.PDFL.WordFinderConfig.getNoEncodingGuess ()
When true, it disables guessing encoding of fonts that have unknown or custom encoding when there is no ToUnicode table. Inappropriate encoding conversions can cause the word finder to mistakenly recognize non-Roman single-byte fonts as Standard Roman encoding fonts and extract the text in an unusable format. When this option is selected, the word finder avoids such unreliable encoding conversions and tries to provide the original characters without any encoding conversion for a client with its own encoding handling.
getNoExtCharOffset()
boolean com.datalogics.PDFL.WordFinderConfig.getNoExtCharOffset ()
When true, it disables generating extended character offset information to improve text extraction performance. The extended character offset information is necessary to determine exact character offset for character-by-character text selection. The beginning character offset of each word is always available regardless of this option, and can be used for word-by-word text selection with reasonable accuracy. When a client has no need for the detailed character offset information, it can use this option to improve the text extraction efficiency. There is a minor difference in the text extraction performance, and less memory is needed for the extracted word list.
getNoHyphenDetection()
boolean com.datalogics.PDFL.WordFinderConfig.getNoHyphenDetection ()
When true, it disables finding and removing soft hyphens in non-tagged PDF, so that the word finder trusts hard hyphens as non-soft hyphens. This option has no effect on tagged PDF files. Normally, the word finder does not differentiate between soft and hard hyphen characters in non-tagged PDF files, because these are often misused.
getNoLigatureExp()
boolean com.datalogics.PDFL.WordFinderConfig.getNoLigatureExp ()
When true, it disables the expansion of ligatures using the default ligatures. The default ligatures are:
fi
ff
fl
ffi
ffl
ch
cl
ct
ll
ss
fs
st
oe
OE
getNoSkewedQuads()
boolean com.datalogics.PDFL.WordFinderConfig.getNoSkewedQuads ()
When true, it disables the creation of a quad per character for skewed words, words with a horizontally-aligned, but non-rectangular, bounding region. Each skewed word will, instead, be associated with a single rectangular, bounding region.
getNoStyleInfo()
boolean com.datalogics.PDFL.WordFinderConfig.getNoStyleInfo ()
When true, it disables generating character style information to improve text extraction performance and memory efficiency. When you select this option, you cannot access the the StyleTransition property of Word objects returned from WordFinder.
getNoTextRenderMode3()
boolean com.datalogics.PDFL.WordFinderConfig.getNoTextRenderMode3 ()
When true, it disables extracting text with Text Rendering mode Tr = 3 ("Neither fill nor stroke text (invisible)."). Normally, the word finder extracts such text as any other.
getNoXYSort()
boolean com.datalogics.PDFL.WordFinderConfig.getNoXYSort ()
When true, it disables generating an XY-ordered word list.
getPreciseQuad()
boolean com.datalogics.PDFL.WordFinderConfig.getPreciseQuad ()
When true, the bounding box or bounding quad will be set based on actual glyph bounding box.
getPreserveRedundantChars()
boolean com.datalogics.PDFL.WordFinderConfig.getPreserveRedundantChars ()
When true, it disables detecting and removing redundant characters. Some PDF pages have the same text drawn multiple times on the same spot to get a special visual effect. Normally, those redundant characters are removed from the word finder output.
Since this option may leave extra characters with overlapping bounding boxes, using it together with the disableCharReordering option is recommended for more consistent text extraction results.
getPreserveSpaces()
boolean com.datalogics.PDFL.WordFinderConfig.getPreserveSpaces ()
When true, the word finder preserves space characters during word breaking. Otherwise, spaces are removed from output text. When false (the default), you can add spaces later by considering the WordAttributeFlags.AdjacentToSpace attribute, but there is no way to restore the exact number of consecutive space characters.
getTrustNBSpace()
boolean com.datalogics.PDFL.WordFinderConfig.getTrustNBSpace ()
When true, it disables treating non-breaking space characters as regular space characters in non-tagged PDF files, so that the word finder preserves the space without breaking the word. This option has no effect on tagged PDF files. Normally, the word finder does not differentiate between breaking and non-breaking space characters in non-tagged PDF files, because these are often misused.
getUnknownToStdEnc()
boolean com.datalogics.PDFL.WordFinderConfig.getUnknownToStdEnc ()
When true, it assumes any font with unknown or custom encoding to be Standard Roman. This option overrides the noEncodingGuess option.
setDisableCharReordering()
void com.datalogics.PDFL.WordFinderConfig.setDisableCharReordering (boolean value)
When true, it disables reconstructing the character orders, and the word finding algorithm is applied to the characters in the drawing order. By default, word finder reorders characters on a single line by the relative horizontal character locations. Most of the time, the character reordering feature improves the text extraction quality. However, on a PDF page with heavily overlapped character bounding boxes, the outcome becomes somewhat unpredictable. In such case, disabling the character reordering (disableCharReordering = true) may produce a more static result.
setDisableTaggedPDF()
void com.datalogics.PDFL.WordFinderConfig.setDisableTaggedPDF (boolean value)
When true, it disables tagged PDF support and treats the document as non-tagged PDF. Use this to keep the word finder in legacy mode when it is created with the latest algorithm version.
setIgnoreCharGaps()
void com.datalogics.PDFL.WordFinderConfig.setIgnoreCharGaps (boolean value)
When true, it disables converting large character gaps to space characters, so that the word finder reports a character space only when a space character appears in the original PDF content. This option has no effect on tagged PDF.
setIgnoreLineGaps()
void com.datalogics.PDFL.WordFinderConfig.setIgnoreLineGaps (boolean value)
When true, it disables treating vertical movements as line breaks, so that the word finder determines a line break only when a line break character or special tag information appears in the original PDF content. This option has no effect on tagged PDF.
setNoAnnots()
void com.datalogics.PDFL.WordFinderConfig.setNoAnnots (boolean value)
When true, it disables extracting text from text annotations. Normally, the word finder extracts text from the normal appearances of text annotations that are inside the page crop box.
setNoEncodingGuess()
void com.datalogics.PDFL.WordFinderConfig.setNoEncodingGuess (boolean value)
When true, it disables guessing encoding of fonts that have unknown or custom encoding when there is no ToUnicode table. Inappropriate encoding conversions can cause the word finder to mistakenly recognize non-Roman single-byte fonts as Standard Roman encoding fonts and extract the text in an unusable format. When this option is selected, the word finder avoids such unreliable encoding conversions and tries to provide the original characters without any encoding conversion for a client with its own encoding handling.
setNoExtCharOffset()
void com.datalogics.PDFL.WordFinderConfig.setNoExtCharOffset (boolean value)
When true, it disables generating extended character offset information to improve text extraction performance. The extended character offset information is necessary to determine exact character offset for character-by-character text selection. The beginning character offset of each word is always available regardless of this option, and can be used for word-by-word text selection with reasonable accuracy. When a client has no need for the detailed character offset information, it can use this option to improve the text extraction efficiency. There is a minor difference in the text extraction performance, and less memory is needed for the extracted word list.
setNoHyphenDetection()
void com.datalogics.PDFL.WordFinderConfig.setNoHyphenDetection (boolean value)
When true, it disables finding and removing soft hyphens in non-tagged PDF, so that the word finder trusts hard hyphens as non-soft hyphens. This option has no effect on tagged PDF files. Normally, the word finder does not differentiate between soft and hard hyphen characters in non-tagged PDF files, because these are often misused.
setNoLigatureExp()
void com.datalogics.PDFL.WordFinderConfig.setNoLigatureExp (boolean value)
When true, it disables the expansion of ligatures using the default ligatures. The default ligatures are:
fi
ff
fl
ffi
ffl
ch
cl
ct
ll
ss
fs
st
oe
OE
setNoSkewedQuads()
void com.datalogics.PDFL.WordFinderConfig.setNoSkewedQuads (boolean value)
When true, it disables the creation of a quad per character for skewed words, words with a horizontally-aligned, but non-rectangular, bounding region. Each skewed word will, instead, be associated with a single rectangular, bounding region.
setNoStyleInfo()
void com.datalogics.PDFL.WordFinderConfig.setNoStyleInfo (boolean value)
When true, it disables generating character style information to improve text extraction performance and memory efficiency. When you select this option, you cannot access the the StyleTransition property of Word objects returned from WordFinder.
setNoTextRenderMode3()
void com.datalogics.PDFL.WordFinderConfig.setNoTextRenderMode3 (boolean value)
When true, it disables extracting text with Text Rendering mode Tr = 3 ("Neither fill nor stroke text (invisible)."). Normally, the word finder extracts such text as any other.
setNoXYSort()
void com.datalogics.PDFL.WordFinderConfig.setNoXYSort (boolean value)
When true, it disables generating an XY-ordered word list.
setPreciseQuad()
void com.datalogics.PDFL.WordFinderConfig.setPreciseQuad (boolean value)
When true, the bounding box or bounding quad will be set based on actual glyph bounding box.
setPreserveRedundantChars()
void com.datalogics.PDFL.WordFinderConfig.setPreserveRedundantChars (boolean value)
When true, it disables detecting and removing redundant characters. Some PDF pages have the same text drawn multiple times on the same spot to get a special visual effect. Normally, those redundant characters are removed from the word finder output.
Since this option may leave extra characters with overlapping bounding boxes, using it together with the disableCharReordering option is recommended for more consistent text extraction results.
setPreserveSpaces()
void com.datalogics.PDFL.WordFinderConfig.setPreserveSpaces (boolean value)
When true, the word finder preserves space characters during word breaking. Otherwise, spaces are removed from output text. When false (the default), you can add spaces later by considering the WordAttributeFlags.AdjacentToSpace attribute, but there is no way to restore the exact number of consecutive space characters.
setTrustNBSpace()
void com.datalogics.PDFL.WordFinderConfig.setTrustNBSpace (boolean value)
When true, it disables treating non-breaking space characters as regular space characters in non-tagged PDF files, so that the word finder preserves the space without breaking the word. This option has no effect on tagged PDF files. Normally, the word finder does not differentiate between breaking and non-breaking space characters in non-tagged PDF files, because these are often misused.
setUnknownToStdEnc()
void com.datalogics.PDFL.WordFinderConfig.setUnknownToStdEnc (boolean value)
When true, it assumes any font with unknown or custom encoding to be Standard Roman. This option overrides the noEncodingGuess option.