Adobe PDF Library Java Documentation
com.datalogics.PDFL.PageLabel Class Reference
Public Member Functions
synchronized void delete ()
int getEndPageIndex ()
int getFirstNumberInRange ()
NumberStyle getNumberStyle ()
String getPrefix ()
int getStartPageIndex ()
PageLabel (int start, NumberStyle ns)
PageLabel (int start, NumberStyle ns, String p, int first)
void setFirstNumberInRange (int arg0)
void setNumberStyle (NumberStyle arg0)
void setPrefix (String arg0)
void setStartPageIndex (int ndx)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PageLabel (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PageLabel obj)
Detailed Description
Describes numbering labels for a range of pages. PageLabel describes how to construct a label string for a range of pages. It contains information on number style, any prefixes, and a starting position within the document.
Note that a single PageLabel describes the label string for several pages all pages up until the first page covered by the next PageLabel, or the end of the document.
Also note that if a Document has any PageLabels, there must be one that starts at page index 0. This will be automatically created if the user does not supply one.
Constructor & Destructor Documentation
PageLabel() [1/3]
com.datalogics.PDFL.PageLabel.PageLabel (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
PageLabel() [2/3]
com.datalogics.PDFL.PageLabel.PageLabel (int start, NumberStyle ns, String p, int first)
Public constructor
Parameters
start Starting page index in the Document for this range
ns Numbering style for this range
p Prefix string for this range
first First number appearing on a page in this range
PageLabel() [3/3]
com.datalogics.PDFL.PageLabel.PageLabel (int start, NumberStyle ns)
Convenience constructor creates a range with no prefix starting with number 1.
Parameters
start Starting page index in the Document for this range
ns Numbering style for this range
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.PageLabel.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.PageLabel.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.PageLabel.finalize () protected
getCPtr()
long com.datalogics.PDFL.PageLabel.getCPtr (PageLabel obj) static protected
getEndPageIndex()
int com.datalogics.PDFL.PageLabel.getEndPageIndex ()
The end index for the page label range
You cannot set the end index for a range; you must change the start index for the following range. A value of -1 means the end index for this PageLabel is unknown.
getFirstNumberInRange()
int com.datalogics.PDFL.PageLabel.getFirstNumberInRange ()
The first number used in the page label range. Must be greater than or equal to 1.
getNumberStyle()
NumberStyle com.datalogics.PDFL.PageLabel.getNumberStyle ()
The numbering style for the page label range
getPrefix()
String com.datalogics.PDFL.PageLabel.getPrefix ()
The prefix string for the page label range
getStartPageIndex()
int com.datalogics.PDFL.PageLabel.getStartPageIndex ()
The start index for the page label range
setFirstNumberInRange()
void com.datalogics.PDFL.PageLabel.setFirstNumberInRange (int arg0)
The first number used in the page label range
setNumberStyle()
void com.datalogics.PDFL.PageLabel.setNumberStyle (NumberStyle arg0)
The numbering style for the page label range
setPrefix()
void com.datalogics.PDFL.PageLabel.setPrefix (String arg0)
The prefix string for the page label range
setStartPageIndex()
void com.datalogics.PDFL.PageLabel.setStartPageIndex (int ndx)
The start index for the page label range
toString()
String com.datalogics.PDFL.PageLabel.toString ()