Adobe PDF Library Java Documentation
com.datalogics.PDFL.StyleTransition Class Reference
Public Member Functions
synchronized void delete ()
int getCharIndex ()
Style getStyle ()
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
StyleTransition (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (StyleTransition obj)
Detailed Description
Represents a style change in a word. A StyleTransition provides information about the character index in the word where the style changes, and the new Style.
Constructor & Destructor Documentation
StyleTransition()
com.datalogics.PDFL.StyleTransition.StyleTransition (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.StyleTransition.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.StyleTransition.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.StyleTransition.finalize () protected
getCharIndex()
int com.datalogics.PDFL.StyleTransition.getCharIndex ()
The index of the character in the word at which this transition begins.
getCPtr()
long com.datalogics.PDFL.StyleTransition.getCPtr (StyleTransition obj) static protected
getStyle()
Style com.datalogics.PDFL.StyleTransition.getStyle ()
The Style that begins at this transition.
toString()
String com.datalogics.PDFL.StyleTransition.toString ()
Returns a string representation of the StyleTransition.