Adobe PDF Library Java Documentation
com.datalogics.PDFL.NumberTree Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
PDFObject get (int key)
PDFDict getPDFDict ()
NumberTree (Document doc)
void put (int key, PDFObject value)
void remove (int key)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
NumberTree (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (NumberTree obj)
Detailed Description
The number tree is a common data structure in PDF files. The number tree is a type of dictionary that can store many more pairs of matched records than a standard object dictionary.
A number tree uses keys that are integers to map to data objects, sorted in ascending numerical order.
Constructor & Destructor Documentation
NumberTree() [1/2]
com.datalogics.PDFL.NumberTree.NumberTree (long cPtr, boolean cMemoryOwn) protected
Referenced by equals(), and getCPtr().
NumberTree() [2/2]
com.datalogics.PDFL.NumberTree.NumberTree (Document doc)
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.NumberTree.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.NumberTree.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.NumberTree.equals (Object rhs)
finalize()
void com.datalogics.PDFL.NumberTree.finalize () protected
get()
PDFObject com.datalogics.PDFL.NumberTree.get (int key)
Retrieves an entry from this NumberTree.
Parameters
key The integer of the PDFObject to get from the tree.
Returns
- The PDFObject value corresponding to the supplied key
getCPtr()
long com.datalogics.PDFL.NumberTree.getCPtr (NumberTree obj) static protected
getPDFDict()
PDFDict com.datalogics.PDFL.NumberTree.getPDFDict ()
Return the PDFDict of this NumberTree.
Returns
PDFDict of the NumberTree
put()
void com.datalogics.PDFL.NumberTree.put (int key, PDFObject value)
Puts a new entry in this NumberTree. If an entry with this name is already in the tree, it is replaced.
Parameters
key The integer of the PDFObject to put in the tree.
value The PDFObject to be associated with key.
remove()
void com.datalogics.PDFL.NumberTree.remove (int key)
Removes the specified PDFObject from this NumberTree. It does nothing if no PDFObject of that number exists in this NumberTree.
Parameters
key The integer of the PDFObject to remove from the tree.