Adobe PDF Library Java Documentation
com.datalogics.PDFL.PDFAConvertParams Class Reference
Public Member Functions
synchronized void delete ()
boolean getAbortIfXFAIsPresent ()
boolean getIgnoreFontErrors ()
boolean getNoValidationErrors ()
String getProfileDesc ()
int getRasterizationResolution ()
boolean getRemoveAllAnnotations ()
boolean getValidateImplementationLimitsOfDocument ()
PDFAConvertParams ()
PDFAConvertParams (boolean RemoveAllAnnotations, boolean IgnoreFontErrors, boolean AbortIfXFAIsPresent)
PDFAConvertParams (boolean removeAllAnnotations, boolean ignoreFontErrors, boolean abortIfXFAIsPresent, boolean noValidationErrors, int rasterizationResolution)
PDFAConvertParams (boolean removeAllAnnotations, boolean ignoreFontErrors, boolean abortIfXFAIsPresent, boolean noValidationErrors, int rasterizationResolution, boolean validateImplementationLimitsOfDocument)
void setAbortIfXFAIsPresent (boolean theSetting)
void setIgnoreFontErrors (boolean theSetting)
void setNoValidationErrors (boolean theSetting)
void setProfileDesc (String profile)
void setRasterizationResolution (int theSetting)
void setRemoveAllAnnotations (boolean theSetting)
void setValidateImplementationLimitsOfDocument (boolean validateImplementationLimitsOfDocument)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PDFAConvertParams (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PDFAConvertParams obj)
Detailed Description
Parameters for converting a document to PDF/A compliance. These parameters control how a Document is converted to the PDF/A standard.
RemoveAllAnnotations if true, will remove all Annotations and Actions from the output
IgnoreFontErrors if true, will try to rasterize the page when fonts cannot be embedded
AbortIfXFAIsPresent if true, will abort conversion process if XFA form entry is detected
NoValidationErrors if true, will ignore validation errors
RasterizationResolution rasterization resolution; if 0, use 72 DPI
ValidateImplementationLimitsOfDocument Validate PDF Implementation Limits of the Document.
PDF/A is an ISO-standard version the PDF format. It is designed to be used with PDF files that need to be archived and stored for long periods. For example, the fonts in a PDF/A file are embedded in the file itself, rather than accessed through a link to a font directory on a local server.
Constructor & Destructor Documentation
PDFAConvertParams() [1/5]
com.datalogics.PDFL.PDFAConvertParams.PDFAConvertParams (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
PDFAConvertParams() [2/5]
com.datalogics.PDFL.PDFAConvertParams.PDFAConvertParams ()
PDFAConvertParams() [3/5]
com.datalogics.PDFL.PDFAConvertParams.PDFAConvertParams (boolean RemoveAllAnnotations, boolean IgnoreFontErrors, boolean AbortIfXFAIsPresent)
Parameters for converting to PDF/A.
Parameters
RemoveAllAnnotations Remove all annotations whether legal or illegal.
IgnoreFontErrors Rasterize a page when fonts cannot be embedded.
AbortIfXFAIsPresent Abort when XFA is present for PDF/A-1.
PDFAConvertParams() [4/5]
com.datalogics.PDFL.PDFAConvertParams.PDFAConvertParams (boolean removeAllAnnotations, boolean ignoreFontErrors, boolean abortIfXFAIsPresent, boolean noValidationErrors, int rasterizationResolution)
Parameters for converting to PDF/A.
Parameters
removeAllAnnotations Remove all annotations whether legal or illegal.
ignoreFontErrors Rasterize a page when fonts cannot be embedded.
abortIfXFAIsPresent Abort when XFA is present for PDF/A-1.
noValidationErrors Ignore validation errors.
rasterizationResolution Rasterization resolution.
PDFAConvertParams() [5/5]
com.datalogics.PDFL.PDFAConvertParams.PDFAConvertParams (boolean removeAllAnnotations, boolean ignoreFontErrors, boolean abortIfXFAIsPresent, boolean noValidationErrors, int rasterizationResolution, boolean validateImplementationLimitsOfDocument)
Parameters for converting to PDF/A.
Parameters
removeAllAnnotations Remove all annotations whether legal or illegal.
ignoreFontErrors Rasterize a page when fonts cannot be embedded.
abortIfXFAIsPresent Abort when XFA is present for PDF/A-1.
noValidationErrors Ignore validation errors.
rasterizationResolution Rasterization resolution.
validateImplementationLimitsOfDocument Validate PDF Implementation Limits of the Document.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.PDFAConvertParams.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.PDFAConvertParams.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.PDFAConvertParams.finalize () protected
getAbortIfXFAIsPresent()
boolean com.datalogics.PDFL.PDFAConvertParams.getAbortIfXFAIsPresent ()
The presence of XFA can result in some loss of data in output PDF/A-1 file as the PDFProcessor does not support XFA. However you can choose to abort the conversion if XFA is present by setting this parameter to true. By default we will not abort if XFA is present for PDF/A-1.
By default we will not abort if XFA is present for PDF/A-1.
If false we will convert even if XFA is found. If true we will abort the process if XFA is found.
getCPtr()
long com.datalogics.PDFL.PDFAConvertParams.getCPtr (PDFAConvertParams obj) static protected
getIgnoreFontErrors()
boolean com.datalogics.PDFL.PDFAConvertParams.getIgnoreFontErrors ()
If we encounter any errors like unembeddable fonts etc. while conversion then we try to rasterize the current page on which the error occured. However the client can modify this behavior by setting the value of this parameter to false in which case we will throw an error if we encounter any problems while conversion.
By default we will rasterize the page on error.
If true we will try to rasterize the current page if any error occured. If false we will abort and throw an exception if any error occured.
getNoValidationErrors()
boolean com.datalogics.PDFL.PDFAConvertParams.getNoValidationErrors ()
Permit validation errors to be ignored
When true, PDF Implementation Limits (as defined in the PDF Specification of the PDF/A target) of the page are ignored. When false, PDF Implementation Limits of the Page are checked and if violated will cause the Page to be rasterized as a fallback mechanism when IgnoreFontErrors is true or simply raise an error if IgnoreFontErrors is false.
getProfileDesc()
String com.datalogics.PDFL.PDFAConvertParams.getProfileDesc ()
The Output Intent of a PDF/A document may be any valid CMYK Profile for CMYK Conversion, and any valid RGB profile for RGB conversion. This parameter allows the user to specify a particular profile for this conversion by description. When this parameter is not present, the profile "U.S. Web Coated (SWOP) v2" will be used for CMYK Conversions, and "sRGB IEC61966-2.1" for RGB conversions.
If this description is present, and specifies a profile of the wrong color family, or specifies a profile which cannot be located in resources, an exception will be raised.
getRasterizationResolution()
int com.datalogics.PDFL.PDFAConvertParams.getRasterizationResolution ()
Permit user to select rasterization resolution When this value is zero, we will rasterize at 72 DPI (Legacy Behaviour). Otherwise, we will interpret the value as the desired resolution.
getRemoveAllAnnotations()
boolean com.datalogics.PDFL.PDFAConvertParams.getRemoveAllAnnotations ()
Some of the standards like PDF/A prohibit the presence of some types of Annotations and Actions in order to comply with those standards.
By default we will filter all illegal Annotations and Actions.
If false we will filter out all illegal Annotations and Actions (according to the standard being used) while retaining the legal ones. If true this will remove all the Annotations and Actions from the output PDF/A compliant file.
getValidateImplementationLimitsOfDocument()
boolean com.datalogics.PDFL.PDFAConvertParams.getValidateImplementationLimitsOfDocument ()
Validate PDF Implementation Limits (as defined in the PDF Specification of the PDF/A target) of the Document. When true. PDF Implementation Limits are checked and if violated raise an error. When false, PDF Implementation Limits are not checked. Note this option applies to the Whole document versus only Pages in the NoValidationErrors option. NOTE: It's recommended NoValidationErrors be set to false, IgnoreFontErrors be set to false, and ValidateImplementationLimitsOfDocument be set to true for getting the best quality output that adheres to the specification.
setAbortIfXFAIsPresent()
void com.datalogics.PDFL.PDFAConvertParams.setAbortIfXFAIsPresent (boolean theSetting)
The presence of XFA can result in some loss of data in output PDF/A-1 file as the PDFProcessor does not support XFA. However you can choose to abort the conversion if XFA is present by setting this parameter to true. By default we will not abort if XFA is present for PDF/A-1.
By default we will not abort if XFA is present for PDF/A-1.
If false we will convert even if XFA is found. If true we will abort the process if XFA is found.
setIgnoreFontErrors()
void com.datalogics.PDFL.PDFAConvertParams.setIgnoreFontErrors (boolean theSetting)
If we encounter any errors like unembeddable fonts etc. while conversion then we try to rasterize the current page on which the error occured. However the client can modify this behavior by setting the value of this parameter to false in which case we will throw an error if we encounter any problems while conversion.
By default we will rasterize the page on error.
If true we will try to rasterize the current page if any error occured. If false we will abort and throw an exception if any error occured.
setNoValidationErrors()
void com.datalogics.PDFL.PDFAConvertParams.setNoValidationErrors (boolean theSetting)
Permit validation errors to be ignored
When true, PDF Implementation Limits (as defined in the PDF Specification of the PDF/A target) of the page are ignored. When false, PDF Implementation Limits of the Page are checked and if violated will cause the Page to be rasterized as a fallback mechanism when IgnoreFontErrors is true or simply raise an error if IgnoreFontErrors is false.
setProfileDesc()
void com.datalogics.PDFL.PDFAConvertParams.setProfileDesc (String profile)
The Output Intent of a PDF/A document may be any valid CMYK Profile for CMYK Conversion, and any valid RGB profile for RGB conversion. This parameter allows the user to specify a particular profile for this conversion by description. When this parameter is not present, the profile "U.S. Web Coated (SWOP) v2" will be used for CMYK Conversions, and "sRGB IEC61966-2.1" for RGB conversions.
If this description is present, and specifies a profile of the wrong color family, or specifies a profile which cannot be located in resources, an exception will be raised.
setRasterizationResolution()
void com.datalogics.PDFL.PDFAConvertParams.setRasterizationResolution (int theSetting)
Permit user to select rasterization resolution When this value is zero, we will rasterize at 72 DPI (Legacy Behaviour). Otherwise, we will interpret the value as the desired resolution.
setRemoveAllAnnotations()
void com.datalogics.PDFL.PDFAConvertParams.setRemoveAllAnnotations (boolean theSetting)
Some of the standards like PDF/A prohibit the presence of some types of Annotations and Actions in order to comply with those standards.
By default we will filter all illegal Annotations and Actions.
If false we will filter out all illegal Annotations and Actions (according to the standard being used) while retaining the legal ones. If true this will remove all the Annotations and Actions from the output PDF/A compliant file.
setValidateImplementationLimitsOfDocument()
void com.datalogics.PDFL.PDFAConvertParams.setValidateImplementationLimitsOfDocument (boolean validateImplementationLimitsOfDocument)
Validate PDF Implementation Limits (as defined in the PDF Specification of the PDF/A target) of the Document. When true. PDF Implementation Limits are checked and if violated raise an error. When false, PDF Implementation Limits are not checked. Note this option applies to the Whole document versus only Pages in the NoValidationErrors option. NOTE: It's recommended NoValidationErrors be set to false, IgnoreFontErrors be set to false, and ValidateImplementationLimitsOfDocument be set to true for getting the best quality output that adheres to the specification.