Adobe PDF Library Java Documentation
com.datalogics.PDFL.RemoteDestination Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
Rect getDestRect ()
String getFitType ()
int getPageNumber ()
PDFObject getPDFObject ()
double getZoom ()
RemoteDestination (Document doc, int pageNum, String fitType, Rect r, double zoom)
void setDestRect (Rect destRect)
void setFitType (String remoteDestFitType)
void setPageNumber (int remoteDestPageNum)
void setZoom (double zoomFactor)
String toString ()
Static Public Attributes
static final double NULL_VALUE
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
RemoteDestination (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (RemoteDestination obj)
Detailed Description
A view of a page contained in a separate document. A RemoteDestination is not the same as a ViewDestination; the two objects are not interchangeable.
Constructor & Destructor Documentation
RemoteDestination() [1/2]
com.datalogics.PDFL.RemoteDestination.RemoteDestination (long cPtr, boolean cMemoryOwn) protected
Referenced by equals(), and getCPtr().
RemoteDestination() [2/2]
com.datalogics.PDFL.RemoteDestination.RemoteDestination (Document doc, int pageNum, String fitType, Rect r, double zoom)
Construct a RemoteDestination.
Parameters
doc Document that the RemoteDestination will be created in.
pageNum Page number of the page in the remote document to display.
fitType Fit Type must be: "XYZ", "Fit", "FitH", "FitV", "FitR", "FitB", "FitBH", or "FitBV".
r Target Rectangle
zoom Zoom level
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.RemoteDestination.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.RemoteDestination.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.RemoteDestination.equals (Object rhs)
finalize()
void com.datalogics.PDFL.RemoteDestination.finalize () protected
getCPtr()
long com.datalogics.PDFL.RemoteDestination.getCPtr (RemoteDestination obj) static protected
Referenced by com.datalogics.PDFL.RemoteGoToAction.RemoteGoToAction(), and com.datalogics.PDFL.RemoteGoToAction.setRemoteDestination().
getDestRect()
Rect com.datalogics.PDFL.RemoteDestination.getDestRect ()
The destination rectangle.
getFitType()
String com.datalogics.PDFL.RemoteDestination.getFitType ()
The fit type.
getPageNumber()
int com.datalogics.PDFL.RemoteDestination.getPageNumber ()
The page number of the destination.
getPDFObject()
PDFObject com.datalogics.PDFL.RemoteDestination.getPDFObject ()
Retrieve the PDFObject representation of this Remote Destination.
getZoom()
double com.datalogics.PDFL.RemoteDestination.getZoom ()
The zoom factor for the destination.
setDestRect()
void com.datalogics.PDFL.RemoteDestination.setDestRect (Rect destRect)
Set the rectangle for the destination.
setFitType()
void com.datalogics.PDFL.RemoteDestination.setFitType (String remoteDestFitType)
Set the fit type for the destination.
setPageNumber()
void com.datalogics.PDFL.RemoteDestination.setPageNumber (int remoteDestPageNum)
Set the page number of the destination (page numbers start at 0)
setZoom()
void com.datalogics.PDFL.RemoteDestination.setZoom (double zoomFactor)
Set the zoom factor for the destination.
toString()
String com.datalogics.PDFL.RemoteDestination.toString ()
Member Data Documentation
NULL_VALUE
final double com.datalogics.PDFL.RemoteDestination.NULL_VALUE static
Constant used for "null" values in destination rectangles or zoom.