Adobe PDF Library Java Documentation
com.datalogics.PDFL.ClosePath Class Reference
Public Member Functions
ClosePath ()
synchronized void delete ()
String toString ()
Protected Member Functions
ClosePath (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (ClosePath obj)
static long getCPtr (Segment obj)
Detailed Description
An operator that completes a vector shape, drawing a line from the first point to the last point. A path is a series of commands that define the boundary of a vector shape. The ClosePath command draws a line from the current location back to its starting point, effectively closing a box or parabolic shape on a page.
Constructor & Destructor Documentation
ClosePath() [1/2]
com.datalogics.PDFL.ClosePath.ClosePath (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
ClosePath() [2/2]
com.datalogics.PDFL.ClosePath.ClosePath ()
Close the current subpath by appending a straight line segment from the current point to the starting point of the subpath. If the current subpath is already closed, ClosePath does nothing.
This segment terminates the current subpath. Appending another segment to the current path begins a new subpath, even if the new segment begins at the endpoint reached by the ClosePath operation.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.ClosePath.delete ()
Reimplemented from com.datalogics.PDFL.Segment.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.ClosePath.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Segment.
finalize()
void com.datalogics.PDFL.ClosePath.finalize () protected
Reimplemented from com.datalogics.PDFL.Segment.
getCPtr() [1/2]
long com.datalogics.PDFL.ClosePath.getCPtr (ClosePath obj) static protected
getCPtr() [2/2]
long com.datalogics.PDFL.Segment.getCPtr (Segment obj) static protected inherited
toString()
String com.datalogics.PDFL.ClosePath.toString ()
Reimplemented from com.datalogics.PDFL.Segment.