Adobe PDF Library Java Documentation
com.datalogics.PDFL.ExponentialFunction Class Reference
Public Member Functions
java.util.List< Double > apply (java.util.List< Double > args)
synchronized void delete ()
ExponentialFunction (java.util.List< Double > domain, int nOutputs, java.util.List< Double > C0, java.util.List< Double > C1, double N)
java.util.List< Double > getC0 ()
java.util.List< Double > getC1 ()
java.util.List< Double > getDomain ()
double getN ()
int getNInputs ()
int getNOutputs ()
java.util.List< Double > getRange ()
void setC0 (java.util.List< Double > C0)
void setC1 (java.util.List< Double > C1)
void setDomain (java.util.List< Double > domain)
void setN (double arg0)
void setRange (java.util.List< Double > range)
String toString ()
Static Public Attributes
static final Function DEFAULT
static final Function IDENTITY
Protected Member Functions
synchronized void delete (Boolean disposing)
ExponentialFunction (long cPtr, boolean cMemoryOwn)
void finalize ()
Static Protected Member Functions
static long getCPtr (ExponentialFunction obj)
static long getCPtr (Function obj)
Detailed Description
An interpolation between two output values as input values vary across a domain. For an Exponential Function, the curve between the two values is determined by the exponent N.
Constructor & Destructor Documentation
ExponentialFunction() [1/2]
com.datalogics.PDFL.ExponentialFunction.ExponentialFunction (long cPtr, boolean cMemoryOwn) protected
Referenced by ExponentialFunction(), and getCPtr().
ExponentialFunction() [2/2]
com.datalogics.PDFL.ExponentialFunction.ExponentialFunction (java.util.List< Double > domain, int nOutputs, java.util.List< Double > C0, java.util.List< Double > C1, double N)
Create an Exponential Function, which is the exponential interpolation between two output values as the input values vary across the domain.
Parameters
domain the domain of the function. 2 elements.
nOutputs the number of outputs of the function
C0 the output value when the input value is 0
C1 the output value when the input value is 1
N the exponential factor, which alters the curve of output values as the input values vary across the domain.
Member Function Documentation
apply()
java.util.List< Double > com.datalogics.PDFL.Function.apply (java.util.List< Double > args) inherited
Apply the function to supplied input values
Parameters
args input values for the function. The number of input values must agree with the number of inputs the function takes.
Returns
a list of the result values from the function
Reimplemented in com.datalogics.PDFL.NamedFunction.
delete() [1/2]
synchronized void com.datalogics.PDFL.ExponentialFunction.delete ()
Reimplemented from com.datalogics.PDFL.Function.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.ExponentialFunction.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Function.
finalize()
void com.datalogics.PDFL.ExponentialFunction.finalize () protected
Reimplemented from com.datalogics.PDFL.Function.
getC0()
java.util.List< Double > com.datalogics.PDFL.ExponentialFunction.getC0 ()
The values for the function when the input is 0.0. There must be the same number of values as the number of outputs in the function.
getC1()
java.util.List< Double > com.datalogics.PDFL.ExponentialFunction.getC1 ()
The values for the function when the input is 1.0. There must be the same number of values as the number of outputs in the function.
getCPtr() [1/2]
long com.datalogics.PDFL.ExponentialFunction.getCPtr (ExponentialFunction obj) static protected
getCPtr() [2/2]
long com.datalogics.PDFL.Function.getCPtr (Function obj) static protected inherited
Referenced by com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), com.datalogics.PDFL.ExtendedGraphicState.setBlackGeneration(), and com.datalogics.PDFL.ExtendedGraphicState.setUndercolorRemoval().
getDomain()
java.util.List< Double > com.datalogics.PDFL.Function.getDomain () inherited
The domain of the function. 2 * m elements, where m is the number of inputs to the function.
Each successive pair of elements gives the minimum and maximum values for one of the inputs.
Input values to the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getN()
double com.datalogics.PDFL.ExponentialFunction.getN ()
The exponential factor N.
getNInputs()
int com.datalogics.PDFL.Function.getNInputs () inherited
The number of inputs to the function.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getNOutputs()
int com.datalogics.PDFL.Function.getNOutputs () inherited
The number of outputs from the function.
Reimplemented in com.datalogics.PDFL.NamedFunction.
getRange()
java.util.List< Double > com.datalogics.PDFL.Function.getRange () inherited
The range of the function. 2 * n elements, where n is the number of outputs from the function.
Each successive pair of elements gives the minimum and maximum values for one of the outputs.
Output values from the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
setC0()
void com.datalogics.PDFL.ExponentialFunction.setC0 (java.util.List< Double > C0)
The values for the function when the input is 0.0. There must be the same number of values as the number of outputs in the function.
setC1()
void com.datalogics.PDFL.ExponentialFunction.setC1 (java.util.List< Double > C1)
The values for the function when the input is 1.0. There must be the same number of values as the number of outputs in the function.
setDomain()
void com.datalogics.PDFL.Function.setDomain (java.util.List< Double > domain) inherited
The domain of the function. 2 * m elements, where m is the number of inputs to the function.
Each successive pair of elements gives the minimum and maximum values for one of the inputs.
Input values to the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
setN()
void com.datalogics.PDFL.ExponentialFunction.setN (double arg0)
The exponential factor N.
setRange()
void com.datalogics.PDFL.Function.setRange (java.util.List< Double > range) inherited
The range of the function. 2 * n elements, where n is the number of outputs from the function.
Each successive pair of elements gives the minimum and maximum values for one of the outputs.
Output values from the function are clamped to these minimum and maximum values.
Reimplemented in com.datalogics.PDFL.NamedFunction.
toString()
String com.datalogics.PDFL.ExponentialFunction.toString ()
A string value describing the function.
Reimplemented from com.datalogics.PDFL.Function.
Member Data Documentation
DEFAULT
final Function com.datalogics.PDFL.Function.DEFAULT static inherited
IDENTITY
final Function com.datalogics.PDFL.Function.IDENTITY static inherited