Adobe PDF Library Java Documentation
com.datalogics.PDFL.Word Class Reference
Public Member Functions
synchronized void delete ()
java.util.EnumSet< WordAttributeFlags > getAttributes ()
java.util.List< Quad > getCharQuads ()
boolean getIsLastWordInRegion ()
java.util.List< Quad > getQuads ()
java.util.List< StyleTransition > getStyleTransitions ()
String getText ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Word (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Word obj)
Detailed Description
A word in a PDF file. Each word contains a sequence of characters in one or more styles (see Style).
Constructor & Destructor Documentation
Word()
com.datalogics.PDFL.Word.Word (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.Word.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.Word.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.Word.finalize () protected
getAttributes()
java.util.EnumSet< WordAttributeFlags > com.datalogics.PDFL.Word.getAttributes ()
Gets a set of summary flags containing information on the types of characters in a word.
Returns
A set of flags containing information on the types of characters in word.
getCharQuads()
java.util.List< Quad > com.datalogics.PDFL.Word.getCharQuads ()
Gets a list of Quads occupied by the individual characters in a word.
Returns
A list containing the Quads found in the words, for each individual character
getCPtr()
long com.datalogics.PDFL.Word.getCPtr (Word obj) static protected
Referenced by com.datalogics.PDFL.WordProc.Call().
getIsLastWordInRegion()
boolean com.datalogics.PDFL.Word.getIsLastWordInRegion ()
Specifies whether this word is the last word in a region as determined by the WordFinder.
This can be useful for determining visual line breaks in tagged PDFs. In tagged PDF documents, WordAttributeFlags.LastWordOnLine is set according to the tags in the document, so that flag cannot be used to determine visual line breaks.
Returns
true if the word is the last word in a region, false if it is not
getQuads()
java.util.List< Quad > com.datalogics.PDFL.Word.getQuads ()
Gets the specified word's quads, specified in user space coordinates.
The quad's height is the height of the font's bounding box, not the height of the tallest character used in the word. The font's bounding box is determined by the glyphs in the font that extend farthest above and below the baseline; it often extends somewhat above the top of 'A' and below the bottom of 'y'.
The quad's width is determined from the characters actually present in the word.
For example, the quads for the words "AWAY" and "away" have the same height, but generally do not have the same width unless the font is a mono-spaced font (a font in which all characters have the same width).
Despite the names of the fields in an Quad (TopLeft for top left, BottomLeft for bottom left, and so forth) the corners of Quad do not necessarily have these positions.
Returns
A list containing the Quads found in the word.
getStyleTransitions()
java.util.List< StyleTransition > com.datalogics.PDFL.Word.getStyleTransitions ()
Gets a list of style transitions for the word. Every word has at least one style transition, at character position zero in the word.
Returns
the list of StyleTransition objects.
getText()
String com.datalogics.PDFL.Word.getText ()
Gets a word's text and also converts ligatures to their constituent characters. The string to return includes any word break characters (such as space characters) that follow the word, but not any that precede the word.
Returns
The text of the Word.