Adobe PDF Library .NET Documentation
Datalogics.PDFL.Container Class Reference
Public Member Functions
new Container Clone ()
new Container Clone (ElementCloneFlags cloneFlags)
Container ColorConvert (Document document, ColorProfile prof, RenderIntent intent, bool embed)
Container ()
Container (string mcTag)
void Dispose ()
override void Dispose (bool disposing)
bool IsCurrentlyVisible (OptionalContentContext occ)
bool IsCurrentlyVisible (OptionalContentContext occ, Content content)
bool MakeVisible (OptionalContentContext occ, Content content)
void Rotate (double theta)
void Scale (double sx, double sy)
void Translate (double tx, double ty)
Properties
Rect BoundingBox [get]
Clip Clip [get, set]
Content Content [get, set]
string MarkedContentTag [get, set]
Matrix Matrix [get, set]
OptionalContentMembershipDict OptionalContentMembershipDict [get, set]
PDFDict PDFDict [get]
Detailed Description
A container class represents a group of elements on a page in a PDF file.
In the PDF file, every container has a set of Marked Content tags, starting with Begin Marked Content (BMC or BDC) and ending with End Marked Content (EMC), so each container has a BMC/EMC or BDC/EMC pair of tags. These tags can be used to define the beginning and end of metadata around objects, providing information about the text and shapes within a PDF file. Containers can be nested within other containers.
Constructor & Destructor Documentation
Container() [1/2]
Datalogics.PDFL.Container.Container ()
Create a new Container.
The new Container has no tag and is not associated with a dictionary.
Referenced by Datalogics.PDFL.Container.Clone(), and Datalogics.PDFL.Container.ColorConvert().
Container() [2/2]
Datalogics.PDFL.Container.Container (string mcTag)
Create a new Container with a given Marked Content Tag.
The new Container has a Marked Content tag but is not associated with a dictionary.
Member Function Documentation
Clone() [1/2]
new Container Datalogics.PDFL.Container.Clone ()
Makes a copy of the container.
Make a copy of an container to obtain a new container that has a distinct set of attributes.
Returns
The copied container.
References Datalogics.PDFL.Container.Container().
Clone() [2/2]
new Container Datalogics.PDFL.Container.Clone (ElementCloneFlags cloneFlags)
Makes a copy of the container.
Make a copy of an container to obtain a new container that has a distinct set of attributes.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied container.
References Datalogics.PDFL.Container.Container().
ColorConvert()
Container Datalogics.PDFL.Container.ColorConvert (Document document, ColorProfile prof, RenderIntent intent, bool embed)
Applies the specified ICC ColorProfile to the objects in the Container
Parameters
document The document the element belongs to.
prof The ICC ColorProfile to be applied.
intent The ICC Rendering Intent for the ColorProfile
embed If true, embed the color space and make the objects calibrated. If it is false and the target profile is CMYK, RGB, or Gray, the colors space of the resulting objects, after conversion, will be DeviceCMYK, DeviceRGB, or DeviceGray, respectively.
Returns
A new Container with the applied ICC ColorProfile.
References Datalogics.PDFL.Container.Container().
Dispose() [1/2]
void Datalogics.PDFL.Element.Dispose () inherited
Dispose() [2/2]
override void Datalogics.PDFL.Container.Dispose (bool disposing) virtual
Reimplemented from Datalogics.PDFL.Element.
IsCurrentlyVisible() [1/2]
bool Datalogics.PDFL.Container.IsCurrentlyVisible (OptionalContentContext occ)
Tests whether a container is visible in a given optional content context, considering the current ON-OFF states of the optional-content groups in the optional-content dictionary (OCMD) and the dictionary's visibility policy.
If the container occurs more than once within the content, this method only checks the visibility of the first occurrence of the container.
This method determines visibility without considering the visbility of the Content object that the container belongs to. To determine the visibility of a container while taking the Content's visibility into considderation, use the alternate version of this method.
Returns
true if the container is currently visible.
IsCurrentlyVisible() [2/2]
bool Datalogics.PDFL.Container.IsCurrentlyVisible (OptionalContentContext occ, Content content)
Tests whether a container is visible in a given optional content context and content.
If the container occurs more than once within the content, this method only checks the visibility of the first occurrence of the container.
Returns
true if the container is currently visible.
MakeVisible()
bool Datalogics.PDFL.Container.MakeVisible (OptionalContentContext occ, Content content)
Makes a container visible in a given optional content context and content by manipulating the ON-OFF states of the optional content groups.
Parameters
occ The optional content context in which the container is made visible.
content The content containing the container.
Returns
true if the container is successfully made visible in the given context and content, false otherwise
Rotate()
void Datalogics.PDFL.Element.Rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Scale()
void Datalogics.PDFL.Element.Scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
Translate()
void Datalogics.PDFL.Element.Translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Property Documentation
BoundingBox
Rect Datalogics.PDFL.Element.BoundingBox get inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
Clip
Clip Datalogics.PDFL.Element.Clip get set inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
Content
Content Datalogics.PDFL.Container.Content get set
Obtain the content of a container.
MarkedContentTag
string Datalogics.PDFL.Container.MarkedContentTag get set
The container's Marked Content Tag.
Matrix
Matrix Datalogics.PDFL.Element.Matrix get set inherited
The transformation matrix for the element.
Referenced by Datalogics.PDFL.Text.GetTextMatrixForCharacter(), and Datalogics.PDFL.Text.GetTextMatrixForTextRun().
OptionalContentMembershipDict
OptionalContentMembershipDict Datalogics.PDFL.Container.OptionalContentMembershipDict get set
The OptionalContentMembershipDict property for this Container.
Setting this property will attach the Container to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Container is detached from any OptionalContentMembershipDict.
Returns
the OptionalContentMembershipDict
PDFDict
PDFDict Datalogics.PDFL.Container.PDFDict get
Retrieve the PDFObject representation of this object