Adobe PDF Library .NET Documentation
Datalogics.PDFL.Group Class Reference
Public Member Functions
new Group Clone ()
new Group Clone (ElementCloneFlags cloneFlags)
Group ColorConvert (Document document, ColorProfile prof, RenderIntent intent, bool embed)
void Dispose ()
override void Dispose (bool disposing)
Group ()
Group (Content content)
void Rotate (double theta)
void Scale (double sx, double sy)
void Translate (double tx, double ty)
Properties
Rect BoundingBox [get]
Clip Clip [get, set]
Content Content [get, set]
Matrix Matrix [get, set]
Detailed Description
A set of elements to be used within a PDF document.
A Group represents objects in a content object, but it resides in memory.
Therefore the group has no state and is not represented in any way in a PDF content stream. When used in a Clip, a group is used to associate Text objects into a single clipping object.
Constructor & Destructor Documentation
Group() [1/2]
Datalogics.PDFL.Group.Group ()
Create a new Group.
Referenced by Datalogics.PDFL.Group.Clone(), and Datalogics.PDFL.Group.ColorConvert().
Group() [2/2]
Datalogics.PDFL.Group.Group (Content content)
Create a Group with the given Content.
Parameters
content The new Content of the group.
Member Function Documentation
Clone() [1/2]
new Group Datalogics.PDFL.Group.Clone ()
Makes a copy of the group.
Make a copy of an group to obtain a new group that has a distinct set of attributes.
Returns
The copied group.
References Datalogics.PDFL.Group.Group().
Clone() [2/2]
new Group Datalogics.PDFL.Group.Clone (ElementCloneFlags cloneFlags)
Makes a copy of the group.
Make a copy of an group to obtain a new group that has a distinct set of attributes.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied group.
References Datalogics.PDFL.Group.Group().
ColorConvert()
Group Datalogics.PDFL.Group.ColorConvert (Document document, ColorProfile prof, RenderIntent intent, bool embed)
Applies the specified ICC ColorProfile to the elements in the Group object
Parameters
document The document the element belongs to.
prof The ICC ColorProfile to be applied.
intent The ICC Rendering Intent for the ColorProfile
embed If true, embed the color space and make the object calibrated. If it is false and the target profile is CMYK, RGB, or Gray, the colors space of the resulting objects, after conversion, will be DeviceCMYK, DeviceRGB, or DeviceGray, respectively.
Returns
A new Group object with the applied ICC ColorProfile.
References Datalogics.PDFL.Group.Group().
Dispose() [1/2]
void Datalogics.PDFL.Element.Dispose () inherited
Dispose() [2/2]
override void Datalogics.PDFL.Group.Dispose (bool disposing) virtual
Reimplemented from Datalogics.PDFL.Element.
Rotate()
void Datalogics.PDFL.Element.Rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Scale()
void Datalogics.PDFL.Element.Scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
Translate()
void Datalogics.PDFL.Element.Translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Property Documentation
BoundingBox
Rect Datalogics.PDFL.Element.BoundingBox get inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
Clip
Clip Datalogics.PDFL.Element.Clip get set inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
Content
Content Datalogics.PDFL.Group.Content get set
Obtain the content of a Group.
Matrix
Matrix Datalogics.PDFL.Element.Matrix get set inherited
The transformation matrix for the element.
Referenced by Datalogics.PDFL.Text.GetTextMatrixForCharacter(), and Datalogics.PDFL.Text.GetTextMatrixForTextRun().