Java API Reference: com.datalogics.PDFL.PageImageParams Class Reference
com.datalogics.PDFL.PageImageParams Class Reference
Public Member Functions
synchronized void delete ()
boolean getBlackPointCompensation ()
boolean getBypassCopyPerm ()
boolean getCalibrateDeviceSpacesWhenPrinting ()
double getHorizontalResolution ()
ColorProfile getICCProfile ()
String getICCProfileCustomPath ()
ColorSpace getImageColorSpace ()
java.util.EnumSet< DrawFlags > getPageDrawFlags ()
int getPixelHeight ()
int getPixelWidth ()
RenderIntent getRenderIntent ()
java.util.EnumSet< SmoothFlags > getSmoothing ()
boolean getThinLineHeuristics ()
boolean getUseDeviceNForImageSeparations ()
double getVerticalResolution ()
PageImageParams ()
PageImageParams (ColorSpace ColorSpace, java.util.EnumSet< SmoothFlags > Smoothing, int PixelWidth, int PixelHeight, double HorizontalResolution, double VerticalResolution, java.util.EnumSet< DrawFlags > PageDrawFlags)
void setBlackPointCompensation (boolean arg0)
void setBypassCopyPerm (boolean value)
void setCalibrateDeviceSpacesWhenPrinting (boolean value)
void setHorizontalResolution (double arg0)
void setICCProfile (ColorProfile colorProfile)
void setICCProfileCustomPath (String colorProfilePath)
void setImageColorSpace (ColorSpace cs)
void setPageDrawFlags (java.util.EnumSet< DrawFlags > arg0)
void setPixelHeight (int arg0)
void setPixelWidth (int arg0)
void setRenderIntent (RenderIntent arg0)
void setSmoothing (java.util.EnumSet< SmoothFlags > smoothflag)
void setThinLineHeuristics (boolean arg0)
void setUseDeviceNForImageSeparations (boolean value)
void setVerticalResolution (double arg0)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PageImageParams (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PageImageParams obj)
Detailed Description
Used to manage converting a PDF page to an image. The Page Image Parameters are a set of parameters used to control converting a PDF page to an image, such as a PNG, JPG, or BMP. The parameters include pixel height & width, color space, resolution, so on.
Constructor & Destructor Documentation
PageImageParams() [1/3]
com.datalogics.PDFL.PageImageParams.PageImageParams (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
PageImageParams() [2/3]
com.datalogics.PDFL.PageImageParams.PageImageParams ()
PageImageParams() [3/3]
com.datalogics.PDFL.PageImageParams.PageImageParams (ColorSpace ColorSpace, java.util.EnumSet< SmoothFlags > Smoothing, int PixelWidth, int PixelHeight, double HorizontalResolution, double VerticalResolution, java.util.EnumSet< DrawFlags > PageDrawFlags)
Set up the parameters for rendering a PDF page to an image. Horizontal and Vertical Resolution have to be either both zero or both non-zero.
Parameters
ColorSpace The desired color space for the image, DEVICERGB, DEVICECMYK or DEVICEGRAY only.
Smoothing Indicates what parts of PDF Page (text, image, art, none) are to be smoothed in rendering to an image. Note these flags can be or'd together
PixelWidth The desired witdth in pixels of the output image.
PixelHeight The desired height in pixels of the output image.
HorizontalResolution The desired horizontal resolution in pixels/inch of the output image. If you pass in 0.0, 300.0 dpi is used.
VerticalResolution The desired vertical resolution in pixels/inch of the output image. If you pass in 0.0, 300.0 dpi is used.
PageDrawFlags An OR of the flags from DrawFlags which control how the PDF page is to be drawn.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.PageImageParams.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.PageImageParams.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.PageImageParams.finalize () protected
getBlackPointCompensation()
boolean com.datalogics.PDFL.PageImageParams.getBlackPointCompensation ()
The BlackPointCompensation desired (default is true if not explicitly set)
getBypassCopyPerm()
boolean com.datalogics.PDFL.PageImageParams.getBypassCopyPerm ()
The BypassCopyPerm allows to bypass copy permitions.
Returns
true if this option is turned on.
getCalibrateDeviceSpacesWhenPrinting()
boolean com.datalogics.PDFL.PageImageParams.getCalibrateDeviceSpacesWhenPrinting ()
Sets if Device spaces should be treated as calibrated to the associated working profile (when true), otherwise it treats them as uncalibrated (when false) when printing.
Returns
true if this option is turned on.
getCPtr()
long com.datalogics.PDFL.PageImageParams.getCPtr (PageImageParams obj) static protected
Referenced by com.datalogics.PDFL.Page.getImage(), com.datalogics.PDFL.Page.getImage(), com.datalogics.PDFL.Page.getImageSeparations(), com.datalogics.PDFL.Page.getImageSeparations(), com.datalogics.PDFL.Page.getOutputPreviewImage(), and com.datalogics.PDFL.Page.getOutputPreviewImage().
getHorizontalResolution()
double com.datalogics.PDFL.PageImageParams.getHorizontalResolution ()
The desired horizontal resolution in pixels/inch of the output image.
getICCProfile()
ColorProfile com.datalogics.PDFL.PageImageParams.getICCProfile ()
Gets the ICC Profile of the colorspace to be used for rendering from a known value.
NOTE: The ICCProfileCustomPath must not be set for this property to be used. The profile must be compatible with the ColorSpace property value, which can't be set to ICCBased either.
getICCProfileCustomPath()
String com.datalogics.PDFL.PageImageParams.getICCProfileCustomPath ()
Gets the ICC Profile of the colorspace to be used for rendering from a custom file path.
NOTE: The ICCProfile is ignored when this property is a non-empty string. The profile must be compatible with the ColorSpace property value, which can't be set to ICCBased either.
getImageColorSpace()
ColorSpace com.datalogics.PDFL.PageImageParams.getImageColorSpace ()
The ColorSpace used in exporting a PDF page to an image
Referenced by com.datalogics.PDFL.Page.makeBufferedImage().
getPageDrawFlags()
java.util.EnumSet< DrawFlags > com.datalogics.PDFL.PageImageParams.getPageDrawFlags ()
the DrawFlags used or rendering a PDF page to an image.
getPixelHeight()
int com.datalogics.PDFL.PageImageParams.getPixelHeight ()
The height in pixels of the image to be created from a PDF page.
getPixelWidth()
int com.datalogics.PDFL.PageImageParams.getPixelWidth ()
The width in pixels of the image to be created from a PDF page.
getRenderIntent()
RenderIntent com.datalogics.PDFL.PageImageParams.getRenderIntent ()
The RenderIntent used to specify color translation for colors outside gamut of the color profile used.
getSmoothing()
java.util.EnumSet< SmoothFlags > com.datalogics.PDFL.PageImageParams.getSmoothing ()
The SmoothFlags used in exporting a PDF page to an image
getThinLineHeuristics()
boolean com.datalogics.PDFL.PageImageParams.getThinLineHeuristics ()
The ThinLineHeuristics used to determine whether thin lines will be fattened non-linearly or the stroke adjust will be applied to thin rectangles. return true if thin line heuristics are applied, false otherwise.
getUseDeviceNForImageSeparations()
boolean com.datalogics.PDFL.PageImageParams.getUseDeviceNForImageSeparations ()
Gets the UseDeviceNForImageSeparations setting, which indicates when the GetImageSeparations() method is called if a DeviceN colorspace will be used for rasterization.When false, if only Process colorants are provided to GetImageSeparations() then it's rendered using DeviceCMYK.When true, then it's rendered using DeviceN.
Returns
true if this option is turned on. NOTE: This member is only applicable when calling the GetImageSeparations() method, only when Colorants used are only Process.
getVerticalResolution()
double com.datalogics.PDFL.PageImageParams.getVerticalResolution ()
The desired vertical resolution in pixels/inch of the output image.
setBlackPointCompensation()
void com.datalogics.PDFL.PageImageParams.setBlackPointCompensation (boolean arg0)
setBypassCopyPerm()
void com.datalogics.PDFL.PageImageParams.setBypassCopyPerm (boolean value)
setCalibrateDeviceSpacesWhenPrinting()
void com.datalogics.PDFL.PageImageParams.setCalibrateDeviceSpacesWhenPrinting (boolean value)
setHorizontalResolution()
void com.datalogics.PDFL.PageImageParams.setHorizontalResolution (double arg0)
setICCProfile()
void com.datalogics.PDFL.PageImageParams.setICCProfile (ColorProfile colorProfile)
Sets the ICC Profile of the colorspace to be used for rendering to a known value.
NOTE: The ICCProfileCustomPath must not be set for this property to be used. The profile must be compatible with the ColorSpace property value, which can't be set to ICCBased either.
setICCProfileCustomPath()
void com.datalogics.PDFL.PageImageParams.setICCProfileCustomPath (String colorProfilePath)
Sets the ICC Profile of the colorspace to be used for rendering from a custom file path.
NOTE: The ICCProfile is ignored when this property is a non-empty string. The profile must be compatible with the ColorSpace property value, which can't be set to ICCBased either.
setImageColorSpace()
void com.datalogics.PDFL.PageImageParams.setImageColorSpace (ColorSpace cs)
setPageDrawFlags()
void com.datalogics.PDFL.PageImageParams.setPageDrawFlags (java.util.EnumSet< DrawFlags > arg0)
setPixelHeight()
void com.datalogics.PDFL.PageImageParams.setPixelHeight (int arg0)
setPixelWidth()
void com.datalogics.PDFL.PageImageParams.setPixelWidth (int arg0)
setRenderIntent()
void com.datalogics.PDFL.PageImageParams.setRenderIntent (RenderIntent arg0)
setSmoothing()
void com.datalogics.PDFL.PageImageParams.setSmoothing (java.util.EnumSet< SmoothFlags > smoothflag)
setThinLineHeuristics()
void com.datalogics.PDFL.PageImageParams.setThinLineHeuristics (boolean arg0)
setUseDeviceNForImageSeparations()
void com.datalogics.PDFL.PageImageParams.setUseDeviceNForImageSeparations (boolean value)
Sets the UseDeviceNForImageSeparations setting, which indicates when GetImageSeparations() is called if a DeviceN colorspace will be used for rasterization.When false, if only Process colorants are provided to GetImageSeparations() then it's rendered using DeviceCMYK.When true, then it's rendered using DeviceN.NOTE: This member is only applicable when calling the GetImageSeparations() method, only when Colorants used are only Process.
setVerticalResolution()
void com.datalogics.PDFL.PageImageParams.setVerticalResolution (double arg0)