Java API Reference: com.datalogics.PDFL.FreeTextAnnotation Class Reference
com.datalogics.PDFL.FreeTextAnnotation Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
FreeTextAnnotation (Page page, Rect initialRect, String defaultAppearance)
FreeTextAnnotation (Page page, Rect initialRect, String defaultAppearance, int addAfter)
Form generateAppearance ()
double getAnnotationFeatureLevel ()
String getBorderStyle ()
java.util.List< Double > getBorderStyleDashPattern ()
double getBorderStyleWidth ()
Color getColor ()
String getContents ()
String getDefaultAppearance ()
java.util.EnumSet< AnnotationFlags > getFlags ()
String getFontFace ()
double getFontSize ()
Color getInteriorColor ()
Form getNormalAppearance ()
double getOpacity ()
OptionalContentMembershipDict getOptionalContentMembershipDict ()
PDFDict getPDFDict ()
HorizontalAlignment getQuadding ()
Rect getRect ()
String getSubtype ()
Color getTextColor ()
String getTitle ()
boolean hasRichTextData ()
boolean isCurrentlyVisible (OptionalContentContext occ)
void setAnnotationFeatureLevel (double featureLevel)
void setBorderStyle (String style)
void setBorderStyleDashPattern (java.util.List< Double > dashPattern)
void setBorderStyleWidth (double width)
void setColor (Color arg0)
void setContents (String arg0)
void setDefaultAppearance (String arg0)
void setFlags (java.util.EnumSet< AnnotationFlags > arg0)
void setFontFace (String fontName)
void setFontSize (double fontSize)
void setInteriorColor (Color color)
void setNormalAppearance (Form form)
void setOpacity (double opacityValue)
void setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd)
void setQuadding (HorizontalAlignment quadding)
void setRect (Rect rect)
void setTextColor (Color textColor)
void setTitle (String title)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
FreeTextAnnotation (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Annotation obj)
static long getCPtr (FreeTextAnnotation obj)
Detailed Description
The free text annotation allows a user to place text directly on a PDF page. An ordinary text annotation appears in a pop up window, and is attached to an icon; it represents a note added to a PDF file, and can be opened for viewing, or closed. But a free text annotation always appears open on the page. A free text annotation can be included anywhere in a PDF file by specifying the location and the CallOutLine points.
Constructor & Destructor Documentation
FreeTextAnnotation() [1/3]
com.datalogics.PDFL.FreeTextAnnotation.FreeTextAnnotation (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
FreeTextAnnotation() [2/3]
com.datalogics.PDFL.FreeTextAnnotation.FreeTextAnnotation (Page page, Rect initialRect, String defaultAppearance)
Create a new FreeTextAnnotation at the end of a page's annotation array. To create a FreeTextAnnotation and place it elsewhere in the page's annotation array, use the version of the constructor that takes an array position.
Parameters
page The page to which the FreeTextAnnotation is added.
initialRect A rectangle specifying the annotation's bounds, specified in user space coordinates.
defaultAppearance The default appearance string to be used in formatting the text.
FreeTextAnnotation() [3/3]
com.datalogics.PDFL.FreeTextAnnotation.FreeTextAnnotation (Page page, Rect initialRect, String defaultAppearance, int addAfter)
Create a new FreeTextAnnotation at a specific index in the page's annotation array.
Parameters
page The page to which the annotation is added.
initialRect A rectangle specifying the annotation's bounds, specified in user space coordinates.
defaultAppearance The default appearance string to be used in formatting the text.
addAfter Where to add the annotation in the page's annotation array. To add the annotation to the end of the array, pass a value of -2 or use the alternate version of this constructor that does not take an index (this is generally what you should do unless you have a need to place the annotation at a special location in the array). Passing a value of -1 adds the annotation to the beginning of the array. Passing other negative values produces undefined results.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.FreeTextAnnotation.delete ()
Reimplemented from com.datalogics.PDFL.Annotation.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.FreeTextAnnotation.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Annotation.
equals()
boolean com.datalogics.PDFL.Annotation.equals (Object rhs) inherited
finalize()
void com.datalogics.PDFL.FreeTextAnnotation.finalize () protected
Reimplemented from com.datalogics.PDFL.Annotation.
generateAppearance()
Form com.datalogics.PDFL.FreeTextAnnotation.generateAppearance ()
Generate a new appearance stream with the current annotation properties.
The resulting Form can then be used to set the annotation's appearance, such as by calling SetNormalAppearance.
Reimplemented from com.datalogics.PDFL.Annotation.
getAnnotationFeatureLevel()
double com.datalogics.PDFL.FreeTextAnnotation.getAnnotationFeatureLevel ()
The minimum PDF version necessary to support the features used in this annotation.
Reimplemented from com.datalogics.PDFL.Annotation.
getBorderStyle()
String com.datalogics.PDFL.FreeTextAnnotation.getBorderStyle ()
The border style.
Can be one of:
S - Solid
D - Dashed. The dash pattern is specified as an array (see DashPattern)
B - Beveled
I - Inset
U - Underline
Other border styles may be defined in the future. Default is "S"
getBorderStyleDashPattern()
java.util.List< Double > com.datalogics.PDFL.FreeTextAnnotation.getBorderStyleDashPattern ()
An array defining a pattern of dashes and gaps to be used in drawing a dashed border (border style D).
The dash array is a series of numbers that specify the lengths of alternating dashes and gaps. Lengths must be nonnegative, and are expressed in user space units.
Default value is [3]
getBorderStyleWidth()
double com.datalogics.PDFL.FreeTextAnnotation.getBorderStyleWidth ()
The border width in points.
If this value is 0, no border is drawn. The default is 1.0.
getColor()
Color com.datalogics.PDFL.FreeTextAnnotation.getColor ()
(Deprecated, function may be removed in future, use GetInteriorColor instead) The color of the annotation. This method the same to the GetInteriorColor method.
Reimplemented from com.datalogics.PDFL.Annotation.
getContents()
String com.datalogics.PDFL.Annotation.getContents () inherited
The text to be displayed for the annotation or, if this type of annotation does not display text, an alternate description of the annotation's contents in human-readable form.
getCPtr() [1/2]
long com.datalogics.PDFL.Annotation.getCPtr (Annotation obj) static protected inherited
Referenced by com.datalogics.PDFL.Page.addAnnotation().
getCPtr() [2/2]
long com.datalogics.PDFL.FreeTextAnnotation.getCPtr (FreeTextAnnotation obj) static protected
getDefaultAppearance()
String com.datalogics.PDFL.FreeTextAnnotation.getDefaultAppearance ()
The default appearance string to be used in formatting the text.
getFlags()
java.util.EnumSet< AnnotationFlags > com.datalogics.PDFL.Annotation.getFlags () inherited
The flags for the annotation.
getFontFace()
String com.datalogics.PDFL.FreeTextAnnotation.getFontFace ()
Get Font face for the text
Returns
current Font face
getFontSize()
double com.datalogics.PDFL.FreeTextAnnotation.getFontSize ()
Get font size for the text;
Returns
current font size
getInteriorColor()
Color com.datalogics.PDFL.Annotation.getInteriorColor () inherited
The interior color with which to fill the annotation's line endings.
The color of the line itself can be retrieved from Annotation.Color.
getNormalAppearance()
Form com.datalogics.PDFL.Annotation.getNormalAppearance () inherited
getOpacity()
double com.datalogics.PDFL.Annotation.getOpacity () inherited
The optional constant opacity value that shall be used in painting a Markup annotation.
Opacity is a range from 0.0 (fully transparent) to 1.0 (fully opaque).
getOptionalContentMembershipDict()
OptionalContentMembershipDict com.datalogics.PDFL.Annotation.getOptionalContentMembershipDict () inherited
The OptionalContentMembershipDict property for this Annotation.
Setting this property will attach the Annotation to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Annotation is detached from any OptionalContentMembershipDict.
Returns
the OptionalContentMembershipDict
getPDFDict()
PDFDict com.datalogics.PDFL.Annotation.getPDFDict () inherited
Retrieve the PDFObject representation of this object
getQuadding()
HorizontalAlignment com.datalogics.PDFL.FreeTextAnnotation.getQuadding ()
A code specifiying the form of quadding (justification) to be used in displaying the annotation's text.
getRect()
Rect com.datalogics.PDFL.Annotation.getRect () inherited
The size and location of the annotation on its page
getSubtype()
String com.datalogics.PDFL.Annotation.getSubtype () inherited
The annotation's subtype
getTextColor()
Color com.datalogics.PDFL.FreeTextAnnotation.getTextColor ()
The text color which used for drawing text
Returns
color Freetext Annotation's text
getTitle()
String com.datalogics.PDFL.Annotation.getTitle () inherited
The title of the annotation.
hasRichTextData()
boolean com.datalogics.PDFL.Annotation.hasRichTextData () inherited
Checks the annotation for Rich Text String content (PDFReference 1.7 Section 8.6.2). Annotations that contain Rich Text String content and do not have a normal appearance set will not be visible when rendering the page.
isCurrentlyVisible()
boolean com.datalogics.PDFL.Annotation.isCurrentlyVisible (OptionalContentContext occ) inherited
Tests whether an annotation is visible in a given optional content context, considering the current ON-OFF states of the optional-content groups in the optional-content dictionary (OCMD) and the dictionary's visibility policy.
If the annotation occurs more than once within the content, this method only checks the visibility of the first occurrence of the annotation.
This method determines visibility without considering the visbility of the Content object that the annotation belongs to. To determine the visibility of an annotation while taking the Content's visibility into consideration, use the alternate version of this method.
Returns
true if the annotation is currently visible.
setAnnotationFeatureLevel()
void com.datalogics.PDFL.FreeTextAnnotation.setAnnotationFeatureLevel (double featureLevel)
Removes features not supported in the supplied version number.
Reimplemented from com.datalogics.PDFL.Annotation.
setBorderStyle()
void com.datalogics.PDFL.FreeTextAnnotation.setBorderStyle (String style)
The border style.
Can be one of:
S - Solid
D - Dashed. The dash pattern is specified as an array (see DashPattern)
B - Beveled
I - Inset
U - Underline
Other border styles may be defined in the future. Default is "S"
setBorderStyleDashPattern()
void com.datalogics.PDFL.FreeTextAnnotation.setBorderStyleDashPattern (java.util.List< Double > dashPattern)
An array defining a pattern of dashes and gaps to be used in drawing a dashed border (border style D).
The dash array is a series of numbers that specify the lengths of alternating dashes and gaps. Lengths must be nonnegative, and are expressed in user space units.
Default value is [3]
setBorderStyleWidth()
void com.datalogics.PDFL.FreeTextAnnotation.setBorderStyleWidth (double width)
The border width in points.
If this value is 0, no border is drawn. The default is 1.0.
setColor()
void com.datalogics.PDFL.FreeTextAnnotation.setColor (Color arg0)
(Deprecated, function may be removed in future, use SetInteriorColor instead) The color of the annotation. This method the same to the SetInteriorColor method.
Reimplemented from com.datalogics.PDFL.Annotation.
setContents()
void com.datalogics.PDFL.Annotation.setContents (String arg0) inherited
The text to be displayed for the annotation or, if this type of annotation does not display text, an alternate description of the annotation's contents in human-readable form.
setDefaultAppearance()
void com.datalogics.PDFL.FreeTextAnnotation.setDefaultAppearance (String arg0)
The default appearance string to be used in formatting the text.
setFlags()
void com.datalogics.PDFL.Annotation.setFlags (java.util.EnumSet< AnnotationFlags > arg0) inherited
The flags for the annotation.
setFontFace()
void com.datalogics.PDFL.FreeTextAnnotation.setFontFace (String fontName)
Set Font face for the text
setFontSize()
void com.datalogics.PDFL.FreeTextAnnotation.setFontSize (double fontSize)
Set font size for text
setInteriorColor()
void com.datalogics.PDFL.Annotation.setInteriorColor (Color color) inherited
The interior color with which to fill the annotation's line endings.
Only RGB colors are allowed.
The color of the line itself can be retrieved from Annotation.Color.
setNormalAppearance()
void com.datalogics.PDFL.Annotation.setNormalAppearance (Form form) inherited
setOpacity()
void com.datalogics.PDFL.Annotation.setOpacity (double opacityValue) inherited
The optional constant opacity value that shall be used in painting a Markup annotation.
Opacity is a range from 0.0 (fully transparent) to 1.0 (fully opaque).
setOptionalContentMembershipDict()
void com.datalogics.PDFL.Annotation.setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd) inherited
The OptionalContentMembershipDict property for this Annotation.
Setting this property will attach the Annotation to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Annotation is detached from any OptionalContentMembershipDict.
Parameters
ocmd the OptionalContentMembershipDict
setQuadding()
void com.datalogics.PDFL.FreeTextAnnotation.setQuadding (HorizontalAlignment quadding)
A code specifiying the form of quadding (justification) to be used in displaying the annotation's text.
setRect()
void com.datalogics.PDFL.Annotation.setRect (Rect rect) inherited
The size and location of the annotation on its page
setTextColor()
void com.datalogics.PDFL.FreeTextAnnotation.setTextColor (Color textColor)
The text color which used for drawing text
setTitle()
void com.datalogics.PDFL.Annotation.setTitle (String title) inherited
The title of the annotation.
toString()
String com.datalogics.PDFL.Annotation.toString () inherited