Java API Reference: com.datalogics.PDFL.EncodingInfo Class Reference
com.datalogics.PDFL.EncodingInfo Class Reference
Public Member Functions
synchronized void delete ()
java.util.List< String > getCharNames ()
String getEncodingName ()
Protected Member Functions
synchronized void delete (Boolean disposing)
EncodingInfo (long cPtr, boolean cMemoryOwn)
void finalize ()
Static Protected Member Functions
static long getCPtr (EncodingInfo obj)
Detailed Description
Represents a font's encoding data. Encoding is the process that transforms a set of Unicode characters into a series of bytes.
With PDF files, Unicode values are used to represent individual character within a font set. Unicode assigns a symbolic value to represent every single character in a wide variety of fonts, scripts, and languages.
For example, the Unicode value "U+0041" refers to the capital letter "A" in a Latin script.
The EncodingInfo Class is used to provide basic information about an encoding. For example, EncodingInfo could be used to provide just the code name and description for a Unicode standard font or language encoding, like this:
IBM860 (Portuguese, DOS)
ibm861 (Icelandic, DOS)
DOS-862 (Hebrew, DOS)
IBM863 (French Canadian, DOS)
IBM864 (Arabic, 864)
iso-8859-9 (Turkish, ISO)
iso-8859-13 (Estonian, ISO)
(c)2007 Datalogics Inc. Datalogics is a registered trademark of Datalogics Incorporated. Other company and brand, product and service names are for identification purposes only and may be trademarks or registered trademarks of their respective holders. Data is subject to change without notice.
Constructor & Destructor Documentation
EncodingInfo()
com.datalogics.PDFL.EncodingInfo.EncodingInfo (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.EncodingInfo.delete ()
Destructor.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.EncodingInfo.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.EncodingInfo.finalize () protected
Destructor.
getCharNames()
java.util.List< String > com.datalogics.PDFL.EncodingInfo.getCharNames ()
container for differences array/character names.
getCPtr()
long com.datalogics.PDFL.EncodingInfo.getCPtr (EncodingInfo obj) static protected
getEncodingName()
String com.datalogics.PDFL.EncodingInfo.getEncodingName ()
Return the encoding name/cmap name for the font eg:.
WinAnsiEncoding
MacRomanEncoding
Identity-H