Java API Reference: com.datalogics.PDFL.TextRun Class Reference
com.datalogics.PDFL.TextRun Class Reference
Public Member Functions
Element clone ()
Element clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
synchronized void delete ()
double getAdvance ()
Rect getBoundingBox ()
Clip getClip ()
Font getFont ()
GraphicState getGraphicState ()
Matrix getMatrix ()
byte[] getRawText ()
String getText ()
TextState getTextState ()
void rotate (double theta)
void scale (double sx, double sy)
void setClip (Clip clip)
void setFont (Font font)
void setGraphicState (GraphicState gstate)
void setMatrix (Matrix matrix)
void setText (String text)
TextRun (String text, Font font, GraphicState gstate, TextState tstate, Matrix matrix)
void translate (double tx, double ty)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
TextRun (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Element obj)
static long getCPtr (TextRun obj)
Detailed Description
Represents one or more contiguous characters in a text object. All the characters contained within a text run have the same style, color, font, and size.
Constructor & Destructor Documentation
TextRun() [1/2]
com.datalogics.PDFL.TextRun.TextRun (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
TextRun() [2/2]
com.datalogics.PDFL.TextRun.TextRun (String text, Font font, GraphicState gstate, TextState tstate, Matrix matrix)
Member Function Documentation
clone() [1/2]
Element com.datalogics.PDFL.Element.clone () inherited
Makes a copy of the element.
Make a copy of an element to obtain a new element that has a distinct set of attributes.
Note: TextRun objects may not be cloned.
Returns
The copied element.
Reimplemented in com.datalogics.PDFL.Container, com.datalogics.PDFL.Form, com.datalogics.PDFL.Group, com.datalogics.PDFL.Image, com.datalogics.PDFL.Path, and com.datalogics.PDFL.Text.
clone() [2/2]
Element com.datalogics.PDFL.Element.clone (java.util.EnumSet< ElementCloneFlags > cloneFlags) inherited
Makes a copy of the element.
Make a copy of an element to obtain a new element that has a distinct set of attributes.
Note: TextRun objects may not be cloned.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied element.
Reimplemented in com.datalogics.PDFL.Container, com.datalogics.PDFL.Group, com.datalogics.PDFL.Image, com.datalogics.PDFL.Path, and com.datalogics.PDFL.Text.
delete() [1/2]
synchronized void com.datalogics.PDFL.TextRun.delete ()
Reimplemented from com.datalogics.PDFL.Element.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.TextRun.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Element.
finalize()
void com.datalogics.PDFL.TextRun.finalize () protected
Reimplemented from com.datalogics.PDFL.Element.
getAdvance()
double com.datalogics.PDFL.TextRun.getAdvance ()
Deprecated, use Text.GetAdvanceForTextRun(int textRunIndex) instead. This version does not indicate the direction of the advance width.
The advance width of this run of text.
The advnace width is the amount by which the current point advances when the text run is drawn. Advance width is returned in user space.
getBoundingBox()
Rect com.datalogics.PDFL.Element.getBoundingBox () inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
getClip()
Clip com.datalogics.PDFL.Element.getClip () inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
getCPtr() [1/2]
long com.datalogics.PDFL.Element.getCPtr (Element obj) static protected inherited
Referenced by com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Content.addElement(), com.datalogics.PDFL.Content.addElement(), and com.datalogics.PDFL.Content.Content().
getCPtr() [2/2]
long com.datalogics.PDFL.TextRun.getCPtr (TextRun obj) static protected
Referenced by com.datalogics.PDFL.Text.addRun(), and com.datalogics.PDFL.Text.addRun().
getFont()
Font com.datalogics.PDFL.TextRun.getFont ()
The font of this TextRun.
getGraphicState()
GraphicState com.datalogics.PDFL.TextRun.getGraphicState ()
Get the graphic state of the text run.
May return null if this element does not have a GraphicState.
getMatrix()
Matrix com.datalogics.PDFL.Element.getMatrix () inherited
The transformation matrix for the element.
getRawText()
byte[] com.datalogics.PDFL.TextRun.getRawText ()
The raw, un-interpreted text as char codes of this TextRun.
getText()
String com.datalogics.PDFL.TextRun.getText ()
The text of this TextRun.
getTextState()
TextState com.datalogics.PDFL.TextRun.getTextState ()
The TextState of this TextRun.
rotate()
void com.datalogics.PDFL.Element.rotate (double theta) inherited
Rotate an element by T degrees counterclockwise units using the matrix [ cos T sin T -sin T cos T 0 0 ].
Reimplemented in com.datalogics.PDFL.Image.
scale()
void com.datalogics.PDFL.Element.scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
setClip()
void com.datalogics.PDFL.Element.setClip (Clip clip) inherited
Sets the current Clip for an Element.
Parameters
clip The clip to set as the current clip for this element.
setFont()
void com.datalogics.PDFL.TextRun.setFont (Font font)
The font of this TextRun.
setGraphicState()
void com.datalogics.PDFL.TextRun.setGraphicState (GraphicState gstate)
Set the Graphic State of the text run.
Parameters
gstate the new/updated Graphic State for the text run.
setMatrix()
void com.datalogics.PDFL.Element.setMatrix (Matrix matrix) inherited
Set the transformation matrix for the element.
Parameters
matrix the transformation matrix for the element.
setText()
void com.datalogics.PDFL.TextRun.setText (String text)
The text of this TextRun.
translate()
void com.datalogics.PDFL.Element.translate (double tx, double ty) inherited
Translate an element by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ].
Reimplemented in com.datalogics.PDFL.Image.