Java API Reference: com.datalogics.PDFL.TextState Class Reference
com.datalogics.PDFL.TextState Class Reference
Public Member Functions
synchronized void delete ()
double getCharacterSpacing ()
double getFontSize ()
double getHScale ()
TextRenderMode getRenderMode ()
double getTextRise ()
double getWordSpacing ()
void setCharacterSpacing (double Tc)
void setFontSize (double Tf)
void setHScale (double Tz)
void setRenderMode (TextRenderMode Tr)
void setTextRise (double Ts)
void setWordSpacing (double Tw)
TextState ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
TextState (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (TextState obj)
Detailed Description
The text state includes parameters that affect text. These parameters include character and word spacing, font, font size, and horizontal scale.
Constructor & Destructor Documentation
TextState() [1/2]
com.datalogics.PDFL.TextState.TextState (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
TextState() [2/2]
com.datalogics.PDFL.TextState.TextState ()
Create a default text state
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.TextState.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.TextState.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.TextState.finalize () protected
getCharacterSpacing()
double com.datalogics.PDFL.TextState.getCharacterSpacing ()
The current character spacing (corresponding to the Tc operator), in unscaled text space units.
getCPtr()
long com.datalogics.PDFL.TextState.getCPtr (TextState obj) static protected
Referenced by com.datalogics.PDFL.Text.addGlyphs(), com.datalogics.PDFL.Text.addGlyphs(), and com.datalogics.PDFL.TextRun.TextRun().
getFontSize()
double com.datalogics.PDFL.TextState.getFontSize ()
The current font size (corresponding to the Tf operator).
getHScale()
double com.datalogics.PDFL.TextState.getHScale ()
The current horizontal scaling (corresponding to the Tz operator), as a percentage of the normal glyph width. Default is 100.
getRenderMode()
TextRenderMode com.datalogics.PDFL.TextState.getRenderMode ()
The current text rendering mode (corresponding to the Tr operator).
getTextRise()
double com.datalogics.PDFL.TextState.getTextRise ()
The current text rise (corresponding to the Ts operator), in unscaled text space units.
getWordSpacing()
double com.datalogics.PDFL.TextState.getWordSpacing ()
The current word spacing (corresponding to the Tw operator), in unscaled text space units.
setCharacterSpacing()
void com.datalogics.PDFL.TextState.setCharacterSpacing (double Tc)
The current character spacing (corresponding to the Tc operator), in unscaled text space units.
Parameters
Tc the new/updated character spacing
setFontSize()
void com.datalogics.PDFL.TextState.setFontSize (double Tf)
The current font size (corresponding to the Tf operator).
Parameters
Tf the new/updated font size
setHScale()
void com.datalogics.PDFL.TextState.setHScale (double Tz)
The current horizontal scaling (corresponding to the Tz operator), as a percentage of the normal glyph width. Default is 100.
Parameters
Tz the new/updated horizontal scaling
setRenderMode()
void com.datalogics.PDFL.TextState.setRenderMode (TextRenderMode Tr)
The current text rendering mode (corresponding to the Tr operator).
Parameters
Tr the new/updated text rendering mode
setTextRise()
void com.datalogics.PDFL.TextState.setTextRise (double Ts)
The current text rise (corresponding to the Ts operator), in unscaled text space units.
Parameters
Ts the new/updated text rise
setWordSpacing()
void com.datalogics.PDFL.TextState.setWordSpacing (double Tw)
The current word spacing (corresponding to the Tw operator), in unscaled text space units.
Parameters
Tw the new/updated character spacing