Java API Reference: com.datalogics.PDFL.Color Class Reference
com.datalogics.PDFL.Color Class Reference
Public Member Functions
Color (ColorSpace colorSpace, java.util.List< Double > values)
Color (double c, double m, double y, double k)
Color (double grey)
Color (double r, double g, double b)
Color (Pattern pattern)
synchronized void delete ()
boolean equals (Object rhs)
Pattern getPattern ()
ColorSpace getSpace ()
java.util.List< Double > getValue ()
String toString ()
Static Public Member Functions
static Color colorFromAWTColor (java.awt.Color c)
Protected Member Functions
Color (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (Color obj)
Detailed Description
A color specified by values appropriate for its color space. The values that are offered range from 0 to 1.0 for red, green, and blue (RGB) or cyan, magenta, yellow, and black (CYMK).
Constructor & Destructor Documentation
Color() [1/6]
com.datalogics.PDFL.Color.Color (long cPtr, boolean cMemoryOwn) protected
Referenced by Color(), colorFromAWTColor(), equals(), and getCPtr().
Color() [2/6]
com.datalogics.PDFL.Color.Color (double grey)
Create a new color in the DeviceGray colorspace with the specified value.
Parameters
grey the grayscale color value for the new color (0.0 - 1.0)
Color() [3/6]
com.datalogics.PDFL.Color.Color (double r, double g, double b)
Create a new color in the DeviceRGB colorspace with the specified value.
Parameters
r the red color value for the new color (0.0 - 1.0)
g the green color value for the new color (0.0 - 1.0)
b the blue color value for the new color (0.0 - 1.0)
Color() [4/6]
com.datalogics.PDFL.Color.Color (double c, double m, double y, double k)
Create a new color in the DeviceCMYK colorspace with the specified value.
Parameters
c the cyan color value for the new color (0.0 - 1.0)
m the magenta color value for the new color (0.0 - 1.0)
y the yellow color value for the new color (0.0 - 1.0)
k the black color value for the new color (0.0 - 1.0)
Color() [5/6]
com.datalogics.PDFL.Color.Color (ColorSpace colorSpace, java.util.List< Double > values)
Create a new color in an arbitrary color space. The number of values passed must match the number of values in the color space.
Parameters
colorSpace the color space in which to create the color
values the values to place into the color
Color() [6/6]
com.datalogics.PDFL.Color.Color (Pattern pattern)
Create a new color in the pattern color space.
Parameters
pattern The pattern to turn into a color
Member Function Documentation
colorFromAWTColor()
Color com.datalogics.PDFL.Color.colorFromAWTColor (java.awt.Color c) static
Create a Color from a standard java.awt.Color object.
Parameters
c the java.awt.Color object to use as a source
delete() [1/2]
synchronized void com.datalogics.PDFL.Color.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.Color.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.Color.equals (Object rhs)
finalize()
void com.datalogics.PDFL.Color.finalize () protected
getCPtr()
long com.datalogics.PDFL.Color.getCPtr (Color obj) static protected
Referenced by com.datalogics.PDFL.ShadingPattern.setBackgroundColor(), com.datalogics.PDFL.Redaction.setBorderColor(), com.datalogics.PDFL.Annotation.setColor(), com.datalogics.PDFL.Bookmark.setColor(), com.datalogics.PDFL.FreeTextAnnotation.setColor(), com.datalogics.PDFL.WatermarkTextParams.setColor(), com.datalogics.PDFL.GraphicState.setFillColor(), com.datalogics.PDFL.Redaction.setFillColor(), com.datalogics.PDFL.Annotation.setInteriorColor(), com.datalogics.PDFL.Redaction.setInternalColor(), com.datalogics.PDFL.GraphicState.setStrokeColor(), com.datalogics.PDFL.FreeTextAnnotation.setTextColor(), and com.datalogics.PDFL.Redaction.setTextColor().
getPattern()
Pattern com.datalogics.PDFL.Color.getPattern ()
The pattern of the color
getSpace()
ColorSpace com.datalogics.PDFL.Color.getSpace ()
The color space of the color
getValue()
java.util.List< Double > com.datalogics.PDFL.Color.getValue ()
The values of the color. Not valid for pattern-based colors.
toString()
String com.datalogics.PDFL.Color.toString ()
a string representing the color.