Java API Reference: com.datalogics.PDFL.Font Class Reference
com.datalogics.PDFL.Font Class Reference
Public Member Functions
synchronized void delete ()
void embedNow (Document doc)
long findIndexOfFirstUnrepresentableChar (String text)
Font (String fontName)
Font (String fontName, java.util.EnumSet< FontCreateFlags > createFlags)
Font (String fontName, java.util.EnumSet< FontCreateFlags > createFlags, WritingMode wrMode)
double getAscent ()
the Ascent value from the font descriptor. This is the maximum height above the baseline reached by glyphs in this font, excluding the height of glyphs for accented characters.
double getAvgWidth ()
the AvgWidth value from the font descriptor. This is the average width of glyphs in the font, or 0 if the value is not defined in the font descriptor.
Rect getBBox ()
double getCapHeight ()
the CapHeight value from the font descriptor. This is the vertical coordinate of the top of flat capital letters, measured from the baseline, or 0 if the value is not defined in the font descriptor.
String getCidFontType ()
double getDescent ()
the Descent value from the font descriptor. This is the maximum depth below the baseline reached by glyphs in this font. The value is a negative number.
boolean getEmbedded ()
String getEncoding ()
EncodingInfo getEncodingInfo ()
java.util.EnumSet< FontFlags > getFlags ()
String getFullName ()
double getItalicAngle ()
the ItalicAngle value from the font descriptor. This is the angle, expressed in degrees counterclockwise from the vertical, of the dominant vertical strokes of the font, defined in the font descriptor.
double getLeading ()
the Leading value from the font descriptor. This is the spacing between baselines of consecutive lines of text, or 0 if the value is not defined in the font descriptor.
double getMaxWidth ()
the MaxWidth value from the font descriptor. This is the maximum glyph width present in the font, or 0 if the value is not defined in the font descriptor.
double getMissingWidth ()
the MissingWidth value from the font descriptor. This is the width given to characters that do not have corresponding glyphs defined in the font, or 0 if the value is not defined in the font descriptor.
String getName ()
PDFDict getPDFDict ()
double getStemH ()
the StemH value from the font descriptor. This is the vertical thickness of the dominant horizontal stems of the font's glyphs, or 0 if the value is not defined in the font descriptor.
double getStemV ()
the StemV value from the font descriptor. This is the horizontal thickness of the dominant vertical stems of the font's glyphs, or 0 if the value is not defined in the font descriptor.
String getType ()
WritingMode getWritingMode ()
Get the writing mode of the font. The writing mode of the fontwhether it will place glyphs horizontally or vertically. Text written with this font will run in the direction of the writing mode.
double getXHeight ()
the XHeight value from the font descriptor. This is the vertical coordinate of the top of flat nonascending lowercase letters in fonts that have Latin characters, as measured from the baseline, or 0 if the value is not defined in the font descriptor.
boolean isFromDoc ()
boolean isTextRepresentable (String text)
double measureTextWidth (String text, double fontSize)
Static Public Member Functions
static java.util.List< Font > getFontList ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Font (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Font obj)
Detailed Description
Represents a font.Defines the typeface, size, style (bold, italic), Unicode values, and other details. The Font class represents a font installed on the system.
Constructor & Destructor Documentation
Font() [1/4]
com.datalogics.PDFL.Font.Font (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr(), and getFontList().
Font() [2/4]
com.datalogics.PDFL.Font.Font (String fontName)
Find a font with the specified name, and construct a Font object from it. Otherwise, it makes a font with the default encoding (MacRomanEncoding on Macs, WinAnsiEncoding elsewhere, or for symbol fonts, their own custom encoding). There is not a way to specify another encoding for the font.
When setting text, it checks to see if the text is representable in the font's encoding. If it is not, then DLE makes a "unicode font" with an Identity-H encoding and uses that to set the text. For non-Type0 fonts, this may result in two versions of a font in the output document.
PDFL enforces the following requirements on fonts:
TrueTypes used as CID fonts must be embedded.
All CID fonts that are embedded must be subsetted.
CID fonts that are marked as embedded get their DoNotEmbed flag turned off (or else PDFL won't make a PDEFont from the SysFont).
Font() [3/4]
com.datalogics.PDFL.Font.Font (String fontName, java.util.EnumSet< FontCreateFlags > createFlags)
Find a font with the specified name, and construct a Font object from it. Otherwise, it makes a font with the default encoding (MacRomanEncoding on Macs, WinAnsiEncoding elsewhere, or for symbol fonts, their own custom encoding). There is not a way to specify another encoding for the font.
When setting text, it checks to see if the text is representable in the font's encoding. If it is not, then DLE makes a "unicode font" with an Identity-H encoding and uses that to set the text. For non-Type0 fonts, this may result in two versions of a font in the output document.
PDFL enforces the following requirements on fonts:
TrueTypes used as CID fonts must be embedded.
All CID fonts that are embedded must be subsetted.
CID fonts that are marked as embedded get their DoNotEmbed flag turned off (or else PDFL won't make a PDEFont from the SysFont).
Parameters
fontName the name of the font to create
createFlags flags specifying embedding and other options for the use of a font in the document
Font() [4/4]
com.datalogics.PDFL.Font.Font (String fontName, java.util.EnumSet< FontCreateFlags > createFlags, WritingMode wrMode)
Find a font with the specified name, and construct a Font object from it. Otherwise, it makes a font with the default encoding (MacRomanEncoding on Macs, WinAnsiEncoding elsewhere, or for symbol fonts, their own custom encoding). There is not a way to specify another encoding for the font.
When setting text, it checks to see if the text is representable in the font's encoding. If it is not, then DLE makes a "unicode font" with an Identity-H or Identity-V encoding and uses that to set the text. For non-Type0 fonts, this may result in two versions of a font in the output document.
PDFL enforces the following requirements on fonts:
TrueTypes used as CID fonts must be embedded.
All CID fonts that are embedded must be subsetted.
CID fonts that are marked as embedded get their DoNotEmbed flag turned off (or else PDFL won't make a PDEFont from the SysFont).
Parameters
fontName the name of the font to create
createFlags flags specifying embedding and other options for the use of a font in the document
wrMode determines whether text will be printed horizontally or vertically
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.Font.delete ()
Destructor.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.Font.delete (Boolean disposing) protected
embedNow()
void com.datalogics.PDFL.Font.embedNow (Document doc)
Embeds the Font.
Parameters
doc the Document the Font is embedded into
finalize()
void com.datalogics.PDFL.Font.finalize () protected
Destructor.
findIndexOfFirstUnrepresentableChar()
long com.datalogics.PDFL.Font.findIndexOfFirstUnrepresentableChar (String text)
Find the index of the first character that cannot be represented in this font. This will return the index of the first character in the string for which the font has no glyph. If all characters can be represented (i.e. if IsTextRepresentable() would return true), this will return the length of the string.
Parameters
text the text to check
Returns
The index of the first character that cannot be represented in this font.
getAscent()
double com.datalogics.PDFL.Font.getAscent ()
the Ascent value from the font descriptor. This is the maximum height above the baseline reached by glyphs in this font, excluding the height of glyphs for accented characters.
Returns
The Ascent value of the font in glyph space units.
getAvgWidth()
double com.datalogics.PDFL.Font.getAvgWidth ()
the AvgWidth value from the font descriptor. This is the average width of glyphs in the font, or 0 if the value is not defined in the font descriptor.
Returns
The AvgWidth value of the font in glyph space units, or 0 if not defined.
getBBox()
Rect com.datalogics.PDFL.Font.getBBox ()
The Bounding Box rectangle of the font.
getCapHeight()
double com.datalogics.PDFL.Font.getCapHeight ()
the CapHeight value from the font descriptor. This is the vertical coordinate of the top of flat capital letters, measured from the baseline, or 0 if the value is not defined in the font descriptor.
Returns
The CapHeight value of the font in glyph space units, or 0 if not defined.
getCidFontType()
String com.datalogics.PDFL.Font.getCidFontType ()
getCPtr()
long com.datalogics.PDFL.Font.getCPtr (Font obj) static protected
Referenced by com.datalogics.PDFL.Text.addGlyphs(), com.datalogics.PDFL.Text.addGlyphs(), com.datalogics.PDFL.TextRun.setFont(), com.datalogics.PDFL.WatermarkTextParams.setFont(), com.datalogics.PDFL.Redaction.setOverlayFont(), and com.datalogics.PDFL.TextRun.TextRun().
getDescent()
double com.datalogics.PDFL.Font.getDescent ()
the Descent value from the font descriptor. This is the maximum depth below the baseline reached by glyphs in this font. The value is a negative number.
Returns
The descent value of the font. \xrefitem pdelayer_apis "PDE Layer" "PDE Layer" PDSysFont PDSysFontGetAttrs \xrefitem pdelayer_apis "PDE Layer" "PDE Layer" PDEFont PDEFontGetAttrs \xrefitem pdlayer_apis "PD Layer" "PD Layer" PDFont PDFontGetMetrics
getEmbedded()
boolean com.datalogics.PDFL.Font.getEmbedded ()
Tests that Font is embedded in the document it was created for returns true if the font is embedded and returns false if it is not
getEncoding()
String com.datalogics.PDFL.Font.getEncoding ()
Return the encoding of the font.
Returns
The encoding of the font, eg:
WinAnsiEncoding
MacRomanEncoding
getEncodingInfo()
EncodingInfo com.datalogics.PDFL.Font.getEncodingInfo ()
Get the populated CEncoding object.
getFlags()
java.util.EnumSet< FontFlags > com.datalogics.PDFL.Font.getFlags ()
Get the font flags for a font.
getFontList()
java.util.List< Font > com.datalogics.PDFL.Font.getFontList () static
Get a list of available fonts.
Returns
The list of available fonts.
getFullName()
String com.datalogics.PDFL.Font.getFullName ()
Get the Full Name of the font.
Returns
The Full Name of the font. Note: This method only returns a meaningful result for TrueType-based technology fonts.
getItalicAngle()
double com.datalogics.PDFL.Font.getItalicAngle ()
the ItalicAngle value from the font descriptor. This is the angle, expressed in degrees counterclockwise from the vertical, of the dominant vertical strokes of the font, defined in the font descriptor.
Returns
The ItalicAngle value of the font in degrees.
getLeading()
double com.datalogics.PDFL.Font.getLeading ()
the Leading value from the font descriptor. This is the spacing between baselines of consecutive lines of text, or 0 if the value is not defined in the font descriptor.
Returns
The leading value of the font, or 0 if not present.
getMaxWidth()
double com.datalogics.PDFL.Font.getMaxWidth ()
the MaxWidth value from the font descriptor. This is the maximum glyph width present in the font, or 0 if the value is not defined in the font descriptor.
Returns
The MaxWidth value of the font in glyph space units, or 0 if not present.
getMissingWidth()
double com.datalogics.PDFL.Font.getMissingWidth ()
the MissingWidth value from the font descriptor. This is the width given to characters that do not have corresponding glyphs defined in the font, or 0 if the value is not defined in the font descriptor.
Returns
The MissingWidth value of the font in glyph space units, or 0 if not present.
getName()
String com.datalogics.PDFL.Font.getName ()
Get the name of the font.
Returns
The name of the font.
getPDFDict()
PDFDict com.datalogics.PDFL.Font.getPDFDict ()
Retrieve the PDFDict representation of this object
getStemH()
double com.datalogics.PDFL.Font.getStemH ()
the StemH value from the font descriptor. This is the vertical thickness of the dominant horizontal stems of the font's glyphs, or 0 if the value is not defined in the font descriptor.
Returns
The StemH value of the font in glyph space units, or 0 if not present.
getStemV()
double com.datalogics.PDFL.Font.getStemV ()
the StemV value from the font descriptor. This is the horizontal thickness of the dominant vertical stems of the font's glyphs, or 0 if the value is not defined in the font descriptor.
Returns
The StemV value of the font in glyph space units, or 0 if not present.
getType()
String com.datalogics.PDFL.Font.getType ()
Get the type of the font.
Returns
The type of the font.
Type0
Type1
MMType1
TrueType
getWritingMode()
WritingMode com.datalogics.PDFL.Font.getWritingMode ()
Get the writing mode of the font. The writing mode of the fontwhether it will place glyphs horizontally or vertically. Text written with this font will run in the direction of the writing mode.
Returns
The WritingMode of the font.
getXHeight()
double com.datalogics.PDFL.Font.getXHeight ()
the XHeight value from the font descriptor. This is the vertical coordinate of the top of flat nonascending lowercase letters in fonts that have Latin characters, as measured from the baseline, or 0 if the value is not defined in the font descriptor.
Returns
The XHeight value of the font in glyph space units, or 0 if not present.
isFromDoc()
boolean com.datalogics.PDFL.Font.isFromDoc ()
isTextRepresentable()
boolean com.datalogics.PDFL.Font.isTextRepresentable (String text)
Is this text representable in this font?
Parameters
text the text to check
measureTextWidth()
double com.datalogics.PDFL.Font.measureTextWidth (String text, double fontSize)
Measures the width of the specified text in points, using the Font at the specified size.
Parameters
text the Text to be measured
fontSize the Font size to be used