Java API Reference: com.datalogics.PDFL.Ink Class Reference
com.datalogics.PDFL.Ink Class Reference
Public Member Functions
synchronized void delete ()
String getAlias ()
double getAngle ()
double getBlack ()
int getBlue ()
String getColorantName ()
byte[] getColorantNameArray ()
double getCyan ()
double getDensity ()
double getFrequency ()
int getGreen ()
InkTypes getInkType ()
boolean getIsProcessColor ()
double getMagenta ()
SeparationPreviewOptions getPreviewOption ()
int getRed ()
double getYellow ()
void setAlias (String theAlias)
void setAngle (double theAngle)
void setColorantName (String theColorantName)
void setDensity (double theDensity)
void setFrequency (double theFrequency)
void setInkType (InkTypes theInkType)
void setIsProcessColor (boolean theSetting)
void setPreviewOption (SeparationPreviewOptions thePreviewOption)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Ink (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Ink obj)
Detailed Description
The ink object represents the color in the color space, CYMK or RGB.
Constructor & Destructor Documentation
Ink()
com.datalogics.PDFL.Ink.Ink (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.Ink.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.Ink.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.Ink.finalize () protected
getAlias()
String com.datalogics.PDFL.Ink.getAlias ()
Another name for this colorant.
getAngle()
double com.datalogics.PDFL.Ink.getAngle ()
The angle for this ink.
getBlack()
double com.datalogics.PDFL.Ink.getBlack ()
Values for display of a colorswatch in a CMYK color space.
getBlue()
int com.datalogics.PDFL.Ink.getBlue ()
RGB values for on-screen display of a colorswatch.
getColorantName()
String com.datalogics.PDFL.Ink.getColorantName ()
The name of the colorant from the Separation or DeviceN color space, or the process color name.
getColorantNameArray()
byte[] com.datalogics.PDFL.Ink.getColorantNameArray ()
The name of the colorant from the Separation or DeviceN color space, or the process color name. NOTE: This property is suitable for retrieving the name when the ColorantName can't be retrieved as a string.
getCPtr()
long com.datalogics.PDFL.Ink.getCPtr (Ink obj) static protected
Referenced by com.datalogics.PDFL.SeparationColorSpace.SeparationColorSpace(), and com.datalogics.PDFL.SeparationPlate.SeparationPlate().
getCyan()
double com.datalogics.PDFL.Ink.getCyan ()
Values for display of a colorswatch in a CMYK color space.
getDensity()
double com.datalogics.PDFL.Ink.getDensity ()
The density for this ink.
getFrequency()
double com.datalogics.PDFL.Ink.getFrequency ()
The frequency for this ink.
getGreen()
int com.datalogics.PDFL.Ink.getGreen ()
RGB values for on-screen display of a colorswatch.
getInkType()
InkTypes com.datalogics.PDFL.Ink.getInkType ()
The ink type of this ink for trapping.
getIsProcessColor()
boolean com.datalogics.PDFL.Ink.getIsProcessColor ()
True if this is a process color, false if this is a spot color.
getMagenta()
double com.datalogics.PDFL.Ink.getMagenta ()
Values for display of a colorswatch in a CMYK color space.
getPreviewOption()
SeparationPreviewOptions com.datalogics.PDFL.Ink.getPreviewOption ()
How to handle the colorant for a separation preview.
getRed()
int com.datalogics.PDFL.Ink.getRed ()
RGB values for on-screen display of a colorswatch.
getYellow()
double com.datalogics.PDFL.Ink.getYellow ()
Values for display of a colorswatch in a CMYK color space.
setAlias()
void com.datalogics.PDFL.Ink.setAlias (String theAlias)
Another name for this colorant.
setAngle()
void com.datalogics.PDFL.Ink.setAngle (double theAngle)
The angle for this ink.
setColorantName()
void com.datalogics.PDFL.Ink.setColorantName (String theColorantName)
The name of the colorant from the Separation or DeviceN color space, or the process color name.
setDensity()
void com.datalogics.PDFL.Ink.setDensity (double theDensity)
The density for this ink.
setFrequency()
void com.datalogics.PDFL.Ink.setFrequency (double theFrequency)
The frequency for this ink.
setInkType()
void com.datalogics.PDFL.Ink.setInkType (InkTypes theInkType)
The ink type of this ink for trapping.
setIsProcessColor()
void com.datalogics.PDFL.Ink.setIsProcessColor (boolean theSetting)
True if this is a process color, false if this is a spot color.
setPreviewOption()
void com.datalogics.PDFL.Ink.setPreviewOption (SeparationPreviewOptions thePreviewOption)
How to handle the colorant for a separation preview.