Java API Reference: com.datalogics.PDFL.RolledBackDocument Class Reference
com.datalogics.PDFL.RolledBackDocument Class Reference
Public Member Functions
void closeDocument ()
synchronized void delete ()
void save (String newPath)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
RolledBackDocument (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (RolledBackDocument obj)
Detailed Description
A class representing a Rolled back instance of a PDF document that was previously saved Incrementally.
Constructor & Destructor Documentation
RolledBackDocument()
com.datalogics.PDFL.RolledBackDocument.RolledBackDocument (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
Member Function Documentation
closeDocument()
void com.datalogics.PDFL.RolledBackDocument.closeDocument ()
delete() [1/2]
synchronized void com.datalogics.PDFL.RolledBackDocument.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.RolledBackDocument.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.RolledBackDocument.finalize () protected
getCPtr()
long com.datalogics.PDFL.RolledBackDocument.getCPtr (RolledBackDocument obj) static protected
save()
void com.datalogics.PDFL.RolledBackDocument.save (String newPath)
Saves the Rolled back document instance using the specified path to disk.