Java API Reference: com.datalogics.PDFL.PrintUserParams Class Reference
com.datalogics.PDFL.PrintUserParams Class Reference
Public Member Functions
void choosePaperSourceBySize (double width, double height)
synchronized void delete ()
java.util.List< String > enumeratePaperSources ()
int getBinaryOK ()
boolean getCollate ()
String getCommand ()
String getDeviceName ()
int getDoOPP ()
String getDriverName ()
int getEmitHalftones ()
boolean getEmitToFile ()
boolean getEmitToPrinter ()
int getEndPage ()
FarEastFont getFarEastFontOpt ()
String getInFileName ()
int getNCopies ()
String getOutFileName ()
int getPaperHeight ()
int getPaperSource ()
int getPaperWidth ()
String getPortName ()
int getPrintAnnots ()
PrintParams getPrintParams ()
int getPsLevel ()
int getReverse ()
boolean getShrinkToFit ()
int getStartPage ()
int getStartResult ()
int getTransQuality ()
boolean getUseCustomPaperSize ()
int paperSourceIdByName (String trayName)
boolean posePrintDialog (Document doc)
PrintUserParams ()
void setBinaryOK (int binaryOK)
void setCollate (boolean collate)
void setCommand (String command)
void setDeviceName (String inStr)
void setDoOPP (int doOPP)
void setDriverName (String inStr)
void setEmitHalftones (int emitHalftones)
void setEmitToFile (boolean emitToFile)
void setEmitToPrinter (boolean emitToPrinter)
void setEndPage (int endPage)
void setFarEastFontOpt (FarEastFont farEastFontOpt)
void setInFileName (String inStr)
void setNCopies (int nCopies)
void setOutFileName (String inStr)
void setPaperHeight (int paperHeight)
void setPaperSource (int PaperSource)
void setPaperWidth (int paperWidth)
void setPortName (String inStr)
void setPrintAnnots (int printAnnots)
void setPsLevel (int psLevel)
void setReverse (int reverse)
void setShrinkToFit (boolean shrinkToFit)
void setStartPage (int startPage)
void setStartResult (int startResult)
void setTransQuality (int transQuality)
void setUseCustomPaperSize (boolean useCustomPaperSize)
void useDefaultPrinter (Document doc)
Static Public Attributes
static final int USE_CROP_BOX
static final int USE_MEDIA_BOX
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PrintUserParams (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PrintUserParams obj)
Detailed Description
A structure used to set parameters for print jobs. Two structures provide settings for setting parameters for print jobs, PrintUserParams and PrintParams. PrintUserParams was created first, and then PrintParams was created as an extension of PrintUserParams, to provide more settings to account for changing technology.
When the system seeks to print a document it will pass the content and the print parameters, such as the page size, paper tray, and landscape v. portrait, to the print API in APDFL. If the setting is in PrintParams it will pass the document and parameters to PrintParams and then to PrintUserParams and from there to the print API to complete the printing process.
The print logic may take different code paths depending on whether or not the print content is being sent to a printer or to a file, or if the printing uses PostScript or not. When you see a print setting that appears in both PrintUserParams and PrintParams, such as "ShrinktoFit," set the appropriate value in both of these classes. Also, PrintParams offers a variety of settings related to PostScript, but the use of PrintParams is not limited to PostScript.
Constructor & Destructor Documentation
PrintUserParams() [1/2]
com.datalogics.PDFL.PrintUserParams.PrintUserParams (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
PrintUserParams() [2/2]
com.datalogics.PDFL.PrintUserParams.PrintUserParams ()
Member Function Documentation
choosePaperSourceBySize()
void com.datalogics.PDFL.PrintUserParams.choosePaperSourceBySize (double width, double height)
Choose the best paper source for a given width and height.
Searches the printer's paper list for the smallest paper size that is greater than or equal to the given width and height, including with rotation, and sets up the job to print with that paper size.
To obtain width and height, specify the Right - Left and Top - Bottom of the MediaBox of a representative Page.
The printerName and portName must be set.
If you use this call in conjunction with PosePrintDialog, UseDefaultPrinter, or UpdateFromPrinterSettings, call this function after those functions.
Setting RotateAndCenter to True is recommended with this function.
Parameters
width the desired width of the output in user units
height the desired height of the output in user units
delete() [1/2]
synchronized void com.datalogics.PDFL.PrintUserParams.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.PrintUserParams.delete (Boolean disposing) protected
enumeratePaperSources()
java.util.List< String > com.datalogics.PDFL.PrintUserParams.enumeratePaperSources ()
Enumerates available tray/bin names for the specified printer.
Returns
Set of the tray/bin names.
finalize()
void com.datalogics.PDFL.PrintUserParams.finalize () protected
getBinaryOK()
int com.datalogics.PDFL.PrintUserParams.getBinaryOK ()
Gets whether to enable Binary data, 1 turns it on and 0 turns it off. It applies to a Postscript printer. This API is available on Windows and macOS only.
Returns
Binary ok setting.
getCollate()
boolean com.datalogics.PDFL.PrintUserParams.getCollate ()
Collate property.
Returns
True if copies should be collated.
getCommand()
String com.datalogics.PDFL.PrintUserParams.getCommand ()
Gets the Optional command line arguments on Unix. It is used only if emitToPrinter is true. For example, "lp" or "lpr" applies to a Postscript printer. This API is available on Unix only.
Returns
command line arguments
getCPtr()
long com.datalogics.PDFL.PrintUserParams.getCPtr (PrintUserParams obj) static protected
Referenced by com.datalogics.PDFL.Document.exportAsPostScript(), com.datalogics.PDFL.Document.exportAsPostScript(), com.datalogics.PDFL.Document.exportAsPostScript(), com.datalogics.PDFL.Document.print(), com.datalogics.PDFL.Document.print(), com.datalogics.PDFL.Document.print(), com.datalogics.PDFL.Document.printToFile(), com.datalogics.PDFL.Document.printToFile(), and com.datalogics.PDFL.Document.printToFile().
getDeviceName()
String com.datalogics.PDFL.PrintUserParams.getDeviceName ()
The unicode name of the device to print to (for example, "Distiller Assistant v3.01"). Available devices can be found in the Windows Registry at HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Devices. It applies to a printer.
getDoOPP()
int com.datalogics.PDFL.PrintUserParams.getDoOPP ()
Gets the OverPrint Preview setting, 1 uses it, 0 does not. It applies to a printer. The default is 0. This API is available on Windows and macOS only.
Returns
1 if OverPrint Preview will be used, 0 if not
getDriverName()
String com.datalogics.PDFL.PrintUserParams.getDriverName ()
The unicode name of the driver (for example, "winspool"). See the registry key for deviceName. It applies to the printer.
getEmitHalftones()
int com.datalogics.PDFL.PrintUserParams.getEmitHalftones ()
Gets the Emit half-tones setting, 1 turns it on, 0 turns it off. It applies to a Postscript printer. This API is available on Windows and macOS only.
Returns
1 if halftones will be emitted, 0 if not
getEmitToFile()
boolean com.datalogics.PDFL.PrintUserParams.getEmitToFile ()
Gets whether a Postscript file is created.
Returns
true if a PostScript file is created.
getEmitToPrinter()
boolean com.datalogics.PDFL.PrintUserParams.getEmitToPrinter ()
Gets whether to Output the PDF document to a Postscript Printer.
Returns
true if output to a printer.
getEndPage()
int com.datalogics.PDFL.PrintUserParams.getEndPage ()
Gets the page on which to finish printing, using zero-based nubmering. It applies to a printer. This API is only available on Windows and macOS only.
Returns
the page to end upon
getFarEastFontOpt()
FarEastFont com.datalogics.PDFL.PrintUserParams.getFarEastFontOpt ()
Gets the Far East Font setting. The default value is DownloadAll. PrintAsImage will not be honored. It applies to a Postscript printer. This API is available on Windows only.
Returns
a PDFarEastFont value that represents the setting to be used
getInFileName()
String com.datalogics.PDFL.PrintUserParams.getInFileName ()
Unicode name used for the Windows DOCINFO structure (lpszDocName) that points to a NULL-terminated string that specifying the name of the document. In case of printing/exporting to Postscript, this field sets the Title DSC comment in the generated Postscript file. If inFileName was not provided, the Title DSC comment is filled with the name of pdf document.
getNCopies()
int com.datalogics.PDFL.PrintUserParams.getNCopies ()
Gets the number of copies to print. It applies to a Postscript file.
Returns
the number of copies that will be printed
getOutFileName()
String com.datalogics.PDFL.PrintUserParams.getOutFileName ()
Unicode name used for the Windows DOCINFO structure (lpszOutput). It points to a NULL-terminated string that specifies the name of an output file. If this pointer is NULL, the output will be sent to the device identified by deviceName, driverName, and portName. It applies to a printer.
getPaperHeight()
int com.datalogics.PDFL.PrintUserParams.getPaperHeight ()
Gets the Height of paper in points. The default value is 792. It applies to a Postscript printer.
Returns
the height of the paper in points
getPaperSource()
int com.datalogics.PDFL.PrintUserParams.getPaperSource ()
Paper source property.
Returns
Value in DEVMODE->dmDefaultSource if initialized or index of selected paper tray or -1 if not specified.
getPaperWidth()
int com.datalogics.PDFL.PrintUserParams.getPaperWidth ()
Gets the Width of paper in points. The default value is 612. It applies to a Postscript printer.
Returns
the width of the paper in points
getPortName()
String com.datalogics.PDFL.PrintUserParams.getPortName ()
The unicode name of the port (for example, "Ne00"). See the registry key for deviceName. It applies to the printer.
getPrintAnnots()
int com.datalogics.PDFL.PrintUserParams.getPrintAnnots ()
Gets the printing annotations setting, 1 turns it on, 0 turns it off. It applies to a printer. This API is available on Windows and macOS only.
Returns
1 if annotations will be printed, 0 if not
getPrintParams()
PrintParams com.datalogics.PDFL.PrintUserParams.getPrintParams ()
Gets the Print Parameter settings.
Returns
the print parameter settings
getPsLevel()
int com.datalogics.PDFL.PrintUserParams.getPsLevel ()
Gets the Postscript level. It applies to a Postscript printer. This API is available on Windows and macOS only.
Returns
Postscript level setting
getReverse()
int com.datalogics.PDFL.PrintUserParams.getReverse ()
Gets whether to reverses print order, 1 reverses it and 0 does regular order. It applies to a printer. This API is available on Windows and macOS only.
Returns
1 to reverse page order or 0 for regular order
getShrinkToFit()
boolean com.datalogics.PDFL.PrintUserParams.getShrinkToFit ()
Gets the Shrink to fit setting, true turns it on, false turns it off. It applies to a Postscript printer. This API is available on Windows and macOS only.
Returns
true if the page will be shrunk to fit
getStartPage()
int com.datalogics.PDFL.PrintUserParams.getStartPage ()
Gets the page to start printing with, using zero-based numbering. It applies to a printer. This API is only available on Windows and macOS only.
Returns
the start page
getStartResult()
int com.datalogics.PDFL.PrintUserParams.getStartResult ()
Gets the Spooler ID from StartDoc. This API is available on Windows and Unix only.
Returns
the Spooler ID
getTransQuality()
int com.datalogics.PDFL.PrintUserParams.getTransQuality ()
Gets the Transparency flattening quality control. 1 is fastest; 5 is best. The default is 3. It applies to a printer. This API is available on Windows only.
Returns
the transparency flatting quality, 1 is fastest; 5 is best
getUseCustomPaperSize()
boolean com.datalogics.PDFL.PrintUserParams.getUseCustomPaperSize ()
Gets whether to force the use of the paper size provided in the PaperWidth and PaperHeight parameters and not search for best fit size provided by printer. SetPageSize must also be set.
Returns
true if force.
paperSourceIdByName()
int com.datalogics.PDFL.PrintUserParams.paperSourceIdByName (String trayName)
Obtain tray/bin number by its name.
Parameters
trayName the tray/bin's name whose number need to obtain.
Returns
Tray/Bin number corresponding to the specified name.
posePrintDialog()
boolean com.datalogics.PDFL.PrintUserParams.posePrintDialog (Document doc)
Set the print parameters by posing a dialog box to the user. The parameters set include the printer, page range, paper size, number of copies, and duplexing mode.
Changes to these parameters made by the user will be copied into the corresponding PrintUserParams fields. If you want to override the user's choices, change these fields after calling PosePrintDialog().
Parameters
doc a Document which will be used to set the maximum page range in the dialog box.
Returns
true if the user accepted the dialog box, false if it was cancelled
setBinaryOK()
void com.datalogics.PDFL.PrintUserParams.setBinaryOK (int binaryOK)
Sets whether to enable Binary datam, 1 turns it on and 0 turns it off. It applies to a Postscript printer. This API is available on Windows and macOS only.
Parameters
binaryOK Binary Ok setting.
setCollate()
void com.datalogics.PDFL.PrintUserParams.setCollate (boolean collate)
Collate property.
Parameters
collate True if need to collate copies.
setCommand()
void com.datalogics.PDFL.PrintUserParams.setCommand (String command)
Sets the Optional command line arguments on Unix. It is used only if emitToPrinter is true. For example, "lp" or "lpr" applies to a Postscript printer. This API is available on Unix only.
Parameters
command the optional command line arguments
setDeviceName()
void com.datalogics.PDFL.PrintUserParams.setDeviceName (String inStr)
setDoOPP()
void com.datalogics.PDFL.PrintUserParams.setDoOPP (int doOPP)
Sets the OverPrint Preview setting, 1 uses it, 0 does not. The default is 0. It applies to a printer. This API is available on Windows and macOS only.
Parameters
doOPP 1 if OverPrint Preview will be used, 0 if not
setDriverName()
void com.datalogics.PDFL.PrintUserParams.setDriverName (String inStr)
setEmitHalftones()
void com.datalogics.PDFL.PrintUserParams.setEmitHalftones (int emitHalftones)
Sets the Emit half-tones setting, 1 turns it on, 0 turns it off. It applies to a Postscript printer. This API is available on Windows and macOS only.
Parameters
emitHalftones 1 if halftones will be emitted, 0 if not
setEmitToFile()
void com.datalogics.PDFL.PrintUserParams.setEmitToFile (boolean emitToFile)
Sets whether a Postscript file is created. You set either this parameter or emitToPrinter, but not both.
Parameters
emitToFile pass true to emit output to a PostScript file
setEmitToPrinter()
void com.datalogics.PDFL.PrintUserParams.setEmitToPrinter (boolean emitToPrinter)
Sets whether to Output the PDF document to a Postscript Printer. Set either this parameter or emitToFile, but not both.
Parameters
emitToPrinter pass true to emit to the printer
setEndPage()
void com.datalogics.PDFL.PrintUserParams.setEndPage (int endPage)
Sets the page on which to finish printing, using zero-based nubmering. It applies to a printer. This API is only available on Windows and macOS only.
Parameters
endPage the page to end upon
setFarEastFontOpt()
void com.datalogics.PDFL.PrintUserParams.setFarEastFontOpt (FarEastFont farEastFontOpt)
Sets the Far East Font setting. The default value is DownloadAll. PrintAsImage will not be honored. It applies to a Postscript printer. This API is available on Windows only.
Parameters
farEastFontOpt a PDFarEastFont value that represents the setting to be used
setInFileName()
void com.datalogics.PDFL.PrintUserParams.setInFileName (String inStr)
setNCopies()
void com.datalogics.PDFL.PrintUserParams.setNCopies (int nCopies)
Sets the number of copies to print. It applies to a Postscript file.
Parameters
nCopies the number of copies to print.
setOutFileName()
void com.datalogics.PDFL.PrintUserParams.setOutFileName (String inStr)
setPaperHeight()
void com.datalogics.PDFL.PrintUserParams.setPaperHeight (int paperHeight)
Sets the Height of paper in points. The default value is 792. It applies to a Postscript printer.
Parameters
paperHeight the height of the paper in points
setPaperSource()
void com.datalogics.PDFL.PrintUserParams.setPaperSource (int PaperSource)
Paper source property.
Parameters
PaperSource paper source which must be selected.
setPaperWidth()
void com.datalogics.PDFL.PrintUserParams.setPaperWidth (int paperWidth)
Sets the Width of paper in points. The default value is 612. It applies to a Postscript printer.
Parameters
paperWidth the width of the paper in points
setPortName()
void com.datalogics.PDFL.PrintUserParams.setPortName (String inStr)
setPrintAnnots()
void com.datalogics.PDFL.PrintUserParams.setPrintAnnots (int printAnnots)
Sets the printing annotations setting, 1 turns it on, 0 turns it off. It applies to a printer. This API is available on Windows and macOS only.
Parameters
printAnnots 1 to print annotations, 0 to not print them.
setPsLevel()
void com.datalogics.PDFL.PrintUserParams.setPsLevel (int psLevel)
Sets the Postscript level. It applies to a Postscript printer. This API is available on Windows and macOS only.
Parameters
psLevel Postscript Level setting.
setReverse()
void com.datalogics.PDFL.PrintUserParams.setReverse (int reverse)
Sets whether to reverses print order, 1 reverses it and 0 does regular order. It applies to a printer. This API is available on Windows and macOS only.
Parameters
reverse 1 to reverse page order or 0 for regular order
setShrinkToFit()
void com.datalogics.PDFL.PrintUserParams.setShrinkToFit (boolean shrinkToFit)
Sets the Shrink to fit setting, true turns it on, false turns it off. It applies to a PostScript printer. This API is available on Windows and macOS only.
Parameters
shrinkToFit pass true to shrink the page to fit
setStartPage()
void com.datalogics.PDFL.PrintUserParams.setStartPage (int startPage)
Sets the page to start printing with, using zero-based numbering. It applies to a printer. This API is only available on Windows and macOS only.
Parameters
startPage the page to start on
setStartResult()
void com.datalogics.PDFL.PrintUserParams.setStartResult (int startResult)
Sets the Spooler ID for StartDoc. This API is available on Windows and Unix only.
Parameters
startResult the Spooler ID
setTransQuality()
void com.datalogics.PDFL.PrintUserParams.setTransQuality (int transQuality)
Sets the Transparency flattening quality control. 1 is fastest; 5 is best. The default is 3. It applies to a printer. This API is available on Windows only.
Parameters
transQuality the transparency flatting quality, 1 is fastest; 5 is best
setUseCustomPaperSize()
void com.datalogics.PDFL.PrintUserParams.setUseCustomPaperSize (boolean useCustomPaperSize)
Sets whether to force the use of the paper size provided in the PaperWidth and PaperHeight parameters and not search for best fit size provided by printer. SetPageSize must also be set.
Parameters
useCustomPaperSize pass true to use custom size.
useDefaultPrinter()
void com.datalogics.PDFL.PrintUserParams.useDefaultPrinter (Document doc)
Set the print parameters to the defaults. The parameters set include the printer, page range, paper size, number of copies, and duplexing mode.
Operating system defaults for these parameters will be copied into the corresponding PrintUserParams fields. If you want to override the system defaults, change these fields after calling UseDefaultPrinter().
Parameters
doc a Document which will be used to set the maximum page range.
Member Data Documentation
USE_CROP_BOX
final int com.datalogics.PDFL.PrintUserParams.USE_CROP_BOX static
When paper height and width are initialized to this value the crop box of each individual page will be used to determine the paper size.
USE_MEDIA_BOX
final int com.datalogics.PDFL.PrintUserParams.USE_MEDIA_BOX static
When paper height and width are initialized to this value the printed product more closely resembles what comes out of most PDF Viewers. This can eliminate some print problems, including PCL blank page problems.