Java API Reference: com.datalogics.PDFL.WatermarkParams Class Reference
com.datalogics.PDFL.WatermarkParams Class Reference
Public Member Functions
synchronized void delete ()
boolean getFixedPrint ()
HorizontalAlignment getHorizAlign ()
float getHorizValue ()
float getOpacity ()
boolean getPercentageVals ()
float getRotation ()
float getScale ()
boolean getShowOnPrint ()
boolean getShowOnScreen ()
PageRange getTargetRange ()
VerticalAlignment getVertAlign ()
float getVertValue ()
WatermarkDrawOption getWatermarkDrawOption ()
boolean getZOrderTop ()
void setFixedPrint (boolean value)
void setHorizAlign (HorizontalAlignment h)
void setHorizValue (float value)
void setOpacity (float value)
void setPercentageVals (boolean value)
void setRotation (float value)
void setScale (float value)
void setShowOnPrint (boolean value)
void setShowOnScreen (boolean value)
void setVertAlign (VerticalAlignment v)
void setVertValue (float value)
void setWatermarkDrawOption (WatermarkDrawOption drawoption)
void setZOrderTop (boolean value)
WatermarkParams ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
WatermarkParams (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (WatermarkParams obj)
Detailed Description
Watermark settings control the appearance of a watermark in a PDF.
Constructor & Destructor Documentation
WatermarkParams() [1/2]
com.datalogics.PDFL.WatermarkParams.WatermarkParams (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
WatermarkParams() [2/2]
com.datalogics.PDFL.WatermarkParams.WatermarkParams ()
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.WatermarkParams.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.WatermarkParams.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.WatermarkParams.finalize () protected
getCPtr()
long com.datalogics.PDFL.WatermarkParams.getCPtr (WatermarkParams obj) static protected
Referenced by com.datalogics.PDFL.Document.watermark(), and com.datalogics.PDFL.Document.watermark().
getFixedPrint()
boolean com.datalogics.PDFL.WatermarkParams.getFixedPrint ()
getHorizAlign()
HorizontalAlignment com.datalogics.PDFL.WatermarkParams.getHorizAlign ()
Get the horizontal alignment to be used when adding the watermark to a page.
getHorizValue()
float com.datalogics.PDFL.WatermarkParams.getHorizValue ()
getOpacity()
float com.datalogics.PDFL.WatermarkParams.getOpacity ()
getPercentageVals()
boolean com.datalogics.PDFL.WatermarkParams.getPercentageVals ()
getRotation()
float com.datalogics.PDFL.WatermarkParams.getRotation ()
getScale()
float com.datalogics.PDFL.WatermarkParams.getScale ()
getShowOnPrint()
boolean com.datalogics.PDFL.WatermarkParams.getShowOnPrint ()
getShowOnScreen()
boolean com.datalogics.PDFL.WatermarkParams.getShowOnScreen ()
getTargetRange()
PageRange com.datalogics.PDFL.WatermarkParams.getTargetRange ()
The page range of the document to which the watermark should be added.
getVertAlign()
VerticalAlignment com.datalogics.PDFL.WatermarkParams.getVertAlign ()
Get the vertical alignment to be used when adding the watermark to a page.
getVertValue()
float com.datalogics.PDFL.WatermarkParams.getVertValue ()
getWatermarkDrawOption()
WatermarkDrawOption com.datalogics.PDFL.WatermarkParams.getWatermarkDrawOption ()
Get the draw option to be used when adding the watermark to a page.
getZOrderTop()
boolean com.datalogics.PDFL.WatermarkParams.getZOrderTop ()
setFixedPrint()
void com.datalogics.PDFL.WatermarkParams.setFixedPrint (boolean value)
setHorizAlign()
void com.datalogics.PDFL.WatermarkParams.setHorizAlign (HorizontalAlignment h)
The horizontal alignment to be used when adding the watermark to a page.
setHorizValue()
void com.datalogics.PDFL.WatermarkParams.setHorizValue (float value)
setOpacity()
void com.datalogics.PDFL.WatermarkParams.setOpacity (float value)
setPercentageVals()
void com.datalogics.PDFL.WatermarkParams.setPercentageVals (boolean value)
setRotation()
void com.datalogics.PDFL.WatermarkParams.setRotation (float value)
setScale()
void com.datalogics.PDFL.WatermarkParams.setScale (float value)
setShowOnPrint()
void com.datalogics.PDFL.WatermarkParams.setShowOnPrint (boolean value)
setShowOnScreen()
void com.datalogics.PDFL.WatermarkParams.setShowOnScreen (boolean value)
setVertAlign()
void com.datalogics.PDFL.WatermarkParams.setVertAlign (VerticalAlignment v)
The vertical alignment to be used when adding the watermark to a page.
setVertValue()
void com.datalogics.PDFL.WatermarkParams.setVertValue (float value)
setWatermarkDrawOption()
void com.datalogics.PDFL.WatermarkParams.setWatermarkDrawOption (WatermarkDrawOption drawoption)
The draw option to be used when adding the watermark to a page.
setZOrderTop()
void com.datalogics.PDFL.WatermarkParams.setZOrderTop (boolean value)