Java API Reference: com.datalogics.PDFL.RectSegment Class Reference
com.datalogics.PDFL.RectSegment Class Reference
Public Member Functions
synchronized void delete ()
double getHeight ()
Point getPoint ()
double getWidth ()
RectSegment (double x, double y, double width, double height)
RectSegment (Point point, double width, double height)
void setHeight (double value)
void setPoint (Point value)
void setWidth (double value)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
RectSegment (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (RectSegment obj)
static long getCPtr (Segment obj)
Detailed Description
A rectangle path operator. RectSegment represents a single path, or line, within a rectangle, with coordinates xy, xy for the beginning and end of the line.
Constructor & Destructor Documentation
RectSegment() [1/3]
com.datalogics.PDFL.RectSegment.RectSegment (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
RectSegment() [2/3]
com.datalogics.PDFL.RectSegment.RectSegment (Point point, double width, double height)
Append a rectangle to the current path as a complete subpath, with lower-left corner point and dimensions width and height in user space.
Parameters
point the lower left corner of the rectangle.
width the width of the rectangle.
height the height of the rectangle.
RectSegment() [3/3]
com.datalogics.PDFL.RectSegment.RectSegment (double x, double y, double width, double height)
Append a rectangle to the current path as a complete subpath, with lower-left corner (x, y) and dimensions width and height in user space.
Parameters
x the left edge of the rectangle.
y the right edge of the rectangle.
width the width of the rectangle.
height the height of the rectangle.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.RectSegment.delete ()
Reimplemented from com.datalogics.PDFL.Segment.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.RectSegment.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Segment.
finalize()
void com.datalogics.PDFL.RectSegment.finalize () protected
Reimplemented from com.datalogics.PDFL.Segment.
getCPtr() [1/2]
long com.datalogics.PDFL.RectSegment.getCPtr (RectSegment obj) static protected
getCPtr() [2/2]
long com.datalogics.PDFL.Segment.getCPtr (Segment obj) static protected inherited
getHeight()
double com.datalogics.PDFL.RectSegment.getHeight ()
The height of the rectangle.
getPoint()
Point com.datalogics.PDFL.RectSegment.getPoint ()
The lower left corner of the rectangle.
getWidth()
double com.datalogics.PDFL.RectSegment.getWidth ()
The width of the rectangle.
setHeight()
void com.datalogics.PDFL.RectSegment.setHeight (double value)
The height of the rectangle.
setPoint()
void com.datalogics.PDFL.RectSegment.setPoint (Point value)
The lower left corner of the rectangle.
setWidth()
void com.datalogics.PDFL.RectSegment.setWidth (double value)
The width of the rectangle.
toString()
String com.datalogics.PDFL.RectSegment.toString ()
Reimplemented from com.datalogics.PDFL.Segment.