Java API Reference: com.datalogics.PDFL.Image Class Reference
com.datalogics.PDFL.Image Class Reference
Public Member Functions
Image changeResolution (int dpi)
Image clone ()
Image clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Image colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
synchronized void delete ()
int getBitsPerComponent ()
Rect getBoundingBox ()
java.awt.image.BufferedImage getBufferedImage ()
Clip getClip ()
ColorSpace getColorSpace ()
CompressionCode getCompression ()
byte[] getData ()
boolean getDidWarningsOccurDuringImport ()
GraphicState getGraphicState ()
int getHeight ()
String getIntent ()
boolean getIsImageMask ()
java.util.List< ImageData > getLargeData ()
Matrix getMatrix ()
int getNumberComponents ()
Image getSoftMask ()
PDFStream getStream ()
int getWidth ()
Image (byte[] buffer, int width, int height, ColorSpace colorSpace)
Image (javax.imageio.stream.ImageInputStream stream) throws java.io.IOException
Image (String fileName)
Image (String fileName, Document document)
void rotate (double angle)
void save (String imagefilename, ImageType imageType)
void save (String imagefilename, ImageType imageType, ImageSaveParams saveparams)
void scale (double sx, double sy)
void setClip (Clip clip)
void setCompression (CompressionCode code)
void setGraphicState (GraphicState gstate)
void setIntent (String intent)
void setMatrix (Matrix matrix)
void setSoftMask (Image softMask)
void translate (double tx, double ty)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
Image (long cPtr, boolean cMemoryOwn)
Image (StreamFile sf, boolean ignore) throws java.io.IOException
Static Protected Member Functions
static long getCPtr (Element obj)
static long getCPtr (Image obj)
Detailed Description
An image resource can either be an image XObject or inline image found in a page's content stream. An Image Xobject is stored separately from the graphics content stream in a PDF, and so can be used multiple times in the document, even across pages. The image is described in the /Xobject entry in the resources dictionary on the PDF page.
Image size and resoultion: For images that are imported from raster image files, the design width and height are stored in the Image object's Matrix, in the A (width) and D (depth) Matrix members, when the image is imported. These are stored in PDF units.
To derive the effective resolution of an image imported from a raster image file:
Horizontal resolution: divide the Image Width by the Image's Matrix A member and multiply by 72 to scale to DPI (dots per inch).
Vertical resolution: divide the Image Height by the Image's Matrix D member and multiply by 72 to scale to DPI (dots per inch).
Constructor & Destructor Documentation
Image() [1/6]
com.datalogics.PDFL.Image.Image (long cPtr, boolean cMemoryOwn) protected
Referenced by changeResolution(), clone(), clone(), colorConvert(), getCPtr(), getSoftMask(), and setSoftMask().
Image() [2/6]
com.datalogics.PDFL.Image.Image (javax.imageio.stream.ImageInputStream stream) throws java.io.IOException
Allows to create Image object from ImageInputStream.
Image() [3/6]
com.datalogics.PDFL.Image.Image (StreamFile sf, boolean ignore) throws java.io.IOException protected
Image() [4/6]
com.datalogics.PDFL.Image.Image (String fileName)
Create a new Image from an existing physical file. This file can be a bitmap, gif, jpeg, png, or a tiff file. An exception will be thrown if the image file is not any of the above.
NOTICE on tiff files: If the tiff file is multi-paged, then the first "page" only of the file will be converted to an Image. See ImageCollection to convert each page in a multi-page tiff file to an Image.
Parameters
fileName the filename of the image file.
Image() [5/6]
com.datalogics.PDFL.Image.Image (String fileName, Document document)
Create a new Image from an existing physical file. This file can be a bitmap, gif, jpeg, png, or a tiff file. An exception will be thrown if the image file is not any of the above.
Specifying the document optimizes data usage for this image within that document.
NOTICE on tiff files: If the tiff file is multi-paged, then the first "page" only of the file will be converted to an Image. See ImageCollection to convert each page in a multi-page tiff file to an Image.
Parameters
fileName the filename of the image file.
document the document in which the image is intended to be used.
Image() [6/6]
com.datalogics.PDFL.Image.Image (byte[] buffer, int width, int height, ColorSpace colorSpace)
Create an image from byte array. This constructor expects that input buffer is non-padded. If buffer doesn't correspond to the expected format, it will be stripped.
For example: The bitmap data generated by Page's drawContents(DrawParams) function is 32-bit aligned. The PDF image operator expects, however, 8-bit aligned image data. To remedy this difference, we check to see if the 32-bit aligned width is different from the 8-bit aligned width. If so, we fix the image data by stripping off the padding at the end.
Parameters
buffer contains Image's data
width width of the image
height height of the image
colorSpace colorspace with wich Image object will be created
Member Function Documentation
changeResolution()
Image com.datalogics.PDFL.Image.changeResolution (int dpi)
Create a new image from an existing one modifying the resolution (dots per inch)
Parameters
dpi the new resolution
Returns
newimage - the original image modified to the new resolution.
clone() [1/2]
Image com.datalogics.PDFL.Image.clone ()
Makes a copy of the image.
Make a copy of an image to obtain a new image that has a distinct set of attributes.
Returns
The copied image.
Reimplemented from com.datalogics.PDFL.Element.
clone() [2/2]
Image com.datalogics.PDFL.Image.clone (java.util.EnumSet< ElementCloneFlags > cloneFlags)
Makes a copy of the image.
Make a copy of an image to obtain a new image that has a distinct set of attributes.
Parameters
cloneFlags Flags that modify the cloning operation.
Returns
The copied image.
Reimplemented from com.datalogics.PDFL.Element.
colorConvert()
Image com.datalogics.PDFL.Image.colorConvert (Document document, ColorProfile prof, RenderIntent intent, boolean embed)
Applies the specified ICC ColorProfile to the Image
Parameters
document The document the element belongs to.
prof The ICC ColorProfile to be applied.
intent The ICC Rendering Intent for the ColorProfile
embed If true, embed the color space and make the object calibrated. If it is false and the target profile is CMYK, RGB, or Gray, the colors space of the resulting object, after conversion, will be DeviceCMYK, DeviceRGB, or DeviceGray, respectively.
Returns
A new Image with the applied ICC ColorProfile.
delete() [1/2]
synchronized void com.datalogics.PDFL.Image.delete ()
Reimplemented from com.datalogics.PDFL.Element.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.Image.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Element.
finalize()
void com.datalogics.PDFL.Image.finalize () protected
Reimplemented from com.datalogics.PDFL.Element.
getBitsPerComponent()
int com.datalogics.PDFL.Image.getBitsPerComponent ()
The number of bits per component in the image.
getBoundingBox()
Rect com.datalogics.PDFL.Element.getBoundingBox () inherited
The bounding box for this element.
The bounding box is a rectangle that is guaranteed to encompass the element, but it is not guaranteed to be the smallest box that could contain the element. For example, if the element is a Path that contains an arc, the bounding box encompasses the bezier control points, and not just the curve itself.
Returns
The bounding box for this element. The coordinates of the bounding box are specified in user space coordinates, relative to the element's Content. Note that user space coordinates correspond to unrotated pages; any rotation specified in the page dictionary is not taken into account.
getBufferedImage()
java.awt.image.BufferedImage com.datalogics.PDFL.Image.getBufferedImage ()
Return this PDF image as a Java BufferedImage.
Images in Gray or RGB color spaces are returned without conversion, while images in other spaces are first converted to RGB.
getClip()
Clip com.datalogics.PDFL.Element.getClip () inherited
Gets the current Clip for an Element.
Returns
- The current Clip for this Element.
getColorSpace()
ColorSpace com.datalogics.PDFL.Image.getColorSpace ()
return the ColorSpace with which this Image was created.
getCompression()
CompressionCode com.datalogics.PDFL.Image.getCompression ()
Returns
A compression code which represents the filter used in the image data.
getCPtr() [1/2]
long com.datalogics.PDFL.Element.getCPtr (Element obj) static protected inherited
Referenced by com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Clip.addElement(), com.datalogics.PDFL.Content.addElement(), com.datalogics.PDFL.Content.addElement(), and com.datalogics.PDFL.Content.Content().
getCPtr() [2/2]
long com.datalogics.PDFL.Image.getCPtr (Image obj) static protected
Referenced by com.datalogics.PDFL.ImageCollection.append(), com.datalogics.PDFL.ImageCollection.ImageCollection(), com.datalogics.PDFL.OCREngine.placeTextUnder(), com.datalogics.PDFL.OCREngine.placeTextUnder(), com.datalogics.PDFL.OCREngine.placeTextUnder(), com.datalogics.PDFL.OCREngine.placeTextUnder(), and com.datalogics.PDFL.OCREngine.placeTextUnder().
getData()
byte[] com.datalogics.PDFL.Image.getData ()
The actual bytes that make up the image, exactly as they appear in the image data.
getDidWarningsOccurDuringImport()
boolean com.datalogics.PDFL.Image.getDidWarningsOccurDuringImport ()
Gets whether or not warnings occurred during import of the raster image file.
getGraphicState()
GraphicState com.datalogics.PDFL.Image.getGraphicState ()
Get the graphic state of the current element.
getHeight()
int com.datalogics.PDFL.Image.getHeight ()
The height of the image in pixels.
Referenced by getBufferedImage().
getIntent()
String com.datalogics.PDFL.Image.getIntent ()
The color rendering intent for the image
getIsImageMask()
boolean com.datalogics.PDFL.Image.getIsImageMask ()
Check that Image is ImageMask object
getLargeData()
java.util.List< ImageData > com.datalogics.PDFL.Image.getLargeData ()
Gets the decompressed image data from very large images.
NOTE: This function is only supported in 64-bit, only if enough contiguous memory is available. The data size must exceed nearly 2GB, otherwise an exception is thrown and you would use the Data member instead to access the image data. The first members of the list returned contain a close to 2GB chunk of the data, but the last member containing the remaining data will be smaller in size. This faciliates retrieving the data in .NET and Java which have 2GB limits on object sizes.
getMatrix()
Matrix com.datalogics.PDFL.Element.getMatrix () inherited
The transformation matrix for the element.
getNumberComponents()
int com.datalogics.PDFL.Image.getNumberComponents ()
The number of components
Referenced by getBufferedImage().
getSoftMask()
Image com.datalogics.PDFL.Image.getSoftMask ()
Gets, for this image, the soft mask (also an image).
Returns
image - an image, the soft mask
getStream()
PDFStream com.datalogics.PDFL.Image.getStream ()
The PDFStream object or null if there is no stream associated with the image
getWidth()
int com.datalogics.PDFL.Image.getWidth ()
The width of the image in pixels.
Referenced by getBufferedImage().
rotate()
void com.datalogics.PDFL.Image.rotate (double angle)
Rotate an image on (angle) degree using the matrix [cos(a), sin(a), -sin(a), cos(a), 0, 0]. For images, this rotate is done without regard to the primary scaling of the original image
Reimplemented from com.datalogics.PDFL.Element.
save() [1/2]
void com.datalogics.PDFL.Image.save (String imagefilename, ImageType imageType)
Save an image into a particular file format with default parameters for saving.
Parameters
imagefilename The physical image file which will be created.
imageType The IMAGETYPE used for saving the image.
save() [2/2]
void com.datalogics.PDFL.Image.save (String imagefilename, ImageType imageType, ImageSaveParams saveparams)
Save an image into a particular file format with the given parameters for saving.
Parameters
imagefilename The physical image file which will be created.
imageType The ImageType used for saving the image.
saveparams The ImageSaveParams for saving the image.
scale()
void com.datalogics.PDFL.Element.scale (double sx, double sy) inherited
Scale an element by (sx,sy) units using the matrix [ sx 0 0 sy 0 0 ].
setClip()
void com.datalogics.PDFL.Element.setClip (Clip clip) inherited
Sets the current Clip for an Element.
Parameters
clip The clip to set as the current clip for this element.
setCompression()
void com.datalogics.PDFL.Image.setCompression (CompressionCode code)
Set a Compression scheme for the image data.
Parameters
code The new new compression scheme to be applied.
setGraphicState()
void com.datalogics.PDFL.Image.setGraphicState (GraphicState gstate)
Set the Graphic State of the current element.
Parameters
gstate the new/updated Graphic State for the element.
setIntent()
void com.datalogics.PDFL.Image.setIntent (String intent)
SetIntent allows to set color rendering intent for the image.
Parameters
intent the intent name
setMatrix()
void com.datalogics.PDFL.Element.setMatrix (Matrix matrix) inherited
Set the transformation matrix for the element.
Parameters
matrix the transformation matrix for the element.
setSoftMask()
void com.datalogics.PDFL.Image.setSoftMask (Image softMask)
Sets, for this image, the soft mask (also an image).
Parameters
softMask an image, the soft mask. If set to NULL, the soft mask is removed.
translate()
void com.datalogics.PDFL.Image.translate (double tx, double ty)
Translate an image by (tx,ty) units using the matrix [ 1 0 0 1 tx ty ]. For images, this translation is done without regard to the scaling and rotation of the original image.
To ensure that this translation can be done, do the translation before any further rotation or scaling.
Reimplemented from com.datalogics.PDFL.Element.