Java API Reference: com.datalogics.PDFL.SeparationParams Class Reference
com.datalogics.PDFL.SeparationParams Class Reference
Public Member Functions
synchronized void delete ()
boolean getApplyOCGPrintOverrides ()
boolean getBinaryChannelAvailable ()
boolean getConvertToProcessUsingOPP ()
boolean getConvertTrueTypeToType42 ()
String getDestinationProfileString ()
boolean getEmitAnnotations ()
SeparationFontOptions getEmitFontOption ()
boolean getEmitHalftones ()
boolean getEmitSeparableImagesOnly ()
boolean getEmitTransferFunctions ()
boolean getInvertPlates ()
MirrorOptions getMirrorPrint ()
OptionalContentContext getOCContext ()
java.util.EnumSet< PageMarkFlags > getPageMarksToEmit ()
java.util.List< SeparationPlate > getPlates ()
int getPostScriptLevel ()
boolean getPrinterHasFarEastFonts ()
boolean getSuppressCJKSubstitution ()
int getTransparencyLevel ()
boolean getUseCMYKWorkingColorSpace ()
boolean getUseWesternStylePageMarks ()
SeparationParams (java.util.List< SeparationPlate > plates)
void setApplyOCGPrintOverrides (boolean theSetting)
void setBinaryChannelAvailable (boolean isAvailable)
void setConvertToProcessUsingOPP (boolean theSetting)
void setConvertTrueTypeToType42 (boolean theSetting)
void setDestinationProfileString (String theDestProfile)
void setEmitAnnotations (boolean theSetting)
void setEmitFontOption (SeparationFontOptions theOption)
void setEmitHalftones (boolean theSetting)
void setEmitSeparableImagesOnly (boolean theSetting)
void setEmitTransferFunctions (boolean theSetting)
void setInvertPlates (boolean theSetting)
void setMirrorPrint (MirrorOptions theOption)
void setOCContext (OptionalContentContext theContext)
void setPageMarksToEmit (java.util.EnumSet< PageMarkFlags > theMarks)
void setPlates (java.util.List< SeparationPlate > thePlates)
void setPostScriptLevel (int theLevel)
void setPrinterHasFarEastFonts (boolean theSetting)
void setSuppressCJKSubstitution (boolean theSetting)
void setTransparencyLevel (int theLevel)
void setUseCMYKWorkingColorSpace (boolean theSetting)
void setUseWesternStylePageMarks (boolean theSetting)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
SeparationParams (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (SeparationParams obj)
Detailed Description
Holds parameters for making color separations.Used with PostScript.
Constructor & Destructor Documentation
SeparationParams() [1/2]
com.datalogics.PDFL.SeparationParams.SeparationParams (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr(), and SeparationParams().
SeparationParams() [2/2]
com.datalogics.PDFL.SeparationParams.SeparationParams (java.util.List< SeparationPlate > plates)
Set up default parameters for making separations.
Parameters
plates The plates to use for making separations.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.SeparationParams.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.SeparationParams.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.SeparationParams.finalize () protected
getApplyOCGPrintOverrides()
boolean com.datalogics.PDFL.SeparationParams.getApplyOCGPrintOverrides ()
If true, apply print-specific visibility state settings from the optional content group. Default is false.
getBinaryChannelAvailable()
boolean com.datalogics.PDFL.SeparationParams.getBinaryChannelAvailable ()
True if a binary channel to the printer is supported, false otherwise. Default is false.
getConvertToProcessUsingOPP()
boolean com.datalogics.PDFL.SeparationParams.getConvertToProcessUsingOPP ()
If true, use the overprint preview (OPP) for converting to process, which better simulates what would happen if the spot ink were really used. Default is false.
getConvertTrueTypeToType42()
boolean com.datalogics.PDFL.SeparationParams.getConvertTrueTypeToType42 ()
If true, send TrueType fonts as TrueType fonts (level 3 and most level 2 PS printers). If false, convert TrueType to T1 (typically desirable only for Level 1 PS where no TrueType handling is present). Default is false.
getCPtr()
long com.datalogics.PDFL.SeparationParams.getCPtr (SeparationParams obj) static protected
Referenced by com.datalogics.PDFL.Page.makeSeparations().
getDestinationProfileString()
String com.datalogics.PDFL.SeparationParams.getDestinationProfileString ()
The profile description of a valid CMYK profile, such as the strings seen in the color management preferences in a PDF Viewer (for example, "U.S. Web Coated (SWOP) v2"). Default is "U.S. Web Coated (SWOP) v2".
getEmitAnnotations()
boolean com.datalogics.PDFL.SeparationParams.getEmitAnnotations ()
If true, emit annotations. Default is false.
getEmitFontOption()
SeparationFontOptions com.datalogics.PDFL.SeparationParams.getEmitFontOption ()
Font output options. Default is EmitAllFonts.
getEmitHalftones()
boolean com.datalogics.PDFL.SeparationParams.getEmitHalftones ()
If true, emit halftones. Default is true.
getEmitSeparableImagesOnly()
boolean com.datalogics.PDFL.SeparationParams.getEmitSeparableImagesOnly ()
If true, emit separable images only. Default is false.
getEmitTransferFunctions()
boolean com.datalogics.PDFL.SeparationParams.getEmitTransferFunctions ()
If true, emit transfer functions. Default is true.
getInvertPlates()
boolean com.datalogics.PDFL.SeparationParams.getInvertPlates ()
If true, invert the plates. Default is false.
getMirrorPrint()
MirrorOptions com.datalogics.PDFL.SeparationParams.getMirrorPrint ()
Options for mirroring. Mirroring is done in the PostScript output stream. Default is DontFlip.
getOCContext()
OptionalContentContext com.datalogics.PDFL.SeparationParams.getOCContext ()
The optional content context to use for visibility state information, or NULL to use the document's current states in the default context. Default is NULL.
getPageMarksToEmit()
java.util.EnumSet< PageMarkFlags > com.datalogics.PDFL.SeparationParams.getPageMarksToEmit ()
The page marks to emit for this plate. It is a bit-wise OR of the PageMarkFlags values. Default is None.
getPlates()
java.util.List< SeparationPlate > com.datalogics.PDFL.SeparationParams.getPlates ()
A list of plates to use for separations.
getPostScriptLevel()
int com.datalogics.PDFL.SeparationParams.getPostScriptLevel ()
The PostScript printing level. 2 means emit as level 2, 3 means level 3. Default is level 2.
getPrinterHasFarEastFonts()
boolean com.datalogics.PDFL.SeparationParams.getPrinterHasFarEastFonts ()
If true, do not include Far East fonts. Default is false.
getSuppressCJKSubstitution()
boolean com.datalogics.PDFL.SeparationParams.getSuppressCJKSubstitution ()
If true, suppress CJK substitution. Default is false.
getTransparencyLevel()
int com.datalogics.PDFL.SeparationParams.getTransparencyLevel ()
The transparency flattening quality level. Range is from 0 to 100. Lower values flatten faster. Higher values provide better quality. Default is 75.
getUseCMYKWorkingColorSpace()
boolean com.datalogics.PDFL.SeparationParams.getUseCMYKWorkingColorSpace ()
If true, color manage DeviceCMYK. If false, pass it directly onto the process plates. Default is false.
getUseWesternStylePageMarks()
boolean com.datalogics.PDFL.SeparationParams.getUseWesternStylePageMarks ()
If true, use the western style for page marks. Default is false.
setApplyOCGPrintOverrides()
void com.datalogics.PDFL.SeparationParams.setApplyOCGPrintOverrides (boolean theSetting)
If true, apply print-specific visibility state settings from the optional content group. Default is false.
setBinaryChannelAvailable()
void com.datalogics.PDFL.SeparationParams.setBinaryChannelAvailable (boolean isAvailable)
True if a binary channel to the printer is supported, false otherwise. Default is false.
setConvertToProcessUsingOPP()
void com.datalogics.PDFL.SeparationParams.setConvertToProcessUsingOPP (boolean theSetting)
If true, use the overprint preview (OPP) for converting to process, which better simulates what would happen if the spot ink were really used. Default is false.
setConvertTrueTypeToType42()
void com.datalogics.PDFL.SeparationParams.setConvertTrueTypeToType42 (boolean theSetting)
If true, send TrueType fonts as TrueType fonts (level 3 and most level 2 PS printers). If false, convert TrueType to T1 (typically desirable only for Level 1 PS where no TrueType handling is present). Default is false.
setDestinationProfileString()
void com.datalogics.PDFL.SeparationParams.setDestinationProfileString (String theDestProfile)
The profile description of a valid CMYK profile, such as the strings seen in the color management preferences in a PDF Viewr (for example, "U.S. Web Coated (SWOP) v2"). Default is "U.S. Web Coated (SWOP) v2".
setEmitAnnotations()
void com.datalogics.PDFL.SeparationParams.setEmitAnnotations (boolean theSetting)
If true, emit annotations. Default is false.
setEmitFontOption()
void com.datalogics.PDFL.SeparationParams.setEmitFontOption (SeparationFontOptions theOption)
Font output options. Default is EmitAllFonts.
setEmitHalftones()
void com.datalogics.PDFL.SeparationParams.setEmitHalftones (boolean theSetting)
If true, emit halftones. Default is true.
setEmitSeparableImagesOnly()
void com.datalogics.PDFL.SeparationParams.setEmitSeparableImagesOnly (boolean theSetting)
If true, emit separable images only. Default is false.
setEmitTransferFunctions()
void com.datalogics.PDFL.SeparationParams.setEmitTransferFunctions (boolean theSetting)
If true, emit transfer functions. Default is true.
setInvertPlates()
void com.datalogics.PDFL.SeparationParams.setInvertPlates (boolean theSetting)
If true, invert the plates. Default is false.
setMirrorPrint()
void com.datalogics.PDFL.SeparationParams.setMirrorPrint (MirrorOptions theOption)
Options for mirroring. Mirroring is done in the PostScript output stream. Default is DontFlip.
setOCContext()
void com.datalogics.PDFL.SeparationParams.setOCContext (OptionalContentContext theContext)
The optional content context to use for visibility state information, or NULL to use the document's current states in the default context. Default is NULL.
setPageMarksToEmit()
void com.datalogics.PDFL.SeparationParams.setPageMarksToEmit (java.util.EnumSet< PageMarkFlags > theMarks)
The page marks to emit for this plate. It is a bit-wise OR of the PageMarkFlags values. Default is None.
setPlates()
void com.datalogics.PDFL.SeparationParams.setPlates (java.util.List< SeparationPlate > thePlates)
A list of plates to use for separations.
setPostScriptLevel()
void com.datalogics.PDFL.SeparationParams.setPostScriptLevel (int theLevel)
The PostScript printing level. 2 means emit as level 2, 3 means level 3. Default is level 2.
setPrinterHasFarEastFonts()
void com.datalogics.PDFL.SeparationParams.setPrinterHasFarEastFonts (boolean theSetting)
If true, do not include Far East fonts. Default is false.
setSuppressCJKSubstitution()
void com.datalogics.PDFL.SeparationParams.setSuppressCJKSubstitution (boolean theSetting)
If true, suppress CJK substitution. Default is false.
setTransparencyLevel()
void com.datalogics.PDFL.SeparationParams.setTransparencyLevel (int theLevel)
The transparency flattening quality level. Range is from 0 to 100. Lower values flatten faster. Higher values provide better quality. Default is 75.
setUseCMYKWorkingColorSpace()
void com.datalogics.PDFL.SeparationParams.setUseCMYKWorkingColorSpace (boolean theSetting)
If true, color manage DeviceCMYK. If false, pass it directly onto the process plates. Default is false.
setUseWesternStylePageMarks()
void com.datalogics.PDFL.SeparationParams.setUseWesternStylePageMarks (boolean theSetting)
If true, use the western style for page marks. Default is false.