Java API Reference: com.datalogics.PDFL.ExtendedGraphicState Class Reference
com.datalogics.PDFL.ExtendedGraphicState Class Reference
Public Member Functions
synchronized void delete ()
ExtendedGraphicState ()
boolean getAlphaIsShape ()
boolean getApplyAutoStroke ()
boolean getApplyOverprintForOtherThanStroking ()
boolean getApplyOverprintForStroking ()
Function getBlackGeneration ()
BlendMode getBlendMode ()
double getOpacityForOtherThanStroking ()
double getOpacityForStroking ()
OverprintMode getOverprintMode ()
PDFDict getPDFDict ()
double getSmoothnessTolerance ()
boolean getTextKnockout ()
java.util.List< Function > getTransferFunction ()
Function getUndercolorRemoval ()
void setAlphaIsShape (boolean alphaIsShape)
void setApplyAutoStroke (boolean applyAutoStrokeAdjustment)
void setApplyOverprintForOtherThanStroking (boolean applyOverprintForOtherThanStroking)
void setApplyOverprintForStroking (boolean applyOverprintForStroking)
void setBlackGeneration (Function function)
void setBlendMode (BlendMode blendMode)
void setOpacityForOtherThanStroking (double opacity)
void setOpacityForStroking (double opacity)
void setOverprintMode (OverprintMode overprintMode)
void setSmoothnessTolerance (double tolerance)
void setTextKnockout (boolean enabled)
void setTransferFunction (java.util.List< Function > function)
void setUndercolorRemoval (Function function)
Protected Member Functions
synchronized void delete (Boolean disposing)
ExtendedGraphicState (long cPtr, boolean cMemoryOwn)
void finalize ()
Static Protected Member Functions
static long getCPtr (ExtendedGraphicState obj)
Detailed Description
The extended graphic state, to supplement original graphic state. The Graphics State is an internal data structure in a PDF file that holds the parameters that describe graphics within that file. These parameters define how individual graphics are presented on the page, including layers and transparencies.
The Extended Graphic State was introduced to expand the original Graphics State data structure, providing space to define and store more data objects within a PDF.
Constructor & Destructor Documentation
ExtendedGraphicState() [1/2]
com.datalogics.PDFL.ExtendedGraphicState.ExtendedGraphicState (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
ExtendedGraphicState() [2/2]
com.datalogics.PDFL.ExtendedGraphicState.ExtendedGraphicState ()
Create a new default ExtendedGraphicState for the document in which this ExtendedGraphicState will be used.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.ExtendedGraphicState.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.ExtendedGraphicState.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.ExtendedGraphicState.finalize () protected
getAlphaIsShape()
boolean com.datalogics.PDFL.ExtendedGraphicState.getAlphaIsShape ()
Returns if the alpha is to be interpreted as a shape or opacity mask.
Returns
alphaIsShape - if set true, interpret sources of alpha as shape, else interpret as opacity mask.
getApplyAutoStroke()
boolean com.datalogics.PDFL.ExtendedGraphicState.getApplyAutoStroke ()
Returns whether stroke adjustment is enabled in the graphics state.
Returns
applyAutoStrokeAdjustment - whether it is enabled, true or false.
getApplyOverprintForOtherThanStroking()
boolean com.datalogics.PDFL.ExtendedGraphicState.getApplyOverprintForOtherThanStroking ()
Specifies if overprint is enabled for operations other than stroking.
Returns
applyOverprintForOtherThanStroking
getApplyOverprintForStroking()
boolean com.datalogics.PDFL.ExtendedGraphicState.getApplyOverprintForStroking ()
Specifies if overprint is enabled for stroke operations.
Returns
applyOverprintForStroking
getBlackGeneration()
Function com.datalogics.PDFL.ExtendedGraphicState.getBlackGeneration ()
Gets the black generation function.
Returns
function - the black generation function.
getBlendMode()
BlendMode com.datalogics.PDFL.ExtendedGraphicState.getBlendMode ()
Returns the blend mode for the color composite for each object painted.
Returns
blendMode - the blend mode used in object painting.
getCPtr()
long com.datalogics.PDFL.ExtendedGraphicState.getCPtr (ExtendedGraphicState obj) static protected
Referenced by com.datalogics.PDFL.GraphicState.setExtendedGraphicState().
getOpacityForOtherThanStroking()
double com.datalogics.PDFL.ExtendedGraphicState.getOpacityForOtherThanStroking ()
Gets the opacity value for other-than-stroke operations.
Returns
opacity, a value between 0.0 and 1.0.
getOpacityForStroking()
double com.datalogics.PDFL.ExtendedGraphicState.getOpacityForStroking ()
Gets the opacity value for stroke operations.
Returns
opacity, a value between 0.0 and 1.0.
getOverprintMode()
OverprintMode com.datalogics.PDFL.ExtendedGraphicState.getOverprintMode ()
Specifies the overprint mode - specifying whether a color component value of 0 in a DeviceCMYK color space should erase that component or leave it unchanged when overprinting.
Returns
overprintMode - the mode setting.
getPDFDict()
PDFDict com.datalogics.PDFL.ExtendedGraphicState.getPDFDict ()
Get the dictionary associated with the extended graphic state.
Returns
The dictionary associated with the extended graphic state.
getSmoothnessTolerance()
double com.datalogics.PDFL.ExtendedGraphicState.getSmoothnessTolerance ()
Gets the smoothness tolerance, the quality of smooth shading.
Returns
tolerance, a value between 0.0 and 1.0.
getTextKnockout()
boolean com.datalogics.PDFL.ExtendedGraphicState.getTextKnockout ()
Returns whether text knockout is enabled in the graphics state.
Returns
enabled - if true, text knockout is enabled.
getTransferFunction()
java.util.List< Function > com.datalogics.PDFL.ExtendedGraphicState.getTransferFunction ()
Gets the transfer function.
Returns
function - the transfer function.
getUndercolorRemoval()
Function com.datalogics.PDFL.ExtendedGraphicState.getUndercolorRemoval ()
Gets the undercolor removal function.
Returns
function - the undercolor removal function.
setAlphaIsShape()
void com.datalogics.PDFL.ExtendedGraphicState.setAlphaIsShape (boolean alphaIsShape)
Specifies if the alpha is to be interpreted as a shape or opacity mask.
Parameters
alphaIsShape if set true, interpret sources of alpha as shape, else interpret as opacity mask.
setApplyAutoStroke()
void com.datalogics.PDFL.ExtendedGraphicState.setApplyAutoStroke (boolean applyAutoStrokeAdjustment)
Specifies whether stroke adjustment is enabled in the graphics state.
Parameters
applyAutoStrokeAdjustment whether it is enabled, true or false.
setApplyOverprintForOtherThanStroking()
void com.datalogics.PDFL.ExtendedGraphicState.setApplyOverprintForOtherThanStroking (boolean applyOverprintForOtherThanStroking)
Specifies if overprint is enabled for operations other than stroking.
Parameters
applyOverprintForOtherThanStroking whether to enable overprint for stroke operations.
setApplyOverprintForStroking()
void com.datalogics.PDFL.ExtendedGraphicState.setApplyOverprintForStroking (boolean applyOverprintForStroking)
Specifies if overprint is enabled for stroke operations.
Parameters
applyOverprintForStroking whether to enable overprint for stroke operations.
setBlackGeneration()
void com.datalogics.PDFL.ExtendedGraphicState.setBlackGeneration (Function function)
Sets the black generation function.
Parameters
function the black generation function.
setBlendMode()
void com.datalogics.PDFL.ExtendedGraphicState.setBlendMode (BlendMode blendMode)
Sets the blend mode for the color composites for each object painted.
Parameters
blendMode the blend mode used in object painting.
setOpacityForOtherThanStroking()
void com.datalogics.PDFL.ExtendedGraphicState.setOpacityForOtherThanStroking (double opacity)
Sets the opacity value for other-than-stroke operations.
Parameters
opacity the opacity level, from 0.0 to 1.0, inclusive.
setOpacityForStroking()
void com.datalogics.PDFL.ExtendedGraphicState.setOpacityForStroking (double opacity)
Sets the opacity value for stroke operations.
Parameters
opacity the opacity level, from 0.0 to 1.0, inclusive.
setOverprintMode()
void com.datalogics.PDFL.ExtendedGraphicState.setOverprintMode (OverprintMode overprintMode)
Specifies the overprint mode - specifying whether a color component value of 0 in a DeviceCMYK color space should erase that component or leave it unchanged when overprinting.
Parameters
overprintMode the mode setting.
setSmoothnessTolerance()
void com.datalogics.PDFL.ExtendedGraphicState.setSmoothnessTolerance (double tolerance)
Sets the smoothness tolerance, the quality of smooth shading.
Parameters
tolerance the smoothness tolerance, from 0.0 to 1.0, inclusive.
setTextKnockout()
void com.datalogics.PDFL.ExtendedGraphicState.setTextKnockout (boolean enabled)
Specifies whether text knockout is enabled in the graphics state.
Parameters
enabled if set true, text knockout will be enabled.
setTransferFunction()
void com.datalogics.PDFL.ExtendedGraphicState.setTransferFunction (java.util.List< Function > function)
Sets the transfer function.
Parameters
function the transfer function.
setUndercolorRemoval()
void com.datalogics.PDFL.ExtendedGraphicState.setUndercolorRemoval (Function function)
Sets the undercolor removal function.
Parameters
function the undercolor removal function.