Java API Reference: com.datalogics.PDFL.PaperSource Class Reference
com.datalogics.PDFL.PaperSource Class Reference
Public Member Functions
synchronized void delete ()
Static Public Attributes
static final int AUTO
static final int CASSETTE
static final int ENV_MAUAL
static final int ENVELOPE
static final int FIRST
static final int FORM_SOURCE
static final int LARGE_CAPACITY
static final int LARGE_FMT
static final int LAST
static final int LOWER
static final int MANUAL
static final int MIDDLE
static final int ONLY_ONE
static final int SMALL_FMT
static final int TRACTOR
static final int UPPER
static final int USE_SYSTEM_DEFAULT
static final int USER
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
PaperSource (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (PaperSource obj)
Detailed Description
Defines a set of paper trays in a printer that can be used to select the paper source when printing.
Constructor & Destructor Documentation
PaperSource()
com.datalogics.PDFL.PaperSource.PaperSource (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.PaperSource.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.PaperSource.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.PaperSource.finalize () protected
getCPtr()
long com.datalogics.PDFL.PaperSource.getCPtr (PaperSource obj) static protected
Member Data Documentation
AUTO
final int com.datalogics.PDFL.PaperSource.AUTO static
Auto select based on paper size
CASSETTE
final int com.datalogics.PDFL.PaperSource.CASSETTE static
Use paper from the cassette tray
ENV_MAUAL
final int com.datalogics.PDFL.PaperSource.ENV_MAUAL static
Use paper from the envelope manual feed
ENVELOPE
final int com.datalogics.PDFL.PaperSource.ENVELOPE static
Use paper from the envelope tray
FIRST
final int com.datalogics.PDFL.PaperSource.FIRST static
Use paper from the upper tray
See also
PaperSource.Upper
FORM_SOURCE
final int com.datalogics.PDFL.PaperSource.FORM_SOURCE static
Use paper from the forms tray
LARGE_CAPACITY
final int com.datalogics.PDFL.PaperSource.LARGE_CAPACITY static
Use paper from the large capacity tray
LARGE_FMT
final int com.datalogics.PDFL.PaperSource.LARGE_FMT static
Use paper from the large forms tray
LAST
final int com.datalogics.PDFL.PaperSource.LAST static
Use paper from the forms tray
See also
PaperSource.FormSource
LOWER
final int com.datalogics.PDFL.PaperSource.LOWER static
Use paper from the lower tray
MANUAL
final int com.datalogics.PDFL.PaperSource.MANUAL static
Use paper from the manual feed
MIDDLE
final int com.datalogics.PDFL.PaperSource.MIDDLE static
Use paper from the middle tray
ONLY_ONE
final int com.datalogics.PDFL.PaperSource.ONLY_ONE static
Use paper from the upper tray
See also
PaperSource.Upper
SMALL_FMT
final int com.datalogics.PDFL.PaperSource.SMALL_FMT static
Use paper from the small forms tray
TRACTOR
final int com.datalogics.PDFL.PaperSource.TRACTOR static
Use paper from the tractor feed
UPPER
final int com.datalogics.PDFL.PaperSource.UPPER static
Use paper from the upper tray
USE_SYSTEM_DEFAULT
final int com.datalogics.PDFL.PaperSource.USE_SYSTEM_DEFAULT static
Use the default paper source
USER
final int com.datalogics.PDFL.PaperSource.USER static
Use paper from device specific trays by setting PaperSource to a value larger than User