Java API Reference: com.datalogics.PDFL.LinkAnnotation Class Reference
com.datalogics.PDFL.LinkAnnotation Class Reference
Public Member Functions
LinkAnnotation copyTo (Page destination)
LinkAnnotation copyTo (Page destination, Point centerPoint)
synchronized void delete ()
boolean equals (Object rhs)
Form generateAppearance ()
Action getAction ()
double getAnnotationFeatureLevel ()
String getBorderStyle ()
java.util.List< Double > getBorderStyleDashPattern ()
double getBorderStyleWidth ()
Color getColor ()
String getContents ()
ViewDestination getDestination ()
java.util.EnumSet< AnnotationFlags > getFlags ()
HighlightStyle getHighlight ()
Color getInteriorColor ()
Form getNormalAppearance ()
double getOpacity ()
OptionalContentMembershipDict getOptionalContentMembershipDict ()
PDFDict getPDFDict ()
Rect getRect ()
String getSubtype ()
String getTitle ()
boolean hasRichTextData ()
boolean isCurrentlyVisible (OptionalContentContext occ)
LinkAnnotation (Page page, Rect initialRect)
LinkAnnotation (Page page, Rect initialRect, int addAfter)
void setAction (Action newaction)
void setAnnotationFeatureLevel (double featureLevel)
void setBorderStyle (String style)
void setBorderStyleDashPattern (java.util.List< Double > dashPattern)
void setBorderStyleWidth (double width)
void setColor (Color arg0)
void setContents (String arg0)
void setDestination (ViewDestination newdest)
void setFlags (java.util.EnumSet< AnnotationFlags > arg0)
void setHighlight (HighlightStyle style)
void setInteriorColor (Color color)
void setNormalAppearance (Form form)
void setOpacity (double opacityValue)
void setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd)
void setRect (Rect rect)
void setTitle (String title)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
LinkAnnotation (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Annotation obj)
static long getCPtr (LinkAnnotation obj)
Detailed Description
A link annotation, which features an embedded hyperlink.
Constructor & Destructor Documentation
LinkAnnotation() [1/3]
com.datalogics.PDFL.LinkAnnotation.LinkAnnotation (long cPtr, boolean cMemoryOwn) protected
Referenced by copyTo(), copyTo(), and getCPtr().
LinkAnnotation() [2/3]
com.datalogics.PDFL.LinkAnnotation.LinkAnnotation (Page page, Rect initialRect)
Create a new LinkAnnotation at the end of a page's annotation array. To create a LinkAnnotation and place it elsewhere in the page's annotation array, use the version of the constructor that takes an array position.
Parameters
page The page to which the LinkAnnotation is added.
initialRect A rectangle specifying the annotation's bounds, specified in user space coordinates.
LinkAnnotation() [3/3]
com.datalogics.PDFL.LinkAnnotation.LinkAnnotation (Page page, Rect initialRect, int addAfter)
Create a new LinkAnnotation at a specific index in the page's annotation array.
Parameters
page The page to which the annotation is added.
initialRect A rectangle specifying the annotation's bounds, specified in user space coordinates.
addAfter Where to add the annotation in the page's annotation array. To add the annotation to the end of the array, pass a value of -2 or use the alternate version of this constructor that does not take an index (this is generally what you should do unless you have a need to place the annotation at a special location in the array). Passing a value of -1 adds the annotation to the beginning of the array. Passing other negative values produces undefined results.
Member Function Documentation
copyTo() [1/2]
LinkAnnotation com.datalogics.PDFL.LinkAnnotation.copyTo (Page destination)
Copy a LinkAnnotation to the specified page. The annotation will be centered on the page. To center the annotation at a specific point, use the version of this method that accepts a Point.
This creates a copy of the original LinkAnnotation and puts the copy in the destination page's annotation dictionary. Structural content information associated with the source annotation will not be present in the copy. An exception will be thrown if the annotation cannot be copied to the specified page.
Note: If copying LinkAnnotations between pages in different documents, the source annotation may have a ViewDestination that's invalid in the destiantion document or an Action referring to a ViewDestination that's invalid in the destination document. In these cases, an exception will be thrown.
Parameters
destination the page to copy the annotation to. The page may be in the same document as the source annotation or in a different document.
Returns
the annotation created on the destination page.
copyTo() [2/2]
LinkAnnotation com.datalogics.PDFL.LinkAnnotation.copyTo (Page destination, Point centerPoint)
Copy a LinkAnnotation to the specified page and center the annotation on the specified point.
This creates a copy of the original LinkAnnotation and puts the copy in the destination page's annotation dictionary. Structural content information associated with the source annotation will not be present in the copy. An exception will be thrown if the annotation cannot be copied to the specified page.
Note: If copying LinkAnnotations between pages in different documents, the source annotation may have a ViewDestination that's invalid in the destiantion document or an Action referring to a ViewDestination that's invalid in the destination document. In these cases, an exception will be thrown.
Parameters
destination the page to copy the annotation to. The page may be in the same document as the source annotation or in a different document.
centerPoint the point to center the annotation on.
Returns
the annotation created on the destination page.
delete() [1/2]
synchronized void com.datalogics.PDFL.LinkAnnotation.delete ()
Reimplemented from com.datalogics.PDFL.Annotation.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.LinkAnnotation.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Annotation.
equals()
boolean com.datalogics.PDFL.Annotation.equals (Object rhs) inherited
finalize()
void com.datalogics.PDFL.LinkAnnotation.finalize () protected
Reimplemented from com.datalogics.PDFL.Annotation.
generateAppearance()
Form com.datalogics.PDFL.LinkAnnotation.generateAppearance ()
Generate a new appearance stream with the current annotation properties.
The resulting Form can then be used to set the annotation's appearance, such as by calling SetNormalAppearance.
Reimplemented from com.datalogics.PDFL.Annotation.
getAction()
Action com.datalogics.PDFL.LinkAnnotation.getAction ()
The Action object for this link.
Note that setting the Action will wipe out the Link's Destination member a link annotation cannot have both members.
getAnnotationFeatureLevel()
double com.datalogics.PDFL.LinkAnnotation.getAnnotationFeatureLevel ()
The minimum PDF version necessary to support the features used in this annotation.
Reimplemented from com.datalogics.PDFL.Annotation.
getBorderStyle()
String com.datalogics.PDFL.LinkAnnotation.getBorderStyle ()
The border style.
Can be one of:
S - Solid
D - Dashed. The dash pattern is specified as an array (see DashPattern)
B - Beveled
I - Inset
U - Underline
Other border styles may be defined in the future. Default is "S"
getBorderStyleDashPattern()
java.util.List< Double > com.datalogics.PDFL.LinkAnnotation.getBorderStyleDashPattern ()
An array defining a pattern of dashes and gaps to be used in drawing a dashed border (border style D).
The dash array is a series of numbers that specify the lengths of alternating dashes and gaps. Lengths must be nonnegative, and are expressed in user space units.
Default value is [3]
getBorderStyleWidth()
double com.datalogics.PDFL.LinkAnnotation.getBorderStyleWidth ()
The border width in points.
If this value is 0, no border is drawn. The default is 1.0.
getColor()
Color com.datalogics.PDFL.Annotation.getColor () inherited
The color of the annotation.
Reimplemented in com.datalogics.PDFL.FreeTextAnnotation.
getContents()
String com.datalogics.PDFL.Annotation.getContents () inherited
The text to be displayed for the annotation or, if this type of annotation does not display text, an alternate description of the annotation's contents in human-readable form.
getCPtr() [1/2]
long com.datalogics.PDFL.Annotation.getCPtr (Annotation obj) static protected inherited
Referenced by com.datalogics.PDFL.Page.addAnnotation().
getCPtr() [2/2]
long com.datalogics.PDFL.LinkAnnotation.getCPtr (LinkAnnotation obj) static protected
getDestination()
ViewDestination com.datalogics.PDFL.LinkAnnotation.getDestination ()
The Destination for this link.
Note that setting the Destination will wipe out the Link's Action member a link annotation cannot have both members.
getFlags()
java.util.EnumSet< AnnotationFlags > com.datalogics.PDFL.Annotation.getFlags () inherited
The flags for the annotation.
getHighlight()
HighlightStyle com.datalogics.PDFL.LinkAnnotation.getHighlight ()
The Highlighstyle for this link.
getInteriorColor()
Color com.datalogics.PDFL.Annotation.getInteriorColor () inherited
The interior color with which to fill the annotation's line endings.
The color of the line itself can be retrieved from Annotation.Color.
getNormalAppearance()
Form com.datalogics.PDFL.Annotation.getNormalAppearance () inherited
getOpacity()
double com.datalogics.PDFL.Annotation.getOpacity () inherited
The optional constant opacity value that shall be used in painting a Markup annotation.
Opacity is a range from 0.0 (fully transparent) to 1.0 (fully opaque).
getOptionalContentMembershipDict()
OptionalContentMembershipDict com.datalogics.PDFL.Annotation.getOptionalContentMembershipDict () inherited
The OptionalContentMembershipDict property for this Annotation.
Setting this property will attach the Annotation to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Annotation is detached from any OptionalContentMembershipDict.
Returns
the OptionalContentMembershipDict
getPDFDict()
PDFDict com.datalogics.PDFL.Annotation.getPDFDict () inherited
Retrieve the PDFObject representation of this object
getRect()
Rect com.datalogics.PDFL.Annotation.getRect () inherited
The size and location of the annotation on its page
getSubtype()
String com.datalogics.PDFL.Annotation.getSubtype () inherited
The annotation's subtype
getTitle()
String com.datalogics.PDFL.Annotation.getTitle () inherited
The title of the annotation.
hasRichTextData()
boolean com.datalogics.PDFL.Annotation.hasRichTextData () inherited
Checks the annotation for Rich Text String content (PDFReference 1.7 Section 8.6.2). Annotations that contain Rich Text String content and do not have a normal appearance set will not be visible when rendering the page.
isCurrentlyVisible()
boolean com.datalogics.PDFL.Annotation.isCurrentlyVisible (OptionalContentContext occ) inherited
Tests whether an annotation is visible in a given optional content context, considering the current ON-OFF states of the optional-content groups in the optional-content dictionary (OCMD) and the dictionary's visibility policy.
If the annotation occurs more than once within the content, this method only checks the visibility of the first occurrence of the annotation.
This method determines visibility without considering the visbility of the Content object that the annotation belongs to. To determine the visibility of an annotation while taking the Content's visibility into consideration, use the alternate version of this method.
Returns
true if the annotation is currently visible.
setAction()
void com.datalogics.PDFL.LinkAnnotation.setAction (Action newaction)
The Action object for this link.
Note that setting the Action will wipe out the Link's Destination member a link annotation cannot have both members.
setAnnotationFeatureLevel()
void com.datalogics.PDFL.LinkAnnotation.setAnnotationFeatureLevel (double featureLevel)
Removes features not supported in the supplied version number.
Reimplemented from com.datalogics.PDFL.Annotation.
setBorderStyle()
void com.datalogics.PDFL.LinkAnnotation.setBorderStyle (String style)
The border style.
Can be one of:
S - Solid
D - Dashed. The dash pattern is specified as an array (see DashPattern)
B - Beveled
I - Inset
U - Underline
Other border styles may be defined in the future. Default is "S"
setBorderStyleDashPattern()
void com.datalogics.PDFL.LinkAnnotation.setBorderStyleDashPattern (java.util.List< Double > dashPattern)
An array defining a pattern of dashes and gaps to be used in drawing a dashed border (border style D).
The dash array is a series of numbers that specify the lengths of alternating dashes and gaps. Lengths must be nonnegative, and are expressed in user space units.
Default value is [3]
setBorderStyleWidth()
void com.datalogics.PDFL.LinkAnnotation.setBorderStyleWidth (double width)
The border width in points.
If this value is 0, no border is drawn. The default is 1.0.
setColor()
void com.datalogics.PDFL.Annotation.setColor (Color arg0) inherited
The color of the annotation.
Reimplemented in com.datalogics.PDFL.FreeTextAnnotation.
setContents()
void com.datalogics.PDFL.Annotation.setContents (String arg0) inherited
The text to be displayed for the annotation or, if this type of annotation does not display text, an alternate description of the annotation's contents in human-readable form.
setDestination()
void com.datalogics.PDFL.LinkAnnotation.setDestination (ViewDestination newdest)
The Destination for this link.
Note that setting the Destination will wipe out the Link's Action member a link annotation cannot have both members.
setFlags()
void com.datalogics.PDFL.Annotation.setFlags (java.util.EnumSet< AnnotationFlags > arg0) inherited
The flags for the annotation.
setHighlight()
void com.datalogics.PDFL.LinkAnnotation.setHighlight (HighlightStyle style)
The Highlighstyle for this link.
setInteriorColor()
void com.datalogics.PDFL.Annotation.setInteriorColor (Color color) inherited
The interior color with which to fill the annotation's line endings.
Only RGB colors are allowed.
The color of the line itself can be retrieved from Annotation.Color.
setNormalAppearance()
void com.datalogics.PDFL.Annotation.setNormalAppearance (Form form) inherited
setOpacity()
void com.datalogics.PDFL.Annotation.setOpacity (double opacityValue) inherited
The optional constant opacity value that shall be used in painting a Markup annotation.
Opacity is a range from 0.0 (fully transparent) to 1.0 (fully opaque).
setOptionalContentMembershipDict()
void com.datalogics.PDFL.Annotation.setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd) inherited
The OptionalContentMembershipDict property for this Annotation.
Setting this property will attach the Annotation to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Annotation is detached from any OptionalContentMembershipDict.
Parameters
ocmd the OptionalContentMembershipDict
setRect()
void com.datalogics.PDFL.Annotation.setRect (Rect rect) inherited
The size and location of the annotation on its page
setTitle()
void com.datalogics.PDFL.Annotation.setTitle (String title) inherited
The title of the annotation.
toString()
String com.datalogics.PDFL.Annotation.toString () inherited