Java API Reference: com.datalogics.PDFL.OptionalContentMembershipDict Class Reference
com.datalogics.PDFL.OptionalContentMembershipDict Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
java.util.List< OptionalContentGroup > getOptionalContentGroups ()
PDFArray getVisibilityExpression ()
VisibilityPolicy getVisibilityPolicy ()
OptionalContentMembershipDict (Document doc, java.util.List< OptionalContentGroup > ocgs, VisibilityPolicy vp)
OptionalContentMembershipDict (Document doc, java.util.List< OptionalContentGroup > ocgs, VisibilityPolicy vp, PDFArray visibilityExpression)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
OptionalContentMembershipDict (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (OptionalContentMembershipDict obj)
Detailed Description
Attaches content to one or more optional content groups. Form, container, and annotation objects can be associated with one or more optional content groups. By associating them with an optional content group, they become part of that 'layer', and the user can control the visibility of the content.
Note that by placing other element objects in a container, they can also be associated with an optional content group.
An OptionalContentMembershipDict connects content to the OptionalContentGroup; it contains a list of OptionalContentGroups, and rules for determining visibility when the OptionalContentGroups have conflicting on/off states in the active OptionalContentContext.
An OptionalContentMembershipDict cannot be changed once created; you must create a new OptionalContentMembershipDict and change the objects to point to it.
Constructor & Destructor Documentation
OptionalContentMembershipDict() [1/3]
com.datalogics.PDFL.OptionalContentMembershipDict.OptionalContentMembershipDict (long cPtr, boolean cMemoryOwn) protected
Referenced by equals(), getCPtr(), OptionalContentMembershipDict(), and OptionalContentMembershipDict().
OptionalContentMembershipDict() [2/3]
com.datalogics.PDFL.OptionalContentMembershipDict.OptionalContentMembershipDict (Document doc, java.util.List< OptionalContentGroup > ocgs, VisibilityPolicy vp)
Create a new OptionalContentMembershipDict.
Parameters
doc The document that the new OptionalContentMembershipDict will belong to.
ocgs The list of OptionalContentGroups this MembershipDict refers to.
vp The VisibilityPolicy of this MembershipDict.
OptionalContentMembershipDict() [3/3]
com.datalogics.PDFL.OptionalContentMembershipDict.OptionalContentMembershipDict (Document doc, java.util.List< OptionalContentGroup > ocgs, VisibilityPolicy vp, PDFArray visibilityExpression)
Create a new OptionalContentMembershipDict.
Parameters
doc The document that the new OptionalContentMembershipDict will belong to.
ocgs The list of OptionalContentGroups this MembershipDict refers to.
vp The VisibilityPolicy of this MembershipDict.
visibilityExpression The VisibilityExpression of this MembershipDict.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.OptionalContentMembershipDict.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.OptionalContentMembershipDict.delete (Boolean disposing) protected
equals()
boolean com.datalogics.PDFL.OptionalContentMembershipDict.equals (Object rhs)
finalize()
void com.datalogics.PDFL.OptionalContentMembershipDict.finalize () protected
getCPtr()
long com.datalogics.PDFL.OptionalContentMembershipDict.getCPtr (OptionalContentMembershipDict obj) static protected
Referenced by com.datalogics.PDFL.Annotation.setOptionalContentMembershipDict(), com.datalogics.PDFL.Container.setOptionalContentMembershipDict(), and com.datalogics.PDFL.Form.setOptionalContentMembershipDict().
getOptionalContentGroups()
java.util.List< OptionalContentGroup > com.datalogics.PDFL.OptionalContentMembershipDict.getOptionalContentGroups ()
Gets the list of OptionalContentGroups for this membership dictionary. This may consist of one OCG or several.
Returns
An array containing OptionalContentGroups.
getVisibilityExpression()
PDFArray com.datalogics.PDFL.OptionalContentMembershipDict.getVisibilityExpression ()
GetVisibilityExpression Gets the Visibility Expression for this membership dictionary.
Returns
A Visibility Expression array.
getVisibilityPolicy()
VisibilityPolicy com.datalogics.PDFL.OptionalContentMembershipDict.getVisibilityPolicy ()
Gets the Visbility Policy for this membership dictionary.
Returns
A Visibility Policy.
toString()
String com.datalogics.PDFL.OptionalContentMembershipDict.toString ()