Java API Reference: com.datalogics.PDFL.Collection Class Reference
com.datalogics.PDFL.Collection Class Reference
Public Member Functions
void changeCollectionViewMode (CollectionViewType view, CollectionSplitType split)
synchronized void delete ()
CollectionSchema getSchema ()
java.util.List< CollectionSortItem > getSort ()
void setSort (java.util.List< CollectionSortItem > sort)
Protected Member Functions
Collection (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (Collection obj)
Detailed Description
Allows for manipulation of PDF collections, or portfolios. The class illustrates how to process a collection's schema. It also describes sorting of a portfolio.
Constructor & Destructor Documentation
Collection()
com.datalogics.PDFL.Collection.Collection (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
Member Function Documentation
changeCollectionViewMode()
void com.datalogics.PDFL.Collection.changeCollectionViewMode (CollectionViewType view, CollectionSplitType split)
SetCollectionView sets view mode value to the Collection.
Parameters
view one of the members of CollectionViewMode enum.
split enum of split mode (selector)
delete() [1/2]
synchronized void com.datalogics.PDFL.Collection.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.Collection.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.Collection.finalize () protected
getCPtr()
long com.datalogics.PDFL.Collection.getCPtr (Collection obj) static protected
getSchema()
CollectionSchema com.datalogics.PDFL.Collection.getSchema ()
GetSchema allows to obtain Schema object for current Collection. The Schema object does not have constructor. Only Collection is able to create Schema.
Returns
Schema object.
getSort()
java.util.List< CollectionSortItem > com.datalogics.PDFL.Collection.getSort ()
GetSort gets sort parameters for the Collection.
Returns
the list of CollectionSortItem, which contains field/fields name to sort Collection by and sort order.
setSort()
void com.datalogics.PDFL.Collection.setSort (java.util.List< CollectionSortItem > sort)
SetSort allows to set field/fields to sort by as well as sort order (ascending or descending).
Parameters
sort the list of CollectionSortItem.