Java API Reference: com.datalogics.PDFL.OCRParams Class Reference
com.datalogics.PDFL.OCRParams Class Reference
Public Member Functions
synchronized void delete ()
java.util.List< String > getCandidateFontNames ()
java.util.Map< String, String > getConfigurationParameters ()
boolean getEnableImagePreprocessing ()
String getEngine ()
java.util.List< LanguageSetting > getLanguages ()
PageSegmentationMode getPageSegmentationMode ()
Performance getPerformance ()
double getResolution ()
OCRParams ()
void setCandidateFontNames (java.util.List< String > candidateFontNames)
void setConfigurationParameters (java.util.Map< String, String > configurationParameters)
void setEnableImagePreprocessing (boolean enable)
void setEngine (String engine)
void setLanguages (java.util.List< LanguageSetting > languages)
void setPageSegmentationMode (PageSegmentationMode mode)
void setPerformance (Performance performance)
void setResolution (double resolution)
Static Public Member Functions
static String getTesseract4Engine ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
OCRParams (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (OCRParams obj)
Constructor & Destructor Documentation
OCRParams() [1/2]
com.datalogics.PDFL.OCRParams.OCRParams (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
OCRParams() [2/2]
com.datalogics.PDFL.OCRParams.OCRParams ()
Create an OCRParams structure with defaults.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.OCRParams.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.OCRParams.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.OCRParams.finalize () protected
getCandidateFontNames()
java.util.List< String > com.datalogics.PDFL.OCRParams.getCandidateFontNames ()
The names of candidate fonts for placing text under an image. The default list should work well in most cases. If you're using text that isn't represented by Latin fonts, or by Chinese, Japanese, or Korean fonts, then retrieve this list, add the font that can represent that text, then set that new list on this object.
Enough font names must be supplied to cover the expected languages/scripts in use.
The code selects a font to represent each word. If a word code-switches between different scripts, for instance, if it contains non-Latin text and Arabic numerals, then make sure to supply the name of a font family that can handle both the text and the numerals.
The quality of the results depends on the font choice. The list is searched in order until a font works for a particular word. To make the text fit better, it's recommended to list proportional fonts before fixed-width fonts. Decorative fonts with flourishes, like Zapf Chancery, deliver poor results. Generally, supply a font that would be used in block text, such as in a newspaper or work of literature, such as Times Roman, or a font already in the list, like MinionPro.
If the PlaceTextUnder method in OCREngine can't identify a font that covers the whole text of a word, an exception will be thrown.
getConfigurationParameters()
java.util.Map< String, String > com.datalogics.PDFL.OCRParams.getConfigurationParameters ()
Get the configuration parameters. Note: Reserved for internal use. Do not use unless directed to by Datalogics Support.
getCPtr()
long com.datalogics.PDFL.OCRParams.getCPtr (OCRParams obj) static protected
Referenced by com.datalogics.PDFL.OCREngine.OCREngine().
getEnableImagePreprocessing()
boolean com.datalogics.PDFL.OCRParams.getEnableImagePreprocessing ()
Get the image preprocessing enable state.True if any image preprocessing is on.
getEngine()
String com.datalogics.PDFL.OCRParams.getEngine ()
The engine in use.
getLanguages()
java.util.List< LanguageSetting > com.datalogics.PDFL.OCRParams.getLanguages ()
The list of languages to use.
getPageSegmentationMode()
PageSegmentationMode com.datalogics.PDFL.OCRParams.getPageSegmentationMode ()
The page segmentation mode.
getPerformance()
Performance com.datalogics.PDFL.OCRParams.getPerformance ()
The desired engine performance.
getResolution()
double com.datalogics.PDFL.OCRParams.getResolution ()
Each image will use this resolution by default.
getTesseract4Engine()
String com.datalogics.PDFL.OCRParams.getTesseract4Engine () static
Specify the Tesseract v4 engine.Pass this to the engine property.
setCandidateFontNames()
void com.datalogics.PDFL.OCRParams.setCandidateFontNames (java.util.List< String > candidateFontNames)
The names of candidate fonts for placing text under an image. The default list should work well in most cases. If you're using text that isn't represented by Latin fonts, or by Chinese, Japanese, or Korean fonts, then retrieve this list, add the font that can represent that text, then set that new list on this object.
Enough font names must be supplied to cover the expected languages/scripts in use.
The code selects a font to represent each word. If a word code-switches between different scripts, for instance, if it contains non-Latin text and Arabic numerals, then make sure to supply the name of a font family that can handle both the text and the numerals.
The quality of the results depends on the font choice. The list is searched in order until a font works for a particular word. To make the text fit better, it's recommended to list proportional fonts before fixed-width fonts. Decorative fonts with flourishes, like Zapf Chancery, deliver poor results. Generally, supply a font that would be used in block text, such as in a newspaper or work of literature, such as Times Roman, or a font already in the list, like MinionPro.
If the PlaceTextUnder method in OCREngine can't identify a font that covers the whole text of a word, an exception will be thrown.
setConfigurationParameters()
void com.datalogics.PDFL.OCRParams.setConfigurationParameters (java.util.Map< String, String > configurationParameters)
Set the configuration parameters. Note: Reserved for internal use. Do not use unless directed to by Datalogics Support.
setEnableImagePreprocessing()
void com.datalogics.PDFL.OCRParams.setEnableImagePreprocessing (boolean enable)
Enable all image preprocessing, default enabled.Note that once the OCREngine is initialized, this setting is permanent.
setEngine()
void com.datalogics.PDFL.OCRParams.setEngine (String engine)
The engine in use.
setLanguages()
void com.datalogics.PDFL.OCRParams.setLanguages (java.util.List< LanguageSetting > languages)
The list of languages to use.
setPageSegmentationMode()
void com.datalogics.PDFL.OCRParams.setPageSegmentationMode (PageSegmentationMode mode)
The page segmentation mode.
setPerformance()
void com.datalogics.PDFL.OCRParams.setPerformance (Performance performance)
The desired engine performance.
setResolution()
void com.datalogics.PDFL.OCRParams.setResolution (double resolution)
Each image will use this resolution by default.