Java API Reference: com.datalogics.PDFL.GoToAction Class Reference
com.datalogics.PDFL.GoToAction Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
ViewDestination getDestination ()
PDFDict getPDFDict ()
String getSubtype ()
GoToAction (ViewDestination dest)
void setDestination (ViewDestination dest)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
GoToAction (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Action obj)
static long getCPtr (GoToAction obj)
Detailed Description
A go-to action can be executed in a PDF document. A go-to action includes a hyperlink that, when clicked, takes the reader to a different place within the same document.
The action is linked to a bookmark within the document.
A remote go-to action includes a hyperlink that takes the reader to a destination in a separate document.
Constructor & Destructor Documentation
GoToAction() [1/2]
com.datalogics.PDFL.GoToAction.GoToAction (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
GoToAction() [2/2]
com.datalogics.PDFL.GoToAction.GoToAction (ViewDestination dest)
General constructor
Parameters
dest The ViewDestination contained in this class.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.GoToAction.delete ()
Reimplemented from com.datalogics.PDFL.Action.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.GoToAction.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Action.
equals()
boolean com.datalogics.PDFL.Action.equals (Object rhs) inherited
finalize()
void com.datalogics.PDFL.GoToAction.finalize () protected
Reimplemented from com.datalogics.PDFL.Action.
getCPtr() [1/2]
long com.datalogics.PDFL.Action.getCPtr (Action obj) static protected inherited
Referenced by com.datalogics.PDFL.Bookmark.setAction(), and com.datalogics.PDFL.LinkAnnotation.setAction().
getCPtr() [2/2]
long com.datalogics.PDFL.GoToAction.getCPtr (GoToAction obj) static protected
getDestination()
ViewDestination com.datalogics.PDFL.GoToAction.getDestination ()
The Destination for this action
getPDFDict()
PDFDict com.datalogics.PDFL.Action.getPDFDict () inherited
Retrieve the PDFObject representation of this object
getSubtype()
String com.datalogics.PDFL.Action.getSubtype () inherited
The action's subtype
setDestination()
void com.datalogics.PDFL.GoToAction.setDestination (ViewDestination dest)
The Destination for this action
toString()
String com.datalogics.PDFL.Action.toString () inherited