Java API Reference: com.datalogics.PDFL.UnderlineAnnotation Class Reference
com.datalogics.PDFL.UnderlineAnnotation Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
Form generateAppearance ()
String getAnnotatedText (boolean splitLines)
double getAnnotationFeatureLevel ()
Color getColor ()
String getContents ()
java.util.EnumSet< AnnotationFlags > getFlags ()
Color getInteriorColor ()
Form getNormalAppearance ()
double getOpacity ()
OptionalContentMembershipDict getOptionalContentMembershipDict ()
PDFDict getPDFDict ()
java.util.List< Quad > getQuads ()
Rect getRect ()
String getSubtype ()
String getTitle ()
boolean hasRichTextData ()
boolean isCurrentlyVisible (OptionalContentContext occ)
void setAnnotationFeatureLevel (double featureLevel)
void setColor (Color arg0)
void setContents (String arg0)
void setFlags (java.util.EnumSet< AnnotationFlags > arg0)
void setInteriorColor (Color color)
void setNormalAppearance (Form form)
void setOpacity (double opacityValue)
void setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd)
void setQuads (java.util.List< Quad > theQuads)
void setRect (Rect rect)
void setTitle (String title)
String toString ()
UnderlineAnnotation (Page page, int addAfter, java.util.List< Quad > quadList)
UnderlineAnnotation (Page page, java.util.List< Quad > quadList)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
UnderlineAnnotation (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Annotation obj)
static long getCPtr (TextMarkupAnnotation obj)
static long getCPtr (UnderlineAnnotation obj)
Detailed Description
A type of text markup annotation, for underlining text. Text markup annotations added to a PDF file appear as highlights, underlines, or strikeouts. The Underline Annotation appears PDF document as underlined text when the documnent is opened in a PDF Viewer.
Constructor & Destructor Documentation
UnderlineAnnotation() [1/3]
com.datalogics.PDFL.UnderlineAnnotation.UnderlineAnnotation (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr(), UnderlineAnnotation(), and UnderlineAnnotation().
UnderlineAnnotation() [2/3]
com.datalogics.PDFL.UnderlineAnnotation.UnderlineAnnotation (Page page, java.util.List< Quad > quadList)
Create a new UnderlineAnnotation at the end of a page's annotation array. To create a FreeTextAnnotation and place it elsewhere in the page's annotation array, use the version of the constructor that takes an array position.
Parameters
page The page to which the UnderlineAnnotation is added.
quadList A list of quads to underline. Each quad encompasses a word or group of contiguous words in the text underlying the annotation.
UnderlineAnnotation() [3/3]
com.datalogics.PDFL.UnderlineAnnotation.UnderlineAnnotation (Page page, int addAfter, java.util.List< Quad > quadList)
Create a new UnderlineAnnotation at a specific index in the page's annotation array.
Parameters
page The page to which the UnderlineAnnotation is added.
quadList A list of quads to underline. Each quad encompasses a word or group of contiguous words in the text underlying the annotation.
addAfter Where to add the annotation in the page's annotation array. To add the annotation to the end of the array, pass a value of -2 or use the alternate version of this constructor that does not take an index (this is generally what you should do unless you have a need to place the annotation at a special location in the array). Passing a value of -1 adds the annotation to the beginning of the array. Passing other negative values produces undefined results.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.UnderlineAnnotation.delete ()
Reimplemented from com.datalogics.PDFL.TextMarkupAnnotation.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.UnderlineAnnotation.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.TextMarkupAnnotation.
equals()
boolean com.datalogics.PDFL.Annotation.equals (Object rhs) inherited
finalize()
void com.datalogics.PDFL.UnderlineAnnotation.finalize () protected
Reimplemented from com.datalogics.PDFL.TextMarkupAnnotation.
generateAppearance()
Form com.datalogics.PDFL.UnderlineAnnotation.generateAppearance ()
Generate a new appearance stream with the current annotation properties.
The resulting Form can then be used to set the annotation's appearance, such as by calling SetNormalAppearance.
Reimplemented from com.datalogics.PDFL.Annotation.
getAnnotatedText()
String com.datalogics.PDFL.TextMarkupAnnotation.getAnnotatedText (boolean splitLines) inherited
The text that is marked by the annotation. Marked text is defined as text which falls within one or more of the quadrilaterals specified by the annotation's QuadPoints entry. If the annotation marks partial words, only those portions of the word that are bounded within the QuadPoints array will be returned. If the annotation marks partial characters, the characters that fall partially within the annotation bounds may not be returned.
Parameters
splitLines If true, text corresponding to each quadrilateral will be separated by CRLF characters. If false, text corresponding to each quadrilateral will be separated by spaces.
Returns
The text marked by the annotation.
getAnnotationFeatureLevel()
double com.datalogics.PDFL.TextMarkupAnnotation.getAnnotationFeatureLevel () inherited
The minimum PDF version necessary to support the features used in this annotation.
Reimplemented from com.datalogics.PDFL.Annotation.
getColor()
Color com.datalogics.PDFL.Annotation.getColor () inherited
The color of the annotation.
Reimplemented in com.datalogics.PDFL.FreeTextAnnotation.
getContents()
String com.datalogics.PDFL.Annotation.getContents () inherited
The text to be displayed for the annotation or, if this type of annotation does not display text, an alternate description of the annotation's contents in human-readable form.
getCPtr() [1/3]
long com.datalogics.PDFL.Annotation.getCPtr (Annotation obj) static protected inherited
Referenced by com.datalogics.PDFL.Page.addAnnotation().
getCPtr() [2/3]
long com.datalogics.PDFL.TextMarkupAnnotation.getCPtr (TextMarkupAnnotation obj) static protected inherited
getCPtr() [3/3]
long com.datalogics.PDFL.UnderlineAnnotation.getCPtr (UnderlineAnnotation obj) static protected
getFlags()
java.util.EnumSet< AnnotationFlags > com.datalogics.PDFL.Annotation.getFlags () inherited
The flags for the annotation.
getInteriorColor()
Color com.datalogics.PDFL.Annotation.getInteriorColor () inherited
The interior color with which to fill the annotation's line endings.
The color of the line itself can be retrieved from Annotation.Color.
getNormalAppearance()
Form com.datalogics.PDFL.Annotation.getNormalAppearance () inherited
getOpacity()
double com.datalogics.PDFL.Annotation.getOpacity () inherited
The optional constant opacity value that shall be used in painting a Markup annotation.
Opacity is a range from 0.0 (fully transparent) to 1.0 (fully opaque).
getOptionalContentMembershipDict()
OptionalContentMembershipDict com.datalogics.PDFL.Annotation.getOptionalContentMembershipDict () inherited
The OptionalContentMembershipDict property for this Annotation.
Setting this property will attach the Annotation to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Annotation is detached from any OptionalContentMembershipDict.
Returns
the OptionalContentMembershipDict
getPDFDict()
PDFDict com.datalogics.PDFL.Annotation.getPDFDict () inherited
Retrieve the PDFObject representation of this object
getQuads()
java.util.List< Quad > com.datalogics.PDFL.TextMarkupAnnotation.getQuads () inherited
A list of quads to mark. Each quad encompasses a word or group of contiguous words in the text underlying the annotation.
getRect()
Rect com.datalogics.PDFL.Annotation.getRect () inherited
The size and location of the annotation on its page
getSubtype()
String com.datalogics.PDFL.Annotation.getSubtype () inherited
The annotation's subtype
getTitle()
String com.datalogics.PDFL.Annotation.getTitle () inherited
The title of the annotation.
hasRichTextData()
boolean com.datalogics.PDFL.Annotation.hasRichTextData () inherited
Checks the annotation for Rich Text String content (PDFReference 1.7 Section 8.6.2). Annotations that contain Rich Text String content and do not have a normal appearance set will not be visible when rendering the page.
isCurrentlyVisible()
boolean com.datalogics.PDFL.Annotation.isCurrentlyVisible (OptionalContentContext occ) inherited
Tests whether an annotation is visible in a given optional content context, considering the current ON-OFF states of the optional-content groups in the optional-content dictionary (OCMD) and the dictionary's visibility policy.
If the annotation occurs more than once within the content, this method only checks the visibility of the first occurrence of the annotation.
This method determines visibility without considering the visbility of the Content object that the annotation belongs to. To determine the visibility of an annotation while taking the Content's visibility into consideration, use the alternate version of this method.
Returns
true if the annotation is currently visible.
setAnnotationFeatureLevel()
void com.datalogics.PDFL.TextMarkupAnnotation.setAnnotationFeatureLevel (double featureLevel) inherited
Removes features not supported in the supplied version number.
Reimplemented from com.datalogics.PDFL.Annotation.
setColor()
void com.datalogics.PDFL.Annotation.setColor (Color arg0) inherited
The color of the annotation.
Reimplemented in com.datalogics.PDFL.FreeTextAnnotation.
setContents()
void com.datalogics.PDFL.Annotation.setContents (String arg0) inherited
The text to be displayed for the annotation or, if this type of annotation does not display text, an alternate description of the annotation's contents in human-readable form.
setFlags()
void com.datalogics.PDFL.Annotation.setFlags (java.util.EnumSet< AnnotationFlags > arg0) inherited
The flags for the annotation.
setInteriorColor()
void com.datalogics.PDFL.Annotation.setInteriorColor (Color color) inherited
The interior color with which to fill the annotation's line endings.
Only RGB colors are allowed.
The color of the line itself can be retrieved from Annotation.Color.
setNormalAppearance()
void com.datalogics.PDFL.Annotation.setNormalAppearance (Form form) inherited
setOpacity()
void com.datalogics.PDFL.Annotation.setOpacity (double opacityValue) inherited
The optional constant opacity value that shall be used in painting a Markup annotation.
Opacity is a range from 0.0 (fully transparent) to 1.0 (fully opaque).
setOptionalContentMembershipDict()
void com.datalogics.PDFL.Annotation.setOptionalContentMembershipDict (OptionalContentMembershipDict ocmd) inherited
The OptionalContentMembershipDict property for this Annotation.
Setting this property will attach the Annotation to an OptionalContentMembershipDict; it will then be associated with the OptionalContentGroups and be subject to the VisibilityPolicy and VisibilityExpression of that MembershipDict.
By setting this property to null, the Annotation is detached from any OptionalContentMembershipDict.
Parameters
ocmd the OptionalContentMembershipDict
setQuads()
void com.datalogics.PDFL.TextMarkupAnnotation.setQuads (java.util.List< Quad > theQuads) inherited
A list of quads to mark. Each quad encompasses a word or group of contiguous words in the text underlying the annotation.
setRect()
void com.datalogics.PDFL.Annotation.setRect (Rect rect) inherited
The size and location of the annotation on its page
setTitle()
void com.datalogics.PDFL.Annotation.setTitle (String title) inherited
The title of the annotation.
toString()
String com.datalogics.PDFL.Annotation.toString () inherited