Java API Reference: com.datalogics.PDFL.LineTo Class Reference
com.datalogics.PDFL.LineTo Class Reference
Public Member Functions
synchronized void delete ()
Point getPoint ()
LineTo (double x, double y)
LineTo (Point lineToPoint)
void setPoint (Point value)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
LineTo (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (LineTo obj)
static long getCPtr (Segment obj)
Detailed Description
A lineto operator, which draws a straight line. A lineto operator creates a line path element. It draws a straight line from the current position (MoveTo) to a new position-a new set of (x,y) coordinates: MoveTo{x:0 y:50} LineTo{x:100 y:100}
Constructor & Destructor Documentation
LineTo() [1/3]
com.datalogics.PDFL.LineTo.LineTo (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
LineTo() [2/3]
com.datalogics.PDFL.LineTo.LineTo (Point lineToPoint)
Create a line to a new point.Append a straight line segment from the current point to the lineToPoint.The new current point is the point the line is drawn to.
LineTo() [3/3]
com.datalogics.PDFL.LineTo.LineTo (double x, double y)
Move to a new current point.Append a straight line segment from the current point to the point (x, y).The new current point is the point the line is drawn to.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.LineTo.delete ()
Reimplemented from com.datalogics.PDFL.Segment.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.LineTo.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Segment.
finalize()
void com.datalogics.PDFL.LineTo.finalize () protected
Reimplemented from com.datalogics.PDFL.Segment.
getCPtr() [1/2]
long com.datalogics.PDFL.LineTo.getCPtr (LineTo obj) static protected
getCPtr() [2/2]
long com.datalogics.PDFL.Segment.getCPtr (Segment obj) static protected inherited
getPoint()
Point com.datalogics.PDFL.LineTo.getPoint ()
The new current point.
setPoint()
void com.datalogics.PDFL.LineTo.setPoint (Point value)
The new current point.
toString()
String com.datalogics.PDFL.LineTo.toString ()
Reimplemented from com.datalogics.PDFL.Segment.