Java API Reference: com.datalogics.PDFL.SignDoc Class Reference
com.datalogics.PDFL.SignDoc Class Reference
Public Member Functions
void addDigitalSignature (Document document)
void createCancelProc (CancelProc cancelProc)
void createProgressMonitor (ProgressMonitor progMon)
synchronized void delete ()
CredentialDataFmt getCredentialDataFormat ()
DigestCategory getDigestCategory ()
SignatureType getDocSignType ()
SignatureFieldID getFieldID ()
String getFieldName ()
String getOutputPath ()
long getSignatureBoxPageNumber ()
Rect getSignatureBoxRectangle ()
void setCredentialDataFormat (CredentialDataFmt value)
void setDigestCategory (DigestCategory value)
void setDocSignType (SignatureType value)
void setFieldID (SignatureFieldID value)
void setFieldName (String name)
void setFieldObject (int aValue, int bValue)
void setNonPfxPassPhrase (String passPhrase, long passphraseSize, CredentialStorageFmt storageFmt)
void setNonPfxPrivateKey (String privateKey, long keySize, CredentialStorageFmt storageFmt)
void setNonPfxSignerCert (String signerCert, long certSize, CredentialStorageFmt storageFmt)
void setOutputPath (String newPath)
void setPfxCredentials (String credentials, CredentialStorageFmt storageFmt)
void setPfxPassPhrase (String passphrase, long passphraseSize, CredentialStorageFmt storageFmt)
void setSignatureBoxPageNumber (long value)
void setSignatureBoxRectangle (Rect rect)
void setSignerInfo (String logoFilePath, float logoOpacity, String name, String location, String reason, String contactInfo, DisplayTraits displayTraits)
SignDoc ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
SignDoc (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (SignDoc obj)
Detailed Description
Implementation of the PDF SignDoc function. Use the SignDoc object to digitally sign a document
Constructor & Destructor Documentation
SignDoc() [1/2]
com.datalogics.PDFL.SignDoc.SignDoc (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
SignDoc() [2/2]
com.datalogics.PDFL.SignDoc.SignDoc ()
Creates an empty SignDoc object and initializes memory for its parameters.
Member Function Documentation
addDigitalSignature()
void com.datalogics.PDFL.SignDoc.addDigitalSignature (Document document)
Adds a digital signature using the specified credentials. If the document has not been previously signed, signs and saves the entire document. If the document has been previously signed, signs and saves only the portions of the document that have changed. If the document has been previously signed and the path to which the file is saved is NULL or the same as the path specified by the parameter, doc, signs and copies the document, saving only the portions of the document that have changed.
createCancelProc()
void com.datalogics.PDFL.SignDoc.createCancelProc (CancelProc cancelProc)
Create Cancel Callback
createProgressMonitor()
void com.datalogics.PDFL.SignDoc.createProgressMonitor (ProgressMonitor progMon)
Create Progress Monitor
delete() [1/2]
synchronized void com.datalogics.PDFL.SignDoc.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.SignDoc.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.SignDoc.finalize () protected
getCPtr()
long com.datalogics.PDFL.SignDoc.getCPtr (SignDoc obj) static protected
getCredentialDataFormat()
CredentialDataFmt com.datalogics.PDFL.SignDoc.getCredentialDataFormat ()
Get the value of the credential data format option.
Returns
- Format of user-credentials used to sign the document.
getDigestCategory()
DigestCategory com.datalogics.PDFL.SignDoc.getDigestCategory ()
Get the value of the digest category.
Returns
- Member of the enumeration DigestCategory, which option to set.
getDocSignType()
SignatureType com.datalogics.PDFL.SignDoc.getDocSignType ()
Get the type of signature added to a document.
Returns
- Member of the enumeration CSignatureType set in a document.
getFieldID()
SignatureFieldID com.datalogics.PDFL.SignDoc.getFieldID ()
Get the field identifier used to determine the form field that will contain the digital signature.
Returns
- SignatureFieldID choice currently set
getFieldName()
String com.datalogics.PDFL.SignDoc.getFieldName ()
Get the form field fully qualified name of the form field that contains the digital signature.
Returns
- Fully qualified field name. May return NULL based on the SignatureFieldID attribute defined by the user.
getOutputPath()
String com.datalogics.PDFL.SignDoc.getOutputPath ()
Get Output Path The path to which the file is saved. A path must be specified in case a full save (PDSaveFull) is needed. In case of an incremental save (PDSaveIncremental), newPath should be set to NULL. If a full save (PDSaveFull) is performed and newPath is the same as the file's original path, the new file is saved to a file system determined temporary path. The old file is then deleted and the new file is renamed to newPath.
getSignatureBoxPageNumber()
long com.datalogics.PDFL.SignDoc.getSignatureBoxPageNumber ()
Get the page number on which the widget annotation of the signature field is created.
Returns
- The page number on which signature field's widget annotation is created. A value of zero is returned if page number was not set.
getSignatureBoxRectangle()
Rect com.datalogics.PDFL.SignDoc.getSignatureBoxRectangle ()
Get the dimension of the annotation rectangle of the signature field being created.
Returns
- Dimension of the annotation rectangle of the signature field being created. A value of {0,0,0,0} is returned if annotation rectangle dimension was not set.
setCredentialDataFormat()
void com.datalogics.PDFL.SignDoc.setCredentialDataFormat (CredentialDataFmt value)
Set the value of the credential data format option.
Parameters
value Encoding format of credentials used to sign a document.
setDigestCategory()
void com.datalogics.PDFL.SignDoc.setDigestCategory (DigestCategory value)
Set the value of the digest category.
Parameters
value Cryptographic hash function to use for generating message digests.
setDocSignType()
void com.datalogics.PDFL.SignDoc.setDocSignType (SignatureType value)
Set the type of signature to be added to a document.
Parameters
value Member of the enumeration CSignatureType to be added to a document.
setFieldID()
void com.datalogics.PDFL.SignDoc.setFieldID (SignatureFieldID value)
Set the field identifier used to determine the form field that will contain the digital signature.
Parameters
value Identifier to determine the form field that will contain the digital signature.
setFieldName()
void com.datalogics.PDFL.SignDoc.setFieldName (String name)
Set the form field fully qualified name option.
Parameters
name Fully qualified name of the form field that will contain the digital signature.
setFieldObject()
void com.datalogics.PDFL.SignDoc.setFieldObject (int aValue, int bValue)
Set the form field CosObject option.
Parameters
aValue a value of the CosObject.
bValue b value of the CosObject.
setNonPfxPassPhrase()
void com.datalogics.PDFL.SignDoc.setNonPfxPassPhrase (String passPhrase, long passphraseSize, CredentialStorageFmt storageFmt)
Set the passphrase used to decrypt Non-PFX credentials.
Note: The passphrase provided must use the exact same character encoding used to encrypt the private key. The application makes no effort whatsoever to re-encode the same.
Parameters
passPhrase Passphrase used to encrypt Non-PFX private key. Should be set to NULL if unencrypted.
passphraseSize Passphrase size in bytes. Shall be set to 0 if private key is unencrypted or passphrase is stored on disk.
storageFmt Storage format for passphrase.
setNonPfxPrivateKey()
void com.datalogics.PDFL.SignDoc.setNonPfxPrivateKey (String privateKey, long keySize, CredentialStorageFmt storageFmt)
Set the private key for Non-PFX credentials..
Parameters
privateKey Private key.
keySize Size of private key in bytes. Shall be set to 0 if key is stored on disk.
storageFmt Storage format for private key.
setNonPfxSignerCert()
void com.datalogics.PDFL.SignDoc.setNonPfxSignerCert (String signerCert, long certSize, CredentialStorageFmt storageFmt)
Set the signer certificate for Non-PFX credentials.
Parameters
signerCert Signer certificate
certSize Size of signer certificate in bytes. Shall be set to 0 if certificate is stored on disk.
storageFmt Storage format for the signer certificate.
setOutputPath()
void com.datalogics.PDFL.SignDoc.setOutputPath (String newPath)
Set Output Path The path to which the file is saved. A path must be specified in case a full save (PDSaveFull) is needed. In case of an incremental save (PDSaveIncremental), newPath should be set to NULL. If a full save (PDSaveFull) is performed and newPath is the same as the file's original path, the new file is saved to a file system determined temporary path. The old file is then deleted and the new file is renamed to newPath.
setPfxCredentials()
void com.datalogics.PDFL.SignDoc.setPfxCredentials (String credentials, CredentialStorageFmt storageFmt)
Set PFX/PKCS#12 credentials.
Parameters
credentials Credentials in PFX/PKCS#12 file format.
storageFmt Storage format for the signer certificate. (Only OnDisk is allowed for this option)
setPfxPassPhrase()
void com.datalogics.PDFL.SignDoc.setPfxPassPhrase (String passphrase, long passphraseSize, CredentialStorageFmt storageFmt)
Set the passphrase used to decrypt PFX/PKCS#12 credentials. Note: The passphrase provided must use the exact same character encoding used to encrypt the PFX credentials. The application makes no effort whatsoever to re-encode the same.
Parameters
passphrase Passphrase used to encrypt PFX/PKCS#12 credentials. Shall be set to NULL if credentials are unencrypted.
passphraseSize Passphrase size in bytes. Shall be set to 0 if PFX credentials are unencrypted or passphrase is stored on disk.
storageFmt Storage format for PFX/PKCS#12 credentials.
setSignatureBoxPageNumber()
void com.datalogics.PDFL.SignDoc.setSignatureBoxPageNumber (long value)
Set the page number on which the widget annotation of the signature field is created.
Parameters
value Page number on which to create the widget annotation.
setSignatureBoxRectangle()
void com.datalogics.PDFL.SignDoc.setSignatureBoxRectangle (Rect rect)
Set the dimension of the annotation rectangle of the signature field being created.
Parameters
rect Dimension of the annotation rectangle of the signature field.
setSignerInfo()
void com.datalogics.PDFL.SignDoc.setSignerInfo (String logoFilePath, float logoOpacity, String name, String location, String reason, String contactInfo, DisplayTraits displayTraits)
Set Signer Info.
Parameters
logoFilePath Image to display as part of signature appearance.
logoOpacity Opacity of image to display as part of signature appearance.
name Name of the person or authority signing the document.
location CPU host name or physical location of the signing.
reason Reason for signing the document.
contactInfo Information provided by the signer to enable recipients to contact signer for signature verification.
displayTraits Fields to display as part of signature appearance.