Java API Reference: com.datalogics.PDFL.NameTree Class Reference
com.datalogics.PDFL.NameTree Class Reference
Public Member Functions
synchronized void delete ()
void enumEntries (PDFObjectEnumProc enumProc)
boolean equals (Object rhs)
PDFObject get (PDFString key)
PDFDict getPDFDict ()
NameTree (Document doc)
void put (PDFString key, PDFObject value)
void remove (PDFString key)
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
NameTree (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (NameTree obj)
Detailed Description
The name tree is a common data structure in PDF files. A name tree is a type of dictionary that can store many more pairs of matched records than a standard object dictionary.
A name tree uses keys that are character strings to map to data objects. The strings can use a standard coding format, such as Unicode, are sorted in order in the data structure, and can be associated with any type of object.
Constructor & Destructor Documentation
NameTree() [1/2]
com.datalogics.PDFL.NameTree.NameTree (long cPtr, boolean cMemoryOwn) protected
Referenced by equals(), and getCPtr().
NameTree() [2/2]
com.datalogics.PDFL.NameTree.NameTree (Document doc)
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.NameTree.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.NameTree.delete (Boolean disposing) protected
enumEntries()
void com.datalogics.PDFL.NameTree.enumEntries (PDFObjectEnumProc enumProc)
Enumerates all the entries of this NameTree.
This method does not enumerate invalid objects, which include objects that are defined as null, objects that are not defined at all (those having no cross-reference entry), and objects that are on the free list.
This re-raises any exception that enumProc raises.
Parameters
enumProc A user-supplied callback to call for each indirect object in dP. Enumeration ends when enumProc returns false or all indirect objects have been enumerated. The value parameter returned in enumProc is always null.
equals()
boolean com.datalogics.PDFL.NameTree.equals (Object rhs)
finalize()
void com.datalogics.PDFL.NameTree.finalize () protected
get()
PDFObject com.datalogics.PDFL.NameTree.get (PDFString key)
Retrieves an entry from this NameTree.
Parameters
key The name of the PDFObject to get from the tree.
Returns
- The PDFObject value corresponding to the supplied key
getCPtr()
long com.datalogics.PDFL.NameTree.getCPtr (NameTree obj) static protected
getPDFDict()
PDFDict com.datalogics.PDFL.NameTree.getPDFDict ()
Return the PDFDict of this NameTree.
Returns
PDFDict of the NameTree
put()
void com.datalogics.PDFL.NameTree.put (PDFString key, PDFObject value)
Puts a new entry in this NameTree. If an entry with this name is already in the tree, it is replaced.
Parameters
key The name of the PDFObject to put in the tree.
value The PDFObject to be associated with key.
remove()
void com.datalogics.PDFL.NameTree.remove (PDFString key)
Removes the specified PDFObject from this NameTree. It does nothing if no PDFObject of that name exists in this NameTree.
Parameters
key The name of the PDFObject to remove from the tree.