Java API Reference: com.datalogics.PDFL.FileSpecification Class Reference
com.datalogics.PDFL.FileSpecification Class Reference
Public Member Functions
synchronized void delete ()
FileSpecification (Document doc, String path)
String getPath ()
PDFObject getPDFObject ()
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
FileSpecification (long cPtr, boolean cMemoryOwn)
void finalize ()
Static Protected Member Functions
static long getCPtr (FileSpecification obj)
Detailed Description
Refers to the location of a PDF file within a file system. The PDF file system is known more commonly as the file path name.
The reference can be either absolute, as in a complete path name, or relative to the current place in a directory structure.
Constructor & Destructor Documentation
FileSpecification() [1/2]
com.datalogics.PDFL.FileSpecification.FileSpecification (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
FileSpecification() [2/2]
com.datalogics.PDFL.FileSpecification.FileSpecification (Document doc, String path)
Creates a new file specification object.
Parameters
doc The document in which the file specification is created.
path The string corresponding to the path of the file to reference. It may be relative or absolute.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.FileSpecification.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.FileSpecification.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.FileSpecification.finalize () protected
getCPtr()
long com.datalogics.PDFL.FileSpecification.getCPtr (FileSpecification obj) static protected
Referenced by com.datalogics.PDFL.LaunchAction.LaunchAction(), com.datalogics.PDFL.RemoteGoToAction.RemoteGoToAction(), com.datalogics.PDFL.LaunchAction.setFileSpecification(), and com.datalogics.PDFL.RemoteGoToAction.setFileSpecification().
getPath()
String com.datalogics.PDFL.FileSpecification.getPath ()
The path to the file referenced.
getPDFObject()
PDFObject com.datalogics.PDFL.FileSpecification.getPDFObject ()
Retrieve the PDFObject representation of this object.
toString()
String com.datalogics.PDFL.FileSpecification.toString ()