Java API Reference: com.datalogics.PDFL.LaunchAction Class Reference
com.datalogics.PDFL.LaunchAction Class Reference
Public Member Functions
synchronized void delete ()
boolean equals (Object rhs)
FileSpecification getFileSpecification ()
boolean getNewWindow ()
PDFDict getPDFDict ()
String getSubtype ()
LaunchAction (FileSpecification fileSpec)
void setFileSpecification (FileSpecification fileSpec)
void setNewWindow (boolean newValue)
String toString ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
LaunchAction (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (Action obj)
static long getCPtr (LaunchAction obj)
Detailed Description
A launch action launches an application or opens or prints a document.
Constructor & Destructor Documentation
LaunchAction() [1/2]
com.datalogics.PDFL.LaunchAction.LaunchAction (long cPtr, boolean cMemoryOwn) protected
Referenced by getCPtr().
LaunchAction() [2/2]
com.datalogics.PDFL.LaunchAction.LaunchAction (FileSpecification fileSpec)
General constructor.
The action's target will be the path referenced in the FileSpecification parameter. If the path is absolute, the target path will also be absolute. If the path is relative, the target path will also be relative.
Generally, the FileSpecification should be associated with the same Document that contains the LaunchAction. (Both FileSpecification and LaunchAction objects are associated with a Document at creation time, and the association cannot be changed.) The LaunchAction will be associated with the same Document that the FileSpecification parameter is associated with.
If the action's FileSpecification is changed during program execution such that the FileSpecification is associated with a different Document than the LaunchAction, saving the Document that contains the action will create a copy of the FileSpecification in the Document that contains the action.
Parameters
fileSpec A FileSpecification representing the application to be launched or the document to be opened or printed by this action.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.LaunchAction.delete ()
Reimplemented from com.datalogics.PDFL.Action.
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.LaunchAction.delete (Boolean disposing) protected
Reimplemented from com.datalogics.PDFL.Action.
equals()
boolean com.datalogics.PDFL.Action.equals (Object rhs) inherited
finalize()
void com.datalogics.PDFL.LaunchAction.finalize () protected
Reimplemented from com.datalogics.PDFL.Action.
getCPtr() [1/2]
long com.datalogics.PDFL.Action.getCPtr (Action obj) static protected inherited
Referenced by com.datalogics.PDFL.Bookmark.setAction(), and com.datalogics.PDFL.LinkAnnotation.setAction().
getCPtr() [2/2]
long com.datalogics.PDFL.LaunchAction.getCPtr (LaunchAction obj) static protected
getFileSpecification()
FileSpecification com.datalogics.PDFL.LaunchAction.getFileSpecification ()
The FileSpecification for this action.
Generally, the FileSpecification should be associated with the same Document that contains the LaunchAction. (Both FileSpecification and LaunchAction are associated with a Document at creation time.)
Returns
The FileSpecification associated with the LaunchAction.
getNewWindow()
boolean com.datalogics.PDFL.LaunchAction.getNewWindow ()
A flag specifying whether to open the destination document in a new window.
By default, this flag is not present.
If the action's FileSpecification is not a PDF, this flag is ignored.
Returns
True if the destination document is set to open in a new window, false otherwise.
getPDFDict()
PDFDict com.datalogics.PDFL.Action.getPDFDict () inherited
Retrieve the PDFObject representation of this object
getSubtype()
String com.datalogics.PDFL.Action.getSubtype () inherited
The action's subtype
setFileSpecification()
void com.datalogics.PDFL.LaunchAction.setFileSpecification (FileSpecification fileSpec)
The FileSpecification for this action.
Generally, the FileSpecification should be associated with the same Document that contains the LaunchAction. (Both FileSpecification and LaunchAction are associated with a Document at creation time.)
Parameters
fileSpec The FileSpecification to associate with the LaunchAction.
setNewWindow()
void com.datalogics.PDFL.LaunchAction.setNewWindow (boolean newValue)
A flag specifying whether to open the destination document in a new window.
By default, this flag is not present.
If the action's FileSpecification is not a PDF, this flag is ignored.
Parameters
newValue The new value for the flag.
toString()
String com.datalogics.PDFL.Action.toString () inherited