Java API Reference: com.datalogics.PDFL.ReportProc Class Reference
com.datalogics.PDFL.ReportProc Class Reference
Public Member Functions
void Call (ReportType reportType, String message, String replacementText)
synchronized void delete ()
ReportProc ()
Protected Member Functions
synchronized void delete (Boolean disposing)
void finalize ()
ReportProc (long cPtr, boolean cMemoryOwn)
Static Protected Member Functions
static long getCPtr (ReportProc obj)
Detailed Description
Represents the error reporting callback function. A ReportProc administrative command is typically passed to generate an error report.
If a process is not completing properly, or taking too long to finish, this process will create an error report in response. At frequent intervals, the method calls ReportProc. If the ReportProc command returns a "true" statement, the method generates an error. If it returns "false," the process continues. The time interval is determined by the ReportProc command.
Constructor & Destructor Documentation
ReportProc() [1/2]
com.datalogics.PDFL.ReportProc.ReportProc (long cPtr, boolean cMemoryOwn) protected
Referenced by Call(), and getCPtr().
ReportProc() [2/2]
com.datalogics.PDFL.ReportProc.ReportProc ()
Represents the error reporting callback function. A ReportProc administrative command is typically passed to generate an error report.
If a process is not completing properly, or taking too long to finish, this process will create an error report in response. At frequent intervals, the method calls ReportProc. If the ReportProc command returns a "true" statement, the method generates an error. If it returns "false," the process continues. The time interval is determined by the ReportProc command.
Member Function Documentation
Call()
void com.datalogics.PDFL.ReportProc.Call (ReportType reportType, String message, String replacementText)
delete() [1/2]
synchronized void com.datalogics.PDFL.ReportProc.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.ReportProc.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.ReportProc.finalize () protected
getCPtr()
long com.datalogics.PDFL.ReportProc.getCPtr (ReportProc obj) static protected
Referenced by com.datalogics.PDFL.Document.embedFonts(), and com.datalogics.PDFL.Document.embedFonts().