Java API Reference: com.datalogics.PDFL.ColorConvertParams Class Reference
com.datalogics.PDFL.ColorConvertParams Class Reference
Public Member Functions
ColorConvertParams (java.util.List< ColorConvertActions > convActions)
synchronized void delete ()
boolean getAllowLossyCompression ()
java.util.List< ColorConvertActions > getColorConvActions ()
ColorProfile getDefaultCMYK ()
ColorProfile getDefaultGray ()
ColorProfile getDefaultRGB ()
RenderIntent getIntentCMYK ()
RenderIntent getIntentGray ()
RenderIntent getIntentRGB ()
void setAllowLossyCompression (boolean newAllowLossyCompression)
void setColorConvActions (java.util.List< ColorConvertActions > newActions)
void setDefaultCMYK (ColorProfile defaultCMYK)
void setDefaultGray (ColorProfile defaultGray)
void setDefaultRGB (ColorProfile defaultRGB)
void setIntentCMYK (RenderIntent intentCMYK)
void setIntentGray (RenderIntent intentGray)
void setIntentRGB (RenderIntent intentRGB)
Protected Member Functions
ColorConvertParams (long cPtr, boolean cMemoryOwn)
synchronized void delete (Boolean disposing)
void finalize ()
Static Protected Member Functions
static long getCPtr (ColorConvertParams obj)
Detailed Description
Holds parameters to be passed to a color convert method.This includes the actions to take in case of a match.Each object is compared against the selection criteria for each of the actions, in order, until a matching action is found.
Constructor & Destructor Documentation
ColorConvertParams() [1/2]
com.datalogics.PDFL.ColorConvertParams.ColorConvertParams (long cPtr, boolean cMemoryOwn) protected
Referenced by ColorConvertParams(), and getCPtr().
ColorConvertParams() [2/2]
com.datalogics.PDFL.ColorConvertParams.ColorConvertParams (java.util.List< ColorConvertActions > convActions)
Default constructor for the ColorConvertParams class.Sets default values to the members.
Member Function Documentation
delete() [1/2]
synchronized void com.datalogics.PDFL.ColorConvertParams.delete ()
Referenced by delete(), and finalize().
delete() [2/2]
synchronized void com.datalogics.PDFL.ColorConvertParams.delete (Boolean disposing) protected
finalize()
void com.datalogics.PDFL.ColorConvertParams.finalize () protected
getAllowLossyCompression()
boolean com.datalogics.PDFL.ColorConvertParams.getAllowLossyCompression ()
If true, DCT or JPX encoding will be used resulting in a smaller PDF.If false, FlateDecoding will be used instead.
getColorConvActions()
java.util.List< ColorConvertActions > com.datalogics.PDFL.ColorConvertParams.getColorConvActions ()
The ColorConvActions to take.
getCPtr()
long com.datalogics.PDFL.ColorConvertParams.getCPtr (ColorConvertParams obj) static protected
Referenced by com.datalogics.PDFL.Page.colorConvertContent(), and com.datalogics.PDFL.Document.colorConvertPages().
getDefaultCMYK()
ColorProfile com.datalogics.PDFL.ColorConvertParams.getDefaultCMYK ()
Gets / Sets a default CMYK Color Profile.
getDefaultGray()
ColorProfile com.datalogics.PDFL.ColorConvertParams.getDefaultGray ()
Gets / Sets a default Gray Color Profile.
getDefaultRGB()
ColorProfile com.datalogics.PDFL.ColorConvertParams.getDefaultRGB ()
Gets / Sets a default RGB Color Profile.
getIntentCMYK()
RenderIntent com.datalogics.PDFL.ColorConvertParams.getIntentCMYK ()
Gets / Sets a default CMYK Render Intent.
getIntentGray()
RenderIntent com.datalogics.PDFL.ColorConvertParams.getIntentGray ()
Gets / Sets a default Gray Render Intent.
getIntentRGB()
RenderIntent com.datalogics.PDFL.ColorConvertParams.getIntentRGB ()
Gets / Sets a default RGB Render Intent.
setAllowLossyCompression()
void com.datalogics.PDFL.ColorConvertParams.setAllowLossyCompression (boolean newAllowLossyCompression)
setColorConvActions()
void com.datalogics.PDFL.ColorConvertParams.setColorConvActions (java.util.List< ColorConvertActions > newActions)
setDefaultCMYK()
void com.datalogics.PDFL.ColorConvertParams.setDefaultCMYK (ColorProfile defaultCMYK)
setDefaultGray()
void com.datalogics.PDFL.ColorConvertParams.setDefaultGray (ColorProfile defaultGray)
setDefaultRGB()
void com.datalogics.PDFL.ColorConvertParams.setDefaultRGB (ColorProfile defaultRGB)
setIntentCMYK()
void com.datalogics.PDFL.ColorConvertParams.setIntentCMYK (RenderIntent intentCMYK)
setIntentGray()
void com.datalogics.PDFL.ColorConvertParams.setIntentGray (RenderIntent intentGray)
setIntentRGB()
void com.datalogics.PDFL.ColorConvertParams.setIntentRGB (RenderIntent intentRGB)