var hierarchy =
[
    [ "System.ApplicationException", null, [
      [ "Datalogics.PDFL.LibraryException", "class_datalogics_1_1_p_d_f_l_1_1_library_exception.html", null ]
    ] ],
    [ "Datalogics.PDFL.PDFAConvertResult", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_a_convert_result.html", null ],
    [ "Datalogics.PDFL.PDFXConvertResult", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_x_convert_result.html", null ],
    [ "global.SystemIDisposable", null, [
      [ "Datalogics.PDFL.Action", "class_datalogics_1_1_p_d_f_l_1_1_action.html", [
        [ "Datalogics.PDFL.GoToAction", "class_datalogics_1_1_p_d_f_l_1_1_go_to_action.html", null ],
        [ "Datalogics.PDFL.LaunchAction", "class_datalogics_1_1_p_d_f_l_1_1_launch_action.html", null ],
        [ "Datalogics.PDFL.RemoteGoToAction", "class_datalogics_1_1_p_d_f_l_1_1_remote_go_to_action.html", null ],
        [ "Datalogics.PDFL.URIAction", "class_datalogics_1_1_p_d_f_l_1_1_u_r_i_action.html", null ]
      ] ],
      [ "Datalogics.PDFL.Annotation", "class_datalogics_1_1_p_d_f_l_1_1_annotation.html", [
        [ "Datalogics.PDFL.CircleAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_circle_annotation.html", null ],
        [ "Datalogics.PDFL.FreeTextAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_free_text_annotation.html", null ],
        [ "Datalogics.PDFL.InkAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_ink_annotation.html", null ],
        [ "Datalogics.PDFL.LineAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_line_annotation.html", null ],
        [ "Datalogics.PDFL.LinkAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_link_annotation.html", null ],
        [ "Datalogics.PDFL.PolyLineAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_poly_line_annotation.html", null ],
        [ "Datalogics.PDFL.PolygonAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_polygon_annotation.html", null ],
        [ "Datalogics.PDFL.Redaction", "class_datalogics_1_1_p_d_f_l_1_1_redaction.html", null ],
        [ "Datalogics.PDFL.SquareAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_square_annotation.html", null ],
        [ "Datalogics.PDFL.TextMarkupAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_text_markup_annotation.html", [
          [ "Datalogics.PDFL.HighlightAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_highlight_annotation.html", null ],
          [ "Datalogics.PDFL.UnderlineAnnotation", "class_datalogics_1_1_p_d_f_l_1_1_underline_annotation.html", null ]
        ] ]
      ] ],
      [ "Datalogics.PDFL.Bookmark", "class_datalogics_1_1_p_d_f_l_1_1_bookmark.html", null ],
      [ "Datalogics.PDFL.CancelProc", "class_datalogics_1_1_p_d_f_l_1_1_cancel_proc.html", null ],
      [ "Datalogics.PDFL.Clip", "class_datalogics_1_1_p_d_f_l_1_1_clip.html", null ],
      [ "Datalogics.PDFL.Collection", "class_datalogics_1_1_p_d_f_l_1_1_collection.html", null ],
      [ "Datalogics.PDFL.CollectionSchema", "class_datalogics_1_1_p_d_f_l_1_1_collection_schema.html", null ],
      [ "Datalogics.PDFL.CollectionSchemaField", "class_datalogics_1_1_p_d_f_l_1_1_collection_schema_field.html", null ],
      [ "Datalogics.PDFL.CollectionSortItem", "class_datalogics_1_1_p_d_f_l_1_1_collection_sort_item.html", null ],
      [ "Datalogics.PDFL.Color", "class_datalogics_1_1_p_d_f_l_1_1_color.html", null ],
      [ "Datalogics.PDFL.ColorConvertActions", "class_datalogics_1_1_p_d_f_l_1_1_color_convert_actions.html", null ],
      [ "Datalogics.PDFL.ColorConvertParams", "class_datalogics_1_1_p_d_f_l_1_1_color_convert_params.html", null ],
      [ "Datalogics.PDFL.ColorSpace", "class_datalogics_1_1_p_d_f_l_1_1_color_space.html", [
        [ "Datalogics.PDFL.CalGrayColorSpace", "class_datalogics_1_1_p_d_f_l_1_1_cal_gray_color_space.html", null ],
        [ "Datalogics.PDFL.CalRGBColorSpace", "class_datalogics_1_1_p_d_f_l_1_1_cal_r_g_b_color_space.html", null ],
        [ "Datalogics.PDFL.DeviceNColorSpace", "class_datalogics_1_1_p_d_f_l_1_1_device_n_color_space.html", null ],
        [ "Datalogics.PDFL.ICCBasedColorSpace", "class_datalogics_1_1_p_d_f_l_1_1_i_c_c_based_color_space.html", null ],
        [ "Datalogics.PDFL.IndexedColorSpace", "class_datalogics_1_1_p_d_f_l_1_1_indexed_color_space.html", null ],
        [ "Datalogics.PDFL.LabColorSpace", "class_datalogics_1_1_p_d_f_l_1_1_lab_color_space.html", null ],
        [ "Datalogics.PDFL.NamedColorSpace", "class_datalogics_1_1_p_d_f_l_1_1_named_color_space.html", null ],
        [ "Datalogics.PDFL.SeparationColorSpace", "class_datalogics_1_1_p_d_f_l_1_1_separation_color_space.html", null ]
      ] ],
      [ "Datalogics.PDFL.ColorValueConverter", "class_datalogics_1_1_p_d_f_l_1_1_color_value_converter.html", null ],
      [ "Datalogics.PDFL.Content", "class_datalogics_1_1_p_d_f_l_1_1_content.html", null ],
      [ "Datalogics.PDFL.DocTextFinder", "class_datalogics_1_1_p_d_f_l_1_1_doc_text_finder.html", null ],
      [ "Datalogics.PDFL.DocTextFinderMatch", "class_datalogics_1_1_p_d_f_l_1_1_doc_text_finder_match.html", null ],
      [ "Datalogics.PDFL.DocTextFinderQuadInfo", "class_datalogics_1_1_p_d_f_l_1_1_doc_text_finder_quad_info.html", null ],
      [ "Datalogics.PDFL.Document", "class_datalogics_1_1_p_d_f_l_1_1_document.html", null ],
      [ "Datalogics.PDFL.DrawParams", "class_datalogics_1_1_p_d_f_l_1_1_draw_params.html", null ],
      [ "Datalogics.PDFL.Element", "class_datalogics_1_1_p_d_f_l_1_1_element.html", [
        [ "Datalogics.PDFL.Container", "class_datalogics_1_1_p_d_f_l_1_1_container.html", null ],
        [ "Datalogics.PDFL.Form", "class_datalogics_1_1_p_d_f_l_1_1_form.html", null ],
        [ "Datalogics.PDFL.Group", "class_datalogics_1_1_p_d_f_l_1_1_group.html", null ],
        [ "Datalogics.PDFL.Image", "class_datalogics_1_1_p_d_f_l_1_1_image.html", null ],
        [ "Datalogics.PDFL.Path", "class_datalogics_1_1_p_d_f_l_1_1_path.html", null ],
        [ "Datalogics.PDFL.PostScript", "class_datalogics_1_1_p_d_f_l_1_1_post_script.html", null ],
        [ "Datalogics.PDFL.Shading", "class_datalogics_1_1_p_d_f_l_1_1_shading.html", null ],
        [ "Datalogics.PDFL.Text", "class_datalogics_1_1_p_d_f_l_1_1_text.html", null ],
        [ "Datalogics.PDFL.TextRun", "class_datalogics_1_1_p_d_f_l_1_1_text_run.html", null ]
      ] ],
      [ "Datalogics.PDFL.EncodingInfo", "class_datalogics_1_1_p_d_f_l_1_1_encoding_info.html", null ],
      [ "Datalogics.PDFL.ExtendedGraphicState", "class_datalogics_1_1_p_d_f_l_1_1_extended_graphic_state.html", null ],
      [ "Datalogics.PDFL.FileAttachment", "class_datalogics_1_1_p_d_f_l_1_1_file_attachment.html", null ],
      [ "Datalogics.PDFL.FileSpecification", "class_datalogics_1_1_p_d_f_l_1_1_file_specification.html", null ],
      [ "Datalogics.PDFL.FlattenTransparencyParams", "class_datalogics_1_1_p_d_f_l_1_1_flatten_transparency_params.html", null ],
      [ "Datalogics.PDFL.Font", "class_datalogics_1_1_p_d_f_l_1_1_font.html", null ],
      [ "Datalogics.PDFL.Function", "class_datalogics_1_1_p_d_f_l_1_1_function.html", [
        [ "Datalogics.PDFL.ExponentialFunction", "class_datalogics_1_1_p_d_f_l_1_1_exponential_function.html", null ],
        [ "Datalogics.PDFL.NamedFunction", "class_datalogics_1_1_p_d_f_l_1_1_named_function.html", null ],
        [ "Datalogics.PDFL.PostScriptCalculatorFunction", "class_datalogics_1_1_p_d_f_l_1_1_post_script_calculator_function.html", null ]
      ] ],
      [ "Datalogics.PDFL.GraphicState", "class_datalogics_1_1_p_d_f_l_1_1_graphic_state.html", null ],
      [ "Datalogics.PDFL.ImageCollection", "class_datalogics_1_1_p_d_f_l_1_1_image_collection.html", null ],
      [ "Datalogics.PDFL.ImageData", "class_datalogics_1_1_p_d_f_l_1_1_image_data.html", null ],
      [ "Datalogics.PDFL.ImageSaveParams", "class_datalogics_1_1_p_d_f_l_1_1_image_save_params.html", null ],
      [ "Datalogics.PDFL.Ink", "class_datalogics_1_1_p_d_f_l_1_1_ink.html", null ],
      [ "Datalogics.PDFL.LanguageSetting", "class_datalogics_1_1_p_d_f_l_1_1_language_setting.html", null ],
      [ "Datalogics.PDFL.Library", "class_datalogics_1_1_p_d_f_l_1_1_library.html", null ],
      [ "Datalogics.PDFL.LogParams", "class_datalogics_1_1_p_d_f_l_1_1_log_params.html", null ],
      [ "Datalogics.PDFL.Matrix", "class_datalogics_1_1_p_d_f_l_1_1_matrix.html", null ],
      [ "Datalogics.PDFL.NameTree", "class_datalogics_1_1_p_d_f_l_1_1_name_tree.html", null ],
      [ "Datalogics.PDFL.NumberTree", "class_datalogics_1_1_p_d_f_l_1_1_number_tree.html", null ],
      [ "Datalogics.PDFL.OCREngine", "class_datalogics_1_1_p_d_f_l_1_1_o_c_r_engine.html", null ],
      [ "Datalogics.PDFL.OCRParams", "class_datalogics_1_1_p_d_f_l_1_1_o_c_r_params.html", null ],
      [ "Datalogics.PDFL.OptionalContentConfig", "class_datalogics_1_1_p_d_f_l_1_1_optional_content_config.html", null ],
      [ "Datalogics.PDFL.OptionalContentContext", "class_datalogics_1_1_p_d_f_l_1_1_optional_content_context.html", null ],
      [ "Datalogics.PDFL.OptionalContentGroup", "class_datalogics_1_1_p_d_f_l_1_1_optional_content_group.html", null ],
      [ "Datalogics.PDFL.OptionalContentMembershipDict", "class_datalogics_1_1_p_d_f_l_1_1_optional_content_membership_dict.html", null ],
      [ "Datalogics.PDFL.OptionalContentOrderNode", "class_datalogics_1_1_p_d_f_l_1_1_optional_content_order_node.html", [
        [ "Datalogics.PDFL.OptionalContentOrderArray", "class_datalogics_1_1_p_d_f_l_1_1_optional_content_order_array.html", null ],
        [ "Datalogics.PDFL.OptionalContentOrderLeaf", "class_datalogics_1_1_p_d_f_l_1_1_optional_content_order_leaf.html", null ]
      ] ],
      [ "Datalogics.PDFL.PDFAConvertParams", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_a_convert_params.html", null ],
      [ "Datalogics.PDFL.PDFObject", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_object.html", [
        [ "Datalogics.PDFL.PDFArray", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_array.html", null ],
        [ "Datalogics.PDFL.PDFBoolean", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_boolean.html", null ],
        [ "Datalogics.PDFL.PDFDict", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_dict.html", null ],
        [ "Datalogics.PDFL.PDFInteger", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_integer.html", null ],
        [ "Datalogics.PDFL.PDFName", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_name.html", null ],
        [ "Datalogics.PDFL.PDFReal", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_real.html", null ],
        [ "Datalogics.PDFL.PDFStream", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_stream.html", null ],
        [ "Datalogics.PDFL.PDFString", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_string.html", null ]
      ] ],
      [ "Datalogics.PDFL.PDFObjectEnumProc", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_object_enum_proc.html", null ],
      [ "Datalogics.PDFL.PDFOptimizer", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_optimizer.html", null ],
      [ "Datalogics.PDFL.PDFXConvertParams", "class_datalogics_1_1_p_d_f_l_1_1_p_d_f_x_convert_params.html", null ],
      [ "Datalogics.PDFL.Page", "class_datalogics_1_1_p_d_f_l_1_1_page.html", null ],
      [ "Datalogics.PDFL.PageImageParams", "class_datalogics_1_1_p_d_f_l_1_1_page_image_params.html", null ],
      [ "Datalogics.PDFL.PageLabel", "class_datalogics_1_1_p_d_f_l_1_1_page_label.html", null ],
      [ "Datalogics.PDFL.PageRange", "class_datalogics_1_1_p_d_f_l_1_1_page_range.html", null ],
      [ "Datalogics.PDFL.PaperSource", "class_datalogics_1_1_p_d_f_l_1_1_paper_source.html", null ],
      [ "Datalogics.PDFL.Pattern", "class_datalogics_1_1_p_d_f_l_1_1_pattern.html", [
        [ "Datalogics.PDFL.ShadingPattern", "class_datalogics_1_1_p_d_f_l_1_1_shading_pattern.html", [
          [ "Datalogics.PDFL.AxialShadingPattern", "class_datalogics_1_1_p_d_f_l_1_1_axial_shading_pattern.html", null ]
        ] ]
      ] ],
      [ "Datalogics.PDFL.Point", "class_datalogics_1_1_p_d_f_l_1_1_point.html", null ],
      [ "Datalogics.PDFL.PrintCancelProc", "class_datalogics_1_1_p_d_f_l_1_1_print_cancel_proc.html", null ],
      [ "Datalogics.PDFL.PrintParams", "class_datalogics_1_1_p_d_f_l_1_1_print_params.html", null ],
      [ "Datalogics.PDFL.PrintProgressProc", "class_datalogics_1_1_p_d_f_l_1_1_print_progress_proc.html", null ],
      [ "Datalogics.PDFL.PrintUserParams", "class_datalogics_1_1_p_d_f_l_1_1_print_user_params.html", null ],
      [ "Datalogics.PDFL.ProgressMonitor", "class_datalogics_1_1_p_d_f_l_1_1_progress_monitor.html", null ],
      [ "Datalogics.PDFL.Quad", "class_datalogics_1_1_p_d_f_l_1_1_quad.html", null ],
      [ "Datalogics.PDFL.Rect", "class_datalogics_1_1_p_d_f_l_1_1_rect.html", null ],
      [ "Datalogics.PDFL.RemoteDestination", "class_datalogics_1_1_p_d_f_l_1_1_remote_destination.html", null ],
      [ "Datalogics.PDFL.RenderProgressProc", "class_datalogics_1_1_p_d_f_l_1_1_render_progress_proc.html", null ],
      [ "Datalogics.PDFL.ReportProc", "class_datalogics_1_1_p_d_f_l_1_1_report_proc.html", null ],
      [ "Datalogics.PDFL.RolledBackDocument", "class_datalogics_1_1_p_d_f_l_1_1_rolled_back_document.html", null ],
      [ "Datalogics.PDFL.Segment", "class_datalogics_1_1_p_d_f_l_1_1_segment.html", [
        [ "Datalogics.PDFL.ClosePath", "class_datalogics_1_1_p_d_f_l_1_1_close_path.html", null ],
        [ "Datalogics.PDFL.CurveTo", "class_datalogics_1_1_p_d_f_l_1_1_curve_to.html", null ],
        [ "Datalogics.PDFL.CurveToV", "class_datalogics_1_1_p_d_f_l_1_1_curve_to_v.html", null ],
        [ "Datalogics.PDFL.CurveToY", "class_datalogics_1_1_p_d_f_l_1_1_curve_to_y.html", null ],
        [ "Datalogics.PDFL.LineTo", "class_datalogics_1_1_p_d_f_l_1_1_line_to.html", null ],
        [ "Datalogics.PDFL.MoveTo", "class_datalogics_1_1_p_d_f_l_1_1_move_to.html", null ],
        [ "Datalogics.PDFL.RectSegment", "class_datalogics_1_1_p_d_f_l_1_1_rect_segment.html", null ]
      ] ],
      [ "Datalogics.PDFL.SeparationParams", "class_datalogics_1_1_p_d_f_l_1_1_separation_params.html", null ],
      [ "Datalogics.PDFL.SeparationPlate", "class_datalogics_1_1_p_d_f_l_1_1_separation_plate.html", null ],
      [ "Datalogics.PDFL.Style", "class_datalogics_1_1_p_d_f_l_1_1_style.html", null ],
      [ "Datalogics.PDFL.StyleTransition", "class_datalogics_1_1_p_d_f_l_1_1_style_transition.html", null ],
      [ "Datalogics.PDFL.TextState", "class_datalogics_1_1_p_d_f_l_1_1_text_state.html", null ],
      [ "Datalogics.PDFL.ViewDestination", "class_datalogics_1_1_p_d_f_l_1_1_view_destination.html", null ],
      [ "Datalogics.PDFL.WatermarkParams", "class_datalogics_1_1_p_d_f_l_1_1_watermark_params.html", null ],
      [ "Datalogics.PDFL.WatermarkTextParams", "class_datalogics_1_1_p_d_f_l_1_1_watermark_text_params.html", null ],
      [ "Datalogics.PDFL.Word", "class_datalogics_1_1_p_d_f_l_1_1_word.html", null ],
      [ "Datalogics.PDFL.WordFinder", "class_datalogics_1_1_p_d_f_l_1_1_word_finder.html", null ],
      [ "Datalogics.PDFL.WordFinderConfig", "class_datalogics_1_1_p_d_f_l_1_1_word_finder_config.html", null ],
      [ "Datalogics.PDFL.WordProc", "class_datalogics_1_1_p_d_f_l_1_1_word_proc.html", null ],
      [ "Datalogics.PDFL.XPSConvertParams", "class_datalogics_1_1_p_d_f_l_1_1_x_p_s_convert_params.html", null ]
    ] ]
];